objects/Account.object
<CustomObject>
    <fields>
        <fullName>FriCloseHour__c</fullName>
        <label>Fri Close Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FriOpenHour__c</fullName>
        <label>Fri Open Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MonCloseHour__c</fullName>
        <label>Mon Close Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MonOpenHour__c</fullName>
        <label>Mon Open Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SatCloseHour__c</fullName>
        <label>Sat Close Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SatOpenHour__c</fullName>
        <label>Sat Open Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SunCloseHour__c</fullName>
        <label>Sun Close Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SunOpenHour__c</fullName>
        <label>Sun Open Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ThuCloseHour__c</fullName>
        <label>Thu Close Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ThuOpenHour__c</fullName>
        <label>Thu Open Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timezone__c</fullName>
        <label>Timezone Offset From GMT</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TueCloseHour__c</fullName>
        <label>Tue Close Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TueOpenHour__c</fullName>
        <label>Tue Open Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WedCloseHour__c</fullName>
        <label>Wed Close Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WedOpenHour__c</fullName>
        <label>Wed Open Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name_TXT__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name_TXT__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Lead Provider)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpportunityStatus_TXT__c</fullName>
        <label>Opportunity Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned/Routed to Dealer</fullName>
                </value>
                <value>
                    <fullName>Auto-response sent</fullName>
                </value>
                <value>
                    <fullName>Lead Opened</fullName>
                </value>
                <value>
                    <fullName>Lead Received</fullName>
                </value>
                <value>
                    <fullName>Customer phoned (Inbound phone)</fullName>
                </value>
                <value>
                    <fullName>Customer emailed (Inbound email)</fullName>
                </value>
                <value>
                    <fullName>Salesperson responded by Email</fullName>
                </value>
                <value>
                    <fullName>Salesperson responded by Phone</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson responded by email</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson responded by Phone</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson request another appointment by email</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson request another appointment by phone</fullName>
                </value>
                <value>
                    <fullName>Credit Application</fullName>
                </value>
                <value>
                    <fullName>Credit Application (3rd party)</fullName>
                </value>
                <value>
                    <fullName>Trade-In Appraisal</fullName>
                </value>
                <value>
                    <fullName>Broadcast Email</fullName>
                </value>
                <value>
                    <fullName>Made Appointment</fullName>
                </value>
                <value>
                    <fullName>Demoed/Test Drove</fullName>
                </value>
                <value>
                    <fullName>Boat/Outboard Sales Presentation</fullName>
                </value>
                <value>
                    <fullName>Appointment Didn’t Show</fullName>
                </value>
                <value>
                    <fullName>Appointment Showed</fullName>
                </value>
                <value>
                    <fullName>Offer to Purchase</fullName>
                </value>
                <value>
                    <fullName>Model in Stock</fullName>
                </value>
                <value>
                    <fullName>Model not in Stock</fullName>
                </value>
                <value>
                    <fullName>Model on back order</fullName>
                </value>
                <value>
                    <fullName>Credit Denied</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson marked sold</fullName>
                </value>
                <value>
                    <fullName>Salesperson marked vehicle sold</fullName>
                </value>
                <value>
                    <fullName>Lost Sales</fullName>
                </value>
                <value>
                    <fullName>Any additional vehicle sold info (delivered, punched, etc.)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PreferredDealerAccount_TXT__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Preferred Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ZipCode_TXT__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/HELMSResponseTimeTriggerHelperTest.cls
@isTest
public class HELMSResponseTimeTriggerHelperTest {
    @isTest static void wholeweek(){
        account acc=new account(Timezone__c='-7',MonOpenHour__c='0000',MonCloseHour__c='2400',TueOpenHour__c='0000',
        TueCloseHour__c='2400',WedOpenHour__c='0000',WedCloseHour__c='2400',ThuOpenHour__c='0000',ThuCloseHour__c='2400',
        FriOpenHour__c='0000',FriCloseHour__c='2400',SatOpenHour__c='0000',SatCloseHour__c='2400',SunOpenHour__c='0000',
        SunCloseHour__c='2400');
        acc.Name = 'Test Account';
        insert acc;
        opportunity opp= new opportunity(Stagename='Dealer Visit',OpportunityStatus_TXT__c='Offer to Purchase',PreferredDealerAccount_TXT__c=acc.id,Name='Response time test class', 
        LeadProvider_ID__c=acc.id, Email__c='call.bijay1@gmail.com', ZipCode_TXT__c='12345', 
        First_Name_TXT__c='Response time test', Last_Name_TXT__c='class');
        opp.CloseDate= system.Today();
        opp.CreatedDate= system.now() -20;
        opp.LastModifiedDate=system.now();
        insert opp;
        List<opportunity> lstopp =new list<opportunity>();
        lstopp.add(opp);
        HELMSResponseTimeTriggerHelper.calculateTime(lstopp);
        
    }
}