objects/Account.object
<CustomObject>
    <fields>
        <fullName>DealerCode_CD__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Dealer_Division__c.object
<CustomObject>
    <description>list of active or inactive division, subdivision, zone, district and other territory related fields based on their business use for Sales, Service, Parts, etc.</description>
    <fields>
        <fullName>DealerSubdivision_CD__c</fullName>
        <description>external key from B2C system to have both Dealer Number + Subdivision.</description>
        <externalId>true</externalId>
        <label>Dealer Subdivision</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <label>Dealer Subdivision</label>
    <nameField>
        <displayFormat>DD-{0}</displayFormat>
        <label>Dealer Division Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Divisions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/HELMSUpdateDealeronDivisionBatchTest.cls
@isTest
public class HELMSUpdateDealeronDivisionBatchTest 
{
    static testMethod void mapdivision() 
    {
        List<Account> lstAccount= new List<Account>();
        List<Dealer_Division__c> lstdvsn= new List<Dealer_Division__c>();
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId();
        
        for(Integer i=0 ;i <200;i++)
        {
            Account acc = new Account();
            acc.Name ='Name'+i;
            acc.recordtypeid = recordTypeId;
            acc.DealerCode_CD__c = '105200'+i;
            lstAccount.add(acc);
            
            Dealer_Division__c divsn= new Dealer_Division__c();
            divsn.SubDiv_TXT__c = 'Honda';
            divsn.DealerSubdivision_CD__c = '105200'+i+'Honda';
            lstdvsn.add(divsn);
        }
        
        insert lstAccount;
        insert lstdvsn;
        
        Test.startTest();

            HELMSUpdateDealeronDivisionBatch obj = new HELMSUpdateDealeronDivisionBatch();
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
    }
}