objects/Account.object
<CustomObject>
    <fields>
        <fullName>DealerCode_CD__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Send_Customer_Acknowledgement_Email_Flag__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Send Customer Acknowledgement Email</description>
        <label>Send Customer Acknowledgement Email</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <description>Used for Provider Records</description>
        <label>Provider</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <label>Provider</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Address_Street__c</fullName>
        <label>Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BodyStyle_TXT__c</fullName>
        <label>BodyStyle</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Condition_TXT__c</fullName>
        <label>Condition</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>excellent</fullName>
                </value>
                <value>
                    <fullName>good</fullName>
                </value>
                <value>
                    <fullName>fair</fullName>
                </value>
                <value>
                    <fullName>poor</fullName>
                </value>
                <value>
                    <fullName>unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContactKey_TXT__c</fullName>
        <label>Contact Key</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Ids_ID__c</fullName>
        <label>Dealer IDs</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Doors_TXT__c</fullName>
        <label>Doors</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Exterior_Color__c</fullName>
        <label>Exterior Color</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <label>External IDs</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Interior_Color__c</fullName>
        <label>Interior Color</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Provider</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Lead Provider)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MSRP_AMT__c</fullName>
        <label>MSRP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Make_TXT__c</fullName>
        <label>Make</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Marketing_Campaign_Name__c</fullName>
        <description>Marketing campaign that drove this lead.</description>
        <label>Marketing Campaign Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ModelDealerAccessoryPrice_AM__c</fullName>
        <label>Model Dealer Accessory Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ModelDestinationCharge_AM__c</fullName>
        <label>Model Destination Charge</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Model_ID__c</fullName>
        <label>Model ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_TXT__c</fullName>
        <label>Model</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Number_NM__c</fullName>
        <label>Vin Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OdometerStatus_TXT__c</fullName>
        <label>Odometer Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>unknown</fullName>
                </value>
                <value>
                    <fullName>rolledover</fullName>
                </value>
                <value>
                    <fullName>replaced</fullName>
                </value>
                <value>
                    <fullName>original</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OdometerUnits_TXT__c</fullName>
        <label>Odometer Units</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>kilometer</fullName>
                </value>
                <value>
                    <fullName>miles</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Odometer_TXT__c</fullName>
        <label>Odometer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredDealerAccount_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProviderDetail_TXT__c</fullName>
        <inlineHelpText>Source Lead Provider Name</inlineHelpText>
        <label>Provider Detail</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Transmission_TXT__c</fullName>
        <label>Transmission</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trim_TXT__c</fullName>
        <label>Model Trim</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>VehicleStatus_TXT__c</fullName>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Used</fullName>
                </value>
                <value>
                    <fullName>Cpo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year_YR__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BodyStyle_TXT__c</fullName>
        <label>Body Style</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Condition_TXT__c</fullName>
        <label>Condition</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Excellent</fullName>
                </value>
                <value>
                    <fullName>Good,</fullName>
                </value>
                <value>
                    <fullName>Fair</fullName>
                </value>
                <value>
                    <fullName>Poor</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContactKey_TXT__c</fullName>
        <label>Contact Key</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Ids_ID__c</fullName>
        <label>Dealer IDs</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Doors_TXT__c</fullName>
        <label>Doors</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exterior_Color__c</fullName>
        <label>Exterior Color</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <label>External IDs</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>First_Name_TXT__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interior_Color__c</fullName>
        <label>Interior Color</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Last_Name_TXT__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Lead Provider)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MSRP_AMT__c</fullName>
        <label>MSRP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Make_TXT__c</fullName>
        <label>Make</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Campaign_Name__c</fullName>
        <description>Marketing campaign that drove this lead.</description>
        <label>Marketing Campaign Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ModelDealerAccessoryPrice_AM__c</fullName>
        <label>Model Dealer Accessory Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ModelDestinationCharge_AM__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Model Destination Charge</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Model_ID__c</fullName>
        <label>Model ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_TXT__c</fullName>
        <label>Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_NM__c</fullName>
        <label>Vin Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OdometerStatus_TXT__c</fullName>
        <label>Odometer Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Rolledover</fullName>
                </value>
                <value>
                    <fullName>Replaced</fullName>
                </value>
                <value>
                    <fullName>Original</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OdometerUnits_TXT__c</fullName>
        <label>Odometer Units</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>kilometer</fullName>
                </value>
                <value>
                    <fullName>miles</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Odometer_TXT__c</fullName>
        <label>Odometer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProviderDetail_TXT__c</fullName>
        <inlineHelpText>Source Lead Provider Name</inlineHelpText>
        <label>Provider Detail</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Transmission_TXT__c</fullName>
        <label>Transmission</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trim_TXT__c</fullName>
        <label>Model Trim</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VehicleStatus_TXT__c</fullName>
        <label>Vehicle Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Used</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year_YR__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZipCode_TXT__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Honda</fullName>
        <active>true</active>
        <businessProcess>HELMS Sales Process</businessProcess>
        <description>Used by the Honda Team</description>
        <label>Honda Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/HELMSeShoppingSendNotificationTest.cls
@isTest
public class HELMSeShoppingSendNotificationTest {
    @isTest
    static void method1(){
        
        Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Provider').getRecordTypeId();
        Id conRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Provider').getRecordTypeId();
        Account accTestRec = new Account(Name='Test Account123another',DealerCode_CD__c = '123',RecordTypeId=dealerAccRecTypeId,
                                         Send_Customer_Acknowledgement_Email_Flag__c=true
                                        );
        insert accTestRec;
         Id dealerAccRecTypeId1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
      
        Account accTestRec1 = new Account(Name='Test Account123another1',DealerCode_CD__c = '1231',RecordTypeId=dealerAccRecTypeId1,
                                         Send_Customer_Acknowledgement_Email_Flag__c=true
                                        );
        insert accTestRec1;
        
        contact con = new Contact(FirstName='John',LastName='Doe',Email='yash1234@testing.com',Title='Mr',
                                  AccountId=accTestRec.Id, RecordTypeId=conRecTypeId );
        insert con;
        
         Opportunity oppRec = new Opportunity(Name='YashLead',
                                             StageName='In Conversation',
                                             PreferredDealerNumber_NUM__c='123456', External_ID__c='12345',
                                             CloseDate=system.today(),
                                            // Lead_ID__c=lead1.Id,
                                             AccountId=accTestRec.Id,
                                             First_Name_TXT__c='qqq1',Last_Name_TXT__c='aqa1'
                                             //   Trim_TXT__c = lead.Trim_TXT__c,ZipCode_TXT__c = '90503',First_Name_TXT__c = 'Test',Last_Name_TXT__c='Test',
                                             //   Make_TXT__c =lead.Make_TXT__c,ContactKey_TXT__c =lead.ContactKey_TXT__c,
                                             //     VehicleStatus_TXT__c=lead.VehicleStatus_TXT__c,Condition_TXT__c=lead.Condition_TXT__c,
                                             //     Number_NM__c=lead.Number_NM__c,Doors_TXT__c=lead.Doors_TXT__c,BodyStyle_TXT__c=lead.BodyStyle_TXT__c,
                                             //     Odometer_TXT__c=lead.Odometer_TXT__c,
                                             //    OdometerStatus_TXT__c=lead.OdometerStatus_TXT__c,
                                             //    OdometerUnits_TXT__c=lead.OdometerUnits_TXT__c
                                            );
        
        
        insert oppRec; 
        
        
        List<Lead> leadList = new List<Lead>(); 
       // set<id> leadListIds=new set<id>();
        Lead lead1 = new Lead(LastName='Doe',Email='yash1234@testing.com',PreferredDealerAccount_ID__c =accTestRec1.id, FirstName='John',
                              Company='Trance',LeadProvider_ID__c=accTestRec.id,
                              MSRP_AMT__c=6000,ModelDestinationCharge_AM__c=9000,ModelDealerAccessoryPrice_AM__c=9877,
                              Interior_Color__c='white',Exterior_Color__c='black',Transmission_TXT__c='aazzzz',
                              Address_Street__c='321',
                              State='telangana',Marketing_Campaign_Name__c='qqqqq',Make_TXT__c='kkkk',
                              Dealer_Ids_ID__c='testing',Year_YR__c='test',Model_TXT__c='demoooo',ProviderDetail_TXT__c='test11:test21',
                              Model_ID__c='demo',Trim_TXT__c='trimmer',SubDiv_TXT__c='Honda',Source_Name__c='Facebook',
                              isConverted=true,Send_confirmation_Email__c=true,
                              ConvertedAccountId=accTestRec.Id,
                              ConvertedOpportunityId=oppRec.id,
                              PreferredDealerNumber_NUM__c='123',
                              Division_CD__c='A',VehicleInterest_TXT__c='buy',
                              ContactKey_TXT__c ='test',VehicleStatus_TXT__c='New',Condition_TXT__c='excellent',
                              Number_NM__c='number',Doors_TXT__c='doortxt',BodyStyle_TXT__c='bodyStyle',Odometer_TXT__c='odmeter',
                              OdometerStatus_TXT__c='unknown',OdometerUnits_TXT__c='kilometer',  Color_TXT__c='<colorcombination><interiorcolor/><exteriorcolor>Deep Pearl Gray</exteriorcolor><preference>1</preference></colorcombination>');
        insert lead1;
        
         Opportunity oppRec1 = new Opportunity();
        oppRec1.id = oppRec.id;
        oppRec1.Lead_ID__c=lead1.Id;       
        update OppRec1;        
       // leadListIds.add(lead1.id);
        leadList.add(lead1);
        
       
        
        Offers__c offer1 = new Offers__c(
            Opportunity__c=oppRec1.Id, Offer_ID__c='AQA'
            
        );
        
        
        insert offer1;
        
        /*      List<Lead> listLead = [Select Id, FirstName,Odometer_TXT__c, BodyStyle_TXT__c,  MSRP_AMT__c, ModelDestinationCharge_AM__c, 
ModelDealerAccessoryPrice_AM__c, Interior_Color__c, Exterior_Color__c, Transmission_TXT__c,
Address_Street__c, Model_ID__c, 
State, Marketing_Campaign_Name__c, Make_TXT__c, Year_YR__c, ConvertedOpportunityId, LastName, Source_Name__c,
Division_CD__c, 
Address, street,City, PostalCode, Email, PreferredDealerAccount_ID__c, PreferredDealerNumber_NUM__c, 
LeadProvider_ID__r.Send_Customer_Acknowledgement_Email_Flag__c From Lead where SubDiv_TXT__c='Honda' 
AND isConverted = true AND Send_confirmation_Email__c = true AND
LeadProvider_ID__r.Send_Customer_Acknowledgement_Email_Flag__c= true AND Id IN : leadIds];*/
        
         
        
        
        
        //  HelmsOpportunityNotificationSms.OpportunityCreation(oppList);      
        if (test.isRunningTest()){
     
        Test.setMock(HttpCalloutMock.class, new UploadFileMock());
        Test.startTest();
       HELMSeShoppingSendNotification.eshoppingAPi(leadList);
        Test.stopTest();
                   
        }
    }
    
}