objects/Account.object
<CustomObject>
    <fields>
        <fullName>DealerCode_CD__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <description>Used for Provider Records</description>
        <label>Provider</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ContactKey_TXT__c</fullName>
        <label>Contact Key</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_ECRM_Update_Done__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is ECRM Update Done</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Location_Enrichment_Done__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Location Enrichment Done</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Provider</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Lead Provider)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreferredDealerAccount_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesRelatedDealerNumber__c</fullName>
        <description>SalesRelatedDealerNumber</description>
        <label>SalesRelatedDealerNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceRelatedDealerNumber__c</fullName>
        <description>ServiceRelatedDealerNumber</description>
        <label>Service Related Dealer Number</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>Subdivision</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division_CD__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/HelmsEconfigServiceTest.cls
@IsTest
public class HelmsEconfigServiceTest {
    
    public static testMethod void testPostCallout() {
        Set<Id> setId = new Set<ID>();
        Account ac1 = new Account(name ='abc' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert ac1;
        //Lead lead1 = new Lead(LastName='Mohann',FirstName='Johnn',Is_Location_Enrichment_Done__c=false,SalesRelatedDealerNumber__c = '',ServiceRelatedDealerNumber__c = '',Email='MohanJohnn@gmail.com',PostalCode='90503',Division_CD__c='A',SubDiv_TXT__c='Honda',LeadProvider_ID__c = ac1.id);
        Lead lead1 = new Lead(LastName='Mohan',FirstName='John',Latitude=39.850583,Longitude=-74.90814,Email='MohanJohn@gmail.com',PostalCode='90503',Division_CD__c='A',SubDiv_TXT__c='Honda',LeadProvider_ID__c = ac1.id);
        insert lead1;
        lead1.ContactKey_TXT__c = 'H12345678';
        lead1.Is_ECRM_Update_Done__c = true; 
        setId.add(lead1.id);
        Test.setMock(HttpCalloutMock.class, new HelmsEconfigServiceMockTest());  
		Test.startTest();
        HelmsEconfigService.econfigAPI(setId);
        Test.stopTest();
    }
    
    
    /*
	public static testMethod void insertLeadForDealerLocator(){
        List<Account> alist = new List<Account>();
        Account ac1 = new Account(name ='abc' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert ac1;
        Account ac2 = new Account(name ='Graz33itti' ,ShippingLatitude = 39.07805, ShippingLongitude=-76.94588,DealerCode_CD__c='206772',recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()) ;
        insert ac2;
        Account ac3 = new Account(name ='Graz33it' ,ShippingLatitude = 39.89801, ShippingLongitude=-74.93263,DealerCode_CD__c='206765',recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()) ;
        insert ac3;
        List<Lead> newvalues = new List<Lead>();    
        //Lead lead = new Lead(LastName='Mohan',FirstName='John',Latitude=33.840222,Longitude=-118.353171,SalesRelatedDealerNumber__c = '206772',ServiceRelatedDealerNumber__c = '206765',PreferredDealerAccount_ID__c=ac2.id,Email='MohanJohn@gmail.com',PostalCode='90503',Division_CD__c='A',SubDiv_TXT__c='Honda',LeadProvider_ID__c = ac1.id);
        Lead lead1 = new Lead(LastName='Mohan',FirstName='John',Latitude=39.850583,Longitude=-74.90814,SalesRelatedDealerNumber__c = '206772',ServiceRelatedDealerNumber__c = '206765',PreferredDealerAccount_ID__c=ac2.id,Email='MohanJohn@gmail.com',PostalCode='08053',Division_CD__c='A',SubDiv_TXT__c='Honda',LeadProvider_ID__c = ac1.id);
        Lead lead2 = new Lead(LastName='Mohann',FirstName='Johnn',Latitude=39.850583,Longitude=-74.90814,SalesRelatedDealerNumber__c = '206765',ServiceRelatedDealerNumber__c = '206772',PreferredDealerAccount_ID__c=ac3.id,Email='MohanJohnn@gmail.com',PostalCode='08053',Division_CD__c='A',SubDiv_TXT__c='Honda',LeadProvider_ID__c = ac1.id);
        Lead lead3 = new Lead(LastName='Mohann',FirstName='Johnn',Latitude=39.850583,Longitude=-74.90814,SalesRelatedDealerNumber__c = '',ServiceRelatedDealerNumber__c = '',Email='MohanJohnn@gmail.com',PostalCode='08053',Division_CD__c='A',SubDiv_TXT__c='Honda',LeadProvider_ID__c = ac1.id);
        newvalues.add(lead1);
        newvalues.add(lead2);
        newvalues.add(lead3);
        insert newvalues;
        //lead.ContactKey_TXT__c = 'H123456';
        lead1.ContactKey_TXT__c = 'E014607139';
        lead2.ContactKey_TXT__c = 'E014607138';
        lead3.ContactKey_TXT__c = 'H014607138';
        //lead.PreferredDealerNumber_NUM__c = '206772';
        //lead.SalesRelatedDealerNumber__c = '206772';
        //lead.ServiceRelatedDealerNumber__c = '206765';
        lead1.Is_ECRM_Update_Done__c = true;
        lead2.Is_ECRM_Update_Done__c = true;
        lead3.Is_ECRM_Update_Done__c = true;
        update lead1;
        update lead2;
        update lead3;
    }*/
}