objects/Account.object
<CustomObject>
    <fields>
        <fullName>DealerCode_CD__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <description>Used for Provider Records</description>
        <label>Provider</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>AcuraCurrentProductsOwned2_TXT__c</fullName>
        <label>Acura Current Products Owned 2</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AcuraCurrentProductsOwned_TXT__c</fullName>
        <label>Acura Current Products Owned</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AcuraHighValueTrimlinePropensity_NUM__c</fullName>
        <label>Acura High Value Trimline Propensity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AcuraOwnershipStatusHousehold_TXT__c</fullName>
        <label>Acura Ownership Status Household</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AcuraOwnershipStatus_TXT__c</fullName>
        <label>Acura Ownership Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Error_CD__c</fullName>
        <label>Address Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Error_Description_TXT__c</fullName>
        <label>Address Error Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Address_Status_TXT__c</fullName>
        <label>Address Status</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Cell_Phone_Error_CD__c</fullName>
        <label>Mobile Phone Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cell_Phone_Error_Description_TXT__c</fullName>
        <label>Mobile Phone Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CleansedAddress_TXT__c</fullName>
        <label>Cleansed Address</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CustomerAccount_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Customer Account)</relationshipLabel>
        <relationshipName>Leads2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateofLastService_DT__c</fullName>
        <label>Date of Last Service</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_CheckedDate_TXT__c</fullName>
        <label>Email Checked Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Error_CD__c</fullName>
        <label>Email Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Error_Description_TXT__c</fullName>
        <label>Email Error Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Error_CD__c</fullName>
        <label>Home Phone Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Error_Description_TXT__c</fullName>
        <label>Phone Error Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HondaCurrentProductsOwned2_TXT__c</fullName>
        <label>Honda Current Products Owned 2</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HondaCurrentProductsOwned_TXT__c</fullName>
        <label>Honda Current Products Owned</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HondaHighValueTrimlinePropensity_NUM__c</fullName>
        <label>Honda High Value Trimline Propensity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HondaOwnershipStatusHousehold_TXT__c</fullName>
        <label>Honda Ownership Status Household</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HondaOwnershipStatus_TXT__c</fullName>
        <label>Honda Ownership Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Provider</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Lead Provider)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_SF_ID__c</fullName>
        <label>Lead SF ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Description_TXT__c</fullName>
        <label>Location Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Location_Error_CD__c</fullName>
        <label>Location Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Error_Description_TXT__c</fullName>
        <label>Location Error Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Location_Status_TXT__c</fullName>
        <label>Location Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Error_CD__c</fullName>
        <label>Model Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredDealerAccount_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>Subdivision</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division_CD__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Triggertypecode__c</fullName>
        <label>Trigger Type Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Instant</fullName>
                    <default>true</default>
                    <label>Instant</label>
                </value>
                <value>
                    <fullName>Future</fullName>
                </value>
                <value>
                    <fullName>FixedDate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ValidAddress_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valid Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ValidEmail_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valid Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ValidMobile_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valid Mobile Number</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ValidPhoneNum_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valid Phone Number</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead_Enrichment_Response__e.object
<CustomObject>
    <fields>
        <fullName>AcuraCurrentProductsOwned2_TXT__c</fullName>
        <label>Acura Current Products Owned 2</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AcuraCurrentProductsOwned_TXT__c</fullName>
        <label>Acura Current Products Owned</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AcuraHighValueTrimlinePropensity_NUM__c</fullName>
        <label>Acura High Value Trimline Propensity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AcuraOwnershipStatusHousehold_TXT__c</fullName>
        <label>Acura Ownership Status Household</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AcuraOwnershipStatus_TXT__c</fullName>
        <label>Acura Ownership Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Error_CD__c</fullName>
        <label>Address Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Error_Description_TXT__c</fullName>
        <label>Address Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Address_Status_TXT__c</fullName>
        <label>Address Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cell_Phone_Error_CD__c</fullName>
        <description>Cell Phone Error Code</description>
        <label>Cell Phone Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cell_Phone_Error_Description_TXT__c</fullName>
        <description>Cell Phone Error Description</description>
        <label>Cell Phone Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CleansedAddress_TXT__c</fullName>
        <label>Cleansed Address</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DateofLastService_DT__c</fullName>
        <label>Date of Last Service</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_CheckedDate_TXT__c</fullName>
        <label>Email Checked Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Error_CD__c</fullName>
        <label>Email Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Error_Description_TXT__c</fullName>
        <label>Email Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Error_CD__c</fullName>
        <label>Home Phone Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Error_Description_TXT__c</fullName>
        <label>Home Phone Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HondaCurrentProductsOwned2_TXT__c</fullName>
        <label>Honda Current Products Owned 2</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HondaCurrentProductsOwned_TXT__c</fullName>
        <label>Honda Current Products Owned</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HondaHighValueTrimlinePropensity_NUM__c</fullName>
        <label>Honda High Value Trimline Propensity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HondaOwnershipStatusHousehold_TXT__c</fullName>
        <label>Honda Ownership Status Household</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HondaOwnershipStatus_TXT__c</fullName>
        <label>Honda Ownership Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_SF_ID__c</fullName>
        <label>Lead SF ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Description_TXT__c</fullName>
        <label>Location Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Location_Error_CD__c</fullName>
        <label>Location Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Error_Description_TXT__c</fullName>
        <label>Location Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Location_Status_TXT__c</fullName>
        <label>Location Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValidAddress_FLG__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Valid Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ValidEmail_FLG__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Valid Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ValidPhoneNum_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valid Phone Number</label>
        <type>Checkbox</type>
    </fields>
    <label>Lead Enrichment Response</label>
    <pluralLabel>Lead Enrichment Response</pluralLabel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/HELMSLeadEnrichmentResponsePEHandlerTest.cls
@isTest
public class HELMSLeadEnrichmentResponsePEHandlerTest {
    @isTest static void leadenrichment()
    {
        Id personAccRecType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        //Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Provider').getRecordTypeId();
        Account personAccTest = new Account(FirstName='Test Person Account',LastName='person',RecordTypeId=personAccRecType);
        Insert personAccTest;
        Account ac1 = new Account(name ='Graz33itti' ,DealerCode_CD__c='301515', recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()) ;
        insert ac1; 
        Account ac2 = new Account(name ='abc' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert ac2;
        Lead ldRec1 = new Lead(FirstName='Test First',LastName='LastName',ValidEmail_FLG__c=true,
                              ValidPhoneNum_FLG__c=true,ValidAddress_FLG__c=true,ValidMobile_FLG__c=true,
                              CustomerAccount_ID__c=personAccTest.Id,Division_CD__c='A',PostalCode='12341',
                              SubDiv_TXT__c='Honda',PreferredDealerAccount_ID__c=ac1.id,LeadProvider_ID__c=ac2.id,
                              Triggertypecode__c='Instant');
        insert ldRec1;
        List<Lead> leadList = new List<Lead>();
        leadList.add(ldRec1);
        Lead_Enrichment_Response__e leadcreation=new Lead_Enrichment_Response__e(AcuraCurrentProductsOwned_TXT__c='1234',
                                                                    AcuraCurrentProductsOwned2_TXT__c='1234',
                                                                    AcuraHighValueTrimlinePropensity_NUM__c=1234,
                                                                    AcuraOwnershipStatus_TXT__c='1234',
                                                                    AcuraOwnershipStatusHousehold_TXT__c='Honda',
                                                                    Address_Error_CD__c='1234',
                                                                    Address_Error_Description_TXT__c='1234',
                                                                    Address_Status_TXT__c ='A',
                                                                    Cell_Phone_Error_CD__c ='345r6', 
                                                                    Cell_Phone_Error_Description_TXT__c='2345678',
                                                                    CleansedAddress_TXT__c='test',
                                                                    DateofLastService_DT__c = System.today(),
                                                                    Email_CheckedDate_TXT__c ='test',
                                                                    Email_Error_CD__c='test',
                                                                    Email_Error_Description_TXT__c ='test',
                                                                    Home_Phone_Error_CD__c='test',
                                                                    Home_Phone_Error_Description_TXT__c='test',
                                                                    HondaCurrentProductsOwned_TXT__c='test',
                                                                    HondaCurrentProductsOwned2_TXT__c='test',
                                                                    HondaHighValueTrimlinePropensity_NUM__c=1234,
                                                                    HondaOwnershipStatus_TXT__c='test',
                                                                    HondaOwnershipStatusHousehold_TXT__c='test',
                                                                    Lead_SF_ID__c=ldRec1.Lead_SF_ID__c,
                                                                    Location_Description_TXT__c ='FinancialDetails',
                                                                    Location_Error_CD__c ='FN',
                                                                    Location_Error_Description_TXT__c = 'LN',
                                                                    Location_Status_TXT__c = 'MN',
                                                                    Model_Error_CD__c = 's',
                                                                    Model_Error_Description_TXT__c = 'abcd',
                                                                    Model_IMG__c = 'bedc',
                                                                    Model_Name_NM__c = 'cdef',
                                                                    PECurrentProductsOwned_TXT__c = '522201',
                                                                    PEOwnershipStatus_TXT__c = 'abcd@gmail.com',
                                                                    PEOwnershipStatusHousehold_TXT__c = '8679876',
                                                                    PreferredDealerNumber_NUM__c = '123456',
                                                                    PSPCurrentProductsOwned_TXT__c = 'abcdef',
                                                                    PSPCurrentProductsOwned2_TXT__c = '12345',
                                                                    PSPOwnershipStatus_TXT__c ='abcde',
                                                                    PSPOwnershipStatusHousehold_TXT__c = '12345',
                                                                    SalesRelatedDealerNumber__c = 'abcd',
                                                                    ServiceRelatedDealerNumber__c = 'standard',
                                                               //     SFMC_description_TXT__c = 'abcd',
                                                               //     SFMC_errorcode_TXT__c = 'abcd',
                                                               //     SFMC_errordescription_TXT__c = 'abcd',
                                                               //     SFMC_status_TXT__c = 'abcd',
                                                                    
                                                                 //   SFMC_Sales_status__c = 'abcd',
                                                                    SFMC_Sales_status__c = 'abcd',
                                                                    SFMC_Sales_description__c = 'abcd',
                                                                    SFMC_Sales_errorcode__c = 'abcd',
                                                                    SFMC_Sales_errordescription__c = 'abcd',
                                                                    SFMC_Service_status__c = 'abcd',
                                                                    SFMC_Service_description__c = 'abcd',
                                                                    SFMC_Service_errordescription__c = 'abcd',
                                                                    SFMC_Service_errorcode__c = 'abcd',             
                                                                    ValidAddress_FLG__c = true,
                                                                    ValidCellPhone_FLG__c = true,
                                                                    ValidEmail_FLG__c = true,
                                                                    Valid_Model_ID_FLG__c = true,
                                                                    ValidPhoneNum_FLG__c = true,
                                                                    YourDealershipServicesLast60Mths_NUM__c = 0,
                                                                    YourDealershipSvsSpentLast60Mth_NUM__c = 0
                     );
        Test.startTest();
        EventBus.publish(leadcreation);
        HELMSLeadEnrichmentResponsePEHandler.updateCustomObject(leadList);
        System.assertEquals(ldRec1.LastName, 'LastName');
        Test.stopTest();    
    }
}