objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active_Divisions__c</fullName>
        <label>Active Divisions</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DealerCRMVendor_TXT__c</fullName>
        <label>Dealer CRM Vendor</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CRM_System__c.object
<CustomObject>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ISActive_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <label>CRM System</label>
    <nameField>
        <label>CRM System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRM Systems</pluralLabel>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Dealer_Division__c.object
<CustomObject>
    <description>list of active or inactive division, subdivision, zone, district and other territory related fields based on their business use for Sales, Service, Parts, etc.</description>
    <fields>
        <fullName>Dealer_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Subdivision</relationshipLabel>
        <relationshipName>Dealer_Divisions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesZone_CD__c</fullName>
        <label>Sales Zone</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive_FLG__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Dealer Subdivision</label>
    <nameField>
        <displayFormat>DD-{0}</displayFormat>
        <label>Dealer Division Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Divisions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Dealer_Participation__c.object
<CustomObject>
    <fields>
        <fullName>CRM_System__c</fullName>
        <label>CRM System</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Division__c</field>
                <operation>equals</operation>
                <valueField>CRM_System__c.Division_CD__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CRM_System__c</referenceTo>
        <relationshipLabel>Dealer Participations</relationshipLabel>
        <relationshipName>Dealer_Participations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DealerAccount_ID__c</fullName>
        <label>Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Participations</relationshipLabel>
        <relationshipName>Dealer_Participations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ISActive_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <formula>(LeadReceivingStartDate_DT__c  &lt;=  NOW() &amp;&amp;  LeadReceivingEndDate_DT__c  &gt;  NOW() ) || (LeadReceivingStartDate_DT__c  &lt;=  NOW() &amp;&amp;  ISBLANK(LeadReceivingEndDate_DT__c ) ) || (ISBLANK(LeadReceivingStartDate_DT__c ) &amp;&amp; LeadReceivingEndDate_DT__c  &gt;  NOW() )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Dealer Participation</label>
    <nameField>
        <label>Dealer Participation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Logs__c.object
<CustomObject>
    <fields>
        <fullName>Error_Line_Number__c</fullName>
        <label>Error Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>130768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Trigger_or_Class_Name__c</fullName>
        <label>Trigger or Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Logs</label>
    <nameField>
        <label>Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

classes/HELMSAccountInfoDailyBatch.cls
/*This Class is used to update Active Division Field on Account based on Related Dealer Subdivision Record with Divison 
Field & SalesZone Field values concate and update */
public class HELMSAccountInfoDailyBatch implements Database.Batchable<sobject>,Schedulable {
	//Start Method - Query to Fetch all Dealer Account Records
    public Database.QueryLocator start(Database.BatchableContext bc){
        string query='select id,Active_Divisions__c,DealerCRMVendor_TXT__c from Account where RecordType.DeveloperName =\'Dealer\' ';
        return Database.getQueryLocator(query);  
    }
    //Execute Method - Getting Dealer Participation & Divisions Records
    public void execute(Database.BatchableContext bc,List<Account> scope){
        try{
            List<Account> updateaccountlist= new List<Account>();
            /*
            List<Dealer_Division__c> activedivisionlst = new List<Dealer_Division__c>([Select id,Division_CD__c from Dealer_Division__c where Dealer_ID__c IN:Scope and 	isActive_FLG__c=true ]);
            List<Dealer_Participation__c> activedlrparticipationlst = new List<Dealer_Participation__c>([Select id from Dealer_Participation__c where 	DealerAccount_ID__c IN:Scope and Is_Active__c=true ]);
            Map<id,List<Dealer_Division__c>> accountdivMap = new Map<id,List<Dealer_Division__c>>();
            Map<id,List<Dealer_Participation__c>> accountdlrpartMap = new Map<id,List<Dealer_Participation__c>>();
            for (Dealer_Division__c div :activedivisionlst){
                if(accountdivMap.containsKey(div.Dealer_ID__c)){
                    accountdivMap.get(div.Dealer_ID__c).add(div);
                }
                else{
                    accountdivMap.put(div.Dealer_ID__c,new List<Dealer_Division__c> {div});
                    accountdivMap.get(div.Dealer_ID__c).add(div);
                }
            }
            for (Dealer_Participation__c dpt :activedlrparticipationlst){
                if(accountdlrpartMap.containsKey(dpt.DealerAccount_ID__c)){
                    accountdlrpartMap.get(dpt.DealerAccount_ID__c).add(dpt);
                }
                else{
                    accountdlrpartMap.put(dpt.DealerAccount_ID__c,new List<Dealer_Participation__c> {dpt});
                    accountdlrpartMap.get(dpt.DealerAccount_ID__c).add(dpt);
                }
            }
            */
            List<Dealer_Division__c> activedivisionlst = new List<Dealer_Division__c>([Select id,Division_CD__c,SalesZone_CD__c,Dealer_ID__c from Dealer_Division__c where Dealer_ID__c IN:scope and isActive_FLG__c=true order by createddate]);
            List<Dealer_Participation__c> activedlrparticipationlst = new List<Dealer_Participation__c>([Select id,CRM_System__r.name,DealerAccount_ID__c from Dealer_Participation__c where 	DealerAccount_ID__c IN:scope and Is_Active__c=true order by createddate]);
            Map<id,List<string>> accountdivMap = new Map<id,List<string>>();
            Map<id,List<string>> accountdlrpartMap = new Map<id,List<string>>();
            for (Dealer_Division__c div :activedivisionlst){
                if(accountdivMap.containsKey(div.Dealer_ID__c)){
                    accountdivMap.get(div.Dealer_ID__c).add(div.Division_CD__c+div.SalesZone_CD__c);
                }
                else{
                    accountdivMap.put(div.Dealer_ID__c,new List<string> {div.Division_CD__c+div.SalesZone_CD__c});
                    //accountdivMap.get(div.Dealer_ID__c).add(div.Division_CD__c + div.SalesZone_CD__c);
                }
            }
            
            for (Dealer_Participation__c dpt :activedlrparticipationlst){
                if(accountdlrpartMap.containsKey(dpt.DealerAccount_ID__c)){
                    accountdlrpartMap.get(dpt.DealerAccount_ID__c).add(dpt.CRM_System__r.name);
                }
                else{
                    accountdlrpartMap.put(dpt.DealerAccount_ID__c,new List<string> {dpt.CRM_System__r.name});
                    //accountdlrpartMap.get(dpt.DealerAccount_ID__c).add(dpt);
                }
            }
            
            for(Account acc: Scope){
                string activedivisions='';
                string activedlrparticipations='';
                boolean changeflag=false;
                if(accountdivMap.get(acc.id)!=null){
                    activedivisions=string.join(accountdivMap.get(acc.id),',');
                }
                if(accountdlrpartMap.get(acc.id)!=null){
                    activedlrparticipations=string.join(accountdlrpartMap.get(acc.id),',');
                }
                //system.debug('Active divisions='+activedivisions);
                //system.debug('Active CRM Names='+activedlrparticipations);
                if(acc.Active_Divisions__c!=activedivisions){
                    acc.Active_Divisions__c=activedivisions;
                    changeflag=true;
                }
                if( acc.DealerCRMVendor_TXT__c!=activedlrparticipations){
                    acc.DealerCRMVendor_TXT__c=activedlrparticipations;
                    changeflag=true;
                }
                if(changeflag){
                    updateaccountlist.add(acc);    
                }
            }
            if(updateaccountlist.Size()>0){
            Database.update(updateaccountlist); 
            }
        }Catch(exception ex){
            Logs__c  l =new Logs__c (name='HELMSAccountInfoDailyBatch',Trigger_or_Class_Name__c='HELMSAccountInfoDailyBatch', Error_Message__c =ex.getMessage(), Error_Line_Number__c =Integer.valueOf(string.valueof(ex.getLineNumber() )) );
            insert l;
            
        }
        
    }
    //Finish Method
    public void finish(Database.BatchableContext bc){
        
    }
    //Executing the Batch Job
    public void execute(SchedulableContext sc){
        HELMSAccountInfoDailyBatch cs= new HELMSAccountInfoDailyBatch();
        id jobID=Database.executebatch(cs);
        
    }

}