objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact_Key__c</fullName>
        <label>Contact Key</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DealerCode_CD__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Customer_Enrichment__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Key__c</fullName>
        <externalId>true</externalId>
        <label>Contact Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Account_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Identifier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Enrichments</relationshipLabel>
        <relationshipName>Customer_Enrichments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Customer Enrichment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Customer Enrichment  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Enrichments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ContactKey_TXT__c</fullName>
        <label>Contact Key</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name_TXT__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name_TXT__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_NM__c</fullName>
        <label>Vin Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sale_Confirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Sale has been registered with Honda.</inlineHelpText>
        <label>Registration Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ZipCode_TXT__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RDR_Sales__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Address_ZIP_Code_TXT__c</fullName>
        <label>Customer Address ZIP Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_First_Name_NUM__c</fullName>
        <label>Customer First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Last_Name_NM__c</fullName>
        <label>Customer Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Number_NUM__c</fullName>
        <label>Dealer Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_id_TXT__c</fullName>
        <label>Email id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Date_DT__c</fullName>
        <label>Sales Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Serial_Number_NUM__c</fullName>
        <label>Serial Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Code_CD__c</fullName>
        <label>Status Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone_Number_NUM__c</fullName>
        <label>Telephone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Vin_TXT__c</fullName>
        <label>Vin</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XPROD_DIV_CD__c</fullName>
        <label>XPROD-DIV-CD</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isProcessed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isUnwind__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isUnwind</label>
        <type>Checkbox</type>
    </fields>
    <label>RDR Sales</label>
    <nameField>
        <displayFormat>RDR Sales - {00000000}</displayFormat>
        <label>RDR Sales</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RDR Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/MatchbackTest.cls
@isTest 
public class MatchbackTest 
{
    static testMethod void testMethod1() 
    {
 opportunity opp= new opportunity(Stagename='Assigned to Dealer',Name='SLA test class', 
          Email__c='call.bijay1@gmail.com', ZipCode_TXT__c='12345', 
        First_Name_TXT__c='John', Last_Name_TXT__c='kiran',Phone__c='1234567890',Serial_Number__c='1111',Number_NM__c='1212',
                                  Sale_Confirmation__c=false,Division_CD__c='P',SubDiv_TXT__c='PowerEquipment',PreferredDealerNumber_NUM__c='2222',ContactKey_TXT__c='H12344');
        opp.CreatedDate= system.now();
        opp.CloseDate= system.Today();
        
        insert opp;
RDR_Sales__c rdr = new RDR_Sales__c(Customer_First_Name_NUM__c='John',Customer_Last_Name_NM__c='kiran',
                                    Email_id_TXT__c='call.bijay1@gmail.com'
                                   ,Status_Code_CD__c='03',isProcessed__c=false,
                                    Dealer_Number_NUM__c='2222',
                                    Customer_Address_ZIP_Code_TXT__c='12345',Telephone_Number_NUM__c='1234567890'
                                   ,XPROD_DIV_CD__c='P',Serial_Number_NUM__c='1111',Vin_TXT__c='1212',Sales_Date_DT__c=system.today()-1);        
        
        insert rdr;
        Test.startTest();

            Matchback obj = new Matchback();
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
    }
    
        static testMethod void testMethod2() 
    {
 opportunity opp1= new opportunity(Stagename='Assigned to Dealer',Name='SLA test class', 
          Email__c='call.bijay1@gmail.com', ZipCode_TXT__c='12345', 
        First_Name_TXT__c='John', Last_Name_TXT__c='kiran',Phone__c='1234567890',
                                  Sale_Confirmation__c=false,Serial_Number__c='1111',Number_NM__c='1212'
                                   ,Division_CD__c='P',
                                   SubDiv_TXT__c='PowerEquipment'
                                 ,PreferredDealerNumber_NUM__c='2222768671',ContactKey_TXT__c='H12344');
        opp1.CreatedDate= system.now();
        opp1.CloseDate= system.today();
        insert opp1;
        
        opportunity opp11= new opportunity(Stagename='Assigned to Dealer',Name='SLA test class', 
          Email__c='call.bijay2@gmail.com', ZipCode_TXT__c='12345', 
        First_Name_TXT__c='thom', Last_Name_TXT__c='thom',Phone__c='1234567890',
                                  Sale_Confirmation__c=false,Serial_Number__c='1111',Number_NM__c='1212'
                                   ,Division_CD__c='P',
                                   SubDiv_TXT__c='PowerEquipment'
                                 ,PreferredDealerNumber_NUM__c='222',ContactKey_TXT__c='H12344');
        opp11.CreatedDate= system.now();
        opp11.CloseDate= system.today();
        insert opp11;
        
RDR_Sales__c rdr2 = new RDR_Sales__c(Customer_First_Name_NUM__c='John',Customer_Last_Name_NM__c='kiran',Email_id_TXT__c='call.bijay1@gmail.com'
                                   ,Status_Code_CD__c='03',isProcessed__c=false,
                                    Dealer_Number_NUM__c='2222136363',
                                    Customer_Address_ZIP_Code_TXT__c='12345',Telephone_Number_NUM__c='1234567890'
                                   ,XPROD_DIV_CD__c='P',Serial_Number_NUM__c='1111',Vin_TXT__c='1212',Sales_Date_DT__c=system.today()-1);        
         insert rdr2;
        RDR_Sales__c rdr21 = new RDR_Sales__c(Customer_First_Name_NUM__c='Thom',Customer_Last_Name_NM__c='Thom',Email_id_TXT__c='call.Tom@gmail.com'
                                   ,Status_Code_CD__c='03',isProcessed__c=false,
                                    Dealer_Number_NUM__c='22245747214',
                                    Customer_Address_ZIP_Code_TXT__c='12345',Telephone_Number_NUM__c='1234567890'
                                   ,XPROD_DIV_CD__c='P',Serial_Number_NUM__c='1111',Vin_TXT__c='1212',Sales_Date_DT__c=system.today()-1);        
         insert rdr21;
        Test.startTest();

            Matchback obj = new Matchback();
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
    }
    
            static testMethod void testMethod3() 
    {
        Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Id dealerAccRecTypeId1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
         Account accTestRec = new Account(Contact_Key__c='12345',Name='Test Account123another',DealerCode_CD__c = '123',RecordTypeId=dealerAccRecTypeId
                                         );
        insert accTestRec;
        Customer_Enrichment__c cu = new Customer_Enrichment__c(Contact_Key__c='12345',Customer_Account_Id__c=accTestRec.Id);
        insert cu;
 opportunity opp1= new opportunity(Stagename='Assigned to Dealer',Name='SLA test class', 
          Email__c='call.bijay1@gmail.com', ZipCode_TXT__c='12345', 
        First_Name_TXT__c='John', Last_Name_TXT__c='kiran',Phone__c='',
                                  Sale_Confirmation__c=false,Serial_Number__c='1111',Number_NM__c='1212'
                                   ,Division_CD__c='P',
                                   SubDiv_TXT__c='PowerEquipment'
                                 ,PreferredDealerNumber_NUM__c='222212',ContactKey_TXT__c='12345');
        opp1.CreatedDate= system.now();
        opp1.CloseDate= system.today();
        insert opp1;
        
        opportunity opp13= new opportunity(Stagename='Assigned to Dealer',Name='SLA test class', 
          Email__c='call.bijay1@gmail.com', ZipCode_TXT__c='12345', 
        First_Name_TXT__c='John1e', Last_Name_TXT__c='kirann',Phone__c='1234567890',
                                  Sale_Confirmation__c=false,Serial_Number__c='1111',Number_NM__c='1212'
                                   ,Division_CD__c='P',
                                   SubDiv_TXT__c='PowerEquipment'
                                 ,PreferredDealerNumber_NUM__c='22221',ContactKey_TXT__c='1234543');
        opp13.CreatedDate= system.now();
        opp13.CloseDate= system.Today();
        insert opp13;
        
RDR_Sales__c rdr2 = new RDR_Sales__c(Customer_First_Name_NUM__c='John',Customer_Last_Name_NM__c='kiran',Email_id_TXT__c='call.bijay1@gmail.com'
                                   ,Status_Code_CD__c='03',isProcessed__c=false,
                                    Dealer_Number_NUM__c='22221',
                                    Customer_Address_ZIP_Code_TXT__c='12345',Telephone_Number_NUM__c='1234567890'
                                   ,XPROD_DIV_CD__c='P',Serial_Number_NUM__c='1111',Vin_TXT__c='1212',Sales_Date_DT__c=system.today()-1);        
         insert rdr2;
        RDR_Sales__c rdr5 = new RDR_Sales__c(Customer_First_Name_NUM__c='John',Customer_Last_Name_NM__c='kiran',Email_id_TXT__c='call.bijay1@gmail.com'
                                   ,Status_Code_CD__c='03',isProcessed__c=false,
                                    Dealer_Number_NUM__c='22227',
                                    Customer_Address_ZIP_Code_TXT__c='12345',Telephone_Number_NUM__c='1234567890'
                                   ,XPROD_DIV_CD__c='P',Serial_Number_NUM__c='1111',Vin_TXT__c='1212',Sales_Date_DT__c=system.today()-1);        
         insert rdr5;
        
     /*  RDR_Sales__c rdr3 = new RDR_Sales__c(Customer_First_Name_NUM__c='John',Customer_Last_Name_NM__c='kiran',Email_id_TXT__c='call.bijay1@gmail.com'
                                   ,Status_Code_CD__c='04',isProcessed__c=true,
                                    Dealer_Number_NUM__c='222213',isUnwind__c=true,
                                    Customer_Address_ZIP_Code_TXT__c='12345',Telephone_Number_NUM__c='1234567890'
                                   ,XPROD_DIV_CD__c='P',Serial_Number_NUM__c='1111',Vin_TXT__c='1212',Sales_Date_DT__c=system.today()-1);        
         insert rdr3;*/
        
        List<Id> rdrList = new List<Id> ();
        rdrList.add(rdr2.Id);
        Test.startTest();

        Matchback obj = new Matchback();
        DataBase.executeBatch(obj); 
            
        Test.stopTest();
    }
    
    static testMethod void testMethod4() 
    {
         opportunity opp= new opportunity(Stagename='Assigned to Dealer',Name='SLA test class', 
           ZipCode_TXT__c='12345',Email__c='call.bijay1@gmail.com',
        First_Name_TXT__c='John', Last_Name_TXT__c='kiran',Sale_Confirmation__c=false,Division_CD__c='P',
        SubDiv_TXT__c='PowerEquipment',PreferredDealerNumber_NUM__c='2222',ContactKey_TXT__c='1234543');
                                  
                                  
        opp.CreatedDate= system.now();
        opp.CloseDate= system.Today();
        
        insert opp;
RDR_Sales__c rdr = new RDR_Sales__c(Customer_First_Name_NUM__c='John',Customer_Last_Name_NM__c='kiran',
                                    Status_Code_CD__c='03',isProcessed__c=false,
                                    Dealer_Number_NUM__c='2222',
                                    Email_id_TXT__c='call.bijay1@gmail.com',
                                    Customer_Address_ZIP_Code_TXT__c='12'
                                   ,XPROD_DIV_CD__c='P',Serial_Number_NUM__c='1111',Vin_TXT__c='1212',Sales_Date_DT__c=system.today()-1);  
        insert rdr;
        Test.startTest();

            Matchback obj = new Matchback();
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
    }
    
}