objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact_Key__c</fullName>
        <label>Contact Key</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DealerCode_CD__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>LeadAdditionalInfos__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-1950 Story name.
Description: This is store the Offers XML Data.
Source System: Coming from Integration.
Integration: Yes.
Data Transformation: N/A.
Functional Definition: This will be Stored Offers Data.</description>
        <label>LeadAdditionalInfos</label>
        <length>118216</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Model_TXT__c</fullName>
        <label>Model</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PreferredDealerAccount_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead_Additional_Attribute__c.object
<CustomObject>
    <fields>
        <fullName>Attribute_Value__c</fullName>
        <label>Attribute Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lead Additional Attribute</label>
    <nameField>
        <label>Lead Additional Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Additional Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead_Additional_Attribute_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Shared_With_Dealer__c</fullName>
        <label>Shared With Dealer</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TRUE</fullName>
                </value>
                <value>
                    <fullName>FALSE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lead Additional Attribute Definition</label>
    <nameField>
        <label>Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Additional Attribute Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name_TXT__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name_TXT__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeadAdditionalInfos__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-1950 Story name.
Description: This is store the Offers XML Data.
Source System: Coming from Integration.
Integration: Yes.
Data Transformation: N/A.
Functional Definition: This will be Stored Offers Data.</description>
        <label>LeadAdditionalInfos</label>
        <length>118216</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Model_TXT__c</fullName>
        <label>Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityStatus_TXT__c</fullName>
        <label>Opportunity Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned/Routed to Dealer</fullName>
                </value>
                <value>
                    <fullName>Auto-response sent</fullName>
                </value>
                <value>
                    <fullName>Lead Opened</fullName>
                </value>
                <value>
                    <fullName>Lead Received</fullName>
                </value>
                <value>
                    <fullName>Customer phoned (Inbound phone)</fullName>
                </value>
                <value>
                    <fullName>Customer emailed (Inbound email)</fullName>
                </value>
                <value>
                    <fullName>Salesperson responded by Email</fullName>
                </value>
                <value>
                    <fullName>Salesperson responded by Phone</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson responded by email</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson responded by Phone</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson request another appointment by email</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson request another appointment by phone</fullName>
                </value>
                <value>
                    <fullName>Credit Application</fullName>
                </value>
                <value>
                    <fullName>Credit Application (3rd party)</fullName>
                </value>
                <value>
                    <fullName>Trade-In Appraisal</fullName>
                </value>
                <value>
                    <fullName>Broadcast Email</fullName>
                </value>
                <value>
                    <fullName>Made Appointment</fullName>
                </value>
                <value>
                    <fullName>Demoed/Test Drove</fullName>
                </value>
                <value>
                    <fullName>Boat/Outboard Sales Presentation</fullName>
                </value>
                <value>
                    <fullName>Appointment Didn’t Show</fullName>
                </value>
                <value>
                    <fullName>Appointment Showed</fullName>
                </value>
                <value>
                    <fullName>Offer to Purchase</fullName>
                </value>
                <value>
                    <fullName>Model in Stock</fullName>
                </value>
                <value>
                    <fullName>Model not in Stock</fullName>
                </value>
                <value>
                    <fullName>Model on back order</fullName>
                </value>
                <value>
                    <fullName>Credit Denied</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson marked sold</fullName>
                </value>
                <value>
                    <fullName>Salesperson marked vehicle sold</fullName>
                </value>
                <value>
                    <fullName>Lost Sales</fullName>
                </value>
                <value>
                    <fullName>Any additional vehicle sold info (delivered, punched, etc.)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PreferredDealerAccount_TXT__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Preferred Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ZipCode_TXT__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Honda</fullName>
        <active>true</active>
        <businessProcess>HELMS Sales Process</businessProcess>
        <description>Used by the Honda Team</description>
        <label>Honda Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/HELMSLeadDynamicAttributesCntrlTest.cls
@IsTest
public class HELMSLeadDynamicAttributesCntrlTest {
    @isTest private static void ldtestmethod()
    {
        Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Account accTestRec = new Account(Name='Chapman Honda',RecordTypeId=dealerAccRecTypeId,DealerCode_CD__c='123456',Contact_Key__c='E150363308'
                                        );
        insert accTestRec;
        
       	Set<id> oppList= new Set<id>();
        List<Lead> leadList=new List<Lead>();
        
         Lead leadRec = new Lead(LastName='1 NOT GIVEN',Email='sur12@testing.com',Street= '4RUNNER',
                                 Status='Manual Validation',Model_TXT__c = 'xyz',PreferredDealerAccount_ID__c=accTestRec.id,
                                 LeadAdditionalInfos__c= '<LeadAdditionalInfos><LeadAdditionalInfo key="CustomerComment">Click for Lead Info</LeadAdditionalInfo></LeadAdditionalInfos>'); 
		                  
         insert leadRec;
                
        leadList.add(leadRec);
                 
         List<Lead_Additional_Attribute__c> ldAdtnlAtrbt = new List<Lead_Additional_Attribute__c>();
		 Lead_Additional_Attribute__c laddatt = new Lead_Additional_Attribute__c();
         laddatt.Attribute_Value__c = 'Red';
         laddatt.Name = 'CustomerComment';   
         laddatt.Sequence_Number__c = 1;
         insert laddatt;
            
         ldAdtnlAtrbt.add(laddatt);
       
        List<Lead_Additional_Attribute_Definition__c> ldaddattdf = new List<Lead_Additional_Attribute_Definition__c>();
		Lead_Additional_Attribute_Definition__c ldadd = new Lead_Additional_Attribute_Definition__c();
		ldadd.Name = 'CustomerComment';
		ldadd.Shared_With_Dealer__c = 'True';
		insert ldadd;
		ldaddattdf.add(ldadd);
        
        Opportunity o = new Opportunity();
        o.name='Test';
        o.First_Name_TXT__c='OppTest';
        o.Last_Name_TXT__c='OppKiran';
        o.Email__c='kiransiddipeta1199@gmail.com';
        o.StageName='Assigned to Dealer';
        o.OpportunityStatus_TXT__c='Assigned/Routed to Dealer';
        o.CloseDate= date.parse('10/10/2021');
        o.ZipCode_TXT__c='59505';
        o.PreferredDealerAccount_TXT__c=accTestRec.id;
        
        insert o;

        oppList.add(o.id); 
        
        Test.startTest();
        system.assertEquals('OppTest', o.First_Name_TXT__c);
        HELMSLeadDynamicAttributesCntrl.createDynamicFields(leadList);
        HELMSLeadDynamicAttributesCntrl.createOpportunityAttributes(oppList);
        Test.stopTest();
        
    }
}