objects/Account.object
<CustomObject>
    <fields>
        <fullName>DealerCode_CD__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <description>Used for Provider Records</description>
        <label>Provider</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <label>Provider</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Dealer_Division__c.object
<CustomObject>
    <description>list of active or inactive division, subdivision, zone, district and other territory related fields based on their business use for Sales, Service, Parts, etc.</description>
    <fields>
        <fullName>Dealer_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Subdivision</relationshipLabel>
        <relationshipName>Dealer_Divisions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <label>Dealer Subdivision</label>
    <nameField>
        <displayFormat>DD-{0}</displayFormat>
        <label>Dealer Division Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Divisions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Color_TXT__c</fullName>
        <label>Color</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Color_XML__c</fullName>
        <label>Color XML</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exterior_Color__c</fullName>
        <label>Exterior Color</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Interior_Color__c</fullName>
        <label>Interior Color</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Provider</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Lead Provider)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreferredDealerAccount_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreferredDealerContact_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Dealer Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProviderDetail_TXT__c</fullName>
        <inlineHelpText>Source Lead Provider Name</inlineHelpText>
        <label>Provider Detail</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>Subdivision</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division_CD__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead_Division_Mapping_From_Subdivision__mdt.object
<CustomObject>
    <description>Lead SubDivision = PowerEquipment , Marine ,Engine  then Division is &apos;P&apos;

Lead SubDivision = Honda  then Division is &apos;A&apos;

SubDivision = Acura , NSX  then Division is &apos;B&apos;

SubDivision = Motorcycle then Division is &apos;M&apos;</description>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division_CD</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <label>Subdivision</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Lead_Division_Mapping_From_Subdivision</label>
    <pluralLabel>Lead_Division_Mapping_From_Subdivision</pluralLabel>
</CustomObject>

objects/Logs__c.object
<CustomObject>
    <fields>
        <fullName>Error_Line_Number__c</fullName>
        <label>Error Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>130768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Trigger_or_Class_Name__c</fullName>
        <label>Trigger or Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Logs</label>
    <nameField>
        <label>Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/HELMSLeadTriggerHandlerUpdated.cls
public class HELMSLeadTriggerHandlerUpdated {
    
    public static void handleLeadInsert(List<Lead> leadList){
        try{
            Map<String,String> SubdivisiomMap = new Map<String,String>();
            for(Lead_Division_Mapping_From_Subdivision__mdt m :[select id,Subdivision__c, Division_CD__c from Lead_Division_Mapping_From_Subdivision__mdt])
            {
                SubdivisiomMap.put(m.Subdivision__c , m.Division_CD__c);
            }
            
            List<String> pnamelist = new List<String>();
            Map<string, id> Providermap = new Map<string, id>(); 
            
            Set<String> leadPreffereddealerNumber = new Set<String>();
            for(Lead leadRec : leadList)
            {
                if(leadRec.PreferredDealerNumber_NUM__c!=null){
                    leadPreffereddealerNumber.add(leadRec.PreferredDealerNumber_NUM__c);
                }
                if(leadRec.PreferredDealerAccount_ID__c!=null){
                    if(leadRec.SubDiv_TXT__c !=null){
                        leadRec.Division_CD__c = SubdivisiomMap.get(leadRec.SubDiv_TXT__c);
                    }
                }
                
                if(leadRec.ProviderDetail_TXT__c!=null){ 
                    string providename =  leadRec.ProviderDetail_TXT__c;
                   
                    if(providename.contains(':')){
                        String[] pdn1 = providename.split(':');
                        if(pdn1[0]!=null){
                            pnamelist.add((pdn1[0]).toLowerCase());
                        }
                    }else{
                        pnamelist.add((leadRec.ProviderDetail_TXT__c).toLowerCase());
                                                    
                    }
                }
                if(String.isNotEmpty(leadRec.Color_TXT__c) ){
                    // leadRec.Color_XML__c to store xml value
                    if(leadRec.Color_XML__c == null ){
                        leadRec.Color_XML__c = leadRec.Color_TXT__c;
                    }
                   // leadRec.Color_TXT__c = getColorCombination(leadRec.Color_TXT__c);
                    Map<String,String> colorsInEx = getColorCombination(leadRec.Color_TXT__c);
                    leadRec.Color_TXT__c = colorsInEx.get('color');
                    leadRec.Interior_Color__c = colorsInEx.get('interior');
                    leadRec.Exterior_Color__c = colorsInEx.get('exterior');
                }
                
                
            }
            
            Id dealerAccRecTypeId2 = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId();
            for(Account a:[select id,name from account where name IN: pnamelist and RecordTypeId=:dealerAccRecTypeId2]){               
                
                Providermap.put((a.name).toLowerCase(),a.id);
                
            }
            
          //  system.debug('test '+leadPreffereddealerNumber);
            Map<String,Account> accountDealerCodeMap = new Map<String,Account>();
            Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId();
            for(Account accRec : [Select id,DealerCode_CD__c,(Select id,Name,FirstName,LastName,Email from Contacts) from Account where DealerCode_CD__c in:leadPreffereddealerNumber and
                                  RecordTypeId=:dealerAccRecTypeId
                                 ])
            {
             //   system.debug('here inside for');
                accountDealerCodeMap.put(accRec.DealerCode_CD__c,accRec);
            }
            //modified as part of CAPS-4336
            Map<String,Dealer_Division__c> dealDivMap = New Map<String,Dealer_Division__c>();
            for(Dealer_Division__c dealDiv:[select id,Division_CD__c, SubDiv_TXT__c,Dealer_ID__r.DealerCode_CD__c from Dealer_Division__c where Dealer_ID__r.DealerCode_CD__c in: accountDealerCodeMap.keySet() WITH SECURITY_ENFORCED]){
                dealDivMap.put(dealDiv.Dealer_ID__r.DealerCode_CD__c,dealDiv);
            }
            for(Lead leadRecord : leadList)
            {
                if(accountDealerCodeMap.containsKey(leadRecord.PreferredDealerNumber_NUM__c))
                {
                    leadRecord.PreferredDealerAccount_ID__c=accountDealerCodeMap.get(leadRecord.PreferredDealerNumber_NUM__c).Id;
                    //modified as part of CAPS-4336
                    if(dealDivMap.containsKey(leadRecord.PreferredDealerNumber_NUM__c))
                    	leadRecord.SubDiv_TXT__c = dealDivMap.get(leadRecord.PreferredDealerNumber_NUM__c).SubDiv_TXT__c;
                    if(leadRecord.SubDiv_TXT__c !=null){
                        leadRecord.Division_CD__c = SubdivisiomMap.get(leadRecord.SubDiv_TXT__c);
                    }
                    for(Contact conRec : accountDealerCodeMap.get(leadRecord.PreferredDealerNumber_NUM__c).Contacts)
                    {
                        //system.debug('here insidecontact '+conRec+' '+leadRecord.Name+' '+conRec.Name);
                        if(leadRecord.FirstName==conRec.FirstName && leadRecord.LastName==conRec.LastName && leadRecord.Email==conRec.Email)
                        {
                            leadRecord.PreferredDealerContact_ID__c=conRec.Id;
                            break;
                        }
                    }
                }
                if(leadRecord.ProviderDetail_TXT__c!=null){ 
                    string providename =  leadRecord.ProviderDetail_TXT__c;
                   
                    if(providename.contains(':')){
                        String[] pdn1 = providename.split(':');
                        if(pdn1[0]!=null && Providermap.containsKey((pdn1[0]).toLowerCase())){
                            leadRecord.LeadProvider_ID__c = Providermap.get((pdn1[0]).toLowerCase());
                        }
                    }else if(Providermap.containsKey((leadRecord.ProviderDetail_TXT__c).toLowerCase())){
                       leadRecord.LeadProvider_ID__c = Providermap.get((leadRecord.ProviderDetail_TXT__c).toLowerCase());
                                                    
                    }
                }
                
                
            }
        }Catch(Exception ex){
           // System.debug('Exception at line : '+ ex.getLineNumber());
          //  System.debug('Exception Message : '+ ex.getMessage());
            
            Logs__c  l =new Logs__c (name='Lead - handleLeadInsert',Trigger_or_Class_Name__c='LeadTriggerHandlerUpdated', Error_Message__c =ex.getMessage(), Error_Line_Number__c =Integer.valueOf(string.valueof(ex.getLineNumber() )) );
           insert l;
        }
    }
    
    
    public static void handleLeadUpdate(Map<Id,Lead> LeadOldMap,Map<Id,Lead> LeadNewMap)
    {
        try{
            Map<String,String> SubdivisiomMap = new Map<String,String>();
            for(Lead_Division_Mapping_From_Subdivision__mdt m :[select id,Subdivision__c, Division_CD__c from Lead_Division_Mapping_From_Subdivision__mdt])
            {
                SubdivisiomMap.put(m.Subdivision__c , m.Division_CD__c);
            }
            Set<String> leadPreffereddealerNumber = new Set<String>();
            
            List<String> pnamelist = new List<String>();
            Map<string, id> Providermap = new Map<string, id>(); 
            List<String> dealerNumbers = New List<String>();
            for(Id leadId :  LeadNewMap.keySet()){
                dealerNumbers.add(LeadNewMap.get(leadId).PreferredDealerNumber_NUM__c);
            }
            //modified as part of CAPS-4336
            Map<String,Dealer_Division__c> dealDivMap = New Map<String,Dealer_Division__c>();
            for(Dealer_Division__c dealDiv:[select id,Division_CD__c, SubDiv_TXT__c,Dealer_ID__r.DealerCode_CD__c from Dealer_Division__c where Dealer_ID__r.DealerCode_CD__c in: dealerNumbers WITH SECURITY_ENFORCED]){
                dealDivMap.put(dealDiv.Dealer_ID__r.DealerCode_CD__c,dealDiv);
            }
            for(Id leadId :  LeadNewMap.keySet())
            {
                if(LeadOldMap.get(leadId).PreferredDealerNumber_NUM__c!=LeadNewMap.get(leadId).PreferredDealerNumber_NUM__c && LeadNewMap.get(leadId).PreferredDealerNumber_NUM__c!=null)
                {
                    leadPreffereddealerNumber.add(LeadNewMap.get(leadId).PreferredDealerNumber_NUM__c);
                }
                
                if(LeadNewMap.get(leadId).PreferredDealerAccount_ID__c!=null){
                    //modified as part of CAPS-4336
                    if(dealDivMap.containsKey(LeadNewMap.get(leadId).PreferredDealerNumber_NUM__c))
                        LeadNewMap.get(leadId).SubDiv_TXT__c = dealDivMap.get(LeadNewMap.get(leadId).PreferredDealerNumber_NUM__c).SubDiv_TXT__c;
                    if(LeadNewMap.get(leadId).SubDiv_TXT__c !=null){
                        LeadNewMap.get(leadId).Division_CD__c = SubdivisiomMap.get(LeadNewMap.get(leadId).SubDiv_TXT__c);
                    }
                }
                
                if(LeadNewMap.get(leadId).ProviderDetail_TXT__c!=null && LeadOldMap.get(leadId).ProviderDetail_TXT__c!=LeadNewMap.get(leadId).ProviderDetail_TXT__c){ 
                    string providename =  LeadNewMap.get(leadId).ProviderDetail_TXT__c;
                   
                    if(providename.contains(':')){
                        String[] pdn1 = providename.split(':');
                        if(pdn1[0]!=null){
                            pnamelist.add((pdn1[0]).toLowerCase());
                        }
                    }else{
                        pnamelist.add((LeadNewMap.get(leadId).ProviderDetail_TXT__c).toLowerCase());
                                                    
                    }
                }
                
                if(String.isNotEmpty(LeadNewMap.get(leadId).Color_TXT__c) && LeadOldMap.get(leadId).Color_TXT__c!=LeadNewMap.get(leadId).Color_TXT__c ){
                    // leadRec.Color_XML__c to store xml value
                    if(LeadNewMap.get(leadId).Color_XML__c == null ){
                        LeadNewMap.get(leadId).Color_XML__c = LeadNewMap.get(leadId).Color_TXT__c;
                    }
                  //  LeadNewMap.get(leadId).Color_TXT__c = getColorCombination(LeadNewMap.get(leadId).Color_TXT__c);
                 Map<String,String> colorsInEx = getColorCombination(LeadNewMap.get(leadId).Color_TXT__c);
                    LeadNewMap.get(leadId).Color_TXT__c = colorsInEx.get('color');
                    LeadNewMap.get(leadId).Interior_Color__c = colorsInEx.get('interior');
                    LeadNewMap.get(leadId).Exterior_Color__c = colorsInEx.get('exterior');
                }
                
            }
            
            
            Id dealerAccRecTypeId2 = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId();
            for(Account a:[select id,name from account where name IN: pnamelist and RecordTypeId=:dealerAccRecTypeId2]){               
                
                Providermap.put((a.name).toLowerCase(),a.id);
                
            }
            
            Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId();
            Map<String,Account> accountDealerCodeMap = new Map<String,Account>();
            for(Account accRec : [Select id,DealerCode_CD__c,(Select id,FirstName,LastName,Email from Contacts) from Account where DealerCode_CD__c in:leadPreffereddealerNumber and
                               RecordTypeId=:dealerAccRecTypeId
                              ])
            {
                accountDealerCodeMap.put(accRec.DealerCode_CD__c,accRec);
            }
            
            for(Id leadRecId : LeadNewMap.keySet())
            {
                if(accountDealerCodeMap.containsKey(LeadNewMap.get(leadRecId).PreferredDealerNumber_NUM__c))
                {
                    LeadNewMap.get(leadRecId).PreferredDealerAccount_ID__c=accountDealerCodeMap.get(LeadNewMap.get(leadRecId).PreferredDealerNumber_NUM__c).Id;
                    if(LeadNewMap.get(leadRecId).SubDiv_TXT__c !=null){
                        LeadNewMap.get(leadRecId).Division_CD__c = SubdivisiomMap.get(LeadNewMap.get(leadRecId).SubDiv_TXT__c);
                    }
                   for(Contact conRec : accountDealerCodeMap.get(LeadNewMap.get(leadRecId).PreferredDealerNumber_NUM__c).Contacts)
                    {
                        if(LeadNewMap.get(leadRecId).FirstName==conRec.FirstName && LeadNewMap.get(leadRecId).LastName==conRec.LastName && LeadNewMap.get(leadRecId).Email==conRec.Email)
                            {
                                LeadNewMap.get(leadRecId).PreferredDealerContact_ID__c=conRec.Id;
                                break;
                            }
                    }
                }
                
                if(LeadNewMap.get(leadRecId).ProviderDetail_TXT__c!=null && LeadOldMap.get(leadRecId).ProviderDetail_TXT__c!=LeadNewMap.get(leadRecId).ProviderDetail_TXT__c){ 
                    string providename =  LeadNewMap.get(leadRecId).ProviderDetail_TXT__c;
                   
                    if(providename.contains(':')){
                        String[] pdn1 = providename.split(':');
                        if(pdn1[0]!=null && Providermap.containsKey((pdn1[0]).toLowerCase())){
                            LeadNewMap.get(leadRecId).LeadProvider_ID__c = Providermap.get((pdn1[0]).toLowerCase());
                        }
                    }else if(Providermap.containsKey((LeadNewMap.get(leadRecId).ProviderDetail_TXT__c).toLowerCase())){
                        LeadNewMap.get(leadRecId).LeadProvider_ID__c = Providermap.get((LeadNewMap.get(leadRecId).ProviderDetail_TXT__c).toLowerCase());
                                                    
                    }
                }
                
            }
        }Catch(Exception ex){
          //  System.debug('Exception at line : '+ ex.getLineNumber());
          //  System.debug('Exception Message : '+ ex.getMessage());
            
            Logs__c  l =new Logs__c (name='Lead - handleLeadUpdate',Trigger_or_Class_Name__c='LeadTriggerHandlerUpdated', Error_Message__c =ex.getMessage(), Error_Line_Number__c =Integer.valueOf(string.valueof(ex.getLineNumber() )) );
           insert l;
        }
        
    }

    // public static String getColorCombination(String colorTXT){
    public static Map<string,String> getColorCombination(String colorTXT){
        String color = '';
        String interior = '';
        String exterior= '';
            Map<string, String> colorsInEx= new Map<String, String>();
        try{
            Integer size = 0;
            List<String> colorCombinations = new List<String>();
            if(String.isNotEmpty(colorTXT)){
                colorCombinations.addAll(colorTXT.split('</colorcombination>'));
            }
            if( colorTXT != '<colorcombination/>'){
            for(String colorCombination : colorCombinations){
                size += 1;
                Dom.Document doc = new Dom.Document();                
                doc.load( colorCombination + '</colorcombination>' );  
                //Retrieve the root element for this document.
                Dom.XMLNode root = doc.getRootElement();               
                // Alternatively, loop through the child elements.
                // This prints out all the elements of the address
                for(Dom.XMLNode child : root.getChildElements()) {                
                    if(child.getName() =='interiorcolor'){
                        
                        //color += child.getName() + ':' + child.getText() + ', ';
                        color += 'Interior Color:' + child.getText() + ',  ';
                        //system.debug('@@@@@@Childtext-----'+child.getText());
                       interior += child.getText() + ', ';
                        interior = interior.removeEnd(', ');
                    }
                    if(child.getName() =='exteriorcolor'){
                        //color += child.getName() + ':' + child.getText() + ', ';
                        color += 'Exterior Color:' + child.getText() + ',  ';
                        exterior += child.getText() + ', ';
                        exterior = exterior.removeEnd(', ');
                    }
                    if(child.getName() =='preference'){
                        //color += child.getName() + ':' + child.getText() + ', ';
                        color += 'Preference:' + child.getText();
                    }
                } 
                }
                //color = color.removeEnd(', ');
                if(size != colorCombinations.size()){
                    
                    color += '\n';
                }
            }
        }Catch(Exception ex){
            Logs__c logRecord = new Logs__c(Name='getColorCombination', Trigger_or_Class_Name__c='HELMSLeadTriggerHandlerUpdated',  Error_Message__c = ex.getMessage(),
            Error_Line_Number__c = Integer.valueOf(ex.getLineNumber()));
            insert logRecord;
        }
        colorsInEx.put('interior',interior);
        colorsInEx.put('exterior',exterior);
        colorsInEx.put('color',color);
       // system.debug(colorsInEx);
         return colorsInEx;
       //  return color;
       
    } 
}