objects/Account.object
<CustomObject>
    <fields>
        <fullName>DealerCode_CD__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Dealer_Ids_ID__c</fullName>
        <label>Dealer IDs</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <label>External IDs</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MSRP_AMT__c</fullName>
        <label>MSRP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Make_TXT__c</fullName>
        <label>Make</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Dealer_Ids_ID__c</fullName>
        <label>Dealer IDs</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <label>External IDs</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>First_Name_TXT__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name_TXT__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MSRP_AMT__c</fullName>
        <label>MSRP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Make_TXT__c</fullName>
        <label>Make</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredDealerAccount_TXT__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Preferred Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_MSRP_AMT__c</fullName>
        <label>Total MSRP AMT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ZipCode_TXT__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Options__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity ID</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Additional_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PriceMSRP_AMT__c</fullName>
        <label>Price MSRP</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Options</label>
    <nameField>
        <label>Options Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HELMSOptionTriggerTest.cls
/****************************************************************************** 
File Name:      HELMSOptionTrigger  
Created On:     3rd June 2021
Created By:     Bandi Sujatha, Appirio
Test Classes:   HELMSOptionTriggerTest        
HELMS Jira Story: 
===============================================================================
Modification Log:  
********************************************************************************/

@isTest
public class HELMSOptionTriggerTest {
    
    static testMethod void TestMethodOne() 
    {
        List<Opportunity> listOfOpportunities = new List<Opportunity>();
        
        Lead objLead = new Lead( FirstName = 'Test', LastName = 'Sample', Company = 'Testing Sample Co',Make_TXT__c='vhn',Dealer_Ids_ID__c='testing');  
        insert objLead;
        Id dealerAccRecTypeId1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        
        Account accTestRec11 = new Account(Name='Test Account123another',RecordTypeId=dealerAccRecTypeId1,
                                           DealerCode_CD__c=objLead.Dealer_Ids_ID__c
                                          );
        insert accTestRec11;
        Opportunity Oppr = new Opportunity(Name='YashLead123',First_Name_TXT__c='Yash',Last_Name_TXT__c='Lead123',StageName='In Conversation',Email__c='test@gmail.com',ZipCode_TXT__c='12348',
                                           PreferredDealerAccount_TXT__c=accTestRec11.Id,amount = 50000.00,
                                           PreferredDealerNumber_NUM__c='123456', External_ID__c='12345',
        Total_MSRP_AMT__c =10,MSRP_AMT__c=10, CloseDate=system.today(),Make_TXT__c =objLead.Make_TXT__c);
        // Required fields are missing: [First_Name_TXT__c, Last_Name_TXT__c]: [First_Name_TXT__c, Last_Name_TXT__c]
        listOfOpportunities.add(Oppr);
        insert listOfOpportunities;
        list<Options__c> lstcon = new list<Options__c>();
        
        Options__c objcon1 = new Options__c();
        objcon1.Name = 'Test1';
        objcon1.PriceMSRP_AMT__c = 10;
        objcon1.Opportunity_ID__c = listOfOpportunities[0].id;
        lstcon.add(objcon1);
        
        Options__c objcon2 = new Options__c();
        objcon2.Name = 'Test2';
                objcon2.PriceMSRP_AMT__c = 10;

        objcon2.Opportunity_ID__c = listOfOpportunities[0].id;
        lstcon.add(objcon2);
        
        insert lstcon;
        
        Delete objcon1;
    }
}