objects/Account.object
<CustomObject>
    <fields>
        <fullName>Launchbox_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>used for Data Migration, external id, unique</description>
        <externalId>true</externalId>
        <label>Launchbox_ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/B2C_Error_Details__c.object
<CustomObject>
    <fields>
        <fullName>DateTime__c</fullName>
        <label>DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>No_of_Records_Failed__c</fullName>
        <label>No of Records Failed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_of_Records_Processed__c</fullName>
        <label>No of Records Processed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ZIP Code Rankings</fullName>
                </value>
                <value>
                    <fullName>City State Rankings</fullName>
                </value>
                <value>
                    <fullName>Dealers</fullName>
                </value>
                <value>
                    <fullName>Dealers Subdivisions</fullName>
                </value>
                <value>
                    <fullName>Model Group name</fullName>
                </value>
                <value>
                    <fullName>RDR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>B2C Error Details</label>
    <nameField>
        <label>B2C Batch Job Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Error Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/City_State_Ranking__c.object
<CustomObject>
    <fields>
        <fullName>Launchbox_ID__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-3903 Story name.
Description: This is used for Data Migration, external id, unique.
Source System: Coming from batch feed daily basis.
Integration: NA.
Data Transformation: N/A.
Functional Definition: This will be used in Einstein Dashboards or Reports.</description>
        <externalId>true</externalId>
        <label>Launchbox_ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>City State Ranking</label>
    <nameField>
        <label>City State Ranking</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>City State Ranking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_System__c.object
<CustomObject>
    <label>CRM System</label>
    <nameField>
        <label>CRM System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRM Systems</pluralLabel>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Dealer_Division__c.object
<CustomObject>
    <description>list of active or inactive division, subdivision, zone, district and other territory related fields based on their business use for Sales, Service, Parts, etc.</description>
    <fields>
        <fullName>Launchbox_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Launchbox ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Dealer Subdivision</label>
    <nameField>
        <displayFormat>DD-{0}</displayFormat>
        <label>Dealer Division Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Divisions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Dealer_Participation__c.object
<CustomObject>
    <fields>
        <fullName>CRM_System__c</fullName>
        <label>CRM System</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Division__c</field>
                <operation>equals</operation>
                <valueField>CRM_System__c.Division_CD__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CRM_System__c</referenceTo>
        <relationshipLabel>Dealer Participations</relationshipLabel>
        <relationshipName>Dealer_Participations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Launchbox_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Launchbox_ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Dealer Participation</label>
    <nameField>
        <label>Dealer Participation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Matchback__c.object
<CustomObject>
    <fields>
        <fullName>RDR_Sales__c</fullName>
        <label>RDR Sales</label>
        <referenceTo>RDR_Sales__c</referenceTo>
        <relationshipLabel>Matchback</relationshipLabel>
        <relationshipName>Matchback</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Matchback</label>
    <nameField>
        <displayFormat>Matchback - {0000000}</displayFormat>
        <label>Matchback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matchback</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RDR_Sales__c.object
<CustomObject>
    <fields>
        <fullName>Launchbox_ID__c</fullName>
        <externalId>true</externalId>
        <label>Launchbox_ID</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>RDR Sales</label>
    <nameField>
        <displayFormat>RDR Sales - {00000000}</displayFormat>
        <label>RDR Sales</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RDR Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Zip_Ranking__c.object
<CustomObject>
    <fields>
        <fullName>Launchbox_ID__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-3903 Story name.
Description: This is used for Data Migration, external id, unique.
Source System: Coming from batch feed daily basis.
Integration: NA.
Data Transformation: N/A.
Functional Definition: This will be used in Einstein Dashboards or Reports.</description>
        <externalId>true</externalId>
        <label>Launchbox_ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Zip Ranking</label>
    <nameField>
        <label>Zip Ranking</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Ranking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HELMSFetchB2CFileDataScheduler.cls
global class HELMSFetchB2CFileDataScheduler implements Schedulable,Database.AllowsCallouts {
    
        global void execute(SchedulableContext sc){
                 B2CFileDataScheduler();   
        }
        
        @future(callout=true) 
        public static void B2CFileDataScheduler(){
          
                Final String VERSION_BULKJOB_WAS_MADE_WITH = 'v53.0';
                List<B2C_Error_Details__c> b2cList= new List<B2C_Error_Details__c>();
                String respBody = '';  
                  
                HttpRequest req = new HttpRequest();
                String endPointUrl = URL.getOrgDomainUrl().toExternalForm() + '/services/data/' + VERSION_BULKJOB_WAS_MADE_WITH + '/jobs/ingest';
                
                req.setEndpoint(endPointUrl);
                req.setMethod('GET');
                req.setHeader('Authorization', 'Bearer ' + UserInfo.getSessionId());
                Http http = new Http();
                HTTPResponse response = http.send(req);
                respBody = response.getBody();
                System.debug('respBody: ++++++' + respBody);
                
                if(response.getStatusCode()==200){
                    respBody = respBody.replaceAll('"object":','"objectName":');
                    bulkjobjsonwrapper bulkjob = (bulkjobjsonwrapper) System.JSON.deserialize(respBody, bulkjobjsonwrapper.class); 
                 
                
                    for(cls_records cls: bulkjob.records){
                      //System.debug('respBody: ++1++++' + cls.createdDate.date());
                      //System.debug('respBody: ++2++++' + date.today());
                      //System.debug('respBody: ++3++++' + cls.objectName);
    
                       if(cls.createdDate.date()==date.today()){
                       
                            if(cls.objectName=='Zip_Ranking__c' || cls.objectName=='City_State_Ranking__c' || cls.objectName=='RDR_Sales__c' || cls.objectName=='Dealer_Participation__c' || cls.objectName=='Dealer_Division__c' || cls.objectName=='Matchback__c' || cls.objectName=='CRM_System__c' || cls.objectName=='Account'){
                            
                                HttpRequest reqst = new HttpRequest();
                                String endPoint = URL.getOrgDomainUrl().toExternalForm() + '/services/data/' + VERSION_BULKJOB_WAS_MADE_WITH + '/jobs/query/'+cls.id;
                                
                                reqst.setEndpoint(endPoint);
                                reqst.setMethod('GET');
                                reqst.setHeader('Authorization', 'Bearer ' + UserInfo.getSessionId());
                                Http https = new Http();
                                HTTPResponse respons = https.send(reqst);
                                respBody = respons.getBody();
                                System.debug('respBody: today++++++' + respBody);
                                
                                if(respons.getStatusCode()==200){
                                    respBody = respBody.replaceAll('"object":','"objectName":');
                                    jsonwraperclass jsnw = (jsonwraperclass) System.JSON.deserialize(respBody, jsonwraperclass.class);
            
                                    B2C_Error_Details__c b2cr= new B2C_Error_Details__c();
                                    b2cr.name = jsnw.id;
                                    
                                    if(jsnw.state=='JobComplete' || jsnw.state=='Closed')
                                        b2cr.Status__c = 'Success';
                                    else if(jsnw.state=='Open')
                                        b2cr.Status__c = 'In Progress';
                                    else
                                        b2cr.Status__c = 'Failure';
                                        
                                    b2cr.DateTime__c = jsnw.createdDate;
                                    
                                    if(jsnw.objectName=='Zip_Ranking__c')
                                        b2cr.Type__c = 'ZIP Code Rankings';
                                    else if(jsnw.objectName=='City_State_Ranking__c')
                                        b2cr.Type__c = 'City State Rankings';
                                    else if(jsnw.objectName=='RDR_Sales__c')
                                        b2cr.Type__c = 'RDR Sales';
                                    else if(jsnw.objectName=='Dealer_Participation__c')
                                        b2cr.Type__c = 'Dealer Participation';
                                    else if(jsnw.objectName=='Dealer_Division__c')
                                        b2cr.Type__c = 'Dealers Subdivisions';
                                    else if(jsnw.objectName=='Matchback__c')
                                        b2cr.Type__c = 'Matchback'; 
                                    else if(jsnw.objectName=='CRM_System__c')
                                        b2cr.Type__c = 'CRM System'; 
                                    else if(jsnw.objectName=='Account')
                                        b2cr.Type__c = 'Dealers';   
                                        
                                    b2cr.No_of_records_processed__c = string.valueof(jsnw.numberRecordsProcessed);
                                    //b2cr.No_of_Records_Failed__c = string.valueof(jsnw.numberRecordsFailed);
            
                                    if(b2cr.Type__c!=null)
                                        b2cList.add(b2cr);
                                    
                                }
                       
                            }
                         }
                    }
                }
                
                if(b2cList.size()>0)
                    insert b2cList;
                  
            }
            
            public class jsonwraperclass{
                    public String id;   //7504x00000GMxdQAAT
                    public String operation;    //upsert
                    public String objectName;   //Zip_Ranking__c
                    public datetime createdDate;  //2022-05-18T14:30:02.000+0000
                    public datetime systemModstamp;   //2022-05-18T14:30:54.000+0000
                    public String state;    //JobComplete
                    public String externalIdFieldName;  //Launchbox_ID__c
                    public Integer numberRecordsProcessed;  //83138
                    public Integer numberRecordsFailed; //0
                    public Integer totalProcessingTime; //146481
                    public Integer apiActiveProcessingTime; //125447
                    public Integer apexProcessingTime;  //138528
        
            
          }
            
          public class bulkjobjsonwrapper{
                public boolean done;                
                public cls_records[] records;
          }  
              
          public class cls_records {
                public String id;   //7504x00000GMOwHAAX
                public datetime createdDate;  //2022-05-14T13:32:21.000+0000
                public String state;    //Open
                public String objectName;   //Zip_Ranking__c

          }
          
           

 }