objects/Account.object
<CustomObject>
    <fields>
        <fullName>DealerCode_CD__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account__x.object
<CustomObject>
    <externalDataSource>HDMP_QA</externalDataSource>
    <externalName>Account</externalName>
    <fields>
        <fullName>Email_c__c</fullName>
        <externalDeveloperName>Email__c</externalDeveloperName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>IsActive_c__c</fullName>
        <defaultValue>false</defaultValue>
        <externalDeveloperName>IsActive__c</externalDeveloperName>
        <label>Is BT Setup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <externalDeveloperName>Name</externalDeveloperName>
        <label>Account Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PoIId_c__c</fullName>
        <externalDeveloperName>PoIId__c</externalDeveloperName>
        <label>Dealer Number</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <externalDeveloperName>Type</externalDeveloperName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Analyst</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Integrator</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Press</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Reseller</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Ext</label>
    <pluralLabel>Accounts Ext</pluralLabel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__x.object
<CustomObject>
    <externalDataSource>HDMP_QA</externalDataSource>
    <externalName>Order</externalName>
    <fields>
        <fullName>AccountId__c</fullName>
        <externalDeveloperName>AccountId</externalDeveloperName>
        <label>Account ID</label>
        <length>18</length>
        <referenceTo>Account__x</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>ExternalLookup</type>
    </fields>
    <fields>
        <fullName>BT_Transaction_Id_c__c</fullName>
        <externalDeveloperName>BT_Transaction_Id__c</externalDeveloperName>
        <label>Customer Payment Gateway Transaction Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BT_Transaction_Status_c__c</fullName>
        <externalDeveloperName>BT_Transaction_Status__c</externalDeveloperName>
        <label>Cust Payment Gateway Transaction Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Authorized</fullName>
                </value>
                <value>
                    <fullName>Submitted_For_Settlement</fullName>
                </value>
                <value>
                    <fullName>Settlement_Pending</fullName>
                </value>
                <value>
                    <fullName>Settling</fullName>
                </value>
                <value>
                    <fullName>Settled</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
                <value>
                    <fullName>Processor_Declined</fullName>
                </value>
                <value>
                    <fullName>Gateway_Rejected</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Settlement_Declined</fullName>
                </value>
                <value>
                    <fullName>Authorization_Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BillingPhoneNumber__c</fullName>
        <externalDeveloperName>BillingPhoneNumber</externalDeveloperName>
        <label>Billing Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Customer_Name_c__c</fullName>
        <externalDeveloperName>Customer_Name__c</externalDeveloperName>
        <label>Billing Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Number_c__c</fullName>
        <externalDeveloperName>Dealer_Number__c</externalDeveloperName>
        <label>Dealer Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivery_Types_c__c</fullName>
        <externalDeveloperName>Delivery_Types__c</externalDeveloperName>
        <label>Delivery Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Install At Dealer</fullName>
                </value>
                <value>
                    <fullName>Pick Up At Dealer</fullName>
                </value>
                <value>
                    <fullName>Ship to Me</fullName>
                </value>
                <value>
                    <fullName>DirectShip</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_c__c</fullName>
        <externalDeveloperName>Email__c</externalDeveloperName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>External_account_POID_c__c</fullName>
        <externalDeveloperName>External_account_POID__c</externalDeveloperName>
        <label>External_account_POID</label>
        <length>1300</length>
        <readOnlyProxy>true</readOnlyProxy>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GrandTotalAmount__c</fullName>
        <externalDeveloperName>GrandTotalAmount</externalDeveloperName>
        <label>Total with Tax</label>
        <precision>18</precision>
        <readOnlyProxy>true</readOnlyProxy>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <externalDeveloperName>Name</externalDeveloperName>
        <label>Order Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderNumber__c</fullName>
        <externalDeveloperName>OrderNumber</externalDeveloperName>
        <label>Order Number</label>
        <length>30</length>
        <readOnlyProxy>true</readOnlyProxy>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderReferenceNumber__c</fullName>
        <externalDeveloperName>OrderReferenceNumber</externalDeveloperName>
        <label>Order Reference Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderedDate__c</fullName>
        <externalDeveloperName>OrderedDate</externalDeveloperName>
        <label>Ordered Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Phone_No_c__c</fullName>
        <externalDeveloperName>Phone_No__c</externalDeveloperName>
        <label>Phone No</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Product_Division_c__c</fullName>
        <externalDeveloperName>Product_Division__c</externalDeveloperName>
        <label>Product Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                    <label>Honda Auto</label>
                </value>
                <value>
                    <fullName>B</fullName>
                    <label>Acura Auto</label>
                </value>
                <value>
                    <fullName>M</fullName>
                    <label>Motorcycle</label>
                </value>
                <value>
                    <fullName>P</fullName>
                    <label>Powerequipment</label>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SHIPPING_from_cart_c__c</fullName>
        <externalDeveloperName>SHIPPING_from_cart__c</externalDeveloperName>
        <label>SHIPPING from cart</label>
        <precision>18</precision>
        <readOnlyProxy>true</readOnlyProxy>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <externalDeveloperName>Status</externalDeveloperName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>ORDER COMPLETE - PICKED UP</fullName>
                </value>
                <value>
                    <fullName>ORDER COMPLETE - SHIPPED</fullName>
                </value>
                <value>
                    <fullName>PARTIAL SHIP</fullName>
                </value>
                <value>
                    <fullName>CUSTOMER CANCELED</fullName>
                </value>
                <value>
                    <fullName>ORDER RETURN</fullName>
                </value>
                <value>
                    <fullName>READY FOR PICKUP</fullName>
                </value>
                <value>
                    <fullName>IN PROGRESS</fullName>
                </value>
                <value>
                    <fullName>DEALER REJECTED</fullName>
                </value>
                <value>
                    <fullName>SYSTEM CANCELED</fullName>
                </value>
                <value>
                    <fullName>DEALER CANCELED</fullName>
                </value>
                <value>
                    <fullName>PARTIAL RETURN</fullName>
                </value>
                <value>
                    <fullName>PAYMENT ISSUE</fullName>
                </value>
                <value>
                    <fullName>ORDER ISSUE</fullName>
                </value>
                <value>
                    <fullName>PARTIAL RETURN COMPLETE</fullName>
                </value>
                <value>
                    <fullName>ORDER COMPLETE - INSTALLED</fullName>
                </value>
                <value>
                    <fullName>PROCESSING IN WAREHOUSE</fullName>
                </value>
                <value>
                    <fullName>PREPARING FOR SHIPMENT</fullName>
                </value>
                <value>
                    <fullName>PARTIALLY SHIPPED</fullName>
                </value>
                <value>
                    <fullName>SENT TO WAREHOUSE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Return_c__c</fullName>
        <externalDeveloperName>Total_Return__c</externalDeveloperName>
        <label>Total Return Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Unavailable_AMT_c__c</fullName>
        <externalDeveloperName>Total_Unavailable_AMT__c</externalDeveloperName>
        <label>Total Unavailable AMT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <externalDeveloperName>Type</externalDeveloperName>
        <label>Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>DirectShip</fullName>
                    <label>Direct Ship</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Updated_Order_Total_c__c</fullName>
        <externalDeveloperName>Updated_Order_Total__c</externalDeveloperName>
        <label>Total Current with Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>isOrderPickedUp_c__c</fullName>
        <defaultValue>false</defaultValue>
        <externalDeveloperName>isOrderPickedUp__c</externalDeveloperName>
        <label>isOrderPickedUp</label>
        <type>Checkbox</type>
    </fields>
    <label>Order Ext</label>
    <pluralLabel>Orders</pluralLabel>
</CustomObject>

classes/B2B_GetOrderExt.cls
/**********************************************************************
Name: B2B_GetOrderExt
Purpose: Apex class is created to show external order details from HDM org in dealer console.
Created Date :  30/07/2021, 3:01 PM
Created By : Vikrant Upneja
Last Modified By :	RajRishi Kaushik ,  18/07/2022, 11:19 AM
Salesforce API Version : 55.0
*************************************************************/

public with sharing class B2B_GetOrderExt {
    @TestVisible private static List<Order__x> mockedOrder = new List<Order__x>();
    @AuraEnabled
    public static List<Order__x> OrderInfo(boolean pageurl,boolean pageurldirectship){
        String userid = UserInfo.getUserId();
        String contactid;
        String dealercode;       
        
        List<User> usrLst = new List<user>();
        if(!String.isEmpty(userid)){           
            usrLst = [SELECT ContactId from User WHERE Id=:userid];
            contactid=usrLst.get(0).ContactId;
        }
        if(!String.isEmpty(contactid)){
            List<Contact> dealercodelst = new List<Contact>();
            dealercodelst= [SELECT Account.DealerCode_CD__c FROM Contact WHERE Id=:contactid];
            dealercode=dealercodelst.get(0).Account.DealerCode_CD__c;
        }
        
        List<Order__x> orderlist = new List<Order__x>();
        
        //R2B changes for HDMP-10201 : added OrderReferenceNumber__c in Query
        if(!String.isEmpty(dealercode)){                
            if(pageurl == true && pageurldirectship == false){    //Modified by Divya for EVSE_Phase2_Sprint1 HDMP-24335           
                orderlist = (!mockedOrder.isEmpty()) ? mockedOrder : [SELECT Id, OrderReferenceNumber__c, OrderNumber__c, Delivery_Types_c__c, Updated_Order_Total_c__c, Total_Return_c__c, Total_Unavailable_AMT_c__c, SHIPPING_from_cart_c__c, Name__c, Customer_Name_c__c,
                            BillingPhoneNumber__c,Phone_No_c__c, Status__c, OrderedDate__c, GrandTotalAmount__c,Email_c__c, Type__c, Product_Division_c__c, AccountId__r.IsActive_c__c,BT_Transaction_Status_c__c,AccountId__r.PoIId_c__c,BT_Transaction_Id_c__c //added by suresh for PR    
                            FROM Order__x 
                            WHERE External_account_POID_c__c=:dealercode AND OrderedDate__c != NULL AND Type__c !=:B2B_Constants.DIRECTSHIP //Modified by Divya for EVSE_Phase2_Sprint1 HDMP-24335
                            AND (Status__c='Activated' OR Status__c='Partial Ship' 
                            OR Status__c='In Progress' OR Status__c='Ready for Pickup' 
                            OR Status__c='Payment Issue' OR Status__c='Order Issue' OR (Status__c='PARTIAL RETURN' AND Delivery_Types_c__c != 'Install At Dealer' AND isOrderPickedUp_c__c = false AND SHIPPING_from_cart_c__c = 0)) order by OrderedDate__c desc];              
            }else if(pageurl == true && pageurldirectship == true){ //Added by Divya for EVSE_Phase2_Sprint1 - START HDMP-24335               
                orderlist = (!mockedOrder.isEmpty()) ? mockedOrder : [SELECT Id, OrderReferenceNumber__c, OrderNumber__c, Delivery_Types_c__c, Updated_Order_Total_c__c, Total_Return_c__c, Total_Unavailable_AMT_c__c, SHIPPING_from_cart_c__c, Name__c, Customer_Name_c__c,
                            BillingPhoneNumber__c, Status__c, OrderedDate__c, GrandTotalAmount__c,Email_c__c, Type__c, Product_Division_c__c, AccountId__r.IsActive_c__c,BT_Transaction_Status_c__c,AccountId__r.PoIId_c__c,BT_Transaction_Id_c__c //added by suresh for PR     
                            FROM Order__x 
                            WHERE Dealer_Number_c__c=:dealercode AND OrderedDate__c != NULL AND Type__c =:B2B_Constants.DIRECTSHIP
                            AND (Status__c=:B2B_Constants.ACTIVATED OR Status__c=:B2B_Constants.PARTIAL_SHIP 
                            OR Status__c=:B2B_Constants.INPROGRESS OR Status__c=:B2B_Constants.PREPARING_FOR_SHIPMENT OR Status__c=:B2B_Constants.PROCESSING_IN_WAREHOUSE
                            OR Status__c=:B2B_Constants.PAYMENT_ISSUE OR Status__c=:B2B_Constants.ORDER_ISSUE) order by OrderedDate__c desc];//Modified by Divya for EVSE_Phase2_Sprint2
            }else {    //Added by Divya for EVSE_Phase2_Sprint1 - END HDMP-24335                            
                orderlist = (!mockedOrder.isEmpty()) ? mockedOrder : [SELECT Id, OrderReferenceNumber__c, OrderNumber__c, Delivery_Types_c__c, Updated_Order_Total_c__c, Total_Return_c__c, Total_Unavailable_AMT_c__c, SHIPPING_from_cart_c__c, Name__c, Customer_Name_c__c,
                            BillingPhoneNumber__c,Phone_No_c__c, Status__c, OrderedDate__c, GrandTotalAmount__c, Email_c__c, Type__c, Product_Division_c__c, AccountId__r.IsActive_c__c,BT_Transaction_Status_c__c,AccountId__r.PoIId_c__c,BT_Transaction_Id_c__c //added by suresh for PR   
                                        FROM Order__x 
                                        WHERE External_account_POID_c__c=:dealercode AND OrderedDate__c != NULL
                            AND (Status__c='ORDER COMPLETE - PICKED UP' OR Status__c='ORDER COMPLETE - SHIPPED' OR Status__c='CUSTOMER CANCELED' 
                            OR Status__c='ORDER RETURN' OR Status__c='DEALER REJECTED' OR Status__c='SYSTEM CANCELED' OR Status__c='ORDER COMPLETE - INSTALLED'
                            OR Status__c='DEALER CANCELED' OR (Status__c='PARTIAL RETURN' AND isOrderPickedUp_c__c = true AND SHIPPING_from_cart_c__c = 0) 
                            OR (Status__c='PARTIAL RETURN' AND SHIPPING_from_cart_c__c > 0) OR (Status__c='PARTIAL RETURN' AND Delivery_Types_c__c = 'Install At Dealer')) order by OrderedDate__c desc];
                
            }
        }
        
        return orderlist;
        
    }
    //Added this method to display message in Dealer Console for CAPS-4066
    @AuraEnabled
    public static Boolean showBTTokenMsg() {
        Boolean isBTTokenActive;
        List<Account__x> dealerList = new List<Account__x>();
        String userid = UserInfo.getUserId();
        String contactid;
        String dealercode;       
        
        List<User> usrLst = new List<user>();
        if(!String.isEmpty(userid)){           
            usrLst = [SELECT ContactId from User WHERE Id=:userid];
            contactid=usrLst.get(0).ContactId;
        }
        if(!String.isEmpty(contactid)){
            List<Contact> dealercodelst = new List<Contact>();
            dealercodelst= [SELECT Account.DealerCode_CD__c FROM Contact WHERE Id=:contactid];
            dealercode=dealercodelst.get(0).Account.DealerCode_CD__c;
        }        
        if(!String.isEmpty(dealercode)){
            dealerList = [SELECT Id,IsActive_c__c FROM Account__x where PoIId_c__c =:dealercode LIMIT 1];
            if(!dealerList.isEmpty()){
                isBTTokenActive = dealerList[0].IsActive_c__c;                
            }
        }
        return isBTTokenActive;
    }

}