objects/Account.object
<CustomObject>
    <fields>
        <fullName>DealerCode_CD__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>HelmsCRMEligible_FLAG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HELMS Access</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__x.object
<CustomObject>
    <externalDataSource>HDMP_QA</externalDataSource>
    <externalName>Order</externalName>
    <fields>
        <fullName>BT_Transaction_Status_c__c</fullName>
        <externalDeveloperName>BT_Transaction_Status__c</externalDeveloperName>
        <label>Cust Payment Gateway Transaction Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Authorized</fullName>
                </value>
                <value>
                    <fullName>Submitted_For_Settlement</fullName>
                </value>
                <value>
                    <fullName>Settlement_Pending</fullName>
                </value>
                <value>
                    <fullName>Settling</fullName>
                </value>
                <value>
                    <fullName>Settled</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
                <value>
                    <fullName>Processor_Declined</fullName>
                </value>
                <value>
                    <fullName>Gateway_Rejected</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Settlement_Declined</fullName>
                </value>
                <value>
                    <fullName>Authorization_Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <externalDeveloperName>Status</externalDeveloperName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>ORDER COMPLETE - PICKED UP</fullName>
                </value>
                <value>
                    <fullName>ORDER COMPLETE - SHIPPED</fullName>
                </value>
                <value>
                    <fullName>PARTIAL SHIP</fullName>
                </value>
                <value>
                    <fullName>CUSTOMER CANCELED</fullName>
                </value>
                <value>
                    <fullName>ORDER RETURN</fullName>
                </value>
                <value>
                    <fullName>READY FOR PICKUP</fullName>
                </value>
                <value>
                    <fullName>IN PROGRESS</fullName>
                </value>
                <value>
                    <fullName>DEALER REJECTED</fullName>
                </value>
                <value>
                    <fullName>SYSTEM CANCELED</fullName>
                </value>
                <value>
                    <fullName>DEALER CANCELED</fullName>
                </value>
                <value>
                    <fullName>PARTIAL RETURN</fullName>
                </value>
                <value>
                    <fullName>PAYMENT ISSUE</fullName>
                </value>
                <value>
                    <fullName>ORDER ISSUE</fullName>
                </value>
                <value>
                    <fullName>PARTIAL RETURN COMPLETE</fullName>
                </value>
                <value>
                    <fullName>ORDER COMPLETE - INSTALLED</fullName>
                </value>
                <value>
                    <fullName>PROCESSING IN WAREHOUSE</fullName>
                </value>
                <value>
                    <fullName>PREPARING FOR SHIPMENT</fullName>
                </value>
                <value>
                    <fullName>PARTIALLY SHIPPED</fullName>
                </value>
                <value>
                    <fullName>SENT TO WAREHOUSE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Updated_Order_Amount_c__c</fullName>
        <externalDeveloperName>Updated_Order_Amount__c</externalDeveloperName>
        <label>Total Current Product Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Updated_Order_Total_c__c</fullName>
        <externalDeveloperName>Updated_Order_Total__c</externalDeveloperName>
        <label>Total Current with Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Updated_Total_Tax_c__c</fullName>
        <externalDeveloperName>Updated_Total_Tax__c</externalDeveloperName>
        <label>Total Current Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order Ext</label>
    <pluralLabel>Orders</pluralLabel>
</CustomObject>

classes/B2B_GetOrderExtTest.cls
@isTest
public class B2B_GetOrderExtTest {
    
    @isTest
    public static void unitTest(){
        Order__x objOrder = new Order__x();
        objOrder.Status__c = 'IN PROGRESS';
        objOrder.Updated_Order_Amount_c__c = 20.00;
        objOrder.Updated_Order_Total_c__c = 22.00;
        objOrder.Updated_Total_Tax_c__c = 2.00;
        objOrder.BT_Transaction_Status_c__c = 'Authorized';     
        B2B_GetOrderExt.mockedOrder.add(objOrder); 
        Contact objContact;//Added by Divya
        
      	Set<String> customerUserTypes = new Set<String> {'CSPLiteUser', 'PowerPartner', 'PowerCustomerSuccess',   'CustomerSuccess'};
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        //Added by Divya Start
        User user = new User();  
        user = [Select Id,Profile.Name from User where id=: userinfo.getUserId()];
        String userProfile = user.Profile.Name;
        User userRoleId = [Select UserRoleId from User where Profile.Name =:userProfile AND UserRoleId != null limit 1];
        UserRole userrole = [Select Id From UserRole Where Id =:userRoleId.UserRoleId  Limit 1];
        user.UserRoleId = userrole.Id;
        update user;
        System.runAs(user){//Added by Divya END
        Account objAccount = new Account();
        objAccount.Name = 'test';
        objAccount.DealerCode_CD__c = '12343';        
        insert objAccount;
        
        objContact = new Contact();//Modified by Divya
        objContact.FirstName = 'test';
        objContact.LastName = 'test';
        objContact.AccountId = objAccount.Id;
        objContact.HelmsCRMEligible_FLAG__c = true;
        objContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        insert objContact;
        }//Added by Divya 
        // This code runs as the system user
       //Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        Profile p = [select Id,name from Profile where UserType in :customerUserTypes limit 1];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles',
                          contactId=objContact.Id,
                          UserName=uniqueUserName); 
        
        System.runAs(u) {
            B2B_GetOrderExt.OrderInfo(true, false);
            B2B_GetOrderExt.OrderInfo(false, true);
            B2B_GetOrderExt.OrderInfo(true, true);//Added by Divya
        }
    }
    
    @isTest
    static void testShowBTTokenMsg() {
        Set<String> customerUserTypes = new Set<String> {'CSPLiteUser', 'PowerPartner', 'PowerCustomerSuccess',   'CustomerSuccess'};
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        
        Account objAccount = new Account();
        objAccount.Name = 'test';
        objAccount.DealerCode_CD__c = '12345';        
        insert objAccount;

        Contact objContact = new Contact();
        objContact.FirstName = 'test';
        objContact.LastName = 'test';
        objContact.AccountId = objAccount.Id;
        objContact.HelmsCRMEligible_FLAG__c = true;
        objContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        insert objContact;
        
        Profile p = [select Id,name from Profile where UserType in :customerUserTypes limit 1];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
                        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                        LocaleSidKey='en_US', ProfileId = p.Id,
                        TimeZoneSidKey='America/Los_Angeles',
                        contactId=objContact.Id,
                        UserName=uniqueUserName); 

       
        System.runAs(u) {
            Boolean tokenExpired = B2B_GetOrderExt.showBTTokenMsg();
        }
      
    }
}