objects/Account.object
<CustomObject>
    <fields>
        <fullName>DealerCode_CD__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Send_Customer_Acknowledgement_Email_Flag__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Send Customer Acknowledgement Email</description>
        <label>Send Customer Acknowledgement Email</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <description>Used for Provider Records</description>
        <label>Provider</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <label>Provider</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>BodyStyle_TXT__c</fullName>
        <label>BodyStyle</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Condition_TXT__c</fullName>
        <label>Condition</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>excellent</fullName>
                </value>
                <value>
                    <fullName>good</fullName>
                </value>
                <value>
                    <fullName>fair</fullName>
                </value>
                <value>
                    <fullName>poor</fullName>
                </value>
                <value>
                    <fullName>unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContactKey_TXT__c</fullName>
        <label>Contact Key</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerAccount_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Customer Account)</relationshipLabel>
        <relationshipName>Leads2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer_Ids_ID__c</fullName>
        <label>Dealer IDs</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Doors_TXT__c</fullName>
        <label>Doors</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Provider</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Lead Provider)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model_ID__c</fullName>
        <label>Model ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_TXT__c</fullName>
        <label>Model</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Number_NM__c</fullName>
        <label>Vin Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OdometerStatus_TXT__c</fullName>
        <label>Odometer Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>unknown</fullName>
                </value>
                <value>
                    <fullName>rolledover</fullName>
                </value>
                <value>
                    <fullName>replaced</fullName>
                </value>
                <value>
                    <fullName>original</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Odometer_TXT__c</fullName>
        <label>Odometer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredDealerAccount_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProviderDetail_TXT__c</fullName>
        <inlineHelpText>Source Lead Provider Name</inlineHelpText>
        <label>Provider Detail</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Send_confirmation_Email__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Business Unit: HELMS.
Jira Story: LMS-5361 Story name.
Description: This is store the true or false form SFMC.
Source System: Coming from Integration.
Integration: No
Data Transformation: N/A.
Functional Definition: If the  flag is true Lead  Data sent to SFMC.</description>
        <label>Send confirmation Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>Subdivision</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division_CD__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trim_TXT__c</fullName>
        <label>Model Trim</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>VehicleInterest_TXT__c</fullName>
        <label>Vehicle Interest</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>buy</fullName>
                </value>
                <value>
                    <fullName>lease</fullName>
                </value>
                <value>
                    <fullName>sell</fullName>
                </value>
                <value>
                    <fullName>trade-in</fullName>
                </value>
                <value>
                    <fullName>test-drive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VehicleStatus_TXT__c</fullName>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Used</fullName>
                </value>
                <value>
                    <fullName>Cpo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year_YR__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead_Expiration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to set the expiration of Leads due to no activity.</description>
    <fields>
        <fullName>M__c</fullName>
        <label>M</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lead Expiration</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BodyStyle_TXT__c</fullName>
        <label>Body Style</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Condition_TXT__c</fullName>
        <label>Condition</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Excellent</fullName>
                </value>
                <value>
                    <fullName>Good,</fullName>
                </value>
                <value>
                    <fullName>Fair</fullName>
                </value>
                <value>
                    <fullName>Poor</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContactKey_TXT__c</fullName>
        <label>Contact Key</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Ids_ID__c</fullName>
        <label>Dealer IDs</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Doors_TXT__c</fullName>
        <label>Doors</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Lead Provider)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model_ID__c</fullName>
        <label>Model ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_TXT__c</fullName>
        <label>Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_NM__c</fullName>
        <label>Vin Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OdometerStatus_TXT__c</fullName>
        <label>Odometer Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Rolledover</fullName>
                </value>
                <value>
                    <fullName>Replaced</fullName>
                </value>
                <value>
                    <fullName>Original</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Odometer_TXT__c</fullName>
        <label>Odometer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProviderDetail_TXT__c</fullName>
        <inlineHelpText>Source Lead Provider Name</inlineHelpText>
        <label>Provider Detail</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Send_confirmation_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send confirmation Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trim_TXT__c</fullName>
        <label>Model Trim</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VehicleInterest_TXT__c</fullName>
        <label>Vehicle Interest</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lease</fullName>
                </value>
                <value>
                    <fullName>Buy</fullName>
                </value>
                <value>
                    <fullName>Sell</fullName>
                </value>
                <value>
                    <fullName>Trade-in</fullName>
                </value>
                <value>
                    <fullName>Test-drive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VehicleStatus_TXT__c</fullName>
        <label>Vehicle Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Used</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year_YR__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>customerAccount_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Customer Account)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Acura</fullName>
        <active>true</active>
        <businessProcess>HELMS Sales Process</businessProcess>
        <description>Used by the Honda Acura Team</description>
        <label>Acura Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Marine</fullName>
        <active>true</active>
        <businessProcess>HELMS Standard Process</businessProcess>
        <description>Used by the Honda Marine Team</description>
        <label>Marine Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/HELMSLeadConvertToOppHandlerTest.cls
/****************************************************************************** 
File Name:      HELMSLeadConvertToOppHandler   
Created On:     19th May, 2021
Created By:     Bandi Sujatha, Appirio
Test Classes:   HELMSLeadConvertToOppHandlerTest        
HELMS Jira Story: 
===============================================================================
Modification Log:14th April 2023 by Bruno Costa
*******************************************************************************
*/

@isTest
public class HELMSLeadConvertToOppHandlerTest {
    public static testMethod void handleLeadToOppInsertTest() {
        List<Lead> leadList = new List<Lead>();    
        Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Id conRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
         Account accTestRec = new Account(Name='Test Account123another',DealerCode_CD__c = '123',RecordTypeId=dealerAccRecTypeId
                                         );
        insert accTestRec;
        contact con = new Contact(FirstName='John',LastName='Doe',Email='yash1234@testing.com',Title='Mr',
                                        AccountId=accTestRec.Id, RecordTypeId=conRecTypeId );
        insert con;
        Id personAccRecType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account personAccTest = new Account(FirstName='Test Person Account',LastName='person',RecordTypeId=personAccRecType);
        Insert personAccTest;
        Account pro = new Account(name ='abc' ,Send_Customer_Acknowledgement_Email_Flag__c =true,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert pro; 
        Test.setMock(HttpCalloutMock.class, new LeadEnrichMockTest()); 
        Lead lead = new Lead(LastName='Doe',Email='yash1234@testing.com',CustomerAccount_ID__c=personAccTest.id,PreferredDealerAccount_ID__c =accTestRec.id, FirstName='John',Company='Test',Status='Ready_to_Convert',
                             Dealer_Ids_ID__c='testing',Year_YR__c='test',Model_TXT__c='demoooo',ProviderDetail_TXT__c='test11:test21',
                             Model_ID__c='demo',Trim_TXT__c='trimmer',SubDiv_TXT__c='Marine',PostalCode='12345',
                             PreferredDealerNumber_NUM__c='123',Division_CD__c='P',VehicleInterest_TXT__c='buy',
                            ContactKey_TXT__c ='test',VehicleStatus_TXT__c='New',Condition_TXT__c='excellent',
                             Number_NM__c='number',Doors_TXT__c='doortxt',BodyStyle_TXT__c='bodyStyle',Odometer_TXT__c='odmeter',
                             LeadProvider_ID__c = pro.Id,Send_confirmation_Email__c=true,
                             OdometerStatus_TXT__c='unknown',OdometerUnits_TXT__c='kilometer',  Color_TXT__c='<colorcombination><interiorcolor/><exteriorcolor>Deep Pearl Gray</exteriorcolor><preference>1</preference></colorcombination>');
        leadList.add(lead);
         Lead lead1 = new Lead(LastName='Doe',CustomerAccount_ID__c=personAccTest.id,PreferredDealerAccount_ID__c =accTestRec.id, FirstName='John',Company='Test',Status='Ready_to_Convert',
                             Dealer_Ids_ID__c='testing',Year_YR__c='test',Model_TXT__c='demoooo',ProviderDetail_TXT__c='test11',
                             Model_ID__c='demo',Trim_TXT__c='trimmer',SubDiv_TXT__c='Acura',PostalCode='12345',
                             PreferredDealerNumber_NUM__c='123',Division_CD__c='B',VehicleInterest_TXT__c='buy', LeadProvider_ID__c = pro.Id,Send_confirmation_Email__c=true,
                            ContactKey_TXT__c ='test',VehicleStatus_TXT__c='New',Condition_TXT__c='excellent',
                             Number_NM__c='number',Doors_TXT__c='doortxt',BodyStyle_TXT__c='bodyStyle',Odometer_TXT__c='odmeter',
                             OdometerStatus_TXT__c='unknown',OdometerUnits_TXT__c='kilometer',  Color_TXT__c='<colorcombination><interiorcolor/><exteriorcolor>Deep Pearl Gray</exteriorcolor><preference>1</preference></colorcombination>');
        leadList.add(lead1);
        
       Lead lead2 = new Lead(LastName='Doe',CustomerAccount_ID__c=personAccTest.id,PreferredDealerAccount_ID__c =accTestRec.id, FirstName='John',Company='Test',Status='Ready_to_Convert',
                             Dealer_Ids_ID__c='testing',Year_YR__c='test',Model_TXT__c='demoooo',ProviderDetail_TXT__c='test11',
                             Model_ID__c='demo',Trim_TXT__c='trimmer',SubDiv_TXT__c='Motorcycle',PostalCode='12345',
                             PreferredDealerNumber_NUM__c='123',Division_CD__c='M',VehicleInterest_TXT__c='buy', LeadProvider_ID__c = pro.Id,Send_confirmation_Email__c=true,
                            ContactKey_TXT__c ='test',VehicleStatus_TXT__c='New',Condition_TXT__c='excellent',
                             Number_NM__c='number',Doors_TXT__c='doortxt',BodyStyle_TXT__c='bodyStyle',Odometer_TXT__c='odmeter',
                             OdometerStatus_TXT__c='unknown',OdometerUnits_TXT__c='kilometer',  Color_TXT__c='<colorcombination><interiorcolor/><exteriorcolor>Deep Pearl Gray</exteriorcolor><preference>1</preference></colorcombination>');
        leadList.add(lead2);
        
        insert leadList;
        
        Lead newld = leadList[0];
        newld.ProviderDetail_TXT__c = 'test11:test22';
        update newld;
        
        
     
        Account accTestRec1 = new Account(Name='Test Account123another',RecordTypeId=dealerAccRecTypeId,
                                          DealerCode_CD__c=leadList[0].Dealer_Ids_ID__c
                                         );
        insert accTestRec1;
        
          Lead_Expiration__c le = new Lead_Expiration__c();
        le.A__c = 90;
        le.B__c = 90;
        le.M__c = 90;
        le.P__c = -1;
        insert le;
        
         List<opportunity> opp1 = new list<opportunity>();
  //       String Str = leadList[0].Model_TXT__c;
       // for(i=0;i<=3;i++){
        Opportunity oppRec = new Opportunity(Name='YashLead',StageName='In Conversation',
                                             PreferredDealerNumber_NUM__c='123456', External_ID__c='12345',ZipCode_TXT__c = '12345',
                                             CloseDate=system.today(),Lead_ID__c=leadList[0].Id,AccountId=accTestRec.id,
                                             Trim_TXT__c = leadList[0].Trim_TXT__c,
                                             Make_TXT__c =leadList[0].Make_TXT__c,ContactKey_TXT__c =leadList[0].ContactKey_TXT__c,
                                             VehicleStatus_TXT__c=leadList[0].VehicleStatus_TXT__c,Condition_TXT__c=leadList[0].Condition_TXT__c,
                                             Number_NM__c=leadList[0].Number_NM__c,Doors_TXT__c=leadList[0].Doors_TXT__c,BodyStyle_TXT__c=leadList[0].BodyStyle_TXT__c,
                                             Odometer_TXT__c=leadList[0].Odometer_TXT__c,
                                             OdometerStatus_TXT__c=leadList[0].OdometerStatus_TXT__c,OdometerUnits_TXT__c=leadList[0].OdometerUnits_TXT__c);
        //insert OppRec; 
            opp1.add(oppRec);
    //        System.debug('OppRec1'+oppRec);
       // }
              //  Database.SaveResult[] results = Database.insert(Opp1, false);
               //System.assert(results.isSuccess());
        HELMSLeadConvertToOppHandler.flag =false;
        list<string> ldIds = new list<string>();
        for(Lead ld:leadList) {
            ldIds.add(ld.id);
        }
        
        /*DSP Code test - start - BrunoC- DS-1182*/
        List<Lead> insertedLeads = [SELECT Id FROM Lead WHERE Id IN :leadList];
		System.assertEquals(3, insertedLeads.size(), 'Expected 3 leads to be inserted, but found ' + insertedLeads.size());
        /*DSP Code test - end - BrunoC- DS-1182*/

        HELMSLeadConvertToOppHandler.handleLeadToOppInsert(leadList);
        
        //HELMSLeadConvertToOppHandler.AutoleadConvert(opp1,ldIds);
    }
    static testMethod void TestAutoleadConvert() { 
        SFMCResponse sfm = new SFMCResponse();
        SFMCResponse.responses sfres = new SFMCResponse.responses();
        sfres.hasErrors = false;
        sfres.recipientSendId = 'test';
        sfres.messages = new list<string> {'test'};
        sfm.requestId = 'testId';
        sfm.responses = new list<SFMCResponse.responses> {sfres};
        HelmsCheckRecursive.runOnce();
        Account accTestRec1 = new Account(Name='Test Account123another');
        insert accTestRec1;
        Test.setMock(HttpCalloutMock.class, new LeadEnrichMockTest());
        Lead objLead = new Lead( FirstName = 'Test', LastName = 'Sample', Company = 'Testing Sample Co',Make_TXT__c='vhn',  Color_TXT__c='<colorcombination><interiorcolor/><exteriorcolor>Deep Pearl Gray</exteriorcolor><preference>1</preference></colorcombination>');  
        insert objLead;
        Account pro = new Account(name ='abc' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert pro; 
        
        List<opportunity> opp = new list<opportunity>();
        Opportunity oppr = new Opportunity(Name='YashLead123',StageName='In Conversation',
                                             PreferredDealerNumber_NUM__c='123456', External_ID__c='12345',
                                             ZipCode_TXT__c = '12345',Email__c='testopp@test.com',
                                             PreferredDealerAccount_TXT__c = accTestRec1.Id,First_Name_TXT__c='Test opp19', Last_Name_TXT__c ='Test opp LAst9', LeadProvider_ID__c=pro.id,
                                             CloseDate=system.today(),Lead_ID__c=objLead.Id,Make_TXT__c =objLead.Make_TXT__c);
        opp.add(oppr);              
        insert opp;
        
        
        
        HELMSLeadConvertToOppHandler.AutoleadConvert(opp);
        
       
        
        
    }  
    static testMethod void TestAutoleadUpdate(){
        List<Lead> leadList1 = new List<Lead>();                  
        Lead lead = new Lead(LastName='Doe',FirstName='John',Company='Test',Status='Ready_to_Convert',
                             Model_TXT__c='demoooo',
                             Model_ID__c='demo',Trim_TXT__c='trimmer',
                             PreferredDealerNumber_NUM__c='test',VehicleInterest_TXT__c='buy',
                             ContactKey_TXT__c ='test',VehicleStatus_TXT__c='New',Condition_TXT__c='excellent',
                             Number_NM__c='number',Doors_TXT__c='doortxt',BodyStyle_TXT__c='bodyStyle',Odometer_TXT__c='odmeter',
                             OdometerStatus_TXT__c='unknown',OdometerUnits_TXT__c='kilometer',  Color_TXT__c='<colorcombination><interiorcolor/><exteriorcolor>Deep Pearl Gray</exteriorcolor><preference>1</preference></colorcombination>');
        leadList1.add(lead);
        Test.setMock(HttpCalloutMock.class, new LeadEnrichMockTest());
        insert leadList1;   
        HELMSLeadConvertToOppHandler.handleLeadToOppInsert(leadList1);
        HELMSLeadTriggerHandlerUpdated.handleLeadInsert(leadList1);
        HELMSLeadTriggerHandlerUpdated.handleLeadInsert(null);
        HELMSLeadTriggerHandlerUpdated.getColorCombination('colour');
        HELMSLeadTriggerHandlerUpdated.getColorCombination(null);
        HELMSLeadTriggerHandlerUpdated.handleLeadUpdate(null,null);
    }
}