objects/Account.object
<CustomObject>
    <fields>
        <fullName>Send_Customer_Acknowledgement_Email_Flag__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Send Customer Acknowledgement Email</description>
        <label>Send Customer Acknowledgement Email</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>BrandsiteShoppingTool_TXT__c</fullName>
        <label>Brandsite Shopping Tool</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactKey_TXT__c</fullName>
        <label>Contact Key</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exterior_Color__c</fullName>
        <label>Exterior Color</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Interior_Color__c</fullName>
        <label>Interior Color</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Provider</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Lead Provider)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model_TXT__c</fullName>
        <label>Model</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PreferredDealerAccount_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreferredDealerContact_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Dealer Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_confirmation_Email__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Business Unit: HELMS.
Jira Story: LMS-5361 Story name.
Description: This is store the true or false form SFMC.
Source System: Coming from Integration.
Integration: No
Data Transformation: N/A.
Functional Definition: If the  flag is true Lead  Data sent to SFMC.</description>
        <label>Send confirmation Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>Subdivision</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division_CD__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year_YR__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/HelmsLeadCrationNotificationSFMCAcura.cls
global class HelmsLeadCrationNotificationSFMCAcura {

    //Fetching all Lead record ids which will Created from Aura.
    public static void leadCreationSFMCAura(List<Lead> acuraLead) {
        
      
        
      /*  List<Lead> ledlist=[SELECT Id,FirstName,Exterior_Color__c,Interior_Color__c,PreferredDealerContact_ID__r.email, ContactKey_TXT__c,
                            Email, Model_TXT__c, SubDiv_TXT__c,Division_CD__c,PreferredDealerAccount_ID__r.Phone,
                            PreferredDealerAccount_ID__r.name,PreferredDealerAccount_ID__r.ShippingStreet,
                            PreferredDealerAccount_ID__r.ShippingCity,PreferredDealerAccount_ID__r.ShippingState,
                            PreferredDealerAccount_ID__r.ShippingPostalCode,PreferredDealerAccount_ID__r.ShippingCountry,
                            BrandsiteShoppingTool_TXT__c,Send_confirmation_Email__c,Year_YR__c,PreferredDealerContact_ID__r.name  FROM Lead
                            where SubDiv_TXT__c='Acura'  AND BrandsiteShoppingTool_TXT__c =null  AND isConverted = true AND Send_confirmation_Email__c = true AND
                            LeadProvider_ID__r.Send_Customer_Acknowledgement_Email_Flag__c = true AND id IN: ids];*/
    
            
        AuraWprapperClass sr = new AuraWprapperClass ();
        for(Lead l : acuraLead) {
            AuraWprapperClass.subscriberAttributes subscribe = new AuraWprapperClass.subscriberAttributes ();
            AuraWprapperClass.contactAttributes conAttributes = new AuraWprapperClass.contactAttributes ();
            AuraWprapperClass.To to = new AuraWprapperClass.To ();
            
            string shippingstreet ='';
            string shippingcity='';
            string shippingState='';
            string shippingpostalcode='';
            string shippingcountry='';
            if(l.PreferredDealerAccount_ID__r.ShippingStreet!=null){
                shippingstreet = l.PreferredDealerAccount_ID__r.ShippingStreet;   
            }
            if(l.PreferredDealerAccount_ID__r.ShippingCity!=null){
                shippingcity = l.PreferredDealerAccount_ID__r.ShippingCity;  
            }
            if(l.PreferredDealerAccount_ID__r.shippingState!=null){
                shippingState= l.PreferredDealerAccount_ID__r.shippingState;
            }
            if(l.PreferredDealerAccount_ID__r.ShippingPostalCode!=null){
                shippingpostalcode = l.PreferredDealerAccount_ID__r.ShippingPostalCode;   
            }
            if(l.PreferredDealerAccount_ID__r.ShippingCountry!=null){
                shippingcountry = l.PreferredDealerAccount_ID__r.ShippingCountry;   
            }
            string dealerAddress1=shippingstreet +' '+ shippingcity +' '+shippingState ;
            string dealerAddress2=shippingpostalcode +' '+shippingcountry;
            
            subscribe.dATA10 = dealerAddress1;
            subscribe.dATA11 = dealerAddress2;
            subscribe.fName= l.FirstName;
            subscribe.dATA39 =l.Year_YR__c;
            subscribe.dATA41 =l.Exterior_Color__c;
            subscribe.dATA42 =l.Interior_Color__c;
            subscribe.sENDERFNAME = l.PreferredDealerAccount_ID__r.name;
            subscribe.dATA9 = l.PreferredDealerContact_ID__r.name;
            subscribe.dATA6 = l.PreferredDealerAccount_ID__r.Phone;
            subscribe.dATA2 = l.Model_TXT__c;
            subscribe.rEPLYTOEMAIL = l.PreferredDealerContact_ID__r.email; //emailMap.get(l.PreferredDealerContact_ID__c);
            conAttributes.subscriberAttributes = subscribe;
            to.address = l.Email;
            to.subscriberKey = l.ContactKey_TXT__c;
            to.contactAttributes = conAttributes;
            sr.To = to;
            
            
            // Authorization Request to get access token.
            HttpRequest req = new HttpRequest();           
            req.setHeader('Accept', 'application/json');
            req.setHeader('Content-Type','application/json;charset=UTF-8');
            req.setMethod('POST');
            req.setEndpoint('callout:mSFMC_Credentails');
            //req.setEndpoint('https://mc219s2l565j37tg6q88270hftr1.auth.marketingcloudapis.com/v2/token'); 
            
            req.setTimeout(120000);
            
            SFMCAuthentication sf=  new SFMCAuthentication();
            sf.grant_type = HELMSConstants.grant_type;
            sf.client_id = HELMSConstants.client_id;
            sf.client_secret = HELMSConstants.client_secret;
            sf.account_id = HELMSConstants.account_id;
            String jsonString = JSON.serialize(sf);
      //      system.debug('JsonString------>>>>'+JsonString);
            req.setBody(jsonString);
            Http http = new Http();
            HTTPResponse res = http.send(req);
      //      system.debug(res.getBody());
            oAuthClass autorize = (oAuthClass)JSON.deserialize(res.getBody(), oAuthClass.class);
            string accesstoken = autorize.access_token; 
            
            
                
            //Requested Json body send to SFMC based on Access Token.
            HttpRequest req1 = new HttpRequest();
            req1.setHeader('Accept', 'application/json');
            req1.setHeader('Content-Type','application/json;charset=UTF-8');
            //string accesstoken ='eyJhbGciOiJIUzI1NiIsImtpZCI6IjQiLCJ2ZXIiOiIxIiwidHlwIjoiSldUIn0.eyJhY2Nlc3NfdG9rZW4iOiI3ekZ0Z0NWY3Y4dXpwSTlaQlJFRW9MRTkiLCJjbGllbnRfaWQiOiJxdm5mY2tqZHM1aW9jMm8yb2gzOG5yM2QiLCJlaWQiOjcyOTM2NDcsInN0YWNrX2tleSI6IlM3IiwicGxhdGZvcm1fdmVyc2lvbiI6MiwiY2xpZW50X3R5cGUiOiJTZXJ2ZXJUb1NlcnZlciJ9._7XHNPD91a4JYbeHeBSZXJPqpzwnwyvzWAR2Y23MPuo.JVetWdbrqfFhoR7ARFI7crsn9jYm3D8S34Ycp2C3yjXSgfngTYEcmOyz-T1dABs8zfmGjpB2IEkXmnpQzwKRqtfo7cJYWiU5Cl1Jc-ICtd9r39lmMDylXGGwyLIHzMjpIU5ldRJY5HPT';
            req1.setHeader('Authorization','Bearer ' + accesstoken);
            req1.setMethod('POST');
            //req1.setEndpoint('https://mc219s2l565j37tg6q88270hftr1.rest.marketingcloudapis.com/messaging/v1/messageDefinitionSends/key:69023/send');
            req1.setEndpoint('callout:AcuraSecondCall');
            req1.setTimeout(120000);
            
            String jsonString1=JSON.serialize(sr);
            req1.setBody(jsonString1);
     //       system.debug('JsonString1'+JsonString1);
            Http http1 = new Http();
            HTTPResponse res1 = http1.send(req1);
    //        system.debug(res1.getBody());
                
        }
    }
    public class oAuthClass {
        public string access_token {get;set;} 
    }
    
    
}