objects/Account.object
<CustomObject>
    <fields>
        <fullName>RoutingDate_DT__c</fullName>
        <defaultValue>DATETIMEVALUE(&quot;2099-01-01 00:00:00&quot;)</defaultValue>
        <label>Routing Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CustomerAccount_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Customer Account)</relationshipLabel>
        <relationshipName>Leads2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LeadGrade_FLG__c</fullName>
        <formula>(Is_Enrichment_Update__c = true &amp;&amp; (NOT( ISBLANK( FirstName ))) &amp;&amp;( NOT( ISBLANK( LastName ))) &amp;&amp; (NOT(ISPICKVAL( Division_CD__c , &apos;&apos;)) &amp;&amp; (ValidEmail_FLG__c = TRUE || ValidPhoneNum_FLG__c = TRUE|| ValidMobile_FLG__c = TRUE ) &amp;&amp; PreferredDealerAccount_ID__c &lt;&gt; NULL &amp;&amp;
(ISPICKVAL( ValidName_TXT__c , &apos;&apos;)||ISPICKVAL( ValidName_TXT__c , &apos;Genuine&apos;)) &amp;&amp;
(ISPICKVAL( Address_Cache_Status__c , &apos;&apos;)||ISPICKVAL( Address_Cache_Status__c , &apos;Genuine&apos;))||
((ISPICKVAL( Email_Cache_Status__c , &apos;&apos;)||ISPICKVAL( Email_Cache_Status__c , &apos;Genuine&apos;))&amp;&amp;
(ISPICKVAL( ValidName_TXT__c , &apos;&apos;)||ISPICKVAL( ValidName_TXT__c , &apos;Genuine&apos;)) &amp;&amp;
NOT(ISPICKVAL( Address_Cache_Status__c , &apos;Genuine&apos;)))&amp;&amp;
(ISPICKVAL( Email_Cache_Status__c , &apos;&apos;)||ISPICKVAL( Email_Cache_Status__c , &apos;Genuine&apos;)) &amp;&amp; NOT( ISBLANK( LeadProvider_ID__c ) ) ) ) &amp;&amp; LeadProvider_ID__r.Enrichment__c = true &amp;&amp;
( (ISPICKVAL( Triggertypecode__c , &apos;Instant&apos;)) ||
( (ISPICKVAL( Triggertypecode__c , &apos;Future&apos;) || ISPICKVAL( Triggertypecode__c , &apos;FixedDate&apos;)) &amp;&amp; ( ISBLANK(LeadProvider_ID__r.Routing_Date_Termination__c ) || LeadProvider_ID__r.Routing_Date_Termination__c &gt; NOW()) &amp;&amp; ISBLANK( LeadProvider_ID__r.RoutingDate_DT__c ) &amp;&amp; TriggerSendbyDate_DT__c &lt;= NOW() ) ||
( (ISPICKVAL( Triggertypecode__c , &apos;Future&apos;) || ISPICKVAL( Triggertypecode__c , &apos;FixedDate&apos;)) &amp;&amp; ( ISBLANK(LeadProvider_ID__r.Routing_Date_Termination__c ) || LeadProvider_ID__r.Routing_Date_Termination__c &gt; NOW()) &amp;&amp; ISBLANK(TriggerSendbyDate_DT__c) &amp;&amp; NOT(ISBLANK( LeadProvider_ID__c )) &amp;&amp; NOT(ISBLANK( LeadProvider_ID__r.RoutingDate_DT__c ))&amp;&amp; LeadProvider_ID__r.RoutingDate_DT__c &lt;= NOW() ) ||
( (ISPICKVAL( Triggertypecode__c , &apos;Future&apos;) || ISPICKVAL( Triggertypecode__c , &apos;FixedDate&apos;)) &amp;&amp; ( ISBLANK(LeadProvider_ID__r.Routing_Date_Termination__c ) || LeadProvider_ID__r.Routing_Date_Termination__c &gt; NOW()) &amp;&amp; NOT(ISBLANK(TriggerSendbyDate_DT__c)) &amp;&amp; NOT(ISBLANK( LeadProvider_ID__c )) &amp;&amp; NOT(ISBLANK( LeadProvider_ID__r.RoutingDate_DT__c )) &amp;&amp; TriggerSendbyDate_DT__c &lt; LeadProvider_ID__r.RoutingDate_DT__c &amp;&amp; TriggerSendbyDate_DT__c &lt;= NOW() ) ||
( (ISPICKVAL( Triggertypecode__c , &apos;Future&apos;)|| ISPICKVAL( Triggertypecode__c , &apos;FixedDate&apos;)) &amp;&amp; ( ISBLANK(LeadProvider_ID__r.Routing_Date_Termination__c ) || LeadProvider_ID__r.Routing_Date_Termination__c &gt; NOW()) &amp;&amp; NOT(ISBLANK(TriggerSendbyDate_DT__c)) &amp;&amp; NOT(ISBLANK( LeadProvider_ID__c )) &amp;&amp; NOT(ISBLANK( LeadProvider_ID__r.RoutingDate_DT__c )) &amp;&amp; LeadProvider_ID__r.RoutingDate_DT__c &lt; TriggerSendbyDate_DT__c &amp;&amp; LeadProvider_ID__r.RoutingDate_DT__c &lt;= NOW() )

)</formula>
        <label>Lead Grade</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Provider</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Lead Provider)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreferredDealerAccount_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RoutingDate_DT__c</fullName>
        <label>Routing Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>StatusReason_TXT__c</fullName>
        <defaultValue>(&quot;Pending&quot;)</defaultValue>
        <label>Status Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Inactivity</fullName>
                </value>
                <value>
                    <fullName>Duplicate Merged</fullName>
                </value>
                <value>
                    <fullName>Validation Email</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Lead Provider error</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Opt Out</fullName>
                </value>
                <value>
                    <fullName>Duplicate Similar</fullName>
                </value>
                <value>
                    <fullName>Matched Leads</fullName>
                </value>
                <value>
                    <fullName>Related Opportunity closed</fullName>
                </value>
                <value>
                    <fullName>Unable to assign Dealer</fullName>
                </value>
                <value>
                    <fullName>Name/Address/Email Error</fullName>
                </value>
                <value>
                    <fullName>Name/Address/Email Cache</fullName>
                </value>
                <value>
                    <fullName>Third Party Duplicate</fullName>
                </value>
                <value>
                    <fullName>Waiting for the routing window to start</fullName>
                </value>
                <value>
                    <fullName>Routing Window Expired</fullName>
                </value>
                <value>
                    <fullName>Concierge</fullName>
                </value>
                <value>
                    <fullName>Lead Enrichment call error</fullName>
                </value>
                <value>
                    <fullName>Dealer Assignment call failed</fullName>
                </value>
                <value>
                    <fullName>Journey Completed</fullName>
                </value>
                <value>
                    <fullName>New Opportunity Created</fullName>
                </value>
                <value>
                    <fullName>Journey incomplete, no response</fullName>
                </value>
                <value>
                    <fullName>Concierge Completed</fullName>
                </value>
                <value>
                    <fullName>Invalid email and phone</fullName>
                </value>
                <value>
                    <fullName>Customer is not Interested in the product</fullName>
                </value>
                <value>
                    <fullName>In nurturing journey</fullName>
                </value>
                <value>
                    <fullName>Waiting for Deal Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TriggerSendbyDate_DT__c</fullName>
        <label>Trigger Send by Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Triggertypecode__c</fullName>
        <label>Trigger Type Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Instant</fullName>
                    <default>true</default>
                    <label>Instant</label>
                </value>
                <value>
                    <fullName>Future</fullName>
                </value>
                <value>
                    <fullName>FixedDate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ValidEmail_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valid Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ValidName_TXT__c</fullName>
        <defaultValue>NULL</defaultValue>
        <label>Name Cache Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reject</fullName>
                </value>
                <value>
                    <fullName>Cache</fullName>
                </value>
                <value>
                    <fullName>Genuine</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ValidPhoneNum_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valid Phone Number</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Lead Provider)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TriggerSendbyDate_DT__c</fullName>
        <label>Trigger Send by Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TriggerTypeCode__c</fullName>
        <label>Trigger Type Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Instant</fullName>
                    <default>true</default>
                    <label>Instant</label>
                </value>
                <value>
                    <fullName>Future</fullName>
                </value>
                <value>
                    <fullName>FixedDate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ValidEmail_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valid Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ValidName_TXT__c</fullName>
        <label>Valid Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reject</fullName>
                </value>
                <value>
                    <fullName>Cache</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ValidPhoneNum_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valid Phone Number</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>customerAccount_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Customer Account)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/HELMS_OpportunityCreationLeadBatch.cls
global class HELMS_OpportunityCreationLeadBatch implements Database.Batchable<sObject>,Database.Stateful,Schedulable{
    
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        //String statusVal = 'Ready_to_Convert';
        //String nullValue = '';
       String fieldsAPIName='';
        String triggertypecode = 'Instant';
        date d = system.today();
        //String whereConition ='isConverted=false and ValidEmail_FLG__c=true and ValidPhoneNum_FLG__c=true  and ValidName_TXT__c=null and PostalCode !=null and PreferredDealerAccount_ID__c!=null and CustomerAccount_ID__c!=null and ( (Triggertypecode__c =:Triggertypecode ) OR (LeadProvider_ID__c = null and TriggerSendbyDate_DT__c <=:d ) OR (LeadProvider_ID__c != null and LeadProvider_ID__r.RoutingDate_DT__c <=: d ))';
        String statusClosed =  'Closed - Not Converted';
        String statusVal = 'Pending';
        String statusVal2 = 'Duplicate Similar';
        String statusonhold = 'Waiting for the routing window to start';
        String journeyCompleted = 'Journey Completed';
        String tpd = 'Third Party Duplicate';
        String newOppcreated = 'New Opportunity Created';
        String conciergeCompleted = 'Concierge Completed';
        String LECE = 'Lead Enrichment call error';
        String WFDR = 'Waiting for Deal Information';
        
        
        String whereConition ='CustomerAccount_ID__c!=null and isConverted=false and LeadGrade_FLG__c=true and (StatusReason_TXT__c=null or StatusReason_TXT__c =:statusVal or StatusReason_TXT__c =:statusVal2 or StatusReason_TXT__c =: statusonhold or StatusReason_TXT__c =:JourneyCompleted or StatusReason_TXT__c =:tpd or StatusReason_TXT__c =:newOppcreated or StatusReason_TXT__c =:ConciergeCompleted or StatusReason_TXT__c =:LECE or StatusReason_TXT__c =:WFDR) and Division_CD__c!=null and Status!=:statusClosed';
        
        //system.debug('batch start');
        for(HELMS_LeadConversionFieldsToOpportunity__mdt metaDataRec : [select Label,LeadFieldAPIName__c from HELMS_LeadConversionFieldsToOpportunity__mdt])
        {
            fieldsAPIName=fieldsAPIName+metaDataRec.LeadFieldAPIName__c+',';
        }
        fieldsAPIName=fieldsAPIName.substring(0,fieldsAPIName.length()-1);
        /* String dataQuery = 'select '+fieldsAPIName+' from lead where LeadGrade_FLG__c=true and '+
            'Status=:statusVal and PreferredDealerAccount_ID__c!=:nullValue and '+
            'CustomerAccount_ID__c!=:nullValue';
        */
        String dataQuery = 'select '+fieldsAPIName+' from lead where '+whereConition;
        
        return Database.getQueryLocator(dataQuery);
    }
    
    global void execute(Database.BatchableContext bc, List<Lead> leadListRecord)
    {
        try
        {
          
           HELMSLeadConvertToOppHandler.handleLeadToOppInsert(leadListRecord);
            
        }catch(Exception ex){
            Logs__c logRecord = new Logs__c(Name='HELMS_OpportunityCreationLead Batch Error', Trigger_or_Class_Name__c='HELMS_OpportunityCreationLead', Error_Message__c = ex.getMessage(), Error_Line_Number__c = Integer.valueOf(ex.getLineNumber()));
            insert logRecord;
            
        }        
        
        
    }
    
    global void finish(Database.BatchableContext bc){
        
    }
    
    
    global void execute (SchedulableContext sc){
         HELMS_OpportunityCreationLeadBatch leadConversionBatchInstance = new HELMS_OpportunityCreationLeadBatch();
        Id batchId = Database.executeBatch(leadConversionBatchInstance,1);
    }
}