objects/Account.object
<CustomObject>
    <fields>
        <fullName>DealerCode_CD__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HondaDigitalSolutions_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Honda Digital Solutions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Routable_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Provider Routable status for the dealers who are not enrolled in the HDS program</inlineHelpText>
        <label>Routable?</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <description>Used for Provider Records</description>
        <label>Provider</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CRM_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRM System</label>
        <referenceTo>CRM_System__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <label>Provider</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CRM_System__c.object
<CustomObject>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ISActive_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vendor_ID__c</fullName>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CRM Systems</relationshipLabel>
        <relationshipName>CRM_Systems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CRM System</label>
    <nameField>
        <label>CRM System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRM Systems</pluralLabel>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Dealer_Division__c.object
<CustomObject>
    <description>list of active or inactive division, subdivision, zone, district and other territory related fields based on their business use for Sales, Service, Parts, etc.</description>
    <fields>
        <fullName>Dealer_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Subdivision</relationshipLabel>
        <relationshipName>Dealer_Divisions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name_TXT__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InternetCertified_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead Enrollment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name_TXT__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>isActive_FLG__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Dealer Subdivision</label>
    <nameField>
        <displayFormat>DD-{0}</displayFormat>
        <label>Dealer Division Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Divisions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Dealer_Participation__c.object
<CustomObject>
    <fields>
        <fullName>CRM_System__c</fullName>
        <label>CRM System</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Division__c</field>
                <operation>equals</operation>
                <valueField>CRM_System__c.Division_CD__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CRM_System__c</referenceTo>
        <relationshipLabel>Dealer Participations</relationshipLabel>
        <relationshipName>Dealer_Participations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DealerAccount_ID__c</fullName>
        <label>Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Participations</relationshipLabel>
        <relationshipName>Dealer_Participations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ISActive_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LeadReceivingStartDate_DT__c</fullName>
        <label>Lead Receiving Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Dealer Participation</label>
    <nameField>
        <label>Dealer Participation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <label>External IDs</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Provider</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Lead Provider)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Group_ID__c</fullName>
        <externalId>true</externalId>
        <label>Lead Group ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MSRP_AMT__c</fullName>
        <label>MSRP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Options_TXT__c</fullName>
        <label>Lead Options</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_AMT__c</fullName>
        <label>Quote</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>Subdivision</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division_CD__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead_Disposition_Last_Event_Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Create a custom setting to map Oppty state and status to one of the below numbers. Only create platform event if a matching entry was fround in the custom setting. 

trigger should fire afterupdate of oppty if status/stage changed

We will need a mapping from the Oppty stage/status combination to on of the following values.  Note that only the numeric portion of the below list is to be populated in the event: SEE LMS-1671
1.  Sale (if oppty stage type changes to Closed/won) = Closed Won
2-  Meeting (oppty stage/status change: tbd) = Dealer Visit
3 - Letter (oppty stage/status change: tbd) = &lt;not used&gt;
4 - Phone (oppty stage/status change: tbd) = In Conversation
5 - Note (oppty stage/status change: tbd) = In Conversation
6 - Inactive (if oppty stage type chagnes to Closed/lost) = Closed Inactive
7 - email (oppty stage/status change: tbd) = In Conversations</description>
    <fields>
        <fullName>Last_Event__c</fullName>
        <label>Last Event</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StageName__c</fullName>
        <label>StageName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Lead_Disposition_Last_Event_Status</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <label>External IDs</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>First_Name_TXT__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name_TXT__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Lead Provider)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Group_ID__c</fullName>
        <externalId>true</externalId>
        <label>Lead Group ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MSRP_AMT__c</fullName>
        <label>MSRP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Options_TXT__c</fullName>
        <label>Options</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PreferredDealerAccount_TXT__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Preferred Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_AMT__c</fullName>
        <label>Quote</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Routable_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Routable?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Quote_AMT__c</fullName>
        <label>Total Quote AMT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ZipCode_TXT__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Acura</fullName>
        <active>true</active>
        <businessProcess>HELMS Sales Process</businessProcess>
        <description>Used by the Honda Acura Team</description>
        <label>Acura Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Engine</fullName>
        <active>true</active>
        <businessProcess>HELMS Standard Process</businessProcess>
        <description>Used by the Honda Engine Team</description>
        <label>Engine Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Honda</fullName>
        <active>true</active>
        <businessProcess>HELMS Sales Process</businessProcess>
        <description>Used by the Honda Team</description>
        <label>Honda Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Marine</fullName>
        <active>true</active>
        <businessProcess>HELMS Standard Process</businessProcess>
        <description>Used by the Honda Marine Team</description>
        <label>Marine Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Power_Equipment</fullName>
        <active>true</active>
        <businessProcess>HELMS Standard Process</businessProcess>
        <description>Used by the Honda Power Equipment Team</description>
        <label>Power Equipment Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Power_Sports</fullName>
        <active>true</active>
        <businessProcess>HELMS Sales Process</businessProcess>
        <description>Used by the Honda Power Sports Team</description>
        <label>Power Sports Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>First_Name_TXT__c</fullName>
        <formula>Opportunity.First_Name_TXT__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name_TXT__c</fullName>
        <formula>Opportunity.Last_Name_TXT__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Quote</fullName>
        <active>true</active>
        <label>Quote</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/HELMSOpportunityTriggerTest.cls
@IsTest
public class HELMSOpportunityTriggerTest{

    @testSetup
    public static void testData()
    {
        Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Account accTestRec = new Account(Name='Test Account123',RecordTypeId=dealerAccRecTypeId,
                                         DealerCode_CD__c='123456'
                                        );
        insert accTestRec;
        system.assertNotEquals(null, accTestRec.Id);
        
        Id conRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Contact conTestRec = new Contact(FirstName='YashLead1234',LastName='Record1234',Email='yash1234@testing.com',Title='Mr',
                                        AccountId=accTestRec.Id, RecordTypeId=conRecTypeId );
        insert conTestRec;
        
        Account accTestRec2 = new Account(Name='Test Account1232',RecordTypeId=dealerAccRecTypeId,
                                         DealerCode_CD__c='1234562'
                                        );
        insert accTestRec2;
        system.assertNotEquals(null, accTestRec.Id);
        Contact conTestRec2 = new Contact(FirstName='Yashead12342',LastName='Record12342',Email='yash12342@testing.com',Title='Mr',
                                        AccountId=accTestRec2.Id);
        //insert conTestRec2;
        
        Lead_Disposition_Last_Event_Status__c custom = new Lead_Disposition_Last_Event_Status__c(name='Test',StageName__c='Closed Won', Last_Event__c=2);
        insert custom;
    }
    
    @IsTest
    public static void handleOppUpdateInsertTest()
    {
        Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Account acc = new Account(Name='Test Account12322',RecordTypeId=dealerAccRecTypeId,
                                         DealerCode_CD__c='1234'
                                        );
        insert acc;
        
         Account pro = new Account(name ='abc' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert pro; 
            
        Opportunity OppRec = new Opportunity(Name='YashLead1234',StageName='In Conversation',PreferredDealerAccount_TXT__c=acc.id, Email__c='abc@test.com', ZipCode_TXT__c='12345',MSRP_AMT__c=200,Quote_AMT__c=500,
                                PreferredDealerNumber_NUM__c='1234', External_ID__c='12345',CloseDate=system.today() , First_Name_TXT__c='Test opp19', Last_Name_TXT__c ='Test opp LAst9', LeadProvider_ID__c=pro.id,
                                Options_TXT__c='<option><optionname>Sport</optionname><manufacturercode>p394</manufacturercode><stock>100</stock><weighting>65</weighting><price>19500</price></option><option><optionname>Sport</optionname><manufacturercode>p394</manufacturercode><stock>100</stock><weighting>65</weighting><price type="invoice" currency="USD" source="Kelley Blue Book">19500</price><price type="appraisal" currency="USD" delta="percentage" relativeto="invoice" source="KBB"/><price type="msrp" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="quote" currency="USD" delta="absolute">19000</price><price type="offer" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="call" currency="USD" delta="percentage" relativeto="msrp">2</price><price type="asking" currency="USD" delta="percentage" relativeto="msrp">2</price></option>'
                                );
                                
        Test.startTest();
        insert OppRec;
        OppRec.StageName='Closed Won';
        OppRec.CloseDate=system.today();
        update OppRec;
        /*
        string json = '[{"optionname": "Sport","manufacturercode": "p394","stock": "100","weighting": "65"},{"optionname": "Sport","manufacturercode": "p394","stock": "100","weighting": "65"}]';
        System.JSONParser parser = System.JSON.createParser(json);
        OptionsJSON2Apex.parse(json);
        */
        Test.stopTest();
        
    }    
    
    @IsTest
    public static void JsonTest() {
       
        UserRole r = new UserRole(DeveloperName = 'HELMS_Standard', Name = 'HELMS_Standard');
        insert r;      
       Profile profile_2 = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
            User admin = new User( 
            Email = 'Test1239username@gmail.com',
            ProfileId = profile_2.Id, 
            UserRoleId = r.Id,
            UserName = 'Test391nameAdminass@gmail.com', 
            Alias = 'Test',
            TimeZoneSidKey = 'America/New_York',
            EmailEncodingKey = 'ISO-8859-1',
            LocaleSidKey = 'en_US', 
            LanguageLocaleKey = 'en_US',
            PortalRole = 'Manager',
            FirstName = 'AdminFirstname',
            LastName = 'AdminLastname'
        );
        insert admin;
        User user;
        Account acc;
        Contact con;
        Account pro;
      System.runAs(admin){
        Id p = [select id from profile where name='HELMS Partner Community'].id;

        Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
         acc = new Account(Name='Test Account123',RecordTypeId=dealerAccRecTypeId,
                                         DealerCode_CD__c='515722'
                                        );
        insert acc;
        
        Id conRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        con = new Contact(FirstName='YashLead1234',LastName='Record1234',Email='yash1234@testing.com',Title='Mr',
                                        AccountId=acc.Id, RecordTypeId=conRecTypeId );
        insert con;
                
        pro = new Account(name ='Acura Dealer Created' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert pro; 
        
        user = new User(alias = 'mamavv', email='test123@noemail.com',
        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
        localesidkey='en_US', profileid = p, country='United States',IsActive =true,
        ContactId = con.Id,
        timezonesidkey='America/Los_Angeles', username='testermamathalaa@noemail.com');

        insert user;
        }
        system.runAs(user) {
        // statements to be executed by this test user.
        pro = new Account(name ='abc' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert pro; 
            Opportunity oppRec = new Opportunity(Name='YashLead1234',StageName='In Conversation',PreferredDealerAccount_TXT__c=acc.id, Email__c='yash1234@testing.com', ZipCode_TXT__c='12345',MSRP_AMT__c=200,Quote_AMT__c=500,
                                    PreferredDealerNumber_NUM__c='515722', External_ID__c='12345',CloseDate=system.today() ,First_Name_TXT__c='Test opp1', Last_Name_TXT__c ='Test opp LAst', 
                                  LeadProvider_ID__c=pro.id,  Options_TXT__c='<option><optionname>Sport</optionname><manufacturercode>p394</manufacturercode><stock>100</stock><weighting>65</weighting><price type="invoice" currency="USD" source="Kelley Blue Book">19500</price><price type="appraisal" currency="USD" delta="percentage" relativeto="invoice" source="KBB"/><price type="msrp" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="quote" currency="USD" delta="absolute">19000</price><price type="offer" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="call" currency="USD" delta="percentage" relativeto="msrp">2</price><price type="asking" currency="USD" delta="percentage" relativeto="msrp">2</price></option>'
                                    );
            Opportunity oppRec2 = new Opportunity(Name='YashLead1234',StageName='In Conversation',PreferredDealerAccount_TXT__c=acc.id, Email__c='yash1234@testing.com', ZipCode_TXT__c='12345',MSRP_AMT__c=200,Quote_AMT__c=500,
                                    PreferredDealerNumber_NUM__c='515722', External_ID__c='12345',CloseDate=system.today() ,Division_CD__c='A', SubDiv_TXT__c='Honda', First_Name_TXT__c='Test opp12', Last_Name_TXT__c ='Test opp LAst2', 
                                    RecordTypeId=Schema.SObjectType.opportunity.getRecordTypeInfosByDeveloperName().get('Honda').getRecordTypeId(),
                                    LeadProvider_ID__c=pro.id, Options_TXT__c='<option><optionname>Sport</optionname><manufacturercode>p394</manufacturercode><stock>100</stock><weighting>65</weighting><price type="invoice" currency="USD" source="Kelley Blue Book">19500</price><price type="appraisal" currency="USD" delta="percentage" relativeto="invoice" source="KBB"/><price type="msrp" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="quote" currency="USD" delta="absolute">19000</price><price type="offer" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="call" currency="USD" delta="percentage" relativeto="msrp">2</price><price type="asking" currency="USD" delta="percentage" relativeto="msrp">2</price></option>'
                                    );
            Opportunity oppRec3 = new Opportunity(Name='YashLead1234',StageName='In Conversation',PreferredDealerAccount_TXT__c=acc.id, Email__c='yash1234@testing.com', ZipCode_TXT__c='12345',MSRP_AMT__c=200,Quote_AMT__c=500,
                                    PreferredDealerNumber_NUM__c='515722', External_ID__c='12345',CloseDate=system.today() , Division_CD__c='B', SubDiv_TXT__c='Acura', First_Name_TXT__c='Test opp13', Last_Name_TXT__c ='Test opp LAst3', 
                                    RecordTypeId=Schema.SObjectType.opportunity.getRecordTypeInfosByDeveloperName().get('Acura').getRecordTypeId(),
                                   LeadProvider_ID__c=pro.id,  Options_TXT__c='<option><optionname>Sport</optionname><manufacturercode>p394</manufacturercode><stock>100</stock><weighting>65</weighting><price type="invoice" currency="USD" source="Kelley Blue Book">19500</price><price type="appraisal" currency="USD" delta="percentage" relativeto="invoice" source="KBB"/><price type="msrp" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="quote" currency="USD" delta="absolute">19000</price><price type="offer" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="call" currency="USD" delta="percentage" relativeto="msrp">2</price><price type="asking" currency="USD" delta="percentage" relativeto="msrp">2</price></option>'
                                    );
            Opportunity oppRec7 = new Opportunity(Name='YashLead1234',StageName='In Conversation',PreferredDealerAccount_TXT__c=acc.id, Email__c='yash1234@testing.com', ZipCode_TXT__c='12345',MSRP_AMT__c=200,Quote_AMT__c=500,
                                    PreferredDealerNumber_NUM__c='515722', External_ID__c='12345',CloseDate=system.today() , Division_CD__c='P', SubDiv_TXT__c='Engine', First_Name_TXT__c='Test opp14', Last_Name_TXT__c ='Test opp LAst4', 
                                    RecordTypeId=Schema.SObjectType.opportunity.getRecordTypeInfosByDeveloperName().get('Engine').getRecordTypeId(),
                                    LeadProvider_ID__c=pro.id, Options_TXT__c='<option><optionname>Sport</optionname><manufacturercode>p394</manufacturercode><stock>100</stock><weighting>65</weighting><price type="invoice" currency="USD" source="Kelley Blue Book">19500</price><price type="appraisal" currency="USD" delta="percentage" relativeto="invoice" source="KBB"/><price type="msrp" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="quote" currency="USD" delta="absolute">19000</price><price type="offer" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="call" currency="USD" delta="percentage" relativeto="msrp">2</price><price type="asking" currency="USD" delta="percentage" relativeto="msrp">2</price></option>'
                                    );
            Opportunity oppRec4 = new Opportunity(Name='YashLead1234',StageName='In Conversation',PreferredDealerAccount_TXT__c=acc.id, Email__c='yash1234@testing.com', ZipCode_TXT__c='12345',MSRP_AMT__c=200,Quote_AMT__c=500,
                                    PreferredDealerNumber_NUM__c='515722', External_ID__c='12345',CloseDate=system.today() , Division_CD__c='M', SubDiv_TXT__c='Motorcycle', First_Name_TXT__c='Test opp15', Last_Name_TXT__c ='Test opp LAst5', 
                                    RecordTypeId=Schema.SObjectType.opportunity.getRecordTypeInfosByDeveloperName().get('Power_Sports').getRecordTypeId(),
                                    LeadProvider_ID__c=pro.id, Options_TXT__c='<option><optionname>Sport</optionname><manufacturercode>p394</manufacturercode><stock>100</stock><weighting>65</weighting><price type="invoice" currency="USD" source="Kelley Blue Book">19500</price><price type="appraisal" currency="USD" delta="percentage" relativeto="invoice" source="KBB"/><price type="msrp" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="quote" currency="USD" delta="absolute">19000</price><price type="offer" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="call" currency="USD" delta="percentage" relativeto="msrp">2</price><price type="asking" currency="USD" delta="percentage" relativeto="msrp">2</price></option>'
                                    );
            Opportunity oppRec5 = new Opportunity(Name='YashLead1234',StageName='In Conversation',PreferredDealerAccount_TXT__c=acc.id, Email__c='yash1234@testing.com', ZipCode_TXT__c='12345',MSRP_AMT__c=200,Quote_AMT__c=500,
                                    PreferredDealerNumber_NUM__c='515722', External_ID__c='12345',CloseDate=system.today() , Division_CD__c='P', SubDiv_TXT__c='PowerEquipment', First_Name_TXT__c='Test opp16', Last_Name_TXT__c ='Test opp LAst6', 
                                    RecordTypeId=Schema.SObjectType.opportunity.getRecordTypeInfosByDeveloperName().get('Power_Equipment').getRecordTypeId(),
                                    LeadProvider_ID__c=pro.id, Options_TXT__c='<option><optionname>Sport</optionname><manufacturercode>p394</manufacturercode><stock>100</stock><weighting>65</weighting><price type="invoice" currency="USD" source="Kelley Blue Book">19500</price><price type="appraisal" currency="USD" delta="percentage" relativeto="invoice" source="KBB"/><price type="msrp" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="quote" currency="USD" delta="absolute">19000</price><price type="offer" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="call" currency="USD" delta="percentage" relativeto="msrp">2</price><price type="asking" currency="USD" delta="percentage" relativeto="msrp">2</price></option>'
                                    );
            Opportunity oppRec6 = new Opportunity(Name='YashLead1234',StageName='In Conversation',PreferredDealerAccount_TXT__c=acc.id, Email__c='yash1234@testing.com', ZipCode_TXT__c='12345',MSRP_AMT__c=200,Quote_AMT__c=500,
                                    PreferredDealerNumber_NUM__c='515722', External_ID__c='12345',CloseDate=system.today() , Division_CD__c='B', SubDiv_TXT__c='Acura', First_Name_TXT__c='Test opp17', Last_Name_TXT__c ='Test opp LAst7',
                                   LeadProvider_ID__c=pro.id,  RecordTypeId=Schema.SObjectType.opportunity.getRecordTypeInfosByDeveloperName().get('Acura').getRecordTypeId(), Total_Quote_AMT__c=100
                                     );
            Test.startTest();
            List<Opportunity> opplist = new List<Opportunity>();
            opplist.add(oppRec);
            opplist.add(oppRec2);
            opplist.add(oppRec3);
            //opplist.add(OppRec4);
            //opplist.add(OppRec5);
            //opplist.add(OppRec6);
            //opplist.add(OppRec7);
            insert opplist;
           
            OppRec.StageName='Closed Won';
            OppRec.CloseDate=system.today();
            update oppRec;

        }
    }
@IsTest
    public static void JsonTest1() {
       
        UserRole r = new UserRole(DeveloperName = 'HELMS_Standard', Name = 'HELMS_Standard');
        insert r;      
       Profile profile_2 = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
            User admin = new User( 
            Email = 'Test1239username@gmail.com',
            ProfileId = profile_2.Id, 
            UserRoleId = r.Id,
            UserName = 'Test391nameAdminass@gmail.com', 
            Alias = 'Test',
            TimeZoneSidKey = 'America/New_York',
            EmailEncodingKey = 'ISO-8859-1',
            LocaleSidKey = 'en_US', 
            LanguageLocaleKey = 'en_US',
            PortalRole = 'Manager',
            FirstName = 'AdminFirstname',
            LastName = 'AdminLastname'
        );
        insert admin;
        User user;
        Account acc;
        Contact con;
        Account pro;
      System.runAs(admin){
        Id p = [select id from profile where name='HELMS Partner Community'].id;

        Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
         acc = new Account(Name='Test Account123',RecordTypeId=dealerAccRecTypeId,
                                         DealerCode_CD__c='515722'
                                        );
        insert acc;
        
        Id conRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        con = new Contact(FirstName='YashLead1234',LastName='Record1234',Email='yash1234@testing.com',Title='Mr',
                                        AccountId=acc.Id, RecordTypeId=conRecTypeId );
        insert con;
                
        pro = new Account(name ='Honda Dealer Created' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        //insert pro; 
        
        user = new User(alias = 'mamavv', email='test123@noemail.com',
        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
        localesidkey='en_US', profileid = p, country='United States',IsActive =true,
        ContactId = con.Id,
        timezonesidkey='America/Los_Angeles', username='testermamathalaa@noemail.com');

        insert user;
        }
        system.runAs(user) {
        // statements to be executed by this test user.
        pro = new Account(name ='Honda Dealer Created' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert pro;
        Account pro1 = new Account(name ='Acura Dealer Created' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert pro1;
            Account pro2 = new Account(name ='Engine Dealer Created' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert pro2;
            Account pro3 = new Account(name ='Motorcycle Dealer Created' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert pro3;
            Account pro4 = new Account(name ='werEquipment Dealer Created' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert pro4;
            Account pro5 = new Account(name ='Marine Dealer Created' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert pro5;
            Test.startTest();
            Opportunity OppRec21 = new Opportunity(Name='YashLead1234',StageName='In Conversation',PreferredDealerAccount_TXT__c=acc.id, Email__c='yash1234@testing.com', ZipCode_TXT__c='12345',MSRP_AMT__c=200,Quote_AMT__c=500,
                                    PreferredDealerNumber_NUM__c='515722', External_ID__c='12345',CloseDate=system.today() ,Division_CD__c='A', SubDiv_TXT__c='Honda', First_Name_TXT__c='Test opp12', Last_Name_TXT__c ='Test opp LAst2', 
                                    RecordTypeId=Schema.SObjectType.opportunity.getRecordTypeInfosByDeveloperName().get('Honda').getRecordTypeId(),
                                    LeadProvider_ID__c=pro.id, Options_TXT__c='<option><optionname>Sport</optionname><manufacturercode>p394</manufacturercode><stock>100</stock><weighting>65</weighting><price type="invoice" currency="USD" source="Kelley Blue Book">19500</price><price type="appraisal" currency="USD" delta="percentage" relativeto="invoice" source="KBB"/><price type="msrp" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="quote" currency="USD" delta="absolute">19000</price><price type="offer" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="call" currency="USD" delta="percentage" relativeto="msrp">2</price><price type="asking" currency="USD" delta="percentage" relativeto="msrp">2</price></option>'
                                    );
            insert OppRec21;
            OppRec21.LeadProvider_ID__c = null;
            update OppRec21;
            OppRec21.LeadProvider_ID__c = null;
            OppRec21.SubDiv_TXT__c='Acura';
            OppRec21.Division_CD__c= 'B';
            OppRec21.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByDeveloperName().get('Acura').getRecordTypeId();
            //update OppRec21;
            OppRec21.LeadProvider_ID__c = null;
            OppRec21.SubDiv_TXT__c='Engine';
            OppRec21.Division_CD__c= 'P';
            OppRec21.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByDeveloperName().get('Engine').getRecordTypeId();
            /*update OppRec21;
            OppRec21.LeadProvider_ID__c = null;
            OppRec21.SubDiv_TXT__c='Motorcycle';
            OppRec21.Division_CD__c= 'M';
            OppRec21.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByDeveloperName().get('Power_Sports').getRecordTypeId();
            //update OppRec21;
            OppRec21.LeadProvider_ID__c = null;
            OppRec21.SubDiv_TXT__c='PowerEquipment';
            OppRec21.Division_CD__c= 'P';
            OppRec21.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByDeveloperName().get('Power_Equipment').getRecordTypeId();
            update OppRec21;
            OppRec21.LeadProvider_ID__c = null;
            OppRec21.SubDiv_TXT__c='Marine';
            OppRec21.Division_CD__c= 'P';
            OppRec21.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByDeveloperName().get('Marine').getRecordTypeId();
            update OppRec21;*/
        }
    } 
    @IsTest
    public static void JsonTest2() {
       
        UserRole r = new UserRole(DeveloperName = 'HELMS_Standard', Name = 'HELMS_Standard');
        insert r;      
       Profile profile_2 = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
            User admin = new User( 
            Email = 'Test1239username@gmail.com',
            ProfileId = profile_2.Id, 
            UserRoleId = r.Id,
            UserName = 'Test391nameAdminass@gmail.com', 
            Alias = 'Test',
            TimeZoneSidKey = 'America/New_York',
            EmailEncodingKey = 'ISO-8859-1',
            LocaleSidKey = 'en_US', 
            LanguageLocaleKey = 'en_US',
            PortalRole = 'Manager',
            FirstName = 'AdminFirstname',
            LastName = 'AdminLastname'
        );
        insert admin;
        User user;
        Account acc;
        Contact con;
        Account pro;
      System.runAs(admin){
        Id p = [select id from profile where name='HELMS Partner Community'].id;

        Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
         acc = new Account(Name='Test Account123',RecordTypeId=dealerAccRecTypeId,
                                         DealerCode_CD__c='515722'
                                        );
        insert acc;
        
        Id conRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        con = new Contact(FirstName='YashLead1234',LastName='Record1234',Email='yash1234@testing.com',Title='Mr',
                                        AccountId=acc.Id, RecordTypeId=conRecTypeId );
        insert con;
                
        pro = new Account(name ='Honda Dealer Created' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        //insert pro; 
        
        user = new User(alias = 'mamavv', email='test123@noemail.com',
        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
        localesidkey='en_US', profileid = p, country='United States',IsActive =true,
        ContactId = con.Id,
        timezonesidkey='America/Los_Angeles', username='testermamathalaa@noemail.com');

        insert user;
        }
        system.runAs(user) {
        // statements to be executed by this test user.
        pro = new Account(name ='Honda Dealer Created' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert pro;
        Account pro1 = new Account(name ='Acura Dealer Created' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        //insert pro1;
            Account pro2 = new Account(name ='Engine Dealer Created' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        //insert pro2;
            Account pro3 = new Account(name ='Motorcycle Dealer Created' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert pro3;
            Account pro4 = new Account(name ='werEquipment Dealer Created' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert pro4;
            Account pro5 = new Account(name ='Marine Dealer Created' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert pro5;
            Account pro6 = new Account(name ='PowerEquipment Dealer Created' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert pro6;
            Test.startTest();
            Opportunity OppRec21 = new Opportunity(Name='YashLead1234',StageName='In Conversation',PreferredDealerAccount_TXT__c=acc.id, Email__c='yash1234@testing.com', ZipCode_TXT__c='12345',MSRP_AMT__c=200,Quote_AMT__c=500,
                                    PreferredDealerNumber_NUM__c='515722', External_ID__c='12345',CloseDate=system.today() ,Division_CD__c='A', SubDiv_TXT__c='Honda', First_Name_TXT__c='Test opp12', Last_Name_TXT__c ='Test opp LAst2', 
                                    RecordTypeId=Schema.SObjectType.opportunity.getRecordTypeInfosByDeveloperName().get('Honda').getRecordTypeId(),
                                    LeadProvider_ID__c=pro.id, Options_TXT__c='<option><optionname>Sport</optionname><manufacturercode>p394</manufacturercode><stock>100</stock><weighting>65</weighting><price type="invoice" currency="USD" source="Kelley Blue Book">19500</price><price type="appraisal" currency="USD" delta="percentage" relativeto="invoice" source="KBB"/><price type="msrp" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="quote" currency="USD" delta="absolute">19000</price><price type="offer" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="call" currency="USD" delta="percentage" relativeto="msrp">2</price><price type="asking" currency="USD" delta="percentage" relativeto="msrp">2</price></option>'
                                    );
            //insert OppRec21;
            //OppRec21.LeadProvider_ID__c = null;
            //update OppRec21;
            /*OppRec21.LeadProvider_ID__c = null;
            OppRec21.SubDiv_TXT__c='Acura';
            OppRec21.Division_CD__c= 'B';
            OppRec21.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByDeveloperName().get('Acura').getRecordTypeId();
            update OppRec21;
            OppRec21.LeadProvider_ID__c = null;
            OppRec21.SubDiv_TXT__c='Engine';
            OppRec21.Division_CD__c= 'P';
            OppRec21.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByDeveloperName().get('Engine').getRecordTypeId();
            update OppRec21;*/
            OppRec21.LeadProvider_ID__c = null;
            OppRec21.SubDiv_TXT__c='Motorcycle';
            OppRec21.Division_CD__c= 'M';
            OppRec21.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByDeveloperName().get('Power_Sports').getRecordTypeId();
            insert OppRec21;
            OppRec21.LeadProvider_ID__c = null;
            OppRec21.SubDiv_TXT__c='PowerEquipment';
            OppRec21.Division_CD__c= 'P';
            OppRec21.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByDeveloperName().get('Power_Equipment').getRecordTypeId();
            update OppRec21;
            OppRec21.LeadProvider_ID__c = null;
            OppRec21.SubDiv_TXT__c='Marine';
            OppRec21.Division_CD__c= 'P';
            OppRec21.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByDeveloperName().get('Marine').getRecordTypeId();
           // update OppRec21;
        }
    } 
   @IsTest
    public static void handleOppUpdateInsertTest1()
    {
        Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Account acc = new Account(Name='Test Account12322',RecordTypeId=dealerAccRecTypeId,
                                         DealerCode_CD__c='1234'
                                        );
        insert acc;
        
         Account pro = new Account(name ='abc' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert pro; 
        Lead newLead = new Lead(lastName='Test last',Email='Testing@testing.com',Lead_Group_ID__c='12345');
        insert newLead;
        Opportunity OppRec = new Opportunity(Name='YashLead1234',StageName='In Conversation',PreferredDealerAccount_TXT__c=acc.id, Email__c='abc@test.com', ZipCode_TXT__c='12345',MSRP_AMT__c=200,Quote_AMT__c=500,
                                PreferredDealerNumber_NUM__c='1234',Lead_Group_ID__c='12345', External_ID__c='12345',CloseDate=system.today() , First_Name_TXT__c='Test opp19', Last_Name_TXT__c ='Test opp LAst9', LeadProvider_ID__c=pro.id,
                                Options_TXT__c='<option><optionname>Sport</optionname><manufacturercode>p394</manufacturercode><stock>100</stock><weighting>65</weighting><price>19500</price></option><option><optionname>Sport</optionname><manufacturercode>p394</manufacturercode><stock>100</stock><weighting>65</weighting><price type="invoice" currency="USD" source="Kelley Blue Book">19500</price><price type="appraisal" currency="USD" delta="percentage" relativeto="invoice" source="KBB"/><price type="msrp" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="quote" currency="USD" delta="absolute">19000</price><price type="offer" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="call" currency="USD" delta="percentage" relativeto="msrp">2</price><price type="asking" currency="USD" delta="percentage" relativeto="msrp">2</price></option>'
                                );
                                
        Test.startTest();
        insert OppRec;
        OppRec.StageName='Closed Won';
        OppRec.CloseDate=system.today();
        update OppRec;
        OppRec.StageName='Closed Inactive';
        OppRec.CloseDate=system.today();
        update OppRec;
        Test.stopTest();
        
    } 
@IsTest
    public static void handleOppUpdateInsertTest2()
    {
        Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Account acc = new Account(Name='Test Account12322',RecordTypeId=dealerAccRecTypeId,
                                         DealerCode_CD__c='1234',Routable_FLG__c=true,HondaDigitalSolutions_FLG__c=true
                                        );
        insert acc;
        
         Account pro = new Account(name ='abc' , HondaDigitalSolutions_FLG__c=true,Routable_FLG__c=true, recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Vendor').getRecordTypeId()) ;
        insert pro; 
        Lead newLead = new Lead(lastName='Test last',Email='Testing@testing.com',Lead_Group_ID__c='12345');
        insert newLead;
        Dealer_Division__c dDivision = new Dealer_Division__c(First_Name_TXT__c='test', 
                                                                  InternetCertified_FLG__c=true,
                                                                  Dealer_ID__c=acc.Id,
                                                                  SubDiv_TXT__c ='Honda',
                                                                  isActive_FLG__c=true);
        insert dDivision;
        CRM_System__c crmSystem = new CRM_System__c(Name='Test crm',Vendor_ID__c=pro.Id,ISActive_FLG__c=true);
        insert crmSystem;
        Dealer_Participation__c dParticip = new Dealer_Participation__c(LeadReceivingStartDate_DT__c=System.NOW()-12,
                                                                           //ISActive_FLG__c=true,
                                                                           DealerAccount_ID__c=acc.Id,
                                                                           Dealer_Subdivision__c=dDivision.Id,
                                                                        CRM_System__c=crmSystem.Id);
        insert dParticip;
        Opportunity OppRec = new Opportunity(Name='YashLead1234',StageName='In Conversation',PreferredDealerAccount_TXT__c=acc.id, Email__c='abc@test.com', ZipCode_TXT__c='12345',MSRP_AMT__c=200,Quote_AMT__c=500,
                                PreferredDealerNumber_NUM__c='1234',Lead_Group_ID__c='12345', External_ID__c='12345',CloseDate=system.today() , First_Name_TXT__c='Test opp19', SubDiv_TXT__c='Honda',Last_Name_TXT__c ='Test opp LAst9', LeadProvider_ID__c=pro.id,
                                recordtypeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Honda').getRecordTypeId(),Routable_FLG__c=false,             
                                Options_TXT__c='<option><optionname>Sport</optionname><manufacturercode>p394</manufacturercode><stock>100</stock><weighting>65</weighting><price>19500</price></option><option><optionname>Sport</optionname><manufacturercode>p394</manufacturercode><stock>100</stock><weighting>65</weighting><price type="invoice" currency="USD" source="Kelley Blue Book">19500</price><price type="appraisal" currency="USD" delta="percentage" relativeto="invoice" source="KBB"/><price type="msrp" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="quote" currency="USD" delta="absolute">19000</price><price type="offer" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="call" currency="USD" delta="percentage" relativeto="msrp">2</price><price type="asking" currency="USD" delta="percentage" relativeto="msrp">2</price></option>'
                                );
                                
        Test.startTest();
        insert OppRec;
        Test.stopTest();
        
    }  
    @IsTest
    public static void handleOppUpdateInsertTest3()
    {
        Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Account acc = new Account(Name='Test Account12322',RecordTypeId=dealerAccRecTypeId,
                                         DealerCode_CD__c='1234'
                                        );
        insert acc;
        
         Account pro = new Account(name ='Acura Dealer Created' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert pro; 
            
        Opportunity OppRec = new Opportunity(Name='YashLead1234',StageName='In Conversation',PreferredDealerAccount_TXT__c=acc.id, Email__c='abc@test.com', ZipCode_TXT__c='12345',MSRP_AMT__c=200,Quote_AMT__c=500,
                                PreferredDealerNumber_NUM__c='1234', External_ID__c='12345',CloseDate=system.today() , First_Name_TXT__c='Test opp19', Last_Name_TXT__c ='Test opp LAst9', LeadProvider_ID__c=pro.id,
                                Options_TXT__c='<option><optionname>Sport</optionname><manufacturercode>p394</manufacturercode><stock>100</stock><weighting>65</weighting><price>19500</price></option><option><optionname>Sport</optionname><manufacturercode>p394</manufacturercode><stock>100</stock><weighting>65</weighting><price type="invoice" currency="USD" source="Kelley Blue Book">19500</price><price type="appraisal" currency="USD" delta="percentage" relativeto="invoice" source="KBB"/><price type="msrp" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="quote" currency="USD" delta="absolute">19000</price><price type="offer" currency="USD" delta="relative" relativeto="invoice" source="KBB">200</price><price type="call" currency="USD" delta="percentage" relativeto="msrp">2</price><price type="asking" currency="USD" delta="percentage" relativeto="msrp">2</price></option>'
                                );
                                
        Test.startTest();
        insert OppRec;
        OppRec.StageName='Closed Won';
        OppRec.CloseDate=system.today();
        update OppRec;
        /*
        string json = '[{"optionname": "Sport","manufacturercode": "p394","stock": "100","weighting": "65"},{"optionname": "Sport","manufacturercode": "p394","stock": "100","weighting": "65"}]';
        System.JSONParser parser = System.JSON.createParser(json);
        OptionsJSON2Apex.parse(json);
        */
        Test.stopTest();
        
    }
    @isTest
    public static void findDuplicateOpportunityTest(){
        Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Account acc = new Account(Name='Test AccountDupOpp',RecordTypeId=dealerAccRecTypeId,
                                         DealerCode_CD__c='1234'
                                        );
        insert acc;
          Account pro = new Account(name ='Acura Dealer Created' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert pro; 
            
        Opportunity OppRec = new Opportunity(Name='TestDupOPP',StageName='In Conversation',PreferredDealerAccount_TXT__c=acc.id, Email__c='abc@test.com', ZipCode_TXT__c='12345',Lead_Group_ID__c='00Q7c00000DOOrrrrr',Duplicate_Similar__c=false,
                                PreferredDealerNumber_NUM__c='1234', External_ID__c='12345',CloseDate=system.today() , First_Name_TXT__c='Test opp1', Last_Name_TXT__c ='Test opp Last1', LeadProvider_ID__c=pro.id);
          insert OppRec;                      
        Test.startTest();
        Opportunity oppRec2=new Opportunity(Name='TestDupOPP',StageName='In Conversation',PreferredDealerAccount_TXT__c=acc.id, Email__c='abc@test.com', ZipCode_TXT__c='12345',Lead_Group_ID__c='00Q7c00000DOOrrrrr',Duplicate_Similar__c=true,
                                PreferredDealerNumber_NUM__c='1234', External_ID__c='12345',CloseDate=system.today() , First_Name_TXT__c='Test opp1', Last_Name_TXT__c ='Test opp Last1', LeadProvider_ID__c=pro.id);
        
        
       insert  OppRec2;
        HELMSupdateOppHandler handler=new HELMSupdateOppHandler();
        list<Opportunity> opplst=new list<opportunity>();
        opplst.add(OppRec2);
      //  handler.findDuplicateOpportunity(opplst);
      }
   
}