objects/Account.object
<CustomObject>
    <fields>
        <fullName>DealerCode_CD__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name_TXT__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name_TXT__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Lead Provider)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_SF_ID__c</fullName>
        <externalId>true</externalId>
        <label>Opportunity_SF_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredDealerAccount_TXT__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Preferred Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ZipCode_TXT__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Routing_Acknowledgement_No_Response__c.object
<CustomObject>
    <description>Custom Object to fetch Blank Routing Acknowledgement Response</description>
    <fields>
        <fullName>Opportunity_SF_ID__c</fullName>
        <label>Opportunity SF ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Routing Acknowledgement No Response</label>
    <nameField>
        <label>Routing Acknowledgement No Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routing Acknowledgement No Response</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HelmsBlankRoutingStatusBatchTest.cls
@isTest
public class HelmsBlankRoutingStatusBatchTest {
	@isTest static void exc(){
     Datetime dt = System.now();
     // adding minutes in negative, effectively subtracts 30 mins
     dt = dt.addMinutes(-60);
     Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
     account acc=new account();
     acc.Name = 'Syam Mohan Ac';
     acc.RecordTypeId = dealerAccRecTypeId;
     acc.DealerCode_CD__c='1234562';
     insert acc;
     
     Routing_Acknowledgement_No_Response__c r1 = new Routing_Acknowledgement_No_Response__c();
     r1.Opportunity_SF_ID__c = '123456';
     r1.CreatedDate = dt;
     insert r1;
      
     opportunity opp= new opportunity(Stagename='Assigned to Dealer',PreferredDealerAccount_TXT__c=acc.id,Name='Syam Mohan',First_Name_TXT__c='Mohan', 
     LeadProvider_ID__c=acc.id,Last_Name_TXT__c = 'Mohan',Email__c='syam.gm@gmail.com', ZipCode_TXT__c='12345',Opportunity_SF_ID__c='123456');
     opp.CloseDate= system.Today();
     opp.CreatedDate = dt;
     insert opp;
     
     Test.startTest();
     HelmsBlankRoutingStatusBatch ba= new HelmsBlankRoutingStatusBatch();
     //Id jobid= Database.executeBatch(ba,1);
	 String sch = '0 0 23 * * ?';
	 system.schedule('Testing', sch, ba );
     system.assertEquals(opp.Last_Name_TXT__c,'Mohan' );
     Test.stopTest();
    }
}