objects/Account.object
<CustomObject>
    <fields>
        <fullName>DealerCode_CD__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <formula>CASE(SubDivision_TXT__c , &quot;Honda&quot; , &quot;A&quot;, &quot;Acura&quot;, &quot;B&quot;, &quot;NSX&quot;, &quot;B&quot;, &quot;Motorcycle&quot;, &quot;M&quot;, &quot;Marine&quot;, &quot;P&quot;, &quot;Engine&quot;, &quot;P&quot;, &quot;PowerEquipment&quot;, &quot;P&quot; , &quot;None&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Dealer_Division__c.object
<CustomObject>
    <description>list of active or inactive division, subdivision, zone, district and other territory related fields based on their business use for Sales, Service, Parts, etc.</description>
    <fields>
        <fullName>Dealer_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Subdivision</relationshipLabel>
        <relationshipName>Dealer_Divisions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>InternetCertified_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead Enrollment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>isActive_FLG__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Dealer Subdivision</label>
    <nameField>
        <displayFormat>DD-{0}</displayFormat>
        <label>Dealer Division Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Divisions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Dealer_Assignment_Type__c</fullName>
        <label>Dealer Assignment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Selected</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Proximity</fullName>
                </value>
                <value>
                    <fullName>LDRA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fuel_Type_Code__c</fullName>
        <label>Fuel Type Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>G</fullName>
                    <label>Gasoline Vehicle</label>
                </value>
                <value>
                    <fullName>H</fullName>
                    <label>Hydrogen Fuel Cell Vehicle</label>
                </value>
                <value>
                    <fullName>N</fullName>
                    <label>Compressed Natural Gas Vehicle</label>
                </value>
                <value>
                    <fullName>E</fullName>
                    <label>Electric Vehicle</label>
                </value>
                <value>
                    <fullName>B</fullName>
                    <label>Plug-In Hybrid Vehicle Electricity</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Location_Enrichment_Done__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Location Enrichment Done</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PreferredDealerAccount_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesRelatedDealerNumber__c</fullName>
        <description>SalesRelatedDealerNumber</description>
        <label>SalesRelatedDealerNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceRelatedDealerNumber__c</fullName>
        <description>ServiceRelatedDealerNumber</description>
        <label>Service Related Dealer Number</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>Subdivision</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division_CD__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead_Enrichment_Callout__mdt.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                    <default>true</default>
                    <label>A</label>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>poi_radius__c</fullName>
        <label>poi radius</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lead Enrichment Callout</label>
    <pluralLabel>Lead Enrichment Callout</pluralLabel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/HelmsDealerLocatorService.cls
//This class is used to assign a dealer to a lead based on the address if a lead comes without a dealer number
global class HelmsDealerLocatorService {
    global static boolean dealerLocatorFlag = false;
    global static boolean isUpdatedSalesToService = false;
    global static boolean isUpdatedSalesOnly = false;
    
    public static void updateSalesOnly(Set<Id> listId){
        List<Lead> listToUpdateSalesOnly = new List<Lead>();
        for(Lead leadRec : [Select Id, Name, Dealer_Assignment_Type__c, Is_Location_Enrichment_Done__c, PreferredDealerNumber_NUM__c, SalesRelatedDealerNumber__c, ServiceRelatedDealerNumber__c FROM Lead WHERE Id IN : listId]){
            leadRec.PreferredDealerNumber_NUM__c = leadRec.SalesRelatedDealerNumber__c;
            leadRec.Is_Location_Enrichment_Done__c = true;
            leadRec.Dealer_Assignment_Type__c = 'Sales';
            listToUpdateSalesOnly.add(leadRec); 
        }
        if(listToUpdateSalesOnly.size() > 0 && HelmsDealerLocatorService.isUpdatedSalesOnly == false){
            //System.debug('Just Before Update');
            HelmsDealerLocatorService.isUpdatedSalesOnly = true;
            update listToUpdateSalesOnly;
            //System.debug('listToUpdateSalesToService : '+listToUpdateSalesOnly);
        }
    }
    
    
    public static void updateSalesToService(Set<Id> listId){
        //System.debug('Inside Sales to Service'); 
        List<Lead> listToUpdateSalesToService = new List<Lead>();
        for(Lead leadRec : [Select Id, Name, Dealer_Assignment_Type__c, Is_Location_Enrichment_Done__c, PreferredDealerNumber_NUM__c, SalesRelatedDealerNumber__c, ServiceRelatedDealerNumber__c FROM Lead WHERE Id IN : listId]){
            if( (leadRec.PreferredDealerNumber_NUM__c  != leadRec.ServiceRelatedDealerNumber__c) && (leadRec.SalesRelatedDealerNumber__c  != leadRec.ServiceRelatedDealerNumber__c) ){
            	leadRec.PreferredDealerNumber_NUM__c = leadRec.ServiceRelatedDealerNumber__c;
                leadRec.Is_Location_Enrichment_Done__c = true;
                leadRec.Dealer_Assignment_Type__c = 'Service';
            	listToUpdateSalesToService.add(leadRec);    
            }
        }
        //System.debug('After For Loop. Inside Sales to Service');
        //System.debug('listToUpdateSalesToService : '+listToUpdateSalesToService);
        //System.debug('HELMSleadEnrichmentIntegrationupdate.flag : '+HelmsDealerLocatorService.isUpdatedSalesToService);
        if(listToUpdateSalesToService.size() > 0 && HelmsDealerLocatorService.isUpdatedSalesToService == false){
            //System.debug('Just Before Update');
            HelmsDealerLocatorService.isUpdatedSalesToService = true;
            update listToUpdateSalesToService;
            //System.debug('listToUpdateSalesToService : '+listToUpdateSalesToService);
        }
    }
    
    public static Map<Id,String> checkDistance(Set<Id> listId){
        //System.debug('Inside Check Distance Fun. '+listId);
        Map<Id,String> isReceivedDealer = new Map<Id,String>();
        Map<String,Integer> ppoi = new Map<String,Integer>();
        List<Lead> leadlist = new List<Lead>([Select id,ServiceRelatedDealerNumber__c,SalesRelatedDealerNumber__c from lead where ID IN :listId]);
        List<string> dlrnumlist = new List<string>();
        Set<string> accDistset = new Set<string>();
        Map<id,Account> leadsalesdealerMap = new Map<id,Account>();
        for(lead l: leadlist){
            if(l.ServiceRelatedDealerNumber__c!=null || l.ServiceRelatedDealerNumber__c!='')
                dlrnumlist.add(l.ServiceRelatedDealerNumber__c);
            if(l.SalesRelatedDealerNumber__c!=null || l.SalesRelatedDealerNumber__c!='')
                accDistset.add(l.SalesRelatedDealerNumber__c);      
        }
        List<Account> salesaccounts= new List<Account>([Select id,DealerCode_CD__c,ShippingLatitude,ShippingLongitude from Account where recordtype.developername='Dealer' And DealerCode_CD__c IN:accDistset]);
        Map<string,string> salesnumAccountMap =  new Map<string,string>();
        for(Account a: salesaccounts){
            salesnumAccountMap.put(a.DealerCode_CD__c,a.ShippingLatitude+','+a.ShippingLongitude);
        }
        Set<Account> accset =new Set<Account>([Select id from Account where recordtype.developername='Dealer' And DealerCode_CD__c IN:dlrnumlist]);
        Map<string,Boolean> leadenrollmentmap = new Map<string,Boolean>();
        
        Set<Dealer_Division__c> dlrdivset=new Set<Dealer_Division__c>([select id,Dealer_ID__r.DealerCode_CD__c,SubDiv_TXT__c,InternetCertified_FLG__c from Dealer_Division__c where Dealer_ID__c IN: accset and isActive_FLG__c=true]);
        for (Dealer_Division__c ddivrec :dlrdivset){
            leadenrollmentmap.put(ddivrec.Dealer_ID__r.DealerCode_CD__c+''+ddivrec.SubDiv_TXT__c,ddivrec.InternetCertified_FLG__c);
        }
        for(Lead_Enrichment_Callout__mdt m :[select id,poi_radius__c, Division__c from Lead_Enrichment_Callout__mdt])
        {
        	ppoi.put(m.Division__c , Integer.valueof(m.poi_radius__c));
        }
        if(listId.size() > 0){
            for(Lead leadrec : [SELECT Id, Division_CD__c,SubDiv_TXT__c, PreferredDealerNumber_NUM__c, PreferredDealerAccount_ID__c, PreferredDealerAccount_ID__r.ShippingLatitude, PreferredDealerAccount_ID__r.ShippingLongitude,  SalesRelatedDealerNumber__c, ServiceRelatedDealerNumber__c,Longitude, Latitude FROM Lead WHERE Id IN : listId]){
                //System.debug('Sales Dealer Number : '+leadrec.SalesRelatedDealerNumber__c);
                //System.debug('Service Dealer Number : '+leadrec.ServiceRelatedDealerNumber__c);
                String DealerSelected = 'Location';
                Integer configuredDistance = 0;
                if(ppoi.size() > 0 && ppoi.containskey(leadrec.Division_CD__c)){
                    configuredDistance = ppoi.get(leadrec.Division_CD__c);
                }
                //if(leadrec.PreferredDealerNumber_NUM__c == leadrec.SalesRelatedDealerNumber__c){
                    Location loc1 = Location.newInstance(leadrec.Latitude,leadrec.Longitude);
                /*
                    string lat=salesnumAccountMap.get(leadrec.SalesRelatedDealerNumber__c).substringbetween('latStart','latEnd');
                    string lon=salesnumAccountMap.get(leadrec.SalesRelatedDealerNumber__c).substringbetween('longtStart','longEnd');
                    double latitude= Double.parseDouble(lat);
                    double longitude= Double.parseDouble(lon);
                    Location loc2 = Location.newInstance(latitude,longitude);
                 */
                    string[] latlong =salesnumAccountMap.get(leadrec.SalesRelatedDealerNumber__c).split(',');
                    double latitude= Double.valueof(latlong[0]);
                    double longitude= Double.valueof(latlong[1]);
                    Location loc2 = Location.newInstance(latitude,longitude);
                    //Location loc2 = Location.newInstance((salesnumAccountMap.get(leadrec.SalesRelatedDealerNumber__c)).ShippingLatitude,(salesnumAccountMap.get(leadrec.ServiceRelatedDealerNumber__c).ShippingLatitudeShippingLongitude));
                    //System.debug('loc1 : '+loc1);
                    //System.debug('loc2 : '+loc2);
                    //System.debug('configuredDistance : '+configuredDistance);
                    Double dist = Location.getDistance(loc1, loc2, 'mi');
                    //System.debug('Sales Dealer Distance : '+dist);    
                    
                    if(dist <= configuredDistance){
                        DealerSelected = 'Sales';
                    }else{
                        //System.debug('Service Dealer Number : '+leadrec.ServiceRelatedDealerNumber__c);
                        if(leadrec.ServiceRelatedDealerNumber__c != null &&  leadenrollmentmap.containskey(leadrec.ServiceRelatedDealerNumber__c+''+leadrec.SubDiv_TXT__c) && leadenrollmentmap.get(leadrec.ServiceRelatedDealerNumber__c+''+leadrec.SubDiv_TXT__c)){
                            Boolean isService = HelmsDealerLocatorService.checkServiceDistance(configuredDistance,leadrec.Latitude, leadrec.Longitude, leadrec.ServiceRelatedDealerNumber__c);
                            if(isService){
                            	DealerSelected = 'Service';    
                            }	
                        }
                    }
                //}
                isReceivedDealer.put(leadrec.Id,DealerSelected);
            }
        } 
        return isReceivedDealer;
    }
    
    public static boolean checkServiceDistance(Integer configueddistanceval, Decimal latitude,Decimal longitude, String serviceDealerNumber){
        //System.debug('Inside Service Distance :'+serviceDealerNumber);
        boolean isWithinAllowedRadius = false;
        //True - Service Dealer is within the Configured Distance
        //System.debug('SQL is : '+'SELECT Id,DealerCode_CD__c,ShippingLatitude,ShippingLongitude FROM Account WHERE DealerCode_CD__c = :'+ serviceDealerNumber+'');
        Account accRec = [SELECT Id,DealerCode_CD__c,ShippingLatitude,ShippingLongitude FROM Account WHERE DealerCode_CD__c = : serviceDealerNumber];
        Location loc1 = Location.newInstance(accRec.ShippingLatitude,accRec.ShippingLongitude);
        Location loc2 = Location.newInstance(latitude,longitude);
        Double serviceDist = Location.getDistance(loc1, loc2, 'mi');
        //System.debug('serviceDist : '+serviceDist);
        if(serviceDist <= configueddistanceval ){
            isWithinAllowedRadius = true;
        }
        return isWithinAllowedRadius;
    }
    
    
    @future(callout=true)
    //Set<Id> leadIdSet
    public static void dealerLocatorService(Set<Id> leadIdSet){
        try{
            Map<String,String> ppoi = new Map<String,String>();
            for(Lead_Enrichment_Callout__mdt m :[select id,poi_radius__c, Division__c from Lead_Enrichment_Callout__mdt])
            {
                ppoi.put(m.Division__c , String.valueOf(Integer.valueof(m.poi_radius__c)));
            }
            List<Lead> leadListToUpdate = new List<Lead>();
            Set<Id> leadIdToUpdate = new Set<Id>();
            //List<Lead> leadList = [SELECT Id,Name,Is_Location_Enrichment_Done__c,Dealer_Assignment_Type__c,PreferredDealerAccount_ID__c,PreferredDealerNumber_NUM__c,postalCode,State,Division_CD__c FROM Lead WHERE Id IN : leadIdSet ];
            List<Lead> leadList = [SELECT Id,Name,Is_Location_Enrichment_Done__c,Dealer_Assignment_Type__c,PreferredDealerAccount_ID__c,PreferredDealerNumber_NUM__c,postalCode,State,City,Division_CD__c,Fuel_Type_Code__c FROM Lead WHERE Id IN : leadIdSet ];
            for(Lead leadrec : leadList){
                String apiHeaderParam = '';
                //String apiHeaderAppId = 'helms.honda.com';
                String apiHeaderAppId = 'bodyshops.honda.com';
                apiHeaderParam += '?AppId='+apiHeaderAppId;
                String apiHeaderState = '';
                String apiHeaderCity = '';
                String apiHeaderZipCode = '';
                String apiHeaderPOIType = '';
                String apiHeaderSearchRadius = '';
                String apiHeaderSearchPoiId = '';
                if(leadrec.State != null && leadrec.State != ''){
                    apiHeaderState = leadrec.State;
                }
                apiHeaderParam += '&State='+apiHeaderState;
                if(leadrec.postalCode != null && leadrec.postalCode != ''){
                    apiHeaderZipCode = leadrec.postalCode;
                }
                apiHeaderParam += '&ZipCode='+apiHeaderZipCode;
                if(leadrec.Division_CD__c != null && leadrec.Division_CD__c != ''){
                    apiHeaderPOIType = leadrec.Division_CD__c;
                }
                apiHeaderParam += '&POIType='+apiHeaderPOIType;
                if(ppoi.size() > 0 && ppoi.containsKey(leadrec.Division_CD__c)){
                    apiHeaderSearchRadius = ppoi.get(leadrec.Division_CD__c);
                }
                apiHeaderParam += '&SearchRadius='+apiHeaderSearchRadius;
                if(leadrec.PreferredDealerNumber_NUM__c != null && leadrec.PreferredDealerNumber_NUM__c != ''){
                    //apiHeaderSearchPoiId = leadrec.PreferredDealerNumber_NUM__c;
                    apiHeaderSearchPoiId = '';
                }
                
                //for bev - Bijay-07/28/2023 filter modified for GM
                if(leadrec.Fuel_Type_Code__c=='E'){
                    apiHeaderParam += '&NumberOfPOIs=1&Filters=01%26GM&ShowAllAttributes=False&ShowAllProperties=False&ShowAllDepartments=False&Output=json';
                }
                else{
                    apiHeaderParam += '&NumberOfPOIs=1&Filters=01&ShowAllAttributes=False&ShowAllProperties=False&ShowAllDepartments=False&Output=json';
                }
                
                //apiHeaderParam += '&NumberOfPOIs=1&Filters=01&ShowAllAttributes=False&ShowAllProperties=False&ShowAllDepartments=False&Output=json';
                apiHeaderParam += '&POIId='+apiHeaderSearchPoiId;
                if(leadrec.City != null && leadrec.City != ''){
                    apiHeaderCity = leadrec.City;
                }
                apiHeaderParam += '&City='+apiHeaderCity;
                // API Sending Code
                
                
                
                String contactkey;
                HttpRequest req = new HttpRequest();
                req.setHeader('Accept', 'application/json');
                req.setHeader('Content-Type','application/json;charset=UTF-8');
                string uniqueuid = HELMSleadEnrichmentIntegrationupdate.getUUID();
                req.setHeader('hondaHeaderType.messageId',uniqueuid);
                req.setHeader('hondaHeaderType.siteId',System.Label.siteid);
                req.setHeader('hondaHeaderType.businessId',System.Label.businessId);
                //req.setEndpoint('callout:Enrichment_Location_Service'+'?AppId=helms.honda.com&State=&ZipCode=90503&POIType=A&SearchRadius=250&NumberOfPOIs=1&ShowAllAttributes=False&ShowAllProperties=False&ShowAllDepartments=False&Output=json&POIId=');
                req.setEndpoint('callout:Enrichment_Location_Service'+apiHeaderParam);
                req.setTimeout(120000);
                req.setMethod('GET');
                Http http = new Http();
                HTTPResponse res = http.send(req);
                System.debug('Response----'+res.getBody());
                System.debug('Status----'+res.getStatusCode());
                String jsonResponse = '';
                if(res.getBody() != null && res.getStatusCode() == 200){
                    //System.debug('Inside response');
                    //jsonResponse = res.getBody();
                    JSONParser parser = JSON.createParser(res.getBody());
                    //System.debug('parser : '+parser);
                    while (parser.nextToken() != null) {
                        if(parser.getCurrentName() == 'POIId' && parser.getText() != '' && parser.getText() !='POIId'){
                            //System.debug('POIID : '+parser.getText());
                            if(leadIdToUpdate.size() == 0){
                                leadIdToUpdate.add(leadrec.Id);
                            	leadrec.PreferredDealerNumber_NUM__c = parser.getText();
                                leadrec.Dealer_Assignment_Type__c = 'Proximity';
                                leadrec.Is_Location_Enrichment_Done__c = true;
                            	leadListToUpdate.add(leadrec);    
                            }
                            else if(!leadIdToUpdate.contains(leadrec.Id)){
                                leadIdToUpdate.add(leadrec.Id);
                            	leadrec.PreferredDealerNumber_NUM__c = parser.getText();
                                leadrec.Dealer_Assignment_Type__c = 'Proximity';
                                leadrec.Is_Location_Enrichment_Done__c = true;
                            	leadListToUpdate.add(leadrec);    
                            }
                            break;
                        }   
                    }
                }
            }
            if(leadListToUpdate.size() > 0){
                update leadListToUpdate;
            }
        }Catch(Exception ex){
        	//System.debug('Exception at line : '+ ex.getLineNumber());
            //System.debug('Exception Message : '+ ex.getMessage());
        }
    }
}