objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Owner_by_Division_and_Zone__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>DivisionZone_CD__c</fullName>
        <label>DivisionZone_CD</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Account_Owner_by_Division_and_Zone</label>
</CustomObject>

objects/Dealer_Division__c.object
<CustomObject>
    <description>list of active or inactive division, subdivision, zone, district and other territory related fields based on their business use for Sales, Service, Parts, etc.</description>
    <fields>
        <fullName>Dealer_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Subdivision</relationshipLabel>
        <relationshipName>Dealer_Divisions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesZone_CD__c</fullName>
        <label>Sales Zone</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive_FLG__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Dealer Subdivision</label>
    <nameField>
        <displayFormat>DD-{0}</displayFormat>
        <label>Dealer Division Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Divisions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

classes/HELMSDealerDivisionTriggerTest.cls
@isTest(SeeAllData=false)
public class HELMSDealerDivisionTriggerTest {
    
    @isTest static void divisionTestMethod1(){
       Test.startTest();
        String pid =[Select Id from Profile Where name ='HELMS Standard User'].Id ;
        UserRole r = new UserRole(DeveloperName = 'HELMS_Standard', Name = 'HELMS_Standard');
        insert r;
        User user = new User(alias = 'test123', email='Test@gmail.com',
                             emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                             localesidkey='en_US', profileid = pid, country='United States',IsActive =true,UserRoleid=r.id,
                             timezonesidkey='America/Los_Angeles', username='testuserdiv1@test.com');
        
        insert user;
        
         System.runAs(user) {
            Account_Owner_by_Division_and_Zone__c aow = new Account_Owner_by_Division_and_Zone__c();
            aow.Name = 'M01';
            aow.DivisionZone_CD__c = 'M01';
            aow.username__c = 'testuserdiv1@test.com';
            insert aow;
            
            Account acc = new Account();
            acc.Name = 'Test Kolbe Cycle Sales';
            acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId(); 
            insert acc;
            
            Dealer_Division__c dd = new Dealer_Division__c();
            dd.isActive_FLG__c = True;
            dd.Dealer_ID__c = acc.Id;
            dd.Division_CD__c = 'M';
            dd.SalesZone_CD__c = '01';
          //   dd.ownerid=user.id;
            insert dd;
            }
        system.assertEquals(user.alias, 'test123');
        Test.stopTest();
    }

}