objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact_Key__c</fullName>
        <label>Contact Key</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DealerCode_CD__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <formula>CASE(SubDivision_TXT__c , &quot;Honda&quot; , &quot;A&quot;, &quot;Acura&quot;, &quot;B&quot;, &quot;NSX&quot;, &quot;B&quot;, &quot;Motorcycle&quot;, &quot;M&quot;, &quot;Marine&quot;, &quot;P&quot;, &quot;Engine&quot;, &quot;P&quot;, &quot;PowerEquipment&quot;, &quot;P&quot; , &quot;None&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HondaDigitalSolutions_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Honda Digital Solutions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Routable_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Provider Routable status for the dealers who are not enrolled in the HDS program</inlineHelpText>
        <label>Routable?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_to_Urban_Science_Flag__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Send to Urban Science</description>
        <label>Send to Urban Science</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <description>Used for Provider Records</description>
        <label>Provider</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CRM_System__c.object
<CustomObject>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ISActive_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vendor_ID__c</fullName>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CRM Systems</relationshipLabel>
        <relationshipName>CRM_Systems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CRM System</label>
    <nameField>
        <label>CRM System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRM Systems</pluralLabel>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Dealer_Division__c.object
<CustomObject>
    <description>list of active or inactive division, subdivision, zone, district and other territory related fields based on their business use for Sales, Service, Parts, etc.</description>
    <fields>
        <fullName>Dealer_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Subdivision</relationshipLabel>
        <relationshipName>Dealer_Divisions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name_TXT__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InternetCertified_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead Enrollment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name_TXT__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>isActive_FLG__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Dealer Subdivision</label>
    <nameField>
        <displayFormat>DD-{0}</displayFormat>
        <label>Dealer Division Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Divisions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Dealer_Participation__c.object
<CustomObject>
    <fields>
        <fullName>CRM_System__c</fullName>
        <label>CRM System</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Division__c</field>
                <operation>equals</operation>
                <valueField>CRM_System__c.Division_CD__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CRM_System__c</referenceTo>
        <relationshipLabel>Dealer Participations</relationshipLabel>
        <relationshipName>Dealer_Participations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DealerAccount_ID__c</fullName>
        <label>Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Participations</relationshipLabel>
        <relationshipName>Dealer_Participations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ISActive_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Dealer Participation</label>
    <nameField>
        <label>Dealer Participation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name_TXT__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name_TXT__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Lead Provider)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpportunityStatus_TXT__c</fullName>
        <label>Opportunity Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned/Routed to Dealer</fullName>
                </value>
                <value>
                    <fullName>Auto-response sent</fullName>
                </value>
                <value>
                    <fullName>Lead Opened</fullName>
                </value>
                <value>
                    <fullName>Lead Received</fullName>
                </value>
                <value>
                    <fullName>Customer phoned (Inbound phone)</fullName>
                </value>
                <value>
                    <fullName>Customer emailed (Inbound email)</fullName>
                </value>
                <value>
                    <fullName>Salesperson responded by Email</fullName>
                </value>
                <value>
                    <fullName>Salesperson responded by Phone</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson responded by email</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson responded by Phone</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson request another appointment by email</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson request another appointment by phone</fullName>
                </value>
                <value>
                    <fullName>Credit Application</fullName>
                </value>
                <value>
                    <fullName>Credit Application (3rd party)</fullName>
                </value>
                <value>
                    <fullName>Trade-In Appraisal</fullName>
                </value>
                <value>
                    <fullName>Broadcast Email</fullName>
                </value>
                <value>
                    <fullName>Made Appointment</fullName>
                </value>
                <value>
                    <fullName>Demoed/Test Drove</fullName>
                </value>
                <value>
                    <fullName>Boat/Outboard Sales Presentation</fullName>
                </value>
                <value>
                    <fullName>Appointment Didn’t Show</fullName>
                </value>
                <value>
                    <fullName>Appointment Showed</fullName>
                </value>
                <value>
                    <fullName>Offer to Purchase</fullName>
                </value>
                <value>
                    <fullName>Model in Stock</fullName>
                </value>
                <value>
                    <fullName>Model not in Stock</fullName>
                </value>
                <value>
                    <fullName>Model on back order</fullName>
                </value>
                <value>
                    <fullName>Credit Denied</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson marked sold</fullName>
                </value>
                <value>
                    <fullName>Salesperson marked vehicle sold</fullName>
                </value>
                <value>
                    <fullName>Lost Sales</fullName>
                </value>
                <value>
                    <fullName>Any additional vehicle sold info (delivered, punched, etc.)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PreferredDealerAccount_TXT__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Preferred Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Routable_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Routable?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Routing_Status_Message__c</fullName>
        <label>CRM Response Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Routing_Status__c</fullName>
        <label>Routing Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Sent to Dealer</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
                <value>
                    <fullName>Submitted for Re-Routing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Routing_Success_Date_Time__c</fullName>
        <label>Routing Success Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SendOnlyToUrbanScience__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SendOnlyToUrbanScience</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Urban_Science_Routing_Response_Message__c</fullName>
        <label>Urban Science Routing Response Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZipCode_TXT__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Honda</fullName>
        <active>true</active>
        <businessProcess>HELMS Sales Process</businessProcess>
        <description>Used by the Honda Team</description>
        <label>Honda Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/ManualRoutingTest.cls
@isTest
public class ManualRoutingTest {
   

   @isTest
    static void manualRoutingTestMethod1(){
        
         Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Account accTestRec = new Account(Name='Chapman Honda',RecordTypeId=dealerAccRecTypeId,DealerCode_CD__c='123456',Contact_Key__c='E150363308',
                                         HondaDigitalSolutions_FLG__c = true
                                        );
        insert accTestRec;
        Id providerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Provider').getRecordTypeId();
         Account accTestRec1 = new Account(Name='abcd', RecordTypeId=providerAccRecTypeId
                                        );
         insert accTestRec1;
        //Set<id> oppList= new Set<id>();
        //set<id> leadList=new set<id>();
 
        
         //Set<id> ddIds= new Set<id>();
       
        
        List<Opportunity> oppToUpdate = new List<Opportunity>();
        
     Opportunity o = new Opportunity();
        o.name='Test';
        o.First_Name_TXT__c='OppTest';
        o.Last_Name_TXT__c='OppKiran';
        o.Email__c='kiransiddipeta1199@gmail.com';
        o.StageName='Assigned to Dealer';
        o.OpportunityStatus_TXT__c='Assigned/Routed to Dealer';
        o.CloseDate= date.parse('10/10/2021');
        o.ZipCode_TXT__c='59505';
        o.PreferredDealerAccount_TXT__c=accTestRec.id;
         o.LeadProvider_ID__c=accTestRec.id;
        o.SendOnlyToUrbanScience__c = false;
          o.Routable_FLG__c = false; 
        o.Routing_Status__c = 'Success';
        o.Routing_Success_Date_Time__c = system.now(); 
        o.Urban_Science_Routing_Response_Message__c = 'abcd';
        o.Routing_Status_Message__c = 'abcd'; 
        
            
        
        insert o;
      
       oppToUpdate.add(o);  
        
          Test.startTest();
        List<String> ss=new List<String>();
        ss.add(oppToUpdate[0].Id);
        
        ManualRouting.FlowOutput flow=new ManualRouting.FlowOutput();
        flow.listOfOppIds= ss;
                
        ManualRouting.opportunityRoutingFlow(new List<ManualRouting.FlowOutput>{flow});
        
               Test.stopTest();
    }
    @isTest
    static void manualRoutingTestMethod2(){
        
        
         Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Account accTestRec = new Account(Name='Chapman Honda',RecordTypeId=dealerAccRecTypeId,DealerCode_CD__c='123456',Contact_Key__c='E150363308',
                                         HondaDigitalSolutions_FLG__c = false
                                        );
        insert accTestRec;
        
         Id providerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Provider').getRecordTypeId();
         Account accTestRec1 = new Account(Name='abcd',RecordTypeId=providerAccRecTypeId, Routable_FLG__c = false
                                        );
        
         insert accTestRec1;
        
            
        //Set<id> oppList= new Set<id>();
        //set<id> leadList=new set<id>();
        
         //Set<id> ddIds= new Set<id>();
       
        
        List<Opportunity> oppToUpdate = new List<Opportunity>();
        
     Opportunity o = new Opportunity();
        o.name='Test';
        o.First_Name_TXT__c='OppTest';
        o.Last_Name_TXT__c='OppKiran';
        o.Email__c='kiransiddipeta1199@gmail.com';
        o.StageName='Assigned to Dealer';
        o.OpportunityStatus_TXT__c='Assigned/Routed to Dealer';
        o.CloseDate= date.parse('10/10/2021');
        o.ZipCode_TXT__c='59505';
        o.PreferredDealerAccount_TXT__c=accTestRec.id;
        o.LeadProvider_ID__c=accTestRec.id;
        o.SendOnlyToUrbanScience__c = false;
          o.Routable_FLG__c = false; 
        o.Routing_Status__c = 'Success';
        o.Routing_Success_Date_Time__c = system.now(); 
        o.Urban_Science_Routing_Response_Message__c = 'abcd';
        o.Routing_Status_Message__c = 'abcd'; 
        
            
        
        insert o;
      
       oppToUpdate.add(o);  

          Test.startTest();
        List<String> ss=new List<String>();
        ss.add(oppToUpdate[0].Id);
        
        ManualRouting.FlowOutput flow=new ManualRouting.FlowOutput();
        flow.listOfOppIds= ss;
                
        ManualRouting.opportunityRoutingFlow(new List<ManualRouting.FlowOutput>{flow});
        
               Test.stopTest();
    } 
   @isTest
    static void manualRoutingTestMethod3(){
        
        
         Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Account accTestRec = new Account(Name='Chapman Honda',RecordTypeId=dealerAccRecTypeId,DealerCode_CD__c='123456',Contact_Key__c='E150363308'
                                        );
        insert accTestRec;
        
         Id providerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Provider').getRecordTypeId();
         Account accTestRec1 = new Account(Name='abcd',RecordTypeId=providerAccRecTypeId,Routable_FLG__c = false , Send_to_Urban_Science_Flag__c = true 
                                        );
        
         insert accTestRec1;
        
            
        //Set<id> oppList= new Set<id>();
        //set<id> leadList=new set<id>();
        
         //Set<id> ddIds= new Set<id>();
       
        
        List<Opportunity> oppToUpdate = new List<Opportunity>();
        
     Opportunity o = new Opportunity();
        o.name='Test';
        o.First_Name_TXT__c='OppTest';
        o.Last_Name_TXT__c='OppKiran';
        o.Email__c='kiransiddipeta1199@gmail.com';
        o.StageName='Assigned to Dealer';
        o.OpportunityStatus_TXT__c='Assigned/Routed to Dealer';
        o.CloseDate= date.parse('10/10/2021');
        o.ZipCode_TXT__c='59505';
        o.PreferredDealerAccount_TXT__c=accTestRec.id;
        o.LeadProvider_ID__c=accTestRec.id;
        o.SendOnlyToUrbanScience__c = true;
          o.Routable_FLG__c = false; 
        o.Routing_Status__c = 'Success';
        o.Routing_Success_Date_Time__c = system.now(); 
        o.Urban_Science_Routing_Response_Message__c = 'abcd';
        o.Routing_Status_Message__c = 'abcd'; 
        
            
        
        insert o;
      
       oppToUpdate.add(o);  
        

          Test.startTest();
        List<String> ss=new List<String>();
        ss.add(oppToUpdate[0].Id);
        
        ManualRouting.FlowOutput flow=new ManualRouting.FlowOutput();
        flow.listOfOppIds= ss;
                
        ManualRouting.opportunityRoutingFlow(new List<ManualRouting.FlowOutput>{flow});
        
               Test.stopTest();
    }
     @isTest
    static void manualRoutingTestMethod4(){
   
         Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Account accTestRec = new Account(Name='Chapman Honda',RecordTypeId=dealerAccRecTypeId,DealerCode_CD__c='123456',Contact_Key__c='E150363308', HondaDigitalSolutions_FLG__c = true
                                        );
        insert accTestRec;
        
         Id providerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Provider').getRecordTypeId();
         Account accTestRec1 = new Account(Name='abcd',RecordTypeId=providerAccRecTypeId,Routable_FLG__c = true , Send_to_Urban_Science_Flag__c = false 
                                        );
        
         insert accTestRec1;
       
         Id vendorAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Vendor').getRecordTypeId();
        
        Account accVendor = new Account(Name='Hello vendor',RecordTypeId=vendorAccRecTypeId,
                                  DealerCode_CD__c='1234Z',HondaDigitalSolutions_FLG__c=true,
                                 Routable_FLG__c=true);
        insert accvendor;
        Id oppHondaRecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Honda Opportunity').getRecordTypeId();
        
    
        List<Opportunity> oppToUpdate = new List<Opportunity>();
        
     Opportunity o = new Opportunity();
        o.name='Test';
        o.First_Name_TXT__c='OppTest';
        o.Last_Name_TXT__c='OppKiran';
        o.Email__c='kiransiddipeta1199@gmail.com';
        o.StageName='Assigned to Dealer';
        o.OpportunityStatus_TXT__c='Assigned/Routed to Dealer';
        o.CloseDate= date.parse('10/10/2021');
        o.ZipCode_TXT__c='59505';
        o.PreferredDealerAccount_TXT__c=accTestRec.id;
        o.LeadProvider_ID__c=accTestRec.id;
        o.SendOnlyToUrbanScience__c = true;
          o.Routable_FLG__c = true; 
        o.Routing_Status__c = 'Success';
        o.Routing_Success_Date_Time__c = system.now(); 
        o.Urban_Science_Routing_Response_Message__c = 'abcd';
        o.Routing_Status_Message__c = 'abcd'; 
        o.recordtypeID=oppHondaRecTypeId;
        o.Division_CD__c = 'A';
        o.SubDiv_TXT__c='Honda';

        insert o;
        
        //bj
        Opportunity o1 = new Opportunity();
        o1.name='Test';
        o1.First_Name_TXT__c='OppTest';
        o1.Last_Name_TXT__c='OppKiran';
        o1.Email__c='kiransiddipeta1199@gmail.com';
        o1.StageName='Assigned to Dealer';
        o1.OpportunityStatus_TXT__c='Assigned/Routed to Dealer';
        o1.CloseDate= date.parse('10/10/2021');
        o1.ZipCode_TXT__c='59505';
        o1.PreferredDealerAccount_TXT__c=accTestRec.id;
        o1.LeadProvider_ID__c=accTestRec.id;
        o1.SendOnlyToUrbanScience__c = true;
          o1.Routable_FLG__c = False; 
        o1.Routing_Status__c = 'Success';
        o1.Routing_Success_Date_Time__c = system.now(); 
        o1.Urban_Science_Routing_Response_Message__c = 'abcd';
        o1.Routing_Status_Message__c = 'abcd'; 
        o1.recordtypeID=oppHondaRecTypeId;
        o1.Division_CD__c = 'A';
        o1.SubDiv_TXT__c='Honda';

        insert o1;

     
      Dealer_Division__c dealerD = new Dealer_Division__c(First_Name_TXT__c='Test', 
                                                            InternetCertified_FLG__c=true, 
                                                            Dealer_ID__c=accTestRec.Id,
                                                            Division_CD__c = 'A' ,
                                                            SubDiv_TXT__c='Honda',
                                                           isActive_FLG__c=true);
      insert dealerD;
        

      
      CRM_System__c crmSystem = new CRM_System__c(Name='Test crm system',Vendor_ID__c=accVendor.Id,ISActive_FLG__c=true,Division_CD__c ='A');
      insert crmSystem;
      

        
      Dealer_Participation__c dealerParticipationList = new Dealer_Participation__c(DealerAccount_ID__c =accTestRec.Id,Division__c='A',
                                                               CRM_System__c = crmSystem.Id, LeadReceivingStartDate_DT__c=System.NOW()-12,Dealer_Subdivision__c =dealerD.id);
       
      insert dealerParticipationList;
        

      
      oppToUpdate.add(o);
 
        

       Test.startTest();
      
        List<String> ss=new List<String>();
        ss.add(oppToUpdate[0].Id);
        
        ManualRouting.FlowOutput flow=new ManualRouting.FlowOutput();
        flow.listOfOppIds= ss;
                
        ManualRouting.opportunityRoutingFlow(new List<ManualRouting.FlowOutput>{flow});
        
       Test.stopTest();
    }
    
    
    
 
}