objects/Account.object
<CustomObject>
    <fields>
        <fullName>DealerCode_CD__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>BodyStyle_TXT__c</fullName>
        <label>BodyStyle</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Color_TXT__c</fullName>
        <label>Color</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Condition_TXT__c</fullName>
        <label>Condition</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>excellent</fullName>
                </value>
                <value>
                    <fullName>good</fullName>
                </value>
                <value>
                    <fullName>fair</fullName>
                </value>
                <value>
                    <fullName>poor</fullName>
                </value>
                <value>
                    <fullName>unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContactKey_TXT__c</fullName>
        <label>Contact Key</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Ids_ID__c</fullName>
        <label>Dealer IDs</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Doors_TXT__c</fullName>
        <label>Doors</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Error_Details_Urban_Science__c</fullName>
        <label>Error Details Urban Science</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Lead_Reference_Number__c</fullName>
        <label>External Lead Reference Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Third_Party_Duplicate_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Third Party Duplicate Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LeadAdditionalInfos__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-1950 Story name.
Description: This is store the Offers XML Data.
Source System: Coming from Integration.
Integration: Yes.
Data Transformation: N/A.
Functional Definition: This will be Stored Offers Data.</description>
        <label>LeadAdditionalInfos</label>
        <length>118216</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Model_ID__c</fullName>
        <label>Model ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_TXT__c</fullName>
        <label>Model</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Number_NM__c</fullName>
        <label>Vin Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OdometerStatus_TXT__c</fullName>
        <label>Odometer Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>unknown</fullName>
                </value>
                <value>
                    <fullName>rolledover</fullName>
                </value>
                <value>
                    <fullName>replaced</fullName>
                </value>
                <value>
                    <fullName>original</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OdometerUnits_TXT__c</fullName>
        <label>Odometer Units</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>kilometer</fullName>
                </value>
                <value>
                    <fullName>miles</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Odometer_TXT__c</fullName>
        <label>Odometer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredDealerAccount_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProviderDetail_TXT__c</fullName>
        <inlineHelpText>Source Lead Provider Name</inlineHelpText>
        <label>Provider Detail</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>StatusReason_TXT__c</fullName>
        <defaultValue>(&quot;Pending&quot;)</defaultValue>
        <label>Status Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Inactivity</fullName>
                </value>
                <value>
                    <fullName>Duplicate Merged</fullName>
                </value>
                <value>
                    <fullName>Validation Email</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Lead Provider error</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Opt Out</fullName>
                </value>
                <value>
                    <fullName>Duplicate Similar</fullName>
                </value>
                <value>
                    <fullName>Matched Leads</fullName>
                </value>
                <value>
                    <fullName>Related Opportunity closed</fullName>
                </value>
                <value>
                    <fullName>Unable to assign Dealer</fullName>
                </value>
                <value>
                    <fullName>Name/Address/Email Error</fullName>
                </value>
                <value>
                    <fullName>Name/Address/Email Cache</fullName>
                </value>
                <value>
                    <fullName>Third Party Duplicate</fullName>
                </value>
                <value>
                    <fullName>Waiting for the routing window to start</fullName>
                </value>
                <value>
                    <fullName>Routing Window Expired</fullName>
                </value>
                <value>
                    <fullName>Concierge</fullName>
                </value>
                <value>
                    <fullName>Lead Enrichment call error</fullName>
                </value>
                <value>
                    <fullName>Dealer Assignment call failed</fullName>
                </value>
                <value>
                    <fullName>Journey Completed</fullName>
                </value>
                <value>
                    <fullName>New Opportunity Created</fullName>
                </value>
                <value>
                    <fullName>Journey incomplete, no response</fullName>
                </value>
                <value>
                    <fullName>Concierge Completed</fullName>
                </value>
                <value>
                    <fullName>Invalid email and phone</fullName>
                </value>
                <value>
                    <fullName>Customer is not Interested in the product</fullName>
                </value>
                <value>
                    <fullName>In nurturing journey</fullName>
                </value>
                <value>
                    <fullName>Waiting for Deal Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>Subdivision</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division_CD__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trim_TXT__c</fullName>
        <label>Model Trim</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>VehicleInterest_TXT__c</fullName>
        <label>Vehicle Interest</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>buy</fullName>
                </value>
                <value>
                    <fullName>lease</fullName>
                </value>
                <value>
                    <fullName>sell</fullName>
                </value>
                <value>
                    <fullName>trade-in</fullName>
                </value>
                <value>
                    <fullName>test-drive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VehicleStatus_TXT__c</fullName>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Used</fullName>
                </value>
                <value>
                    <fullName>Cpo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year_YR__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/HELMSLeadStatusToUrbanScienceTest.cls
@isTest
public class HELMSLeadStatusToUrbanScienceTest {
    public static testMethod void handleOffersInsertTest(){
        Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Id conRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Account accTestRec = new Account(Name='Test Account123another',DealerCode_CD__c = '123',RecordTypeId=dealerAccRecTypeId
                                         );
        insert accTestRec;
        contact con = new Contact(FirstName='John',LastName='Doe',Email='yash1234@testing.com',Title='Mr',
                                        AccountId=accTestRec.Id, RecordTypeId=conRecTypeId );
        insert con; 
        
        String strLeadInfo = '<LeadAdditionalInfos><LeadAdditionalInfo key="Offer Id">HP-18D</LeadAdditionalInfo><LeadAdditionalInfo key="Offer Name">2021 Pilot Special APR</LeadAdditionalInfo><LeadAdditionalInfo key="Offer Type">Finance</LeadAdditionalInfo><LeadAdditionalInfo key="end_date">Expires 09/07/21</LeadAdditionalInfo><LeadAdditionalInfo key="special_short_description">1.9% APR for 24-60 months or 2.9% for 61-72 months</LeadAdditionalInfo><LeadAdditionalInfo key="special_description">For well-qualified buyers. Example: 10% down payment. 60 months financing at $17.48/month per $1,000 financed.</LeadAdditionalInfo></LeadAdditionalInfos>';
        
        Lead lead = new Lead(LastName='Doe',Email='yash1234@testing.com',PreferredDealerAccount_ID__c =accTestRec.id, FirstName='John',Company='Test',Status='Ready_to_Convert',
                             Dealer_Ids_ID__c='testing',Year_YR__c='test',Model_TXT__c='demoooo',ProviderDetail_TXT__c='test11:test21',
                             Model_ID__c='demo',Trim_TXT__c='trimmer',SubDiv_TXT__c='Honda',
                             PreferredDealerNumber_NUM__c='123',Division_CD__c='A',VehicleInterest_TXT__c='buy',StatusReason_TXT__c = 'Third Party Duplicate',  External_Lead_Reference_Number__c = '123',
                            ContactKey_TXT__c ='test',VehicleStatus_TXT__c='New',Condition_TXT__c='excellent',LeadAdditionalInfos__c = strLeadInfo,
                             Number_NM__c='number',Doors_TXT__c='doortxt',BodyStyle_TXT__c='bodyStyle',Odometer_TXT__c='odmeter',
                             OdometerStatus_TXT__c='unknown',OdometerUnits_TXT__c='kilometer',Is_Third_Party_Duplicate_Lead__c=true,  Color_TXT__c='<colorcombination><interiorcolor/><exteriorcolor>Deep Pearl Gray</exteriorcolor><preference>1</preference></colorcombination>');
        insert lead;
        
        lead.Error_Details_Urban_Science__c = 'Test Duplicate';
        Test.startTest();
        update lead;
        Test.stopTest();
        System.assertEquals( 1, HELMSLeadStatusToUrbanScience.listUrbanEvents.size());
    }  
}