objects/Account.object
<CustomObject>
    <fields>
        <fullName>FriCloseHour__c</fullName>
        <label>Fri Close Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FriOpenHour__c</fullName>
        <label>Fri Open Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MonCloseHour__c</fullName>
        <label>Mon Close Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MonOpenHour__c</fullName>
        <label>Mon Open Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SatCloseHour__c</fullName>
        <label>Sat Close Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SatOpenHour__c</fullName>
        <label>Sat Open Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SunCloseHour__c</fullName>
        <label>Sun Close Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SunOpenHour__c</fullName>
        <label>Sun Open Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ThuCloseHour__c</fullName>
        <label>Thu Close Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ThuOpenHour__c</fullName>
        <label>Thu Open Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timezone__c</fullName>
        <label>Timezone Offset From GMT</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TueCloseHour__c</fullName>
        <label>Tue Close Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TueOpenHour__c</fullName>
        <label>Tue Open Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WedCloseHour__c</fullName>
        <label>Wed Close Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WedOpenHour__c</fullName>
        <label>Wed Open Hour</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Hours_Elasped__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Number of business hours elapsed since the opportunity has been created.</inlineHelpText>
        <label>Business Hours Elapsed</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name_TXT__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name_TXT__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Lead Provider)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreferredDealerAccount_TXT__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Preferred Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Level_Agreement_TXT__c</fullName>
        <defaultValue>&quot;No Escalation&quot;</defaultValue>
        <inlineHelpText>This shows how high of an escalation was done for this opportunity. The highest level is Level 3 and that escalation goes to upper management.</inlineHelpText>
        <label>Service Level Agreement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Escalation</fullName>
                </value>
                <value>
                    <fullName>Level 1</fullName>
                </value>
                <value>
                    <fullName>Level 2</fullName>
                </value>
                <value>
                    <fullName>Level 3</fullName>
                </value>
                <value>
                    <fullName>Level 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ZipCode_TXT__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/HELMSBUSINESSHOURSCALCULATIONTEST.cls
@isTest
private class HELMSBUSINESSHOURSCALCULATIONTEST {
    @isTest static void monday(){
        account acc=new account(Timezone__c='-7',MonOpenHour__c='0000',MonCloseHour__c='2400',TueOpenHour__c='0000',
        TueCloseHour__c='2400',WedOpenHour__c='0000',WedCloseHour__c='2400',ThuOpenHour__c='0000',ThuCloseHour__c='2400',
        FriOpenHour__c='0000',FriCloseHour__c='2400',SatOpenHour__c='0000',SatCloseHour__c='2400',SunOpenHour__c='0000',
        SunCloseHour__c='2400');
        acc.Name = 'Test Account';
        insert acc;
        opportunity opp= new opportunity(Stagename='Assigned to Dealer',PreferredDealerAccount_TXT__c=acc.id,Name='SLA test class', 
         LeadProvider_ID__c=acc.id, Email__c='call.bijay1@gmail.com', ZipCode_TXT__c='12345', 
        First_Name_TXT__c='SLA test', Last_Name_TXT__c='class');
        opp.CloseDate= system.Today();
        opp.createddate=system.now()-20;
        insert opp;
        Test.startTest();
        HELMSBUSINESSHOURSCALCULATION ba= new HELMSBUSINESSHOURSCALCULATION();
        Id jobid= Database.executeBatch(ba,1);
        Test.stopTest();
        string level= [select id,Service_Level_Agreement_TXT__c from opportunity where id=:opp.id].Service_Level_Agreement_TXT__c;
        //system.assertEquals('Level 3', level);
    }
    @isTest static void level1(){
        account acc=new account(Timezone__c='-7',MonOpenHour__c='0000',MonCloseHour__c='2400',TueOpenHour__c='0000',
        TueCloseHour__c='2400',WedOpenHour__c='0000',WedCloseHour__c='2400',ThuOpenHour__c='0000',ThuCloseHour__c='2400',
        FriOpenHour__c='0000',FriCloseHour__c='2400',SatOpenHour__c='0000',SatCloseHour__c='2400',SunOpenHour__c='0000',
        SunCloseHour__c='2400');
        acc.Name = 'Test Account';
        insert acc;
        opportunity opp= new opportunity(Stagename='Assigned to Dealer',PreferredDealerAccount_TXT__c=acc.id,Name='SLA test class', 
         LeadProvider_ID__c=acc.id, Email__c='call.bijay1@gmail.com', ZipCode_TXT__c='12345', 
        First_Name_TXT__c='SLA test', Last_Name_TXT__c='class',Business_Hours_Elasped__c=49);
        opp.CloseDate= system.Today();
        opp.createddate=system.now()-2.5;
        insert opp;
        Test.startTest();
        HELMSBUSINESSHOURSCALCULATION ba= new HELMSBUSINESSHOURSCALCULATION();
        Id jobid= Database.executeBatch(ba,1);
        Test.stopTest();
        string level= [select id,Service_Level_Agreement_TXT__c from opportunity where id=:opp.id].Service_Level_Agreement_TXT__c;
        //system.assertEquals('Level 1', level);
        
    }
    @isTest static void level2(){
        account acc=new account(Timezone__c='-7',MonOpenHour__c='0000',MonCloseHour__c='2400',TueOpenHour__c='0000',
        TueCloseHour__c='2400',WedOpenHour__c='0000',WedCloseHour__c='2400',ThuOpenHour__c='0000',ThuCloseHour__c='2400',
        FriOpenHour__c='0000',FriCloseHour__c='2400',SatOpenHour__c='0000',SatCloseHour__c='2400',SunOpenHour__c='0000',
        SunCloseHour__c='2400');
        acc.Name = 'Test Account';
        insert acc;
        opportunity opp= new opportunity(Stagename='Assigned to Dealer',PreferredDealerAccount_TXT__c=acc.id,Name='SLA test class', 
         LeadProvider_ID__c=acc.id, Email__c='call.bijay1@gmail.com', ZipCode_TXT__c='12345', 
        First_Name_TXT__c='SLA test', Last_Name_TXT__c='class',Business_Hours_Elasped__c=73);
        opp.CloseDate= system.Today();
        opp.createddate=system.now()-3.5;
        insert opp;
        Test.startTest();
        HELMSBUSINESSHOURSCALCULATION ba= new HELMSBUSINESSHOURSCALCULATION();
        Id jobid= Database.executeBatch(ba,1);
        Test.stopTest();
        string level= [select id,Service_Level_Agreement_TXT__c from opportunity where id=:opp.id].Service_Level_Agreement_TXT__c;
        //system.assertEquals('Level 2', level);
        
    }
    @isTest static void level3(){
        account acc=new account(Timezone__c='-7',MonOpenHour__c='0000',MonCloseHour__c='2400',TueOpenHour__c='0000',
        TueCloseHour__c='2400',WedOpenHour__c='0000',WedCloseHour__c='2400',ThuOpenHour__c='0000',ThuCloseHour__c='2400',
        FriOpenHour__c='0000',FriCloseHour__c='2400',SatOpenHour__c='0000',SatCloseHour__c='2400',SunOpenHour__c='0000',
        SunCloseHour__c='2400');
        acc.Name = 'Test Account';
        insert acc;
        opportunity opp= new opportunity(Stagename='Assigned to Dealer',PreferredDealerAccount_TXT__c=acc.id,Name='SLA test class', 
         LeadProvider_ID__c=acc.id, Email__c='call.bijay1@gmail.com', ZipCode_TXT__c='12345', 
        First_Name_TXT__c='SLA test', Last_Name_TXT__c='class',Business_Hours_Elasped__c=98);
        opp.CloseDate= system.Today();
        opp.createddate=system.now()-20;
        insert opp;
        Test.startTest();
        HELMSBUSINESSHOURSCALCULATION ba= new HELMSBUSINESSHOURSCALCULATION();
        Id jobid= Database.executeBatch(ba,1);
        Test.stopTest();
        string level= [select id,Service_Level_Agreement_TXT__c from opportunity where id=:opp.id].Service_Level_Agreement_TXT__c;
        //system.assertEquals('Level 3', level);
        
    }
    @isTest static void exc(){
        account acc=new account(Timezone__c='-7',MonOpenHour__c=null,MonCloseHour__c='2400',TueOpenHour__c='0000',
        TueCloseHour__c='2400',WedOpenHour__c='0000',WedCloseHour__c='2400',ThuOpenHour__c='0000',ThuCloseHour__c='2400',
        FriOpenHour__c='0000',FriCloseHour__c='2400',SatOpenHour__c='0000',SatCloseHour__c='2400',SunOpenHour__c='0000',
        SunCloseHour__c='2400');
        acc.Name = 'Test Account';
        insert acc;
        opportunity opp= new opportunity(Stagename='Assigned to Dealer',PreferredDealerAccount_TXT__c=acc.id,Name='SLA test class', 
         LeadProvider_ID__c=acc.id, Email__c='call.bijay1@gmail.com', ZipCode_TXT__c='12345', 
        First_Name_TXT__c='SLA test', Last_Name_TXT__c='class',Business_Hours_Elasped__c=98);
        opp.CloseDate= system.Today();
        opp.createddate=system.now()-20;
        insert opp;
        Test.startTest();
        
        HELMSBUSINESSHOURSCALCULATION ba= new HELMSBUSINESSHOURSCALCULATION();
        Id jobid= Database.executeBatch(ba,1);
		String sch = '0 0 23 * * ?';
		system.schedule('Testing', sch, ba );
        Test.stopTest();
    }
   

}