objects/Account.object
<CustomObject>
    <fields>
        <fullName>DealerCode_CD__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <formula>CASE(SubDivision_TXT__c , &quot;Honda&quot; , &quot;A&quot;, &quot;Acura&quot;, &quot;B&quot;, &quot;NSX&quot;, &quot;B&quot;, &quot;Motorcycle&quot;, &quot;M&quot;, &quot;Marine&quot;, &quot;P&quot;, &quot;Engine&quot;, &quot;P&quot;, &quot;PowerEquipment&quot;, &quot;P&quot; , &quot;None&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <description>Used for Provider Records</description>
        <label>Provider</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ContactKey_TXT__c</fullName>
        <label>Contact Key</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Assignment_Type__c</fullName>
        <label>Dealer Assignment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Selected</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Proximity</fullName>
                </value>
                <value>
                    <fullName>LDRA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_ECRM_Update_Done__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is ECRM Update Done</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Location_Enrichment_Done__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Location Enrichment Done</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Provider</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Lead Provider)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreferredDealerAccount_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesRelatedDealerNumber__c</fullName>
        <description>SalesRelatedDealerNumber</description>
        <label>SalesRelatedDealerNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceRelatedDealerNumber__c</fullName>
        <description>ServiceRelatedDealerNumber</description>
        <label>Service Related Dealer Number</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>Subdivision</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division_CD__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead_Enrichment_Callout__mdt.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                    <default>true</default>
                    <label>A</label>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>poi_radius__c</fullName>
        <label>poi radius</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lead Enrichment Callout</label>
    <pluralLabel>Lead Enrichment Callout</pluralLabel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/HelmsDealerLocatorTest.cls
@IsTest
public class HelmsDealerLocatorTest {
    
    public static testMethod void testPostCallout() {
        Set<Id> setId = new Set<ID>();
        
        /*Lead_Enrichment_Callout__mdt enrichnment = new Lead_Enrichment_Callout__mdt();
        enrichnment.poi_radius__c = 50;
        enrichnment.Division__c = 'A';
        insert enrichnment;*/
        
        //List<Lead> Leadlst= new List<Lead>();
        Account ac1 = new Account(name ='abc' , recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
          Account ac2 = new Account(name ='abc' ,DealerCode_CD__c= '10509', ShippingLatitude=39.850583,ShippingLongitude=-74.90814, recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()) ;
        insert ac1;
        insert ac2;
        //Lead lead1 = new Lead(LastName='Mohann',FirstName='Johnn',Is_Location_Enrichment_Done__c=false,SalesRelatedDealerNumber__c = '',ServiceRelatedDealerNumber__c = '',Email='MohanJohnn@gmail.com',PostalCode='90503',Division_CD__c='A',SubDiv_TXT__c='Honda',LeadProvider_ID__c = ac1.id);
        Lead lead1 = new Lead(LastName='Mohan',FirstName='John',Latitude=39.850583,Longitude=-74.90814,Email='MohanJohn@gmail.com',PostalCode='90503',Division_CD__c='A',SubDiv_TXT__c='Honda',LeadProvider_ID__c = ac1.id, State = 'NY', PreferredDealerAccount_ID__c = ac2.id, SalesRelatedDealerNumber__c = '10509', ServiceRelatedDealerNumber__c = '10509');
        insert lead1;
         Lead lead2 = new Lead(LastName='Mohan',FirstName='John',Latitude=39.850583,Longitude=-74.90814,Email='MohanJohn@gmail.com',PostalCode='90503',Division_CD__c='A',SubDiv_TXT__c='Honda',LeadProvider_ID__c = ac1.id, State = 'NY', PreferredDealerAccount_ID__c = ac2.id, SalesRelatedDealerNumber__c = '10509', ServiceRelatedDealerNumber__c = '10509');
        insert lead2;
        lead1.ContactKey_TXT__c = 'H12345678';
        lead1.Is_ECRM_Update_Done__c = true;
        lead1.Dealer_Assignment_Type__c = 'Proximity';
         lead1.Dealer_Assignment_Type__c = 'Sales';
          lead2.ContactKey_TXT__c = 'H123456780';
        lead2.Is_ECRM_Update_Done__c = true;
         lead2.Dealer_Assignment_Type__c = 'Service';
        update lead1;
        update lead2;
        //Leadlst.add(lead1);
        setId.add(lead1.id);
          setId.add(lead2.id);
        Test.setMock(HttpCalloutMock.class, new HelmsDealerLocatorMockTest());  
		Test.startTest();
       // HelmsDealerLocatorService.dealerLocatorService(setId);
         HelmsDealerLocatorService.updateSalesOnly(setId);
       // HelmsDealerLocatorService.updateSalesToService(setId);
        HelmsDealerLocatorService.checkDistance(setId);
        boolean abc = HelmsDealerLocatorService.checkServiceDistance(5,39.850583, -74.90814, '10509');
        
         
        
        Test.stopTest();
    }
     public static testMethod void testPostCallout2() {
        Set<Id> setId = new Set<ID>();
        
        /*Lead_Enrichment_Callout__mdt enrichnment = new Lead_Enrichment_Callout__mdt();
        enrichnment.poi_radius__c = 50;
        enrichnment.Division__c = 'A';
        insert enrichnment;*/
        
        //List<Lead> Leadlst= new List<Lead>();
        Account ac1 = new Account(name ='abc' , recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
          Account ac2 = new Account(name ='abc' ,DealerCode_CD__c= '10509', ShippingLatitude=39.850583,ShippingLongitude=-74.90814, recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()) ;
        insert ac1;
        insert ac2;
        //Lead lead1 = new Lead(LastName='Mohann',FirstName='Johnn',Is_Location_Enrichment_Done__c=false,SalesRelatedDealerNumber__c = '',ServiceRelatedDealerNumber__c = '',Email='MohanJohnn@gmail.com',PostalCode='90503',Division_CD__c='A',SubDiv_TXT__c='Honda',LeadProvider_ID__c = ac1.id);
        Lead lead1 = new Lead(LastName='Mohan',FirstName='John',Latitude=39.850583,Longitude=-74.90814,Email='MohanJohn@gmail.com',PostalCode='90503',Division_CD__c='A',SubDiv_TXT__c='Honda',LeadProvider_ID__c = ac1.id, State = 'NY', PreferredDealerAccount_ID__c = ac2.id, SalesRelatedDealerNumber__c = '10509', ServiceRelatedDealerNumber__c = '10509');
        insert lead1;
         Lead lead2 = new Lead(LastName='Mohan',FirstName='John',Latitude=39.850583,Longitude=-74.90814,Email='MohanJohn@gmail.com',PostalCode='90503',Division_CD__c='A',SubDiv_TXT__c='Honda',LeadProvider_ID__c = ac1.id, State = 'NY',PreferredDealerNumber_NUM__c = '10509', PreferredDealerAccount_ID__c = ac2.id, SalesRelatedDealerNumber__c = '10509', ServiceRelatedDealerNumber__c = '10509');
        insert lead2;
        lead1.ContactKey_TXT__c = 'H12345678';
        lead1.Is_ECRM_Update_Done__c = true;
        lead1.Dealer_Assignment_Type__c = 'Proximity';
         lead1.Dealer_Assignment_Type__c = 'Sales';
          lead2.ContactKey_TXT__c = 'H123456780';
        lead2.Is_ECRM_Update_Done__c = true;
         lead2.Dealer_Assignment_Type__c = 'Service';
        update lead1;
        update lead2;
        //Leadlst.add(lead1);
        setId.add(lead1.id);
         setId.add(lead2.id);
        Test.setMock(HttpCalloutMock.class, new HelmsDealerLocatorMockTest());  
		Test.startTest();
       // HelmsDealerLocatorService.dealerLocatorService(setId);
        // HelmsDealerLocatorService.updateSalesOnly(setId);
        HelmsDealerLocatorService.updateSalesToService(setId);
        HelmsDealerLocatorService.checkDistance(setId);
        //boolean abc = HelmsDealerLocatorService.checkServiceDistance(5,39.850583, -74.90814, '10509');
        
         
        
        Test.stopTest();
    }
    
     public static testMethod void testPostCallout1() {
        Set<Id> setId = new Set<ID>();
        
        /*Lead_Enrichment_Callout__mdt enrichnment = new Lead_Enrichment_Callout__mdt();
        enrichnment.poi_radius__c = 50;
        enrichnment.Division__c = 'A';
        insert enrichnment;*/
        
        //List<Lead> Leadlst= new List<Lead>();
        Account ac1 = new Account(name ='abc' , recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert ac1;
         Account ac2 = new Account(name ='abc' ,DealerCode_CD__c= '10509', ShippingLatitude=39.850583,ShippingLongitude=-74.90814, recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()) ;
        insert ac2;
        //Lead lead1 = new Lead(LastName='Mohann',FirstName='Johnn',Is_Location_Enrichment_Done__c=false,SalesRelatedDealerNumber__c = '',ServiceRelatedDealerNumber__c = '',Email='MohanJohnn@gmail.com',PostalCode='90503',Division_CD__c='A',SubDiv_TXT__c='Honda',LeadProvider_ID__c = ac1.id);
        Lead lead1 = new Lead(LastName='Mohan',FirstName='John',Latitude=39.850583,Longitude=-74.90814,Email='MohanJohn@gmail.com',PostalCode='90503',Division_CD__c='A',SubDiv_TXT__c='Honda',LeadProvider_ID__c = ac1.id, State = 'NY', SalesRelatedDealerNumber__c = '10509', ServiceRelatedDealerNumber__c = '10509', PreferredDealerAccount_ID__c = ac2.id);
        insert lead1;
        lead1.ContactKey_TXT__c = 'H12345678';
        lead1.Is_ECRM_Update_Done__c = true;
        update lead1;
        //Leadlst.add(lead1);
        setId.add(lead1.id);
        Test.setMock(HttpCalloutMock.class, new HelmsDealerLocatorMockTest());  
		Test.startTest();
        HelmsDealerLocatorService.dealerLocatorService(setId);
        
        Test.stopTest();
    }
    
	public static testMethod void insertLeadForDealerLocator(){
        List<Account> alist = new List<Account>();
        Account ac1 = new Account(name ='abc' ,  recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()) ;
        insert ac1;
        Account ac2 = new Account(name ='Graz33itti' ,ShippingLatitude = 39.07805, ShippingLongitude=-76.94588,DealerCode_CD__c='206772',recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()) ;
        insert ac2;
        Account ac3 = new Account(name ='Graz33it' ,ShippingLatitude = 39.89801, ShippingLongitude=-74.93263,DealerCode_CD__c='206765',recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()) ;
        insert ac3;
        List<Lead> newvalues = new List<Lead>();    
        //Lead lead = new Lead(LastName='Mohan',FirstName='John',Latitude=33.840222,Longitude=-118.353171,SalesRelatedDealerNumber__c = '206772',ServiceRelatedDealerNumber__c = '206765',PreferredDealerAccount_ID__c=ac2.id,Email='MohanJohn@gmail.com',PostalCode='90503',Division_CD__c='A',SubDiv_TXT__c='Honda',LeadProvider_ID__c = ac1.id);
        Lead lead1 = new Lead(LastName='Mohan',FirstName='John',Latitude=39.850583,Longitude=-74.90814,SalesRelatedDealerNumber__c = '206772',ServiceRelatedDealerNumber__c = '206765',PreferredDealerAccount_ID__c=ac2.id,Email='MohanJohn@gmail.com',PostalCode='08053',Division_CD__c='A',SubDiv_TXT__c='Honda',LeadProvider_ID__c = ac1.id, State = 'NY');
        Lead lead2 = new Lead(LastName='Mohann',FirstName='Johnn',Latitude=39.850583,Longitude=-74.90814,SalesRelatedDealerNumber__c = '206765',ServiceRelatedDealerNumber__c = '206772',PreferredDealerAccount_ID__c=ac3.id,Email='MohanJohnn@gmail.com',PostalCode='08053',Division_CD__c='A',SubDiv_TXT__c='Honda',LeadProvider_ID__c = ac1.id, State = 'NY');
        Lead lead3 = new Lead(LastName='Mohann',FirstName='Johnn',Latitude=39.850583,Longitude=-74.90814,SalesRelatedDealerNumber__c = '',ServiceRelatedDealerNumber__c = '',Email='MohanJohnn@gmail.com',PostalCode='08053',Division_CD__c='A',SubDiv_TXT__c='Honda',LeadProvider_ID__c = ac1.id, State = 'NY');
        newvalues.add(lead1);
        newvalues.add(lead2);
        newvalues.add(lead3);
        insert newvalues;
        //lead.ContactKey_TXT__c = 'H123456';
        lead1.ContactKey_TXT__c = 'E014607139';
        lead2.ContactKey_TXT__c = 'E014607138';
        lead3.ContactKey_TXT__c = 'H014607138';
        //lead.PreferredDealerNumber_NUM__c = '206772';
        //lead.SalesRelatedDealerNumber__c = '206772';
        //lead.ServiceRelatedDealerNumber__c = '206765';
        lead1.Is_ECRM_Update_Done__c = true;
        lead2.Is_ECRM_Update_Done__c = true;
        lead3.Is_ECRM_Update_Done__c = true;
        lead1.Dealer_Assignment_Type__c = 'Proximity';
        lead2.Dealer_Assignment_Type__c = 'Proximity';
        lead3.Dealer_Assignment_Type__c = 'Proximity';
        lead1.Dealer_Assignment_Type__c = 'Sales';
        lead2.Dealer_Assignment_Type__c = 'Sales';
        lead3.Dealer_Assignment_Type__c = 'Sales';
        update lead1;
        update lead2;
        update lead3;
    }
}