objects/Account.object
<CustomObject>
    <fields>
        <fullName>Send_Customer_Acknowledgement_Email_Flag__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Send Customer Acknowledgement Email</description>
        <label>Send Customer Acknowledgement Email</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Address_Street__c</fullName>
        <label>Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BodyStyle_TXT__c</fullName>
        <label>BodyStyle</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BrandsiteShoppingTool_TXT__c</fullName>
        <label>Brandsite Shopping Tool</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactKey_TXT__c</fullName>
        <label>Contact Key</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exterior_Color__c</fullName>
        <label>Exterior Color</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Interior_Color__c</fullName>
        <label>Interior Color</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Provider</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Lead Provider)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MSRP_AMT__c</fullName>
        <label>MSRP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Make_TXT__c</fullName>
        <label>Make</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Marketing_Campaign_Name__c</fullName>
        <description>Marketing campaign that drove this lead.</description>
        <label>Marketing Campaign Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ModelDealerAccessoryPrice_AM__c</fullName>
        <label>Model Dealer Accessory Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ModelDestinationCharge_AM__c</fullName>
        <label>Model Destination Charge</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Model_ID__c</fullName>
        <label>Model ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_TXT__c</fullName>
        <label>Model</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Odometer_TXT__c</fullName>
        <label>Odometer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredDealerAccount_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreferredDealerContact_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Dealer Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_confirmation_Email__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Business Unit: HELMS.
Jira Story: LMS-5361 Story name.
Description: This is store the true or false form SFMC.
Source System: Coming from Integration.
Integration: No
Data Transformation: N/A.
Functional Definition: If the  flag is true Lead  Data sent to SFMC.</description>
        <label>Send confirmation Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_Name__c</fullName>
        <label>Source Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FB</fullName>
                    <label>Facebook</label>
                </value>
                <value>
                    <fullName>GY</fullName>
                    <label>Gigya</label>
                </value>
                <value>
                    <fullName>TD</fullName>
                    <label>Dealer Associate</label>
                </value>
                <value>
                    <fullName>TH</fullName>
                    <label>Company Associate</label>
                </value>
                <value>
                    <fullName>HH</fullName>
                    <label>HondaHelper</label>
                </value>
                <value>
                    <fullName>CM</fullName>
                    <label>CampaignName</label>
                </value>
                <value>
                    <fullName>TB</fullName>
                    <label>Business Partner Associate</label>
                </value>
                <value>
                    <fullName>TW</fullName>
                    <label>Twitter</label>
                </value>
                <value>
                    <fullName>IG</fullName>
                    <label>Ignition One</label>
                </value>
                <value>
                    <fullName>American Honda eShopping Service</fullName>
                </value>
                <value>
                    <fullName>sample2.eshopping.services.honda.com</fullName>
                </value>
                <value>
                    <fullName>powersports.honda.com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>Subdivision</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division_CD__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transmission_TXT__c</fullName>
        <label>Transmission</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Year_YR__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BodyStyle_TXT__c</fullName>
        <label>Body Style</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BrandsiteShoppingTool_TXT__c</fullName>
        <label>Brandsite Shopping Tool</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactKey_TXT__c</fullName>
        <label>Contact Key</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exterior_Color__c</fullName>
        <label>Exterior Color</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Interior_Color__c</fullName>
        <label>Interior Color</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Lead Provider)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MSRP_AMT__c</fullName>
        <label>MSRP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Make_TXT__c</fullName>
        <label>Make</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Campaign_Name__c</fullName>
        <description>Marketing campaign that drove this lead.</description>
        <label>Marketing Campaign Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ModelDealerAccessoryPrice_AM__c</fullName>
        <label>Model Dealer Accessory Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ModelDestinationCharge_AM__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Model Destination Charge</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Model_ID__c</fullName>
        <label>Model ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_TXT__c</fullName>
        <label>Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Odometer_TXT__c</fullName>
        <label>Odometer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredDealerContact_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Dealer Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_confirmation_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send confirmation Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_Name__c</fullName>
        <label>Source Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FB</fullName>
                    <label>Facebook</label>
                </value>
                <value>
                    <fullName>GY</fullName>
                    <label>Gigya</label>
                </value>
                <value>
                    <fullName>TD</fullName>
                    <label>Dealer Associate</label>
                </value>
                <value>
                    <fullName>TH</fullName>
                    <label>Company Associate</label>
                </value>
                <value>
                    <fullName>HH</fullName>
                    <label>HondaHelper</label>
                </value>
                <value>
                    <fullName>CM</fullName>
                    <label>CampaignName</label>
                </value>
                <value>
                    <fullName>TB</fullName>
                    <label>Business Partner Associate</label>
                </value>
                <value>
                    <fullName>TW</fullName>
                    <label>Twitter</label>
                </value>
                <value>
                    <fullName>IG</fullName>
                    <label>Ignition One</label>
                </value>
                <value>
                    <fullName>American Honda eShopping Service</fullName>
                </value>
                <value>
                    <fullName>sample2.eshopping.services.honda.com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transmission_TXT__c</fullName>
        <label>Transmission</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_YR__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Acura</fullName>
        <active>true</active>
        <businessProcess>HELMS Sales Process</businessProcess>
        <description>Used by the Honda Acura Team</description>
        <label>Acura Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Honda</fullName>
        <active>true</active>
        <businessProcess>HELMS Sales Process</businessProcess>
        <description>Used by the Honda Team</description>
        <label>Honda Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Marine</fullName>
        <active>true</active>
        <businessProcess>HELMS Standard Process</businessProcess>
        <description>Used by the Honda Marine Team</description>
        <label>Marine Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/HelmsSFMCQueueable.cls
/**** 
 * This class is used for the email notifications and sms notifications 
****/
public class HelmsSFMCQueueable implements Queueable ,Database.AllowsCallouts {
    private set<id> ledids;
    private set<id> oppids;
    Public List<Lead> pSPLead;
    Public List<Lead> acuraLead;
     Public List<Lead> pEMarineLead;
    Public List<Lead> hondaLead;
    public HelmsSFMCQueueable(set<id> ids,set<id> opids) {
      
      acuraLead=[SELECT Id,FirstName,Exterior_Color__c,Interior_Color__c,PreferredDealerContact_ID__r.email, ContactKey_TXT__c,
                            Email, Model_TXT__c, SubDiv_TXT__c,Division_CD__c,PreferredDealerAccount_ID__r.Phone,
                            PreferredDealerAccount_ID__r.name,PreferredDealerAccount_ID__r.ShippingStreet,
                            PreferredDealerAccount_ID__r.ShippingCity,PreferredDealerAccount_ID__r.ShippingState,
                            PreferredDealerAccount_ID__r.ShippingPostalCode,PreferredDealerAccount_ID__r.ShippingCountry,
                            BrandsiteShoppingTool_TXT__c,Send_confirmation_Email__c,Year_YR__c,PreferredDealerContact_ID__r.name  FROM Lead
                            where SubDiv_TXT__c='Acura'  AND BrandsiteShoppingTool_TXT__c =null  AND isConverted = true AND Send_confirmation_Email__c = true AND
                            LeadProvider_ID__r.Send_Customer_Acknowledgement_Email_Flag__c = true AND id IN: ids];
        
 	 pSPLead=[SELECT Id,Exterior_Color__c,Interior_Color__c,FirstName, ContactKey_TXT__c,
                            PreferredDealerContact_ID__r.email, Email, Model_TXT__c, SubDiv_TXT__c,Division_CD__c,
                            PreferredDealerAccount_ID__r.Phone,PreferredDealerAccount_ID__r.name,
                            PreferredDealerAccount_ID__r.ShippingStreet,PreferredDealerAccount_ID__r.ShippingCity,
                            PreferredDealerAccount_ID__r.ShippingState,PreferredDealerAccount_ID__r.ShippingPostalCode,
                            PreferredDealerAccount_ID__r.ShippingCountry,BrandsiteShoppingTool_TXT__c,
                            Send_confirmation_Email__c,Year_YR__c,PreferredDealerContact_ID__r.name  FROM Lead 
                            where SubDiv_TXT__c='Motorcycle'  AND BrandsiteShoppingTool_TXT__c =null AND isConverted = true AND Send_confirmation_Email__c = true AND
                            LeadProvider_ID__r.Send_Customer_Acknowledgement_Email_Flag__c = true AND id IN: ids];
        
      hondaLead = [Select Id, FirstName,Odometer_TXT__c, BodyStyle_TXT__c,  MSRP_AMT__c, ModelDestinationCharge_AM__c, 
                               ModelDealerAccessoryPrice_AM__c, Interior_Color__c, Exterior_Color__c, Transmission_TXT__c, Address_Street__c, Model_ID__c, 
                               State, Marketing_Campaign_Name__c, Make_TXT__c, Year_YR__c, ConvertedOpportunityId, LastName, Source_Name__c, Division_CD__c, 
                               Address, street,City, PostalCode, Email, PreferredDealerAccount_ID__c, PreferredDealerNumber_NUM__c, 
                               LeadProvider_ID__r.Send_Customer_Acknowledgement_Email_Flag__c From Lead where SubDiv_TXT__c='Honda' 
                               AND isConverted = true AND Send_confirmation_Email__c = true AND
                               LeadProvider_ID__r.Send_Customer_Acknowledgement_Email_Flag__c= true AND Id IN : ids];
        
      pEMarineLead =[SELECT Id, ContactKey_TXT__c, Email, Model_TXT__c, SubDiv_TXT__c,Division_CD__c,ConvertedOpportunityId,
                        PreferredDealerAccount_ID__r.Phone,PreferredDealerAccount_ID__r.name,
                        PreferredDealerAccount_ID__r.ShippingStreet,PreferredDealerAccount_ID__r.ShippingCity,
                        PreferredDealerAccount_ID__r.ShippingPostalCode,PreferredDealerAccount_ID__r.ShippingCountry,
                        BrandsiteShoppingTool_TXT__c,Send_confirmation_Email__c  FROM Lead 
                        where (SubDiv_TXT__c='Marine' OR SubDiv_TXT__c='PowerEquipment')   AND isConverted = true AND Send_confirmation_Email__c = true AND
                        LeadProvider_ID__r.Send_Customer_Acknowledgement_Email_Flag__c = true AND BrandsiteShoppingTool_TXT__c =null AND id IN: ids];
    
    
        this.ledids = ids;
        this.oppids = opids;
        
    }
    public void execute(System.QueueableContext qc) {
       
        if(oppids.size()>0){
             HelmsOpportunityNotificationSms.opportunityCreation(oppids);
        }
        if(acuraLead.size()>0){
             HelmsLeadCrationNotificationSFMCAcura.leadCreationSFMCAura(acuraLead); 
        }
        if(pSPLead.size()>0){
             HelmsLeadCrationNotificationSFMCPSP.leadCreationSFMCPSP(pSPLead);
        }
       if(pEMarineLead.size()>0){
             HelmsLeadCrationNotificationSFMC.leadCreationSFMC(pEMarineLead);
       }
       if(hondaLead.size()>0){
             //Sending Email once Lead from Honda is converted to Opportunity
             HELMSeShoppingSendNotification.eshoppingAPi(hondaLead);
       }
     }
}