objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Provider</fullName>
        <active>true</active>
        <description>Used for Provider Records</description>
        <label>Provider</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Provider</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Lead Provider)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MSRP_AMT__c</fullName>
        <label>MSRP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Model_TXT__c</fullName>
        <label>Model</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>Subdivision</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division_CD__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Logs__c.object
<CustomObject>
    <fields>
        <fullName>Error_Line_Number__c</fullName>
        <label>Error Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>130768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Trigger_or_Class_Name__c</fullName>
        <label>Trigger or Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Logs</label>
    <nameField>
        <label>Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Duplicate_Similar__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Duplicate Similar</description>
        <label>Duplicate Similar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name_TXT__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name_TXT__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Lead Provider)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MSRP_AMT__c</fullName>
        <label>MSRP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Model_TXT__c</fullName>
        <label>Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_For_Cloning__c</fullName>
        <label>Reason For Cloning</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dealer Buy-Sell</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_MSRP_AMT__c</fullName>
        <label>Total MSRP AMT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Quote_AMT__c</fullName>
        <label>Total Quote AMT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ZipCode_TXT__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Acura</fullName>
        <active>true</active>
        <businessProcess>HELMS Sales Process</businessProcess>
        <description>Used by the Honda Acura Team</description>
        <label>Acura Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Engine</fullName>
        <active>true</active>
        <businessProcess>HELMS Standard Process</businessProcess>
        <description>Used by the Honda Engine Team</description>
        <label>Engine Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Honda</fullName>
        <active>true</active>
        <businessProcess>HELMS Sales Process</businessProcess>
        <description>Used by the Honda Team</description>
        <label>Honda Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Marine</fullName>
        <active>true</active>
        <businessProcess>HELMS Standard Process</businessProcess>
        <description>Used by the Honda Marine Team</description>
        <label>Marine Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Relations__c.object
<CustomObject>
    <fields>
        <fullName>New_Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>New Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Relationships (Original Opportunity)</relationshipLabel>
        <relationshipName>Opportunity_Relations1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Relationships (New Opportunity)</relationshipLabel>
        <relationshipName>Opportunity_Relations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_For_Cloning__c</fullName>
        <description>Business Unit: HELMS
Jira Story: LMS-4878 &amp; LMS-5028
Description: It describes the type of relationship.
Source System: Manual and automated process depending on the type
Integration:NA
Data Transformation: NA</description>
        <label>Relationship Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dealer Buy-Sell</fullName>
                </value>
                <value>
                    <fullName>Duplicate-Similar</fullName>
                </value>
                <value>
                    <fullName>Customer Requested Dealer Reassignment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Relationship</label>
    <nameField>
        <displayFormat>0R-{0000}</displayFormat>
        <label>Opportunity Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/HELMSupdateOppHandler.cls
/*******************************************************************************************
* @Name         HELMSupdateOppHandler 
//

*******************************************************************************************/
public with sharing  class HELMSupdateOppHandler {    
    public void updateOppAmount(List<Opportunity> newOpp){
        for(Opportunity lg : newOpp){
            if(lg.Total_Quote_AMT__c != NULL){
                lg.Amount = lg.Total_Quote_AMT__c;
                
            }
            else{
                if(lg.Total_MSRP_AMT__c==null){
                    lg.Total_MSRP_AMT__c= lg.MSRP_AMT__c;
                    lg.Amount = lg.Total_MSRP_AMT__c;
                }else{
                    lg.Amount = lg.Total_MSRP_AMT__c;
                }
            }
        }        
    }
    //Assigning lead provider on lead record
    public Static void assignLeadProviders(List<Opportunity> newOpps){
        try{
            List<Opportunity> newOpps2 = new List<Opportunity>();
            for(Opportunity opp : newOpps){         
                if(opp.LeadProvider_ID__c == Null || opp.LeadProvider_ID__c == ''){
                    newOpps2.add(opp);
                }
            }
            String profileId = UserInfo.getProfileId();
            Profile communityProfile = [SELECT Id, Name FROM Profile WHERE Id =:profileId and profile.Name = 'HELMS Partner Community'];
            if(communityProfile != NULL && newOpps2.size()>0){
                List<Opportunity> updateOppLst = new List<Opportunity>();
                List<Account> accountsLst = [Select Id,Name FROM Account 
                                             WHERE Name IN ('Acura Dealer Created', 'Engine Dealer Created','Honda Dealer Created','Marine Dealer Created', 'PowerEquipment Dealer Created','Motorcycle Dealer Created')
                                             AND RecordTypeId=:Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider').getRecordTypeId()
                                            ];
                
                Map<String,ID> accountNameIDMap = new Map<String,ID>();
                for(Account acc : AccountsLst){
                    accountNameIDMap.put(acc.Name,acc.Id);     
                }
                system.debug(' test class accountNameIDMap-->'+accountNameIDMap);
                for(Opportunity opp : newOpps){
                    if(opp.LeadProvider_ID__c == Null || opp.LeadProvider_ID__c == ''){
                       // system.debug('test class opp.SubDiv_TXT__c--->'+opp.SubDiv_TXT__c);
                        
                            
                        if(opp.SubDiv_TXT__c == 'Acura'){
                            if(accountNameIDMap.containsKey('Acura Dealer Created')){
                                opp.LeadProvider_ID__c =  accountNameIDMap.get('Acura Dealer Created');
                            }                                        
                        }else if(opp.SubDiv_TXT__c == 'Engine'){
                            if(accountNameIDMap.containsKey('Engine Dealer Created')){
                                opp.LeadProvider_ID__c =  accountNameIDMap.get('Engine Dealer Created');
                            }
                        }else if(opp.SubDiv_TXT__c == 'Honda'){
                            if(accountNameIDMap.containsKey('Honda Dealer Created')){
                                opp.LeadProvider_ID__c =  accountNameIDMap.get('Honda Dealer Created');
                            }
                        }else if(opp.SubDiv_TXT__c == 'Motorcycle'){
                            if(accountNameIDMap.containsKey('Motorcycle Dealer Created')){
                                opp.LeadProvider_ID__c =  accountNameIDMap.get('Motorcycle Dealer Created');
                            }
                        }else if(opp.SubDiv_TXT__c == 'PowerEquipment'){
                            if(accountNameIDMap.containsKey('PowerEquipment Dealer Created')){
                                opp.LeadProvider_ID__c =  accountNameIDMap.get('PowerEquipment Dealer Created');
                            }
                        }else if(opp.SubDiv_TXT__c == 'Marine'){
                            
                            if(accountNameIDMap.containsKey('Marine Dealer Created')){
                                opp.LeadProvider_ID__c =  accountNameIDMap.get('Marine Dealer Created');
                            }
                        }
                        
                        // updateOppLst.add(opp);
                    }
                }
                /* if(!updateOppLst.isEmpty()){
update updateOppLst;
} */
            }
        }catch(Exception e){
            
        }     
    } 

 //LMS-4878 Duplicate Opportunity(based on Opportunity RelationShip Object )
    public void findDuplicateOpportunity(List<Opportunity> newOpps){
       
        try{
            set<string> emailset= new set<string>();
            set<string> dlrNoSet= new set<string>();
            set<string> zipSet= new set<string>();
            		//system.debug('newOpps:---->'+newOpps);
            
            for(Opportunity opp: newOpps){
                if(!string.isblank(opp.Email__c)){
                   emailset.add(opp.Email__c);
                }if(!string.isblank(opp.PreferredDealerNumber_NUM__c)){
                    dlrNoSet.add(opp.PreferredDealerNumber_NUM__c);  
                }if(!string.isblank(opp.ZipCode_TXT__c)){
                    zipSet.add(opp.ZipCode_TXT__c);}  
            }
         system.debug('***emailset'+emailset);
            list<Opportunity_Relations__c> opRelationList=new list<Opportunity_Relations__c>();
            List<Opportunity> newOpporunityList=new List<Opportunity>();
            list<Opportunity_Relations__c> reltList=new list<Opportunity_Relations__c>();
            Set<id> opprelid= new Set<id>();
            
            List<Opportunity> opporunityList= [select id,First_Name_TXT__c,Last_Name_TXT__c,Email__c,Phone__c,ZipCode_TXT__c,PreferredDealerNumber_NUM__c,                                              Duplicate_Similar__c,Model_TXT__c,Division_CD__c,SubDiv_TXT__c 
                                from Opportunity where Email__c in :emailset and ZipCode_TXT__c in :zipSet and PreferredDealerNumber_NUM__c in :dlrNoSet  ORDER BY CreatedDate ASC];
            system.debug('***before opporunityList'+opporunityList);
            map<id,opportunity> maporgvsdup= new map<id,opportunity>();
            map<id,opportunity> mapdupopp= new map<id,opportunity>();
            for(Opportunity opp: newOpps){
               
                    for(Opportunity obj: opporunityList){
                        if(opp.First_Name_TXT__c == obj.First_Name_TXT__c && opp.Last_Name_TXT__c == obj.Last_Name_TXT__c && opp.Email__c==obj.Email__c
                        && opp.Phone__c==obj.Phone__c && opp.ZipCode_TXT__c==obj.ZipCode_TXT__c && opp.PreferredDealerNumber_NUM__c==obj.PreferredDealerNumber_NUM__c
                        && opp.Model_TXT__c==obj.Model_TXT__c && opp.SubDiv_TXT__c==obj.SubDiv_TXT__c ){
                            if(obj.Duplicate_Similar__c==false){
                                maporgvsdup.put(obj.id,obj);
                            }else if(opp.Duplicate_Similar__c==false){
                                 maporgvsdup.put(opp.id,opp);
                            }
                            
                            if(obj.Duplicate_Similar__c==true){
                                mapdupopp.put(obj.id,obj);
                            }
                        }
                    }
               
            }
            system.debug('***before maporgvsdup'+maporgvsdup);
            map<id,set<id>> maporgvsRel= new map<id,set<id>>();
           		// system.debug('maporgvsdup:-------->'+maporgvsdup);
           		 reltList=[Select id,New_Opportunity__c,Previous_Opportunity__c from Opportunity_Relations__c where Previous_Opportunity__c in :maporgvsdup.keyset() Limit 40000];
         
            for(Opportunity_Relations__c rel: reltList){
                if(maporgvsRel!=null){
                    if(maporgvsRel.keyset().contains(rel.Previous_Opportunity__c)){
                            maporgvsRel.get(rel.Previous_Opportunity__c).add(rel.New_Opportunity__c);
                    }else{
                        maporgvsRel.put(rel.Previous_Opportunity__c ,new set<id>{});
                        maporgvsRel.get(rel.Previous_Opportunity__c).add(rel.New_Opportunity__c);
                    }
                }else{
                    maporgvsRel.put(rel.Previous_Opportunity__c ,new set<id>{});
                    maporgvsRel.get(rel.Previous_Opportunity__c).add(rel.New_Opportunity__c);
                }
            }
             system.debug('***before maporgvsRel'+maporgvsRel);
            for(Opportunity opp: newOpps){
                if(opp.Duplicate_Similar__c==true){
                    for(opportunity orgopp: maporgvsdup.values()){
                        if(opp.First_Name_TXT__c == orgopp.First_Name_TXT__c && opp.Last_Name_TXT__c == orgopp.Last_Name_TXT__c && opp.Email__c==orgopp.Email__c
                        && opp.Phone__c==orgopp.Phone__c && opp.ZipCode_TXT__c==orgopp.ZipCode_TXT__c && opp.PreferredDealerNumber_NUM__c==orgopp.PreferredDealerNumber_NUM__c
                        && opp.Model_TXT__c==orgopp.Model_TXT__c && opp.SubDiv_TXT__c==orgopp.SubDiv_TXT__c){
                            
                            if(maporgvsRel.get(orgopp.id)!=null){ 
                                if(!maporgvsRel.get(orgopp.id).contains(opp.Id)){
                                    Opportunity_Relations__c opr=new Opportunity_Relations__c();
                                    opr.Previous_Opportunity__c= orgopp.id; 
                                    opr.New_Opportunity__c= opp.Id;
                                    opr.Reason_For_Cloning__c='Duplicate-Similar';
                                    opRelationList.add(opr);
                                }
                            }else {
                                Opportunity_Relations__c opr=new Opportunity_Relations__c();
                                opr.Previous_Opportunity__c= orgopp.id; 
                                opr.New_Opportunity__c= opp.Id;
                                opr.Reason_For_Cloning__c='Duplicate-Similar';
                                opRelationList.add(opr);
                            }
                            
                        }
                    }
                }else if(opp.Duplicate_Similar__c==false){
                    system.debug('**mapdupopp::::::::'+mapdupopp.values());
                    system.debug('**opp::::::::'+opp);
                    for(opportunity dupopp: mapdupopp.values()){
                        if(opp.First_Name_TXT__c == dupopp.First_Name_TXT__c && opp.Last_Name_TXT__c == dupopp.Last_Name_TXT__c && opp.Email__c==dupopp.Email__c
                        && opp.Phone__c==dupopp.Phone__c && opp.ZipCode_TXT__c==dupopp.ZipCode_TXT__c && opp.PreferredDealerNumber_NUM__c==dupopp.PreferredDealerNumber_NUM__c
                        && opp.Model_TXT__c==dupopp.Model_TXT__c && opp.SubDiv_TXT__c==dupopp.SubDiv_TXT__c && dupopp.Duplicate_Similar__c==true){
                            
                            system.debug('**dupopp::::::::::'+dupopp);
                                Opportunity_Relations__c opr=new Opportunity_Relations__c();
                                opr.Previous_Opportunity__c= opp.Id; 
                                opr.New_Opportunity__c= dupopp.id;
                                opr.Reason_For_Cloning__c='Duplicate-Similar';
                                opRelationList.add(opr);
                                
                                if(maporgvsRel!=null){
                                    if(maporgvsRel.keyset().contains(opr.Previous_Opportunity__c)){
                                            maporgvsRel.get(opr.Previous_Opportunity__c).add(opr.New_Opportunity__c);
                                    }else{
                                        maporgvsRel.put(opr.Previous_Opportunity__c ,new set<id>{});
                                        maporgvsRel.get(opr.Previous_Opportunity__c).add(opr.New_Opportunity__c);
                                    }
                                }else{
                                    maporgvsRel.put(opr.Previous_Opportunity__c ,new set<id>{});
                                    maporgvsRel.get(opr.Previous_Opportunity__c).add(opr.New_Opportunity__c);
                                }
                        }
                    }
                }
            }   
              
            system.debug('***before insertion opRelationList'+opRelationList.size());
            system.debug('***before insertion opRelationList'+opRelationList);
            if(!opRelationList.isempty()){ 
                insert opRelationList;
            }            
            system.debug('**** after insertion opRelationList'+opRelationList);
         
        }
        catch(Exception ex){
           Logs__c l = new Logs__c(name = 'Opportunity_FindDuplicate', Trigger_or_Class_Name__c = 'HELMSupdateOppHandler', Error_Message__c = ex.getMessage(), Error_Line_Number__c = Integer.valueOf(string.valueof(ex.getLineNumber())));
           insert l;
       }
 }
            
            

}