objects/Account.object
<CustomObject>
    <fields>
        <fullName>DealerCode_CD__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>HelmsCRMEligible_FLAG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HELMS Access</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name_TXT__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name_TXT__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Lead Provider)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpportunityStatus_TXT__c</fullName>
        <label>Opportunity Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned/Routed to Dealer</fullName>
                </value>
                <value>
                    <fullName>Auto-response sent</fullName>
                </value>
                <value>
                    <fullName>Lead Opened</fullName>
                </value>
                <value>
                    <fullName>Lead Received</fullName>
                </value>
                <value>
                    <fullName>Customer phoned (Inbound phone)</fullName>
                </value>
                <value>
                    <fullName>Customer emailed (Inbound email)</fullName>
                </value>
                <value>
                    <fullName>Salesperson responded by Email</fullName>
                </value>
                <value>
                    <fullName>Salesperson responded by Phone</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson responded by email</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson responded by Phone</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson request another appointment by email</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson request another appointment by phone</fullName>
                </value>
                <value>
                    <fullName>Credit Application</fullName>
                </value>
                <value>
                    <fullName>Credit Application (3rd party)</fullName>
                </value>
                <value>
                    <fullName>Trade-In Appraisal</fullName>
                </value>
                <value>
                    <fullName>Broadcast Email</fullName>
                </value>
                <value>
                    <fullName>Made Appointment</fullName>
                </value>
                <value>
                    <fullName>Demoed/Test Drove</fullName>
                </value>
                <value>
                    <fullName>Boat/Outboard Sales Presentation</fullName>
                </value>
                <value>
                    <fullName>Appointment Didn’t Show</fullName>
                </value>
                <value>
                    <fullName>Appointment Showed</fullName>
                </value>
                <value>
                    <fullName>Offer to Purchase</fullName>
                </value>
                <value>
                    <fullName>Model in Stock</fullName>
                </value>
                <value>
                    <fullName>Model not in Stock</fullName>
                </value>
                <value>
                    <fullName>Model on back order</fullName>
                </value>
                <value>
                    <fullName>Credit Denied</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson marked sold</fullName>
                </value>
                <value>
                    <fullName>Salesperson marked vehicle sold</fullName>
                </value>
                <value>
                    <fullName>Lost Sales</fullName>
                </value>
                <value>
                    <fullName>Any additional vehicle sold info (delivered, punched, etc.)</fullName>
                </value>
                <value>
                    <fullName>Note</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ZipCode_TXT__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/HELMSOpptyStageStatusTestClass.cls
@isTest
public class HELMSOpptyStageStatusTestClass {
      @isTest static void method1(){
        List<Account> alist = new List<Account>();
            Account ac3 = new Account(name ='testgazi', DealerCode_CD__c='30Z214', recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()) ;
            
            insert ac3;
            ac3.name ='Grazittilav';
           
            alist.add(ac3); 
            update alist;
       
        Id conRecordTypeId = Schema.SObjectType.contact.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
            Contact conTestRec = new Contact(FirstName='YashLeadlav',LastName='Recordlav',Email='yashlav@testing.com',Title='Mr',
                                             AccountId=alist[0].Id,RecordTypeId=conRecordTypeId,HelmsCRMEligible_FLAG__c=false);
            insert conTestRec;
        
        Profile p = [Select Id From Profile Where Name = 'HELMS Partner Community'];
        User u = new User(firstname= 'Test',
                          lastname='User',
                          Alias='TUser',
                          email = 'test@test.com',
                          username= 'testWipro@test.com', 
                          profileId= p.id, 
                          emailencodingkey='UTF-8',
                          languagelocalekey='en_US',
                          localesidkey='en_US',
                          timezonesidkey='America/Los_Angeles',
                         ContactId = conTestRec.Id);
        insert u; 
        
        
        
        List<Opportunity> listOpp = new List<Opportunity>();
        
        Opportunity opp = new Opportunity( Name = 'Test Oppo', CloseDate = System.today()+10, 
                                          LeadProvider_ID__c = alist[0].Id, Email__c = 'test@test.com',ZipCode_TXT__c = '88763',
                                          First_Name_TXT__c = 'Test', Last_Name_TXT__c = 'Opp', StageName = 'Acknowledged',
                                          OpportunityStatus_TXT__c = 'Auto-response sent', CreatedDate = System.today());
        
           insert opp;
        listOpp.add(opp);
        List<Task> tsk = new List<Task>();
        Task task = new Task(WhatId = Opp.Id, Subject = 'inbound Call');
       		tsk.add(task);
        insert task;
        System.runAs(u) {
        System.assertEquals(UserInfo.getUserId(), u.Id, 'user has been inserted');
        
        }
        HELMSOpptystageandstatusonTaskandevent.updateopptyStageandStatusforTask(tsk);
        
    }
    @isTest static void method2(){
        List<Account> alist = new List<Account>();
            Account ac3 = new Account(name ='testgazi', DealerCode_CD__c='30Z214', recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()) ;
            
            insert ac3;
            ac3.name ='Grazittilav';
           
            alist.add(ac3); 
            update alist;
       
        Id conRecordTypeId = Schema.SObjectType.contact.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
            Contact conTestRec = new Contact(FirstName='YashLeadlav',LastName='Recordlav',Email='yashlav@testing.com',Title='Mr',
                                             AccountId=alist[0].Id,RecordTypeId=conRecordTypeId,HelmsCRMEligible_FLAG__c=false);
            insert conTestRec;
        
        Profile p = [Select Id From Profile Where Name = 'HELMS Partner Community'];
        User u = new User(firstname= 'Test',
                          lastname='User',
                          Alias='TUser',
                          email = 'test@test.com',
                          username= 'testWipro@test.com', 
                          profileId= p.id, 
                          emailencodingkey='UTF-8',
                          languagelocalekey='en_US',
                          localesidkey='en_US',
                          timezonesidkey='America/Los_Angeles',
                         ContactId = conTestRec.Id);
        insert u; 
        
        
        
        List<Opportunity> listOpp = new List<Opportunity>();
        
        Opportunity opp = new Opportunity( Name = 'Test Oppo', CloseDate = System.today()+10, 
                                          LeadProvider_ID__c = alist[0].Id, Email__c = 'test@test.com',ZipCode_TXT__c = '88763',
                                          First_Name_TXT__c = 'Test', Last_Name_TXT__c = 'Opp', StageName = 'Acknowledged',
                                          OpportunityStatus_TXT__c = 'Auto-response sent', CreatedDate = System.today());
        
           insert opp;
        listOpp.add(opp);
        List<Task> tsk = new List<Task>();
        Task task = new Task(WhatId = Opp.Id, Subject = 'outbound Call');
       		tsk.add(task);
        insert task;
        System.runAs(u) {
        System.assertEquals(UserInfo.getUserId(), u.Id, 'user has been inserted');
        
        }
        HELMSOpptystageandstatusonTaskandevent.updateopptyStageandStatusforTask(tsk);
        
    }
    @isTest static void method3(){
        List<Account> alist = new List<Account>();
            Account ac3 = new Account(name ='testgazi', DealerCode_CD__c='30Z214', recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()) ;
            
            insert ac3;
            ac3.name ='Grazittilav';
           
            alist.add(ac3); 
            update alist;
       
        Id conRecordTypeId = Schema.SObjectType.contact.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
            Contact conTestRec = new Contact(FirstName='YashLeadlav',LastName='Recordlav',Email='yashlav@testing.com',Title='Mr',
                                             AccountId=alist[0].Id,RecordTypeId=conRecordTypeId,HelmsCRMEligible_FLAG__c=false);
            insert conTestRec;
        
        Profile p = [Select Id From Profile Where Name = 'HELMS Partner Community'];
        User u = new User(firstname= 'Test',
                          lastname='User',
                          Alias='TUser',
                          email = 'test@test.com',
                          username= 'testWipro@test.com', 
                          profileId= p.id, 
                          emailencodingkey='UTF-8',
                          languagelocalekey='en_US',
                          localesidkey='en_US',
                          timezonesidkey='America/Los_Angeles',
                         ContactId = conTestRec.Id);
        insert u; 
        
        
        
        List<Opportunity> listOpp = new List<Opportunity>();
        
        Opportunity opp = new Opportunity( Name = 'Test Oppo', CloseDate = System.today()+10, 
                                          LeadProvider_ID__c = alist[0].Id, Email__c = 'test@test.com',ZipCode_TXT__c = '88763',
                                          First_Name_TXT__c = 'Test', Last_Name_TXT__c = 'Opp', StageName = 'Assigned to Dealer',
                                          OpportunityStatus_TXT__c = 'Auto-response sent', CreatedDate = System.today());
        
           insert opp;
        listOpp.add(opp);
        List<Task> tsk = new List<Task>();
        Task task = new Task(WhatId = Opp.Id, Subject = 'abc');
       		tsk.add(task);
        insert task;
        System.runAs(u) {
        System.assertEquals(UserInfo.getUserId(), u.Id, 'user has been inserted');
        
        }
        HELMSOpptystageandstatusonTaskandevent.updateopptyStageandStatusforTask(tsk);
        
    }
    @isTest static void method4(){
        List<Account> alist = new List<Account>();
            Account ac3 = new Account(name ='testgazi', DealerCode_CD__c='30Z214', recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()) ;
            
            insert ac3;
            ac3.name ='Grazittilav';
           
            alist.add(ac3); 
            update alist;
       
        Id conRecordTypeId = Schema.SObjectType.contact.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
            Contact conTestRec = new Contact(FirstName='YashLeadlav',LastName='Recordlav',Email='yashlav@testing.com',Title='Mr',
                                             AccountId=alist[0].Id,RecordTypeId=conRecordTypeId,HelmsCRMEligible_FLAG__c=false);
            insert conTestRec;
        
        Profile p = [Select Id From Profile Where Name = 'HELMS Partner Community'];
        User u = new User(firstname= 'Test',
                          lastname='User',
                          Alias='TUser',
                          email = 'test@test.com',
                          username= 'testWipro@test.com', 
                          profileId= p.id, 
                          emailencodingkey='UTF-8',
                          languagelocalekey='en_US',
                          localesidkey='en_US',
                          timezonesidkey='America/Los_Angeles',
                         ContactId = conTestRec.Id);
        insert u; 
        
        
        
        List<Opportunity> listOpp = new List<Opportunity>();
        
        Opportunity opp = new Opportunity( Name = 'Test Oppo', CloseDate = System.today()+10, 
                                          LeadProvider_ID__c = alist[0].Id, Email__c = 'test@test.com',ZipCode_TXT__c = '88763',
                                          First_Name_TXT__c = 'Test', Last_Name_TXT__c = 'Opp', StageName = 'In Conversation',
                                          OpportunityStatus_TXT__c = 'abc', CreatedDate = System.today());
        
           insert opp;
        listOpp.add(opp);
        List<Task> tsk = new List<Task>();
        Task task = new Task(WhatId = Opp.Id, Subject = 'abc');
       		tsk.add(task);
        insert task;
        System.runAs(u) {
        System.assertEquals(UserInfo.getUserId(), u.Id, 'user has been inserted');
        
        }
        HELMSOpptystageandstatusonTaskandevent.updateopptyStageandStatusforTask(tsk);
        
    }
	@isTest static void method5(){
        List<Account> alist = new List<Account>();
            Account ac3 = new Account(name ='testgazi', DealerCode_CD__c='30Z214', recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()) ;
            
            insert ac3;
            ac3.name ='Grazittilav';
           
            alist.add(ac3); 
            update alist;
       
        Id conRecordTypeId = Schema.SObjectType.contact.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
            Contact conTestRec = new Contact(FirstName='YashLeadlav',LastName='Recordlav',Email='yashlav@testing.com',Title='Mr',
                                             AccountId=alist[0].Id,RecordTypeId=conRecordTypeId,HelmsCRMEligible_FLAG__c=false);
            insert conTestRec;
        
        Profile p = [Select Id From Profile Where Name = 'HELMS Partner Community'];
        User u = new User(firstname= 'Test',
                          lastname='User',
                          Alias='TUser',
                          email = 'test@test.com',
                          username= 'testWipro@test.com', 
                          profileId= p.id, 
                          emailencodingkey='UTF-8',
                          languagelocalekey='en_US',
                          localesidkey='en_US',
                          timezonesidkey='America/Los_Angeles',
                         ContactId = conTestRec.Id);
        insert u; 
        
        
        
        List<Opportunity> listOpp = new List<Opportunity>();
        
        Opportunity opp = new Opportunity( Name = 'Test Oppo', CloseDate = System.today()+10, 
                                          LeadProvider_ID__c = alist[0].Id, Email__c = 'test@test.com',ZipCode_TXT__c = '88763',
                                          First_Name_TXT__c = 'Test', Last_Name_TXT__c = 'Opp', StageName = 'In Conversation',
                                          OpportunityStatus_TXT__c = 'Note', CreatedDate = System.today());
        
           insert opp;
        listOpp.add(opp);
        List<Event> evt = new List<Event>();
        Event event1 = new Event(WhatId = Opp.Id, Subject = 'abc', StartDatetime  = System.now(), EndDateTime = system.now()+2);
       		evt.add(event1);
        insert event1;
        System.runAs(u) {
        System.assertEquals(UserInfo.getUserId(), u.Id, 'user has been inserted');
        
        }
        HELMSOpptystageandstatusonTaskandevent.updateopptyStageandStatusforEvent(evt);
        
    }
	@isTest static void method6(){
        List<Account> alist = new List<Account>();
            Account ac3 = new Account(name ='testgazi', DealerCode_CD__c='30Z214', recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()) ;
            
            insert ac3;
            ac3.name ='Grazittilav';
           
            alist.add(ac3); 
            update alist;
       
        Id conRecordTypeId = Schema.SObjectType.contact.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
            Contact conTestRec = new Contact(FirstName='YashLeadlav',LastName='Recordlav',Email='yashlav@testing.com',Title='Mr',
                                             AccountId=alist[0].Id,RecordTypeId=conRecordTypeId,HelmsCRMEligible_FLAG__c=false);
            insert conTestRec;
        
        Profile p = [Select Id From Profile Where Name = 'HELMS Partner Community'];
        User u = new User(firstname= 'Test',
                          lastname='User',
                          Alias='TUser',
                          email = 'test@test.com',
                          username= 'testWipro@test.com', 
                          profileId= p.id, 
                          emailencodingkey='UTF-8',
                          languagelocalekey='en_US',
                          localesidkey='en_US',
                          timezonesidkey='America/Los_Angeles',
                         ContactId = conTestRec.Id);
        insert u; 
        
        
        
        List<Opportunity> listOpp = new List<Opportunity>();
        
        Opportunity opp = new Opportunity( Name = 'Test Oppo', CloseDate = System.today()+10, 
                                          LeadProvider_ID__c = alist[0].Id, Email__c = 'test@test.com',ZipCode_TXT__c = '88763',
                                          First_Name_TXT__c = 'Test', Last_Name_TXT__c = 'Opp', StageName = 'Assigned to Dealer',
                                          OpportunityStatus_TXT__c = 'Note', CreatedDate = System.today());
        
           insert opp;
        listOpp.add(opp);
        List<Event> evt = new List<Event>();
        Event event1 = new Event(WhatId = Opp.Id, Subject = 'abc', StartDatetime  = System.now(), EndDateTime = system.now()+2);
       		evt.add(event1);
        insert event1;
        System.runAs(u) {
        System.assertEquals(UserInfo.getUserId(), u.Id, 'user has been inserted');
        
        }
        HELMSOpptystageandstatusonTaskandevent.updateopptyStageandStatusforEvent(evt);
        
    }  

     @isTest static void method7(){
        List<Account> alist = new List<Account>();
            Account ac3 = new Account(name ='testgazi', DealerCode_CD__c='30Z214', recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()) ;
            
            insert ac3;
            ac3.name ='Grazittilav';
           
            alist.add(ac3); 
            update alist;
       
        Id conRecordTypeId = Schema.SObjectType.contact.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
            Contact conTestRec = new Contact(FirstName='YashLeadlav',LastName='Recordlav',Email='yashlav@testing.com',Title='Mr',
                                             AccountId=alist[0].Id,RecordTypeId=conRecordTypeId,HelmsCRMEligible_FLAG__c=false);
            insert conTestRec;
        
        Profile p = [Select Id From Profile Where Name = 'HELMS Partner Community'];
        User u = new User(firstname= 'Test',
                          lastname='User',
                          Alias='TUser',
                          email = 'test@test.com',
                          username= 'testWipro@test.com', 
                          profileId= p.id, 
                          emailencodingkey='UTF-8',
                          languagelocalekey='en_US',
                          localesidkey='en_US',
                          timezonesidkey='America/Los_Angeles',
                         ContactId = conTestRec.Id);
        insert u; 
        
        
        
        List<Opportunity> listOpp = new List<Opportunity>();
        
        Opportunity opp = new Opportunity( Name = 'Test Oppo', CloseDate = System.today()+10, 
                                          LeadProvider_ID__c = alist[0].Id, Email__c = 'test@test.com',ZipCode_TXT__c = '88763',
                                          First_Name_TXT__c = 'Test', Last_Name_TXT__c = 'Opp', StageName = 'Assigned to Dealer',
                                          OpportunityStatus_TXT__c = 'Note', CreatedDate = System.today());
        
           insert opp;
        listOpp.add(opp);
        
         List <EmailMessage> emailMessage = new List <EmailMessage> ();
        EmailMessage et =new EmailMessage(RelatedToId = opp.Id) ;
        emailMessage.add(et);
        insert et;
       
        
        System.runAs(u) {
        System.assertEquals(UserInfo.getUserId(), u.Id, 'user has been inserted');
        
        }
        HELMSOpptystageandstatusonTaskandevent.updateopptyStageandStatusforEmailMessage(EmailMessage);
        
    } 

     @isTest static void method8(){
        List<Account> alist = new List<Account>();
            Account ac3 = new Account(name ='testgazi', DealerCode_CD__c='30Z214', recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()) ;
            
            insert ac3;
            ac3.name ='Grazittilav';
           
            alist.add(ac3); 
            update alist;
       
        Id conRecordTypeId = Schema.SObjectType.contact.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
            Contact conTestRec = new Contact(FirstName='YashLeadlav',LastName='Recordlav',Email='yashlav@testing.com',Title='Mr',
                                             AccountId=alist[0].Id,RecordTypeId=conRecordTypeId,HelmsCRMEligible_FLAG__c=false);
            insert conTestRec;
        
        Profile p = [Select Id From Profile Where Name = 'HELMS Partner Community'];
        User u = new User(firstname= 'Test',
                          lastname='User',
                          Alias='TUser',
                          email = 'test@test.com',
                          username= 'testWipro@test.com', 
                          profileId= p.id, 
                          emailencodingkey='UTF-8',
                          languagelocalekey='en_US',
                          localesidkey='en_US',
                          timezonesidkey='America/Los_Angeles',
                         ContactId = conTestRec.Id);
        insert u; 
        
        
        
        List<Opportunity> listOpp = new List<Opportunity>();
        
        Opportunity opp = new Opportunity( Name = 'Test Oppo', CloseDate = System.today()+10, 
                                          LeadProvider_ID__c = alist[0].Id, Email__c = 'test@test.com',ZipCode_TXT__c = '88763',
                                          First_Name_TXT__c = 'Test', Last_Name_TXT__c = 'Opp', StageName = 'Assigned to Dealer',
                                          OpportunityStatus_TXT__c = 'Note', CreatedDate = System.today());
        
           insert opp;
        listOpp.add(opp);
        
        //List<ContentDocumentLink> ContentDocumentLink = new List<ContentDocumentLink>();
        //ContentDocumentLink cdl = new ContentDocumentLink(LinkedEntityId = Opp.Id);
       	//ContentDocumentLink.add(cdl);
         ContentVersion cv = new ContentVersion();
		cv.Title = 'Test Document';
		cv.PathOnClient = 'TestDocument.pdf';
		cv.VersionData = Blob.valueOf('Test Content');
		cv.IsMajorVersion = true;
		Insert cv;
 
		//Get Content Documents
		Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
 
		//Create ContentDocumentLink 
		ContentDocumentLink cdl = New ContentDocumentLink();
		cdl.LinkedEntityId = opp.Id;
		cdl.ContentDocumentId = conDocId;
		cdl.shareType = 'V';
		Insert cdl;
        List<ContentDocumentlink> cdlist = new list<ContentDocumentlink>();
        cdlist.add(cdl);
        
        System.runAs(u) {
        System.assertEquals(UserInfo.getUserId(), u.Id);
        
        }
        HELMSOpptystageandstatusonTaskandevent.updateopptyStageandStatusforNote(cdlist);
        
    }  
     @isTest static void method9(){
        List<Account> alist = new List<Account>();
            Account ac3 = new Account(name ='testgazi', DealerCode_CD__c='30Z214', recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dealer').getRecordTypeId()) ;
            
            insert ac3;
            ac3.name ='Grazittilav';
           
            alist.add(ac3); 
            update alist;
       
        Id conRecordTypeId = Schema.SObjectType.contact.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
            Contact conTestRec = new Contact(FirstName='YashLeadlav',LastName='Recordlav',Email='yashlav@testing.com',Title='Mr',
                                             AccountId=alist[0].Id,RecordTypeId=conRecordTypeId,HelmsCRMEligible_FLAG__c=false);
            insert conTestRec;
        
        Profile p = [Select Id From Profile Where Name = 'HELMS Partner Community'];
        User u = new User(firstname= 'Test',
                          lastname='User',
                          Alias='TUser',
                          email = 'test@test.com',
                          username= 'testWipro@test.com', 
                          profileId= p.id, 
                          emailencodingkey='UTF-8',
                          languagelocalekey='en_US',
                          localesidkey='en_US',
                          timezonesidkey='America/Los_Angeles',
                         ContactId = conTestRec.Id);
        insert u; 
        
        
        
        List<Opportunity> listOpp = new List<Opportunity>();
        
        Opportunity opp = new Opportunity( Name = 'Test Oppo', CloseDate = System.today()+10, 
                                          LeadProvider_ID__c = alist[0].Id, Email__c = 'test@test.com',ZipCode_TXT__c = '88763',
                                          First_Name_TXT__c = 'Test', Last_Name_TXT__c = 'Opp', StageName = 'In Conversation',
                                          OpportunityStatus_TXT__c = 'Abc', CreatedDate = System.today());
        
           insert opp;
        listOpp.add(opp);
        
         ContentVersion cv = new ContentVersion();
		cv.Title = 'Test Document';
		cv.PathOnClient = 'TestDocument.pdf';
		cv.VersionData = Blob.valueOf('Test Content');
		cv.IsMajorVersion = true;
		Insert cv;
 
		//Get Content Documents
		Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
 
		//Create ContentDocumentLink 
		ContentDocumentLink cdl = New ContentDocumentLink();
		cdl.LinkedEntityId = opp.Id;
		cdl.ContentDocumentId = conDocId;
		cdl.shareType = 'V';
		Insert cdl;
        List<ContentDocumentlink> cdlist = new list<ContentDocumentlink>();
        cdlist.add(cdl);
        
        System.runAs(u) {
        System.assertEquals(UserInfo.getUserId(), u.Id);
        
        }
        HELMSOpptystageandstatusonTaskandevent.updateopptyStageandStatusforNote(cdlist);
        
    }  
  
}