objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active_Divisions__c</fullName>
        <label>Active Divisions</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DealerCRMVendor_TXT__c</fullName>
        <label>Dealer CRM Vendor</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DealerCode_CD__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <formula>CASE(SubDivision_TXT__c , &quot;Honda&quot; , &quot;A&quot;, &quot;Acura&quot;, &quot;B&quot;, &quot;NSX&quot;, &quot;B&quot;, &quot;Motorcycle&quot;, &quot;M&quot;, &quot;Marine&quot;, &quot;P&quot;, &quot;Engine&quot;, &quot;P&quot;, &quot;PowerEquipment&quot;, &quot;P&quot; , &quot;None&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HondaDigitalSolutions_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Honda Digital Solutions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Routable_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Provider Routable status for the dealers who are not enrolled in the HDS program</inlineHelpText>
        <label>Routable?</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CRM_System__c.object
<CustomObject>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ISActive_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vendor_ID__c</fullName>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CRM Systems</relationshipLabel>
        <relationshipName>CRM_Systems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CRM System</label>
    <nameField>
        <label>CRM System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRM Systems</pluralLabel>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <label>System</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Dealer_Division__c.object
<CustomObject>
    <description>list of active or inactive division, subdivision, zone, district and other territory related fields based on their business use for Sales, Service, Parts, etc.</description>
    <fields>
        <fullName>Dealer_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Subdivision</relationshipLabel>
        <relationshipName>Dealer_Divisions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesZone_CD__c</fullName>
        <label>Sales Zone</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive_FLG__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Dealer Subdivision</label>
    <nameField>
        <displayFormat>DD-{0}</displayFormat>
        <label>Dealer Division Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Divisions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Dealer_Participation__c.object
<CustomObject>
    <fields>
        <fullName>CRM_System__c</fullName>
        <label>CRM System</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Division__c</field>
                <operation>equals</operation>
                <valueField>CRM_System__c.Division_CD__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CRM_System__c</referenceTo>
        <relationshipLabel>Dealer Participations</relationshipLabel>
        <relationshipName>Dealer_Participations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DealerAccount_ID__c</fullName>
        <label>Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Participations</relationshipLabel>
        <relationshipName>Dealer_Participations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Dealer_Subdivision__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer Subdivision</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.DealerAccount_ID__c</field>
                <operation>equals</operation>
                <valueField>Dealer_Division__c.Dealer_ID__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Division__c</field>
                <operation>equals</operation>
                <valueField>Dealer_Division__c.Division_CD__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Dealer_Division__c</referenceTo>
        <relationshipLabel>Dealer Participations</relationshipLabel>
        <relationshipName>Dealer_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ISActive_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LeadReceivingStartDate_DT__c</fullName>
        <label>Lead Receiving Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Dealer Participation</label>
    <nameField>
        <label>Dealer Participation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

classes/HELMSAccountInfoDailyBatchTest.cls
@IsTest
public class HELMSAccountInfoDailyBatchTest {

    @isTest static void testAccountInfoDaily() { 
       
        List<Account> lstacc= new List<Account>();
        Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Account accTestRec = new Account(Name='Test Account123',Active_Divisions__c='A06',DealerCRMVendor_TXT__c = 'Elead1',
                                         RecordTypeId=dealerAccRecTypeId, DealerCode_CD__c='728456');
        lstacc.add(accTestRec);
        insert lstacc;
        
        accTestRec.name='TestAms Helms1';
        update accTestRec;
        
         Dealer_Division__c dd = new Dealer_Division__c();
         dd.isActive_FLG__c = True;
         dd.Dealer_ID__c = accTestRec.Id;
         dd.Division_CD__c = 'M';
         dd.SalesZone_CD__c = '01';
            
         insert dd;
        
         Id vendorAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Vendor').getRecordTypeId();
        
       Account accVendor = new Account(Name='Hello1 vendor1', RecordTypeId=vendorAccRecTypeId,
                                  DealerCode_CD__c='1234Z',HondaDigitalSolutions_FLG__c=false,
                                 Routable_FLG__c=true);
        insert accvendor;
        
      CRM_System__c crmSystem = new CRM_System__c(Name='Test crm system1',Vendor_ID__c=accVendor.Id,ISActive_FLG__c=true,Division_CD__c ='M');
      insert crmSystem;
        
      Dealer_Participation__c dealerParticipationList = new Dealer_Participation__c(DealerAccount_ID__c =accTestRec.Id,Division__c='M',
                                                               CRM_System__c = crmSystem.Id, LeadReceivingStartDate_DT__c=System.NOW()-12,Dealer_Subdivision__c =dd.id);
       
      insert dealerParticipationList;
        
         Test.startTest();
	 	
        HELMSAccountInfoDailyBatch accInfoDailyBatch = new HELMSAccountInfoDailyBatch(); 
        Database.executeBatch(accInfoDailyBatch);
        System.assertEquals(accTestRec.name, 'TestAms Helms1');
        Test.stopTest();
        }

}