objects/Account.object
<CustomObject>
    <fields>
        <fullName>Send_Customer_Acknowledgement_Email_Flag__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Send Customer Acknowledgement Email</description>
        <label>Send Customer Acknowledgement Email</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>BrandsiteShoppingTool_TXT__c</fullName>
        <label>Brandsite Shopping Tool</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactKey_TXT__c</fullName>
        <label>Contact Key</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Provider</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Lead Provider)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model_TXT__c</fullName>
        <label>Model</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PreferredDealerAccount_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_confirmation_Email__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Business Unit: HELMS.
Jira Story: LMS-5361 Story name.
Description: This is store the true or false form SFMC.
Source System: Coming from Integration.
Integration: No
Data Transformation: N/A.
Functional Definition: If the  flag is true Lead  Data sent to SFMC.</description>
        <label>Send confirmation Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>Subdivision</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division_CD__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Logs__c.object
<CustomObject>
    <fields>
        <fullName>Error_Line_Number__c</fullName>
        <label>Error Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>130768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Trigger_or_Class_Name__c</fullName>
        <label>Trigger or Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Logs</label>
    <nameField>
        <label>Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BrandsiteShoppingTool_TXT__c</fullName>
        <label>Brandsite Shopping Tool</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactKey_TXT__c</fullName>
        <label>Contact Key</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Acknowledgement__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Business Unit: HELMS.
Jira Story: LMS-5361 Story name.
Description: This is store the true or false form Integration
Source System: Coming from Integration.
Integration: Yes.
Data Transformation: N/A.
Functional Definition: This will store true or false based on mail triggered..</description>
        <label>Customer Acknowledgement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Lead Provider)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model_TXT__c</fullName>
        <label>Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_confirmation_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send confirmation Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Marine</fullName>
        <active>true</active>
        <businessProcess>HELMS Standard Process</businessProcess>
        <description>Used by the Honda Marine Team</description>
        <label>Marine Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/HelmsLeadCrationNotificationSFMC.cls
/*-------------------------------------------------------------------------------------------
Story Number :LMS-5361
Class Name : HelmsLeadCrationNotificationSFMC 
Test Class Name : HelmsLeadCrationNotificationSFMCTest
Last Modified Version Owner : Ghouse
Comments : Send Email From SFMC when Lead is created From Marien or PE Brand Sites.
--------------------------------------------------------------------------------------------*/

global with sharing class HelmsLeadCrationNotificationSFMC {
    

    //Fetching all Lead record ids which will Created from Marien or PE sites.
    global static void leadCreationSFMC(List<Lead> pEMarineLead) {
        try{
             //  system.debug(':ids::::3333333333:::::::'+ids);
               
               /*  List<Lead> lead_List=[SELECT Id, ContactKey_TXT__c, Email, Model_TXT__c, SubDiv_TXT__c,Division_CD__c,ConvertedOpportunityId,
                        PreferredDealerAccount_ID__r.Phone,PreferredDealerAccount_ID__r.name,
                        PreferredDealerAccount_ID__r.ShippingStreet,PreferredDealerAccount_ID__r.ShippingCity,
                        PreferredDealerAccount_ID__r.ShippingPostalCode,PreferredDealerAccount_ID__r.ShippingCountry,
                        BrandsiteShoppingTool_TXT__c,Send_confirmation_Email__c  FROM Lead 
                        where (SubDiv_TXT__c='Marine' OR SubDiv_TXT__c='PowerEquipment')   AND isConverted = true AND Send_confirmation_Email__c = true AND
                        LeadProvider_ID__r.Send_Customer_Acknowledgement_Email_Flag__c = true AND BrandsiteShoppingTool_TXT__c =null AND id IN: ids];
    
    */
    
            //Iterating all Lead Records and mapping the requested parameters from SFMC.
            
            SFMCRequest sr = new SFMCRequest ();
            list<Opportunity> updateOppList = new list<Opportunity>();
            for(Lead l : pEMarineLead) {
                
           //     system.debug(':::ContactKey_TXT__c::::'+l.ContactKey_TXT__c);
                
                SFMCRequest.SubscriberAttributes subscribe = new SFMCRequest.SubscriberAttributes ();
                SFMCRequest.ContactAttributes conAttributes = new SFMCRequest.ContactAttributes ();
                SFMCRequest.To to = new SFMCRequest.To ();
                    
                string shippingstreet ='';
                string shippingcity='';
                string shippingpostalcode='';
                string shippingcountry='';
                if(l.PreferredDealerAccount_ID__r.ShippingStreet!=null){
                    shippingstreet = l.PreferredDealerAccount_ID__r.ShippingStreet;   
                }
                if(l.PreferredDealerAccount_ID__r.ShippingCity!=null){
                    shippingcity = l.PreferredDealerAccount_ID__r.ShippingCity;  
                }
                if(l.PreferredDealerAccount_ID__r.ShippingPostalCode!=null){
                    shippingpostalcode = l.PreferredDealerAccount_ID__r.ShippingPostalCode;   
                }
                if(l.PreferredDealerAccount_ID__r.ShippingCountry!=null){
                    shippingcountry = l.PreferredDealerAccount_ID__r.ShippingCountry;   
                }
                string dealerAddress=shippingstreet +' '+ shippingcity +' '+shippingpostalcode +' '+shippingcountry;
                
                subscribe.Dealer_Address = dealerAddress;
                subscribe.Dealer_Name = l.PreferredDealerAccount_ID__r.name;
                subscribe.Dealer_Phone = l.PreferredDealerAccount_ID__r.Phone;
                subscribe.Model_Name = l.Model_TXT__c;
                subscribe.Sub_Division =l.SubDiv_TXT__c; //PowerEquipment //Marine
                conAttributes.SubscriberAttributes = subscribe;
                to.Address = l.Email;
                //string ckey = 'H352338222';
                to.SubscriberKey = l.ContactKey_TXT__c;
                to.ContactAttributes = conAttributes;
                sr.To = to;
                
                
                // Authorization Request to get access token.
                HttpRequest req = new HttpRequest();           
                req.setHeader('Accept', 'application/json');
                req.setHeader('Content-Type','application/json;charset=UTF-8');
                req.setMethod('POST');
                req.setEndpoint('callout:mSFMC_Credentails');
                //req.setEndpoint('https://mc219s2l565j37tg6q88270hftr1.auth.marketingcloudapis.com/v2/token'); 
                req.setTimeout(120000);
                
               SFMCAuthentication sf=  new SFMCAuthentication();
                //sr.SFMCAuth(HELMSConstants.grant_type,HELMSConstants.client_id,HELMSConstants.client_secret,HELMSConstants.account_id);
                sf.grant_type = HELMSConstants.grant_type;
                sf.client_id = HELMSConstants.client_id;
                sf.client_secret = HELMSConstants.client_secret;
                sf.account_id = HELMSConstants.account_id;
                String jsonString = JSON.serialize(sf);
             //   system.debug('JsonString------>>>>'+jsonString);
                req.setBody(jsonString);
                Http http = new Http();
                HTTPResponse res = http.send(req);
             //   system.debug(res.getBody());
                oAuthClass autorize = (oAuthClass)JSON.deserialize(res.getBody(), oAuthClass.class);
                string accesstoken = autorize.access_token; 
                
                //Requested Json body send to SFMC based on Access Token.
                HttpRequest req1 = new HttpRequest();
                req1.setHeader('Accept', 'application/json');
                req1.setHeader('Content-Type','application/json;charset=UTF-8');
                //string accesstoken ='eyJhbGciOiJIUzI1NiIsImtpZCI6IjQiLCJ2ZXIiOiIxIiwidHlwIjoiSldUIn0.eyJhY2Nlc3NfdG9rZW4iOiI3ekZ0Z0NWY3Y4dXpwSTlaQlJFRW9MRTkiLCJjbGllbnRfaWQiOiJxdm5mY2tqZHM1aW9jMm8yb2gzOG5yM2QiLCJlaWQiOjcyOTM2NDcsInN0YWNrX2tleSI6IlM3IiwicGxhdGZvcm1fdmVyc2lvbiI6MiwiY2xpZW50X3R5cGUiOiJTZXJ2ZXJUb1NlcnZlciJ9._7XHNPD91a4JYbeHeBSZXJPqpzwnwyvzWAR2Y23MPuo.JVetWdbrqfFhoR7ARFI7crsn9jYm3D8S34Ycp2C3yjXSgfngTYEcmOyz-T1dABs8zfmGjpB2IEkXmnpQzwKRqtfo7cJYWiU5Cl1Jc-ICtd9r39lmMDylXGGwyLIHzMjpIU5ldRJY5HPT';
                req1.setHeader('Authorization','Bearer ' + accesstoken);
                req1.setMethod('POST');
                //req1.setEndpoint('https://mc219s2l565j37tg6q88270hftr1.rest.marketingcloudapis.com/messaging/v1/messageDefinitionSends/key:68881/send');
                req1.setEndpoint('callout:mSFMC_SecondCall');
                req1.setTimeout(120000);
                
                String jsonString1=JSON.serialize(sr);
                req1.setBody(jsonString1);
            //    system.debug('JsonString1'+jsonString1);
                Http http1 = new Http();
                HTTPResponse res1 = http1.send(req1);
            //    system.debug(res1.getBody());
                Opportunity opp = [select id,Customer_Acknowledgement__c from Opportunity where id=: l.ConvertedOpportunityId limit 1];
                if(opp != null) {
                    Opp.Customer_Acknowledgement__c = false;
                }
                SFMCResponse message = (SFMCResponse)JSON.deserialize(res1.getBody(), SFMCResponse.class);
                if(message!=null && message.responses!=null && message.responses[0] != null){
                    if(message.responses[0].messages[0] != null && message.responses[0].messages[0] == 'Queued' && l.ConvertedOpportunityId != null){
                        if(Opp.Customer_Acknowledgement__c == false) {
                            Opp.Customer_Acknowledgement__c = true;
                        }
                    }
                }
                //update opp; 
                updateOppList.add(opp);
            }
            
            
      
            if(updateOppList.size() > 0) {
                update updateOppList;
            }
        } catch(Exception ex) {
            Logs__c  l =new Logs__c (name='HelmsLeadCrationNotificationSFMC',Trigger_or_Class_Name__c='HelmsLeadCrationNotificationSFMC', Error_Message__c =ex.getMessage(), Error_Line_Number__c =Integer.valueOf(string.valueof(ex.getLineNumber() )) );
            insert l;
            
        }
        
    }
   
    
    global class oAuthClass {
        global string access_token {get;set;} 
    }
    

}