objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact_Key__c</fullName>
        <label>Contact Key</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DealerCode_CD__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <formula>CASE(SubDivision_TXT__c , &quot;Honda&quot; , &quot;A&quot;, &quot;Acura&quot;, &quot;B&quot;, &quot;NSX&quot;, &quot;B&quot;, &quot;Motorcycle&quot;, &quot;M&quot;, &quot;Marine&quot;, &quot;P&quot;, &quot;Engine&quot;, &quot;P&quot;, &quot;PowerEquipment&quot;, &quot;P&quot; , &quot;None&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Launchbox_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>used for Data Migration, external id, unique</description>
        <externalId>true</externalId>
        <label>Launchbox_ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Used for Dealer Records</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Zip_Ranking__c.object
<CustomObject>
    <fields>
        <fullName>Dealer_Number__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-3903 Story name.
Description: This is store the Dealer Number.
Source System: Coming from batch feed daily basis.
Integration: NA.
Data Transformation: N/A.
Functional Definition: This will be used in Einstein Dashboards or Reports.</description>
        <label>Dealer Number</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-3903 Story name.
Description: This is store the Dealer Division.
Source System: Coming from batch feed daily basis.
Integration: NA.
Data Transformation: N/A.
Functional Definition: This will be used in Einstein Dashboards or Reports.</description>
        <label>Division</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Launchbox_ID__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-3903 Story name.
Description: This is used for Data Migration, external id, unique.
Source System: Coming from batch feed daily basis.
Integration: NA.
Data Transformation: N/A.
Functional Definition: This will be used in Einstein Dashboards or Reports.</description>
        <externalId>true</externalId>
        <label>Launchbox_ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-3903 Story name.
Description: This is store the Postal Code.
Source System: Coming from batch feed daily basis.
Integration: NA.
Data Transformation: N/A.
Functional Definition: This will be used in Einstein Dashboards or Reports.</description>
        <label>Postal Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ranking__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-3903 Story name.
Description: This defines the ranking of dealer for the particular postal code and city.
Source System: Coming from batch feed daily basis.
Integration: NA.
Data Transformation: N/A.
Functional Definition: This will be used in Einstein Dashboards or Reports.</description>
        <label>Ranking</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Zip Ranking</label>
    <nameField>
        <label>Zip Ranking</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Ranking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HELMSZipRankingDealerAccUpdateTest.cls
@isTest
public class HELMSZipRankingDealerAccUpdateTest {
        @isTest static void mytestmethod(){

                Id dealerAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Account accTestRec = new Account(Name='South West Motors',RecordTypeId=dealerAccRecTypeId,DealerCode_CD__c='123456',Contact_Key__c='E150363308'
                                        );
        insert accTestRec;
        
        List<string> zipRanklst = new List<string>();
        Zip_Ranking__c zRank = new Zip_Ranking__c();
            zRank.Dealer_Number__c = '123456';
            zRank.Postal_Code__c = '12345';
            zRank.Division__c = 'P';
            zRank.Ranking__c = 2;
            zRank.Launchbox_ID__c = zRank.Postal_Code__c + zRank.Division__c + zRank.Ranking__c;
            insert zRank;
            
            zipRanklst.add(zRank.id);
            system.assertEquals('123456', zRank.Dealer_Number__c);
        }
}