objects/Dealer_Division__c.object
<CustomObject>
    <description>list of active or inactive division, subdivision, zone, district and other territory related fields based on their business use for Sales, Service, Parts, etc.</description>
    <fields>
        <fullName>Dealer_Access_Level__c</fullName>
        <label>Dealer Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Full Access</fullName>
                </value>
                <value>
                    <fullName>No Access</fullName>
                </value>
                <value>
                    <fullName>Reporting Only</fullName>
                    <default>true</default>
                    <label>Reporting Only</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealer_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Subdivision</relationshipLabel>
        <relationshipName>Dealer_Divisions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <label>Dealer Subdivision</label>
    <nameField>
        <displayFormat>DD-{0}</displayFormat>
        <label>Dealer Division Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Divisions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Lead_Division_Mapping_From_Subdivision__mdt.object
<CustomObject>
    <description>Lead SubDivision = PowerEquipment , Marine ,Engine  then Division is &apos;P&apos;

Lead SubDivision = Honda  then Division is &apos;A&apos;

SubDivision = Acura , NSX  then Division is &apos;B&apos;

SubDivision = Motorcycle then Division is &apos;M&apos;</description>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division_CD</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opp_Recortype_API_name__c</fullName>
        <label>Opp_Recortype_API_name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <label>Subdivision</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Lead_Division_Mapping_From_Subdivision</label>
    <pluralLabel>Lead_Division_Mapping_From_Subdivision</pluralLabel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/HELMSOpportunityController.cls
//****************************************************************************** 
// File Name:       HELMSOpportunityController.cls
//===============================================================================
// Modification Log: 
// May 28, 2021 Arunprasad N (Wipro) initial coding
//*******************************************************************************
public with sharing class HELMSOpportunityController {
  @AuraEnabled(cacheable = true)
    public static List<Action> getActions(){
        try{
            List<Action> actions = new List<Action>();
            List<String> subDivisions = new List<String>();
            //String userId = UserInfo.getUserId();
            User u = [SELECT AccountId, Profile.Name FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
            if(u.Profile.Name == 'System Administrator'){
                // Describe the Dealer_Division__c.SubDiv_TXT__c field
                Schema.DescribeFieldResult fieldSubDiv = Dealer_Division__c.SubDiv_TXT__c.getDescribe();
                // Get picklist values from field SubDiv_TXT__c
                List<Schema.PicklistEntry> entires = getPicklistValues(fieldSubDiv.getSobjectField());
                // Do something with entries
                for (Schema.PicklistEntry entry : entires) {
                    subDivisions.add(entry.getValue());
                }
            }else{
                if(!String.isEmpty(u.AccountId)){
                    List<Dealer_Division__c> dealerDivisions = [SELECT Id, Name, Dealer_ID__c, SubDiv_TXT__c, Dealer_Access_Level__c FROM Dealer_Division__c WHERE Dealer_ID__c = :u.AccountId and Dealer_Access_Level__c='Full Access'];
                   // List<Dealer_Division__c> dealerDivisions = [SELECT Id, Name, Dealer_ID__c, SubDiv_TXT__c, Dealer_Access_Level__c FROM Dealer_Division__c WHERE Dealer_ID__c = :u.AccountId and Dealer_Access_Level__c IN ('Full Access','Reporting Only')];
                    for(Dealer_Division__c dealerDivision : dealerDivisions){
                        subDivisions.add(dealerDivision.SubDiv_TXT__c);
                    }
                }
            }
            Map<String,String> recordTypeSubDivisionMap = new Map<String,String>();
            Map<String,String> subDivsionRecordTypeMap = new Map<String,String>();
            for(Lead_Division_Mapping_From_Subdivision__mdt m :[SELECT Id, Subdivision__c, Opp_Recortype_API_name__c, Division_CD__c FROM Lead_Division_Mapping_From_Subdivision__mdt])
            {
                recordTypeSubDivisionMap.put(m.Opp_Recortype_API_name__c , m.Subdivision__c);
                subDivsionRecordTypeMap.put(m.Subdivision__c , m.Opp_Recortype_API_name__c);
            }
            List<RecordType> recordTypes = [SELECT Id, Name, DeveloperName, IsActive FROM RecordType WHERE SobjectType = 'Opportunity' AND IsActive = true AND DeveloperName IN :recordTypeSubDivisionMap.keySet()];
            Map<String, Id> recordTypeMap = new Map<String, Id>();
            for(RecordType rt : recordTypes){
                recordTypeMap.put(rt.DeveloperName, rt.Id);
            }
            for(String subDivision : subDivisions){
                if(subDivsionRecordTypeMap.get(subDivision) != null){
                    Action ac = new Action();
                    ac.name = subDivision;
                    ac.label = 'New ' + subDivision + ' Opportunity';
                    ac.recordTypeId = recordTypeMap.get(subDivsionRecordTypeMap.get(subDivision));
                    actions.add(ac);
                }
            }
            return actions;
        }catch (Exception ex) {
            throw new AuraHandledException(ex.getLineNumber() + ':' + ex.getMessage());
        }
    }
    
    // Retrieves active picklist values for a given object and field
    // Example: getPicklistValues(Dealer_Division__c.Dealer_ID__c)
    public static List<Schema.PicklistEntry> getPicklistValues(
            Schema.sObjectField field) {
        // Get all picklist values
        List<Schema.PicklistEntry> entries = field.getDescribe().getPickListValues();
        // Only return active picklist values
        List<Schema.PicklistEntry> activeEntries = new List<Schema.PicklistEntry>();
        for (Schema.PicklistEntry entry : entries) {
            if (entry.isActive()) {
                activeEntries.add(entry);
            }
        }
        return activeEntries;
    }
    
    public class Action {
        @AuraEnabled
        public String recordTypeId {get; set;}
        @AuraEnabled
        public String name {get; set;}
        @AuraEnabled
        public String label {get; set;}
        
    }
      @AuraEnabled(cacheable = true)
    public static List<Action> getActionsImage(){
        try{
            List<Action> actions = new List<Action>();
            List<String> subDivisions = new List<String>();
           // String userId = UserInfo.getUserId();
            User u = [SELECT AccountId, Profile.Name FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
            if(u.Profile.Name == 'System Administrator'){
                // Describe the Dealer_Division__c.SubDiv_TXT__c field
              //  Schema.DescribeFieldResult fieldSubDiv = Dealer_Division__c.SubDiv_TXT__c.getDescribe();
                // Get picklist values from field SubDiv_TXT__c
              //  List<Schema.PicklistEntry> entires = getPicklistValues(fieldSubDiv.getSobjectField());
                // Do something with entries
           //     for (Schema.PicklistEntry entry : entires) {
            //        subDivisions.add(entry.getValue());
            //    }
            }else
            { 
                if(!String.isEmpty(u.AccountId)){
                    //List<Dealer_Division__c> dealerDivisions = [SELECT Id, Name, Dealer_ID__c, SubDiv_TXT__c, Dealer_Access_Level__c FROM Dealer_Division__c WHERE Dealer_ID__c = :u.AccountId and Dealer_Access_Level__c='Full Access'];
                    List<Dealer_Division__c> dealerDivisions = [SELECT Id, Name, Dealer_ID__c, SubDiv_TXT__c, Dealer_Access_Level__c FROM Dealer_Division__c WHERE Dealer_ID__c = :u.AccountId and Dealer_Access_Level__c IN ('Full Access','Reporting Only')];
                    for(Dealer_Division__c dealerDivision : dealerDivisions){
                        subDivisions.add(dealerDivision.SubDiv_TXT__c);
                    }
                }
            }
          //  Map<String,String> recordTypeSubDivisionMap = new Map<String,String>();
            Map<String,String> subDivsionRecordTypeMap = new Map<String,String>();
            for(Lead_Division_Mapping_From_Subdivision__mdt m :[SELECT Id, Subdivision__c, Opp_Recortype_API_name__c, Division_CD__c FROM Lead_Division_Mapping_From_Subdivision__mdt])
            {
              //  recordTypeSubDivisionMap.put(m.Opp_Recortype_API_name__c , m.Subdivision__c);
                subDivsionRecordTypeMap.put(m.Subdivision__c , m.Opp_Recortype_API_name__c);
            } 
           // List<RecordType> recordTypes = [SELECT Id, Name, DeveloperName, IsActive FROM RecordType WHERE SobjectType = 'Opportunity' AND IsActive = true AND DeveloperName IN :recordTypeSubDivisionMap.keySet()];
          //  Map<String, Id> recordTypeMap = new Map<String, Id>();
          //  for(RecordType rt : recordTypes){
         //       recordTypeMap.put(rt.DeveloperName, rt.Id);
         //   }
            for(String subDivision : subDivisions){
                if(subDivsionRecordTypeMap.get(subDivision) != null){
                    Action ac = new Action();
                    ac.name = subDivision;
                    ac.label = 'New ' + subDivision + ' Opportunity';
              //      ac.recordTypeId = recordTypeMap.get(subDivsionRecordTypeMap.get(subDivision));
                    actions.add(ac);
                }
            } 
            return actions;
        }catch (Exception ex) {
            throw new AuraHandledException(ex.getLineNumber() + ':' + ex.getMessage());
        }
    }

}