objects/Dealer_Deprovision__c.object
<CustomObject>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Staging</label>
    <nameField>
        <displayFormat>DP-{0000}</displayFormat>
        <label>Dealer Deprovision Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/StagingDeletionBatchTest.cls
@isTest 
public class StagingDeletionBatchTest
{
    static testMethod void testMethod1()
    {
  
        
        Dealer_Deprovision__c d1=new Dealer_Deprovision__c();
        d1.FirstName__c='kiran';
        d1.CreatedDate= System.today()-35 ;
        insert d1;
        
        Test.startTest();

        StagingDeletionBatch obj = new StagingDeletionBatch();
         obj.execute(null);
         obj.Finish(null);
            
        Test.stopTest();
    }
}