objects/Dealer_CRM_Disposition__e.object
<CustomObject>
    <fields>
        <fullName>HELMS_Opportunity_External_Key_TXT__c</fullName>
        <label>HELMS Opportunity External Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>The_Last_Event_TXT__c</fullName>
        <description>Disposition Code</description>
        <label>The Last Event</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Dealer CRM Disposition</label>
    <pluralLabel>Dealer CRM Dispositions</pluralLabel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name_TXT__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name_TXT__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeadProvider_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lead Provider Name</inlineHelpText>
        <label>Lead Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Lead Provider)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpportunityStatus_TXT__c</fullName>
        <label>Opportunity Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned/Routed to Dealer</fullName>
                </value>
                <value>
                    <fullName>Auto-response sent</fullName>
                </value>
                <value>
                    <fullName>Lead Opened</fullName>
                </value>
                <value>
                    <fullName>Lead Received</fullName>
                </value>
                <value>
                    <fullName>Customer phoned (Inbound phone)</fullName>
                </value>
                <value>
                    <fullName>Customer emailed (Inbound email)</fullName>
                </value>
                <value>
                    <fullName>Salesperson responded by Email</fullName>
                </value>
                <value>
                    <fullName>Salesperson responded by Phone</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson responded by email</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson responded by Phone</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson request another appointment by email</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson request another appointment by phone</fullName>
                </value>
                <value>
                    <fullName>Credit Application</fullName>
                </value>
                <value>
                    <fullName>Credit Application (3rd party)</fullName>
                </value>
                <value>
                    <fullName>Trade-In Appraisal</fullName>
                </value>
                <value>
                    <fullName>Broadcast Email</fullName>
                </value>
                <value>
                    <fullName>Made Appointment</fullName>
                </value>
                <value>
                    <fullName>Demoed/Test Drove</fullName>
                </value>
                <value>
                    <fullName>Boat/Outboard Sales Presentation</fullName>
                </value>
                <value>
                    <fullName>Appointment Didn’t Show</fullName>
                </value>
                <value>
                    <fullName>Appointment Showed</fullName>
                </value>
                <value>
                    <fullName>Offer to Purchase</fullName>
                </value>
                <value>
                    <fullName>Model in Stock</fullName>
                </value>
                <value>
                    <fullName>Model not in Stock</fullName>
                </value>
                <value>
                    <fullName>Model on back order</fullName>
                </value>
                <value>
                    <fullName>Credit Denied</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson marked sold</fullName>
                </value>
                <value>
                    <fullName>Salesperson marked vehicle sold</fullName>
                </value>
                <value>
                    <fullName>Lost Sales</fullName>
                </value>
                <value>
                    <fullName>Any additional vehicle sold info (delivered, punched, etc.)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_SF_ID__c</fullName>
        <externalId>true</externalId>
        <label>Opportunity_SF_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Level_Agreement_TXT__c</fullName>
        <defaultValue>&quot;No Escalation&quot;</defaultValue>
        <inlineHelpText>This shows how high of an escalation was done for this opportunity. The highest level is Level 3 and that escalation goes to upper management.</inlineHelpText>
        <label>Service Level Agreement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Escalation</fullName>
                </value>
                <value>
                    <fullName>Level 1</fullName>
                </value>
                <value>
                    <fullName>Level 2</fullName>
                </value>
                <value>
                    <fullName>Level 3</fullName>
                </value>
                <value>
                    <fullName>Level 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ZipCode_TXT__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/HELMSOpportunityResponsePEHandler_Test.cls
@isTest
public class HELMSOpportunityResponsePEHandler_Test {
    static testMethod void testPEHandler(){
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        List<Opportunity> listOpp = new List<Opportunity>();
        Opportunity opp = new Opportunity( Name = 'Test Opp', CloseDate = System.today()+10, 
                                          LeadProvider_ID__c = acc.Id, Email__c = 'test@test.com',ZipCode_TXT__c = '88763',
                                          First_Name_TXT__c = 'Test', Last_Name_TXT__c = 'Opp', StageName = 'Acknowledged',
                                          OpportunityStatus_TXT__c = 'Auto-response sent', CreatedDate = System.today());
        Opportunity opp1 = new Opportunity( Name = 'Test Opp', CloseDate = System.today()+10, 
                                          LeadProvider_ID__c = acc.Id, Email__c = 'test1@test.com',ZipCode_TXT__c = '88763',
                                          First_Name_TXT__c = 'Test', Last_Name_TXT__c = 'Opp', StageName = 'Acknowledged',
                                          OpportunityStatus_TXT__c = 'Auto-response sent', CreatedDate = System.today()-2,
                                          Service_Level_Agreement_TXT__c='Level 1');
        Opportunity opp2 = new Opportunity( Name = 'Test Opp', CloseDate = System.today()+10, 
                                          LeadProvider_ID__c = acc.Id, Email__c = 'test@test.com',ZipCode_TXT__c = '88763',
                                          First_Name_TXT__c = 'Test', Last_Name_TXT__c = 'Opp', StageName = 'Acknowledged',
                                          OpportunityStatus_TXT__c = 'Auto-response sent', CreatedDate = System.today()-50,
                                          Service_Level_Agreement_TXT__c='Level 2');
        Opportunity opp3 = new Opportunity( Name = 'Test Opp', CloseDate = System.today()+10, 
                                          LeadProvider_ID__c = acc.Id, Email__c = 'test@test.com',ZipCode_TXT__c = '88763',
                                          First_Name_TXT__c = 'Test', Last_Name_TXT__c = 'Opp', StageName = 'Acknowledged',
                                          OpportunityStatus_TXT__c = 'Auto-response sent', CreatedDate = System.today()-5,
                                          Service_Level_Agreement_TXT__c='Level 2');
        listOpp.add(opp);
        listOpp.add(opp1);
        listOpp.add(opp2);
        listOpp.add(opp3);
        insert listOpp;
        for(Opportunity eachOpp:listOpp) {
            eachOpp.Opportunity_SF_ID__c = eachOpp.Id;
        }
        update listOpp;
        Profile p = [Select Id From Profile Where Name = 'System Administrator'];
        User u = new User(firstname= 'Test',
                          lastname='User',
                          Alias='TUser',
                          email = 'test@test.com',
                          username= 'testWipro@test.com', 
                          profileId= p.id, 
                          emailencodingkey='UTF-8',
                          languagelocalekey='en_US',
                          localesidkey='en_US',
                          timezonesidkey='America/Los_Angeles');
        insert u;    
        Test.startTest();
        System.runAs(u){
          List<Dealer_CRM_Disposition__e> listDealerDisp = new List<Dealer_CRM_Disposition__e>();
            for(integer i =0 ; i < 4 ; i++){
                Dealer_CRM_Disposition__e dealerDisp = new Dealer_CRM_Disposition__e();
                dealerDisp.HELMS_Opportunity_External_Key_TXT__c = listOpp[i].Id;
                dealerDisp.The_Last_Event_TXT__c = String.Valueof(i+1);
                listDealerDisp.add(dealerDisp); 
            }
            
        EventBus.publish(listDealerDisp);
        Test.stopTest();  
        }
        
        List<Opportunity> updateOpp = [Select Id, StageName, OpportunityStatus_TXT__c from Opportunity];
        System.assertEquals('Acknowledged', opp3.StageName);
        List<Task> t = [Select Id, Disposition_Code_CD__c from Task];
        System.debug('====>>>>>>>'+t.Size());
     //   System.assertEquals(listOpp.Size(), t.Size());
    } 
}