objects/Dealer_Division__c.object
<CustomObject>
    <description>list of active or inactive division, subdivision, zone, district and other territory related fields based on their business use for Sales, Service, Parts, etc.</description>
    <fields>
        <fullName>DealerSubdivision_CD__c</fullName>
        <description>external key from B2C system to have both Dealer Number + Subdivision.</description>
        <externalId>true</externalId>
        <label>Dealer Subdivision</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Dealer Subdivision</label>
    <nameField>
        <displayFormat>DD-{0}</displayFormat>
        <label>Dealer Division Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Divisions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/HELMSHttpCalloutMockImpl.cls
global class HELMSHttpCalloutMockImpl implements HttpCalloutMock {
    global HTTPResponse respond(HTTPRequest req) {
        // Create a fake response.
        // Set response values, and 
        // return response.
        
     
        
        datetime ndate= system.now();

string st = ndate.date()+'T13:32:21.000+0000';
st = st.replace(' 00:00:00','');

        String  respBody = '{"done":true,"nextRecordsUrl":null,"records":[{"id":"7504x00000GMOwHAAX","operation":"upsert","object":"Dealer_Division__c","createdById":"0054x000004lOmuAAE","createdDate":"'+st+'","systemModstamp":"'+st+'","state":"Open","externalIdFieldName":"DealerSubdivision_CD__c","concurrencyMode":"Parallel","contentType":"CSV","apiVersion":51.0,"jobType":"V2Ingest","contentUrl":"services/data/v51.0/jobs/ingest/7504x00000GMOwHAAX/batches","lineEnding":"CRLF","columnDelimiter":"PIPE"}]}';
             

            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'text/json');
            res.setBody(respBody);
            res.setStatusCode(200);
            return res;
    }
    
    
}