objects/Error_c__x.object
<CustomObject>
    <externalDataSource>HDMP_QA</externalDataSource>
    <externalName>Error__c</externalName>
    <fields>
        <fullName>Account_c__c</fullName>
        <externalDeveloperName>Account__c</externalDeveloperName>
        <label>Account</label>
        <length>18</length>
        <referenceTo>Account__x</referenceTo>
        <relationshipName>Errors2</relationshipName>
        <type>ExternalLookup</type>
    </fields>
    <fields>
        <fullName>Cart_c__c</fullName>
        <externalDeveloperName>Cart__c</externalDeveloperName>
        <label>Cart</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClassName_c__c</fullName>
        <externalDeveloperName>ClassName__c</externalDeveloperName>
        <label>ClassName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duration_c__c</fullName>
        <externalDeveloperName>Duration__c</externalDeveloperName>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Error_Message_c__c</fullName>
        <externalDeveloperName>Error_Message__c</externalDeveloperName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Type_c__c</fullName>
        <externalDeveloperName>Error_Type__c</externalDeveloperName>
        <label>Error Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number_c__c</fullName>
        <externalDeveloperName>Line_Number__c</externalDeveloperName>
        <label>Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MethodName_c__c</fullName>
        <externalDeveloperName>MethodName__c</externalDeveloperName>
        <label>MethodName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <externalDeveloperName>Name</externalDeveloperName>
        <label>Error Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notify_Support_c__c</fullName>
        <defaultValue>false</defaultValue>
        <externalDeveloperName>Notify_Support__c</externalDeveloperName>
        <label>Notify Support</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Transaction_c__c</fullName>
        <externalDeveloperName>Order_Transaction__c</externalDeveloperName>
        <label>Order Transaction</label>
        <length>18</length>
        <referenceTo>Order_Transaction_c__x</referenceTo>
        <relationshipName>Errors</relationshipName>
        <type>ExternalLookup</type>
    </fields>
    <fields>
        <fullName>Order_c__c</fullName>
        <externalDeveloperName>Order__c</externalDeveloperName>
        <label>Order</label>
        <length>18</length>
        <referenceTo>Order__x</referenceTo>
        <relationshipName>Errors</relationshipName>
        <type>ExternalLookup</type>
    </fields>
    <fields>
        <fullName>Person_Account_c__c</fullName>
        <externalDeveloperName>Person_Account__c</externalDeveloperName>
        <label>Person Account</label>
        <length>18</length>
        <referenceTo>Account__x</referenceTo>
        <relationshipName>Errors</relationshipName>
        <type>ExternalLookup</type>
    </fields>
    <fields>
        <fullName>RecordId_c__c</fullName>
        <externalDeveloperName>RecordId__c</externalDeveloperName>
        <label>RecordId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Payload_c__c</fullName>
        <externalDeveloperName>Request_Payload__c</externalDeveloperName>
        <label>Request Payload</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Payload_c__c</fullName>
        <externalDeveloperName>Response_Payload__c</externalDeveloperName>
        <label>Response Payload</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Severity_c__c</fullName>
        <externalDeveloperName>Severity__c</externalDeveloperName>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Critical</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StackTrace_c__c</fullName>
        <externalDeveloperName>StackTrace__c</externalDeveloperName>
        <label>StackTrace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Support_Notification_Date_c__c</fullName>
        <externalDeveloperName>Support_Notification_Date__c</externalDeveloperName>
        <label>Support Notification Date</label>
        <type>DateTime</type>
    </fields>
    <label>Error Ext</label>
    <pluralLabel>Errors Ext</pluralLabel>
</CustomObject>

classes/B2B_Util.cls
/****************************************************************************************************************
Name: 			B2B_Util
Purpose: 		This class is to provide Tax from Vertex API.
Date: 			28/01/2021
Created By: 	Soumya Sahoo
******************************************************************************************************************
MODIFICATIONS – 	Date 		|	Dev Name		|	Method		|	User Story
******************************************************************************************************************
22/05/2022	|	Soumya Sahoo	|				    |	Error handling changes- JIRA- 8617
******************************************************************************************************************/
public class B2B_Util{
   
    // This method will generate unique UI which is required in request header.
    public static String createGui() {
        String kHexChars = '0123456789abcdef';
        String returnValue = '';
        Integer nextByte = 0;

        for (Integer i=0; i<16; i++) {

            if (i==4 || i==6 || i==8 || i==10) 
                returnValue += '-';

            nextByte = (Math.round(Math.random() * 255)-128) & 255;

            if (i==6) {
                nextByte = nextByte & 15;
                nextByte = nextByte | (4 << 4);
            }

            if (i==8) {
                nextByte = nextByte & 63;
                nextByte = nextByte | 128;
            }

            returnValue += getCharAtIndex(kHexChars, nextByte >> 4);
            returnValue += getCharAtIndex(kHexChars, nextByte & 15);
        }

        return returnValue;
    }

    // This method is internally called from createGui()
    public static String getCharAtIndex(String str, Integer index) {
        if (str == null) return null;
        if (str.length() <= 0) return str; 
        if (index == str.length()) return null;  
        return str.substring(index, index+1);
    }

    public static Boolean isSalesforceID(String value){
        try{ //Added by shalini for issue HDMP-6372
            if(Pattern.compile('[a-zA-Z0-9]{15}|[a-zA-Z0-9]{18}').matcher(value).matches()){
                return true;
            } else{
                return false;
            }
           
        }catch(Exception ex){
            return false;
        }
    }
    public static Long fetchCurrentTime(){
        Long beforeAPI = DateTime.now().getTime();
        return beforeAPI;
    }
    
    public static Long calInMilliSeconds(Long beforeApi, Long afterAPI){
        Long timeDuration =(afterAPI-beforeApi);
        return timeDuration;
    }
    // Below method utilize to create record over error object
    public static void createErrorRecord(String errorName,String orderreturnId,String accountId,String personAccountId, String cartId,String className, String errorMessage, String errorType, String lineNumber,String methodName,Boolean notifySupport,String OrderId,String recordid,String stackTrace,Long duration,String severity,String requestPayload,String responsePayload){
        try{
            Error_c__x errorRecord  =  new Error_c__x();
            List<Error_c__x> errorRecToInsertList  =  new List<Error_c__x>();
            errorRecord.Name__c  =  errorName;
            if(String.isNotBlank(orderreturnId))
                errorRecord.Order_Transaction_c__c = orderreturnId;
            if(String.isNotBlank(accountId))
                errorRecord.Account_c__c  =  accountId;
            if(String.isNotBlank(personAccountId))
                errorRecord.Person_Account_c__c = personAccountId;
            if(String.isNotBlank(cartId))
                errorRecord.Cart_c__c	 = cartId;
            errorRecord.ClassName_c__c  = className;
           	if(String.isNotBlank(OrderId))
                errorRecord.Order_c__c=OrderId;
            errorRecord.Duration_c__c  = duration;
            errorRecord.Error_Message_c__c = errorMessage;
            errorRecord.Error_Type_c__c = errorType;
            if(String.isNotBlank(lineNumber))
                errorRecord.Line_Number_c__c = Integer.valueOf(lineNumber);
            errorRecord.MethodName_c__c = methodName;
            errorRecord.Notify_Support_c__c = notifySupport;
            errorRecord.Support_Notification_Date_c__c = system.now();
            if(String.isNotBlank(orderId))
                errorRecord.Order_c__c = orderId;
            errorRecord.RecordId_c__c = recordid;
            errorRecord.Severity_c__c = Severity;
            errorRecord.StackTrace_c__c = stackTrace;
            errorRecord.Request_Payload_c__c = requestPayload;
            errorRecord.Response_Payload_c__c = responsePayload;
            errorRecToInsertList.add(errorRecord);
            if(!errorRecToInsertList.isEmpty()){
                if(!Test.isRunningTest()){
                    Database.insertImmediate(errorRecToInsertList);
                }                
            }
                
        }catch(Exception e) {
            System.debug(e.getMessage());
        }
       
    }
    
}