objects/Helms_Matchback_Exract__mdt.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Helms Matchback Extract</label>
    <pluralLabel>Helms Matchback Extract</pluralLabel>
</CustomObject>

objects/Matchback_New__c.object
<CustomObject>
    <fields>
        <fullName>Matchback_Date__c</fullName>
        <label>Retail Sales Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Matchback_Status__c</fullName>
        <label>Matchback Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Matched to Dealer</fullName>
                </value>
                <value>
                    <fullName>Matched to other Dealer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Matchback New</relationshipLabel>
        <relationshipName>Matchback_New</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>RDR_Sales__c</fullName>
        <label>RDR Sales</label>
        <referenceTo>RDR_Sales__c</referenceTo>
        <relationshipLabel>Matchback New</relationshipLabel>
        <relationshipName>Matchback_New</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Matchback New</label>
    <nameField>
        <displayFormat>Matchback - {0000000}</displayFormat>
        <label>Matchback New Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matchback New</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Address_TXT__c</fullName>
        <formula>Apartment_TXT__c&amp;&quot;,&quot; &amp;Street_TXT__c&amp;&quot;,&quot;
&amp;City_TXT__c&amp;&quot;,&quot; &amp;State_TXT__c &amp;&quot;,&quot; &amp;ZipCode_TXT__c &amp;&quot;,&quot;
&amp;Country_TXT__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City_TXT__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactKey_TXT__c</fullName>
        <label>Contact Key</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name_TXT__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name_TXT__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Matchback_Date__c</fullName>
        <label>Retail Sales Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Number_NM__c</fullName>
        <label>Vin Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sale_Confirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Sale has been registered with Honda.</inlineHelpText>
        <label>Registration Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_TXT__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_TXT__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Updated_by_New_MB__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Updated by New MB</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ValidEmail_FLG__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valid Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ZipCode_TXT__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RDR_Sales__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Address_ZIP_Code_TXT__c</fullName>
        <label>Customer Address ZIP Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Cellphone_Number__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-5532 Story name.
Description: This is to store the CELL_PHONE
Source System: Coming from Integration from Mainframe/SAP.
Integration: NA.
Data Transformation: N/A.</description>
        <label>Customer Cellphone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Customer_City_TXT__c</fullName>
        <label>Customer City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_First_Name_NUM__c</fullName>
        <label>Customer First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Home_Phone_Number__c</fullName>
        <label>Customer Home Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Customer_Last_Name_NM__c</fullName>
        <label>Customer Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Street_Address_TXT__c</fullName>
        <label>Customer Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Number_NUM__c</fullName>
        <label>Dealer Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_id_TXT__c</fullName>
        <label>Email id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Driver_Cellphone_Number__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-5532 Story name.
Description: This is to store the Driver Cell Phone
Source System: Coming from Integration from Mainframe/SAP.
Integration: NA.
Data Transformation: N/A.</description>
        <label>Primary Driver Cellphone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Primary_Driver_Email__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-5532 Story name.
Description: This is to store the Driver Email
Source System: Coming from Integration from Mainframe/SAP.
Integration: NA.
Data Transformation: N/A.</description>
        <label>Primary Driver Email</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Driver_Home_Phone_Number__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-5532 Story name.
Description: This is to store the Driver Home Phone
Source System: Coming from Integration from Mainframe/SAP.
Integration: NA.
Data Transformation: N/A.</description>
        <label>Primary Driver Home Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Primary_Driver_Phone_Number__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-5532 Story name.
Description: This is to store the Driver Phone
Source System: Coming from Integration from Mainframe/SAP.
Integration: NA.
Data Transformation: N/A.</description>
        <label>Primary Driver Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sales_Date_DT__c</fullName>
        <label>Sales Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Serial_Number_NUM__c</fullName>
        <label>Serial Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Code_CD__c</fullName>
        <label>State Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone_Number_NUM__c</fullName>
        <label>Telephone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Updated_by_New_MB__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Updated by New MB</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vin_TXT__c</fullName>
        <label>Vin</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XPROD_DIV_CD__c</fullName>
        <label>XPROD-DIV-CD</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isProcessed</label>
        <type>Checkbox</type>
    </fields>
    <label>RDR Sales</label>
    <nameField>
        <displayFormat>RDR Sales - {00000000}</displayFormat>
        <label>RDR Sales</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RDR Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

classes/HELMSMatchbackBatch.cls
global class HELMSMatchbackBatch implements Database.Batchable<sObject>, Database.Stateful {
	
        global Database.QueryLocator start(Database.BatchableContext BC) { 
        Helms_Matchback_Exract__mdt matchbackqry = Helms_Matchback_Exract__mdt.getInstance('Helms_Matchback_Extract');
    	String query = 'SELECT Id, Name, Dealer_Number_NUM__c, Customer_First_Name_NUM__c, Customer_Last_Name_NM__c, isProcessed__c, XPROD_DIV_CD__c, Telephone_Number_NUM__c,Customer_Home_Phone_Number__c,Primary_Driver_Home_Phone_Number__c,Primary_Driver_Phone_Number__c,Customer_Cellphone_Number__c,Primary_Driver_Cellphone_Number__c, Email_id_TXT__c,Primary_Driver_Email__c, Serial_Number_NUM__c,Vin_TXT__c, Sales_Date_DT__c,Customer_Street_Address_TXT__c,Customer_Address_ZIP_Code_TXT__c,Customer_City_TXT__c,State_Code_CD__c,Updated_by_New_MB__c FROM RDR_Sales__c where Updated_by_New_MB__c=false';
           if(matchbackqry.Start_Date__c!=null){
                query = query+' and CreatedDate>='+matchbackqry.Start_Date__c;
            }
            if(matchbackqry.End_Date__c!=null){
                query = query+' and CreatedDate<='+matchbackqry.End_Date__c;
            }
            //query = query + ' LIMIT 5';
            system.debug('query:'+query);
        return Database.getQueryLocator(query);    
    } 

    global void execute(Database.BatchableContext BC, List<RDR_Sales__c> rdrList) {
        set<String> firstName = new set<String>();
        set<String> lastName = new set<String>();
        set<String> email = new set<String>();
        set<String> phone = new set<String>();
        set<String> dealerNo = new set<String>();
        set<String> division = new set<String>();
        set<string> zipcodes = new set<string>();
        set<string> serialnos = new set<string>();
        set<string> vinNumbers = new set<string>();
        Set<Id> processedOpportunityIds = new Set<Id>(); 
        set<Opportunity> updateoppList = new set<Opportunity>();
        set<RDR_Sales__c> rdrset = new set<RDR_Sales__c>();
             
        for (RDR_Sales__c rdr : rdrList) {
            if (rdr.Customer_First_Name_NUM__c != null) {
                firstName.add(rdr.Customer_First_Name_NUM__c);
            }
            if (rdr.Customer_Last_Name_NM__c != null) {
                lastName.add(rdr.Customer_Last_Name_NM__c);
            }
            if (rdr.Email_id_TXT__c != null) {
                email.add(rdr.Email_id_TXT__c);
            }
            if (rdr.Primary_Driver_Email__c != null) {
                email.add(rdr.Primary_Driver_Email__c);
            }
            if (rdr.Telephone_Number_NUM__c != null) {
                phone.add(rdr.Telephone_Number_NUM__c);
            }
            if (rdr.Customer_Home_Phone_Number__c!= null) {
                phone.add(rdr.Customer_Home_Phone_Number__c);
            }
            if (rdr.Primary_Driver_Home_Phone_Number__c!= null) {
                phone.add(rdr.Primary_Driver_Home_Phone_Number__c);
            }
            if (rdr.Primary_Driver_Phone_Number__c!= null) {
                phone.add(rdr.Primary_Driver_Phone_Number__c);
            }
            if (rdr.Customer_Cellphone_Number__c!= null) {
                phone.add(rdr.Customer_Cellphone_Number__c);
            }
            if (rdr.Primary_Driver_Cellphone_Number__c!= null) {
                phone.add(rdr.Primary_Driver_Cellphone_Number__c);
            }
            if (rdr.Dealer_Number_NUM__c != null) {
                dealerNo.add(rdr.Dealer_Number_NUM__c);
            }
            if (rdr.XPROD_DIV_CD__c != null) {
                division.add(rdr.XPROD_DIV_CD__c);
            }
            if(rdr.Customer_Address_ZIP_Code_TXT__c != null){
                zipcodes.add(rdr.Customer_Address_ZIP_Code_TXT__c );
            }
            /*if(rdr.Serial_Number_NUM__c != null){
                serialnos.add(rdr.Serial_Number_NUM__c );
            }
            if(rdr.Vin_TXT__c != null){
                vinNumbers.add(rdr.Vin_TXT__c );
            }*/
        }

        Helms_Matchback_Exract__mdt matchbackqry = Helms_Matchback_Exract__mdt.getInstance('Helms_Matchback_Extract');
        
        Datetime startDate;
        if(matchbackqry.Start_Date__c!=null){
           startDate = Date.valueOf(matchbackqry.Start_Date__c).addDays(-120);
        }
        
        List<Opportunity> oppBackList = new List<Opportunity>();
        
        if(matchbackqry.Start_Date__c!=null && matchbackqry.End_Date__c!=null){
             oppBackList = [SELECT Id, Name, First_Name_TXT__c, Last_Name_TXT__c, Phone__c, Email__c, ZipCode_TXT__c, Division_CD__c, Sale_Confirmation__c, Matchback_Date__c, PreferredDealerNumber_NUM__c, Address_TXT__c, Number_NM__c, Serial_Number__c, CreatedDate, ContactKey_TXT__c, State_TXT__c, City_TXT__c, Street_TXT__c, ValidEmail_FLG__c, Updated_by_New_MB__c
                                  FROM Opportunity
                                  WHERE ((Email__c IN :email AND Division_CD__c IN :division)
                                         OR ((First_Name_TXT__c IN :firstName OR Last_Name_TXT__c IN :lastName) 
                                             AND Division_CD__c IN :division 
                                             AND (Phone__c IN :phone OR ZipCode_TXT__c IN :zipcodes)))
                                  AND Updated_by_New_MB__c != TRUE AND CreatedDate>= :startDate AND CreatedDate<= :Date.valueOf(matchbackqry.End_Date__c)];

        }
        else{
             oppBackList = [SELECT Id, Name, First_Name_TXT__c, Last_Name_TXT__c, Phone__c, Email__c, ZipCode_TXT__c, Division_CD__c, Sale_Confirmation__c, Matchback_Date__c, PreferredDealerNumber_NUM__c, Address_TXT__c, Number_NM__c, Serial_Number__c, CreatedDate, ContactKey_TXT__c, State_TXT__c, City_TXT__c, Street_TXT__c, ValidEmail_FLG__c, Updated_by_New_MB__c
                                  FROM Opportunity
                                  WHERE ((Email__c IN :email AND Division_CD__c IN :division)
                                         OR ((First_Name_TXT__c IN :firstName OR Last_Name_TXT__c IN :lastName) 
                                             AND Division_CD__c IN :division 
                                             AND (Phone__c IN :phone OR ZipCode_TXT__c IN :zipcodes)))
                                  AND Updated_by_New_MB__c != TRUE];
        }
        
        List<Matchback_New__c> matchBackList = new List<Matchback_New__c>();
        
        for (RDR_Sales__c objrds : rdrList) {
            for (Opportunity opp : oppBackList) {
                if(
				(opp.ValidEmail_FLG__c != False && opp.Email__c != null && (objrds.Email_id_TXT__c == opp.Email__c || objrds.Primary_Driver_Email__c == opp.Email__c) && objrds.XPROD_DIV_CD__c == opp.Division_CD__c)
	||
	(
	((objrds.Customer_First_Name_NUM__c != null && objrds.Customer_First_Name_NUM__c.tolowercase() == opp.First_Name_TXT__c.tolowercase()) || (objrds.Customer_Last_Name_NM__c != null && objrds.Customer_Last_Name_NM__c.tolowercase() == opp.Last_Name_TXT__c.tolowercase())) 
	&& 
	objrds.XPROD_DIV_CD__c == opp.Division_CD__c	
	&& 
	(
	(opp.Phone__c != null  && opp.Phone__c.length() >= 10 && (objrds.Telephone_Number_NUM__c == opp.Phone__c || objrds.Customer_Home_Phone_Number__c == opp.Phone__c || objrds.Primary_Driver_Home_Phone_Number__c == opp.Phone__c || objrds.Primary_Driver_Phone_Number__c == opp.Phone__c || objrds.Customer_Cellphone_Number__c == opp.Phone__c || objrds.Primary_Driver_Cellphone_Number__c == opp.Phone__c)) 
	||  
	(opp.Street_TXT__c != null && opp.ZipCode_TXT__c != null && objrds.Customer_Street_Address_TXT__c == opp.Street_TXT__c && objrds.Customer_Address_ZIP_Code_TXT__c == opp.ZipCode_TXT__c)
	)
 )                
) 
                {     
                    if (opp.PreferredDealerNumber_NUM__c == objrds.Dealer_Number_NUM__c && opp.Updated_by_New_MB__c != true && objrds.Updated_by_New_MB__c != true && !processedOpportunityIds.contains(opp.Id)) { 
                        Matchback_New__c mB = new Matchback_New__c();
                        mB.Opportunity__c = opp.Id;
                        mB.RDR_Sales__c = objrds.Id;
                        mB.Matchback_Date__c = objrds.Sales_Date_DT__c;
                        mB.Matchback_Status__c = 'Matched to Dealer';
                        matchBackList.add(mB);
                        processedOpportunityIds.add(opp.Id); 
                        opp.Updated_by_New_MB__c = true;
                        //opp.Sale_Confirmation__c = true;
                        opp.Matchback_Date__c = objrds.Sales_Date_DT__c;
                        updateoppList.add(opp);
                    }     
                    else if (opp.PreferredDealerNumber_NUM__c != objrds.Dealer_Number_NUM__c && objrds.Updated_by_New_MB__c != true && !processedOpportunityIds.contains(opp.Id)) { 
                        Matchback_New__c mB = new Matchback_New__c();
                        mB.Opportunity__c = opp.Id;
                        mB.RDR_Sales__c = objrds.Id;
                        opp.Matchback_Date__c = objrds.Sales_Date_DT__c;
                        mB.Matchback_Date__c = objrds.Sales_Date_DT__c;
                        mB.Matchback_Status__c = 'Matched to other Dealer';
                        matchBackList.add(mB);
                        processedOpportunityIds.add(opp.Id); 
                        updateoppList.add(opp);
                    } 
                } 
            }
            objrds.Updated_by_New_MB__c = true;
            rdrset.add(objrds);    
        }
               
        if (!matchBackList.isEmpty()) {
            insert matchBackList;
        }
        
        if (!rdrset.isEmpty()) {
            List<RDR_Sales__c> rdrlist1 = new List<RDR_Sales__c>(rdrset);
            update rdrlist1;
        }

        if (!updateoppList.isEmpty()) {
            List<Opportunity> updateoppList1 = new List<Opportunity>(updateoppList);
            Database.SaveResult[] results = Database.update(updateoppList1, false);
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        System.debug('Batch is Processed Successfully');
    }
}