objects/HELMS_LeadConversionFieldsToOpportunity__mdt.object
<CustomObject>
    <description>To track the Lead fields that needs to be mapped with new Opportunity when created.</description>
    <fields>
        <fullName>LeadFieldAPIName__c</fullName>
        <label>LeadFieldAPIName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>HELMS LeadConversionFieldsToOpportunity</label>
    <pluralLabel>HELMS LeadConversionFields</pluralLabel>
</CustomObject>

classes/HELMS_OpportunityCreationLeadBatchTest.cls
@isTest
public class HELMS_OpportunityCreationLeadBatchTest {
    @isTest static void exc(){
      string Label;
       List<HELMS_LeadConversionFieldsToOpportunity__mdt>  accrec = new List<HELMS_LeadConversionFieldsToOpportunity__mdt>();
        HELMS_LeadConversionFieldsToOpportunity__mdt a1 = new HELMS_LeadConversionFieldsToOpportunity__mdt();
        a1.LeadFieldAPIName__c='ModelTrim';
        accrec.add(a1);
       Test.startTest();
     //   insert a1;
        HELMS_OpportunityCreationLeadBatch  mybatch = new HELMS_OpportunityCreationLeadBatch();
        Database.executeBatch(mybatch);
        Test.stopTest(); 
    }
}