objects/HELMS_Dealer_Broadcast_Message__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Custom Settings is to display broadcast message for all dealer users.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>Expires on</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Starts On</label>
        <type>DateTime</type>
    </fields>
    <label>HELMS Dealer Broadcast Message</label>
</CustomObject>

classes/HELMSDealerBroadcastMessagectrlTest.cls
@isTest
public class HELMSDealerBroadcastMessagectrlTest 
{
   @isTest static void testHELMSDealerBroadcastMessagectrl()
   {
        List<HELMS_Dealer_Broadcast_Message__c> fetchMeta = new List<HELMS_Dealer_Broadcast_Message__c>();
        HELMS_Dealer_Broadcast_Message__c dMessage = new HELMS_Dealer_Broadcast_Message__c();
        dMessage.Name = 'Dealer BroadCase Message';
        dMessage.Message__c = 'ToDisplayDealerBroadCastMessage';
        dMessage.Start_Date__c = Date.newInstance(2022, 04, 26);
        dMessage.End_Date__c = Date.newInstance(2023, 04, 30);
        Test.startTest();
        insert dMessage;
        Test.stopTest();
        fetchMeta.add(dMessage);
        HELMSDealerBroadcastMessagectrl.fetchMetaListLwc();
        System.assertEquals(dMessage.Name, 'Dealer BroadCase Message');
    }     

    
}