objects/Lead_Dealer_Acknowledgement_ADF__e.object
<CustomObject>
    <fields>
        <fullName>Oppotunity_SF_ID__c</fullName>
        <label>Oppotunity SF ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Routing_Error__c</fullName>
        <label>Routing Error</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <label>Status Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Lead Dealer Acknowledgement ADF</label>
    <pluralLabel>Lead Dealer Acknowledgement ADF</pluralLabel>
</CustomObject>

classes/Lead_Dealer_AcknowledgementPETest.cls
@isTest
//Test Class for Lead Dealer Acknowledgement Trigger
public class Lead_Dealer_AcknowledgementPETest {
	@isTest public static void testschedule() { 
        List<Lead_Dealer_Acknowledgement_ADF__e> eve = new List<Lead_Dealer_Acknowledgement_ADF__e>();
     	Lead_Dealer_Acknowledgement_ADF__e testObj = new Lead_Dealer_Acknowledgement_ADF__e();
        testObj.Oppotunity_SF_ID__c = 'test';
        testObj.Routing_Error__c = 'test';
        testObj.Status_Code__c = 'test';
        eve.add(testObj);
        Test.startTest();
        EventBus.publish(eve);
        Test.stopTest();
        system.assertEquals('test', testObj.Oppotunity_SF_ID__c);
    }
}