objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_ECRM_Update_Done__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is ECRM Update Done</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_HELMS_Contact_Key__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked true if the Contact Key is made in HELMS instead of being received from ECRM.</description>
        <label>Is HELMS Contact Key</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Make_TXT__c</fullName>
        <label>Make</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Model_TXT__c</fullName>
        <label>Model</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>Subdivision</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division_CD__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year_YR__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Logs__c.object
<CustomObject>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>130768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Logs</label>
    <nameField>
        <label>Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/HELMSAdditionalDataScoringServiceTest2.cls
@isTest
private class HELMSAdditionalDataScoringServiceTest2 {
    
    @isTest static void POSTCalloutTest(){
       Test.startTest();
       	
       Test.setMock(HttpCalloutMock.class, new HELMSAdditionalDataMock2());
       Lead l = new Lead();
        
       l.FirstName = 'Francisco';
       l.LastName = 'Ramos';
       l.Email = 'terihonda@outlook.com';
       l.Phone = '(707) 570-8801';
       l.Country = 'US';
       l.State = 'MD';
       l.City = 'Waldorf';
       l.Status = 'New';
       l.Division_CD__c = 'A';
       l.SubDiv_TXT__c = 'Honda';
       l.Make_TXT__c = 'Honda';
       l.Model_TXT__c = 'Civic Type R';
       l.Year_YR__c = '2020';
       insert l;
       Set<id> leadIds = new Set<Id>();
       List<Lead> tlsBefore = [SELECT ID, Is_ECRM_Update_Done__c, FirstName FROM Lead];
       leadIds.add(tlsBefore[0].Id);
       HELMSAdditionalDataScoringService.GetAdditionaldata(leadIds);
        Test.stopTest();
        
        List<Lead> tlsAfter = [SELECT ID, Is_ECRM_Update_Done__c FROM Lead];
        lIST<Logs__c> error = [SELECT ID , 	Error_Message__c FROM Logs__c];
        //if(!error.isEmpty())
        //System.debug(error[0].Error_Message__c);
	        
       //System.assertEquals(tlsAfter[0].Is_ECRM_Update_Done__c, true);
    }
    
    @isTest static void POSTCalloutTest2(){
        Test.startTest();
       	
       Test.setMock(HttpCalloutMock.class, new HELMSAdditionalDataMock2());
       Lead l = new Lead();
        
       l.FirstName = 'Francisco';
       l.LastName = 'Ramos';
       l.Email = 'terihonda@outlook.com';
       l.Phone = '(707) 570-8801';
       l.Country = 'US';
       l.State = 'MD';
       l.City = 'Waldorf';
       l.Status = 'New';
       l.Division_CD__c = 'A';
       l.SubDiv_TXT__c = 'Honda';
       l.Make_TXT__c = 'Honda';
       l.Model_TXT__c = 'Civic Type R';
       l.Year_YR__c = '2020';
       l.Is_HELMS_Contact_Key__c = true;
       insert l;
        
       Set<id> leadIds = new Set<Id>();
       List<Lead> tlsBefore = [SELECT ID, Is_ECRM_Update_Done__c, FirstName FROM Lead];
       leadIds.add(tlsBefore[0].Id);
       HELMSAdditionalDataScoringService.GetAdditionaldata(leadIds);
        Test.stopTest();
        
        List<Lead> tlsAfter = [SELECT ID, Is_ECRM_Update_Done__c FROM Lead];
        lIST<Logs__c> error = [SELECT ID , 	Error_Message__c FROM Logs__c];
        //if(!error.isEmpty())
        //System.debug(error[0].Error_Message__c);
    }

}