objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Error_Details_Urban_Science__c</fullName>
        <label>Error Details Urban Science</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Lead_Reference_Number__c</fullName>
        <label>External Lead Reference Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Duplicate_Similar_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Duplicate Similar Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Third_Party_Duplicate_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Third Party Duplicate Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sent_to_Urban_Science_Status__c</fullName>
        <label>Sent to Urban Science Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusReason_TXT__c</fullName>
        <defaultValue>(&quot;Pending&quot;)</defaultValue>
        <label>Status Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Inactivity</fullName>
                </value>
                <value>
                    <fullName>Duplicate Merged</fullName>
                </value>
                <value>
                    <fullName>Validation Email</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Lead Provider error</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Opt Out</fullName>
                </value>
                <value>
                    <fullName>Duplicate Similar</fullName>
                </value>
                <value>
                    <fullName>Matched Leads</fullName>
                </value>
                <value>
                    <fullName>Related Opportunity closed</fullName>
                </value>
                <value>
                    <fullName>Unable to assign Dealer</fullName>
                </value>
                <value>
                    <fullName>Name/Address/Email Error</fullName>
                </value>
                <value>
                    <fullName>Name/Address/Email Cache</fullName>
                </value>
                <value>
                    <fullName>Third Party Duplicate</fullName>
                </value>
                <value>
                    <fullName>Waiting for the routing window to start</fullName>
                </value>
                <value>
                    <fullName>Routing Window Expired</fullName>
                </value>
                <value>
                    <fullName>Concierge</fullName>
                </value>
                <value>
                    <fullName>Lead Enrichment call error</fullName>
                </value>
                <value>
                    <fullName>Dealer Assignment call failed</fullName>
                </value>
                <value>
                    <fullName>Journey Completed</fullName>
                </value>
                <value>
                    <fullName>New Opportunity Created</fullName>
                </value>
                <value>
                    <fullName>Journey incomplete, no response</fullName>
                </value>
                <value>
                    <fullName>Concierge Completed</fullName>
                </value>
                <value>
                    <fullName>Invalid email and phone</fullName>
                </value>
                <value>
                    <fullName>Customer is not Interested in the product</fullName>
                </value>
                <value>
                    <fullName>In nurturing journey</fullName>
                </value>
                <value>
                    <fullName>Waiting for Deal Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Logs__c.object
<CustomObject>
    <fields>
        <fullName>Error_Line_Number__c</fullName>
        <label>Error Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>130768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Trigger_or_Class_Name__c</fullName>
        <label>Trigger or Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Logs</label>
    <nameField>
        <label>Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sending_Lead_Status_To_Urban_Science__e.object
<CustomObject>
    <fields>
        <fullName>External_Reference_ID__c</fullName>
        <label>External Reference ID</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reason_For_Rejection__c</fullName>
        <label>Reason For Rejection</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Sending Lead Status To Urban Science</label>
    <pluralLabel>Sending Lead Status To Urban Science</pluralLabel>
</CustomObject>

classes/HELMSLeadStatusToUrbanScience.cls
public with sharing class HELMSLeadStatusToUrbanScience {
    @testVisible public static List<Sending_Lead_Status_To_Urban_Science__e> listUrbanEvents = new List<Sending_Lead_Status_To_Urban_Science__e>();
    public static void sendLeadStatus(List<Lead> listLead){
        //List<Sending_Lead_Status_To_Urban_Science__e> listUrbanEvents = new List<Sending_Lead_Status_To_Urban_Science__e>();
        for(Lead l : listLead){
            Sending_Lead_Status_To_Urban_Science__e ubEvent = new Sending_Lead_Status_To_Urban_Science__e();
            //ubEvent.Reason_For_Rejection__c = l.StatusReason_TXT__c;
            
            if(l.Is_Duplicate_Similar_Lead__c == true){
                ubEvent.Reason_For_Rejection__c =  HELMSConstants.Dupsim;
            }else if(l.Is_Third_Party_Duplicate_Lead__c == true){
                ubEvent.Reason_For_Rejection__c =  HELMSConstants.TPD;
            }
            ubEvent.External_Reference_ID__c = l.External_Lead_Reference_Number__c;
            //system.debug ('==============>'+ubEvent.Reason_For_Rejection__c);
            //system.debug ('==============>'+ubEvent.External_Reference_ID__c);
      //      ubEvent.Acknowledge_Duplicate_Error_Details__c = l.Sent_to_Urban_Science_Status__c;
     //       ubEvent.Acknowledge_Duplicate_Rejection_Status__c = l.Error_Details_Urban_Science__c;
            listUrbanEvents.add(ubEvent);
        }
        try{
            If(listUrbanEvents.Size() > 0){
                List<Database.SaveResult> results = EventBus.publish(listUrbanEvents);
            }  
        }Catch(Exception ex){           
            Logs__c  l =new Logs__c (name='HELMSLeadStatusToUrbanScience- Trigger Handler',Trigger_or_Class_Name__c='HELMSLeadStatusToUrbanScience', Error_Message__c =ex.getMessage(), Error_Line_Number__c =Integer.valueOf(string.valueof(ex.getLineNumber() )) );
            insert l;
        }    
    }
}