objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name_TXT__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name_TXT__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityStatus_TXT__c</fullName>
        <label>Opportunity Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned/Routed to Dealer</fullName>
                </value>
                <value>
                    <fullName>Auto-response sent</fullName>
                </value>
                <value>
                    <fullName>Lead Opened</fullName>
                </value>
                <value>
                    <fullName>Lead Received</fullName>
                </value>
                <value>
                    <fullName>Customer phoned (Inbound phone)</fullName>
                </value>
                <value>
                    <fullName>Customer emailed (Inbound email)</fullName>
                </value>
                <value>
                    <fullName>Salesperson responded by Email</fullName>
                </value>
                <value>
                    <fullName>Salesperson responded by Phone</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson responded by email</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson responded by Phone</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson request another appointment by email</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson request another appointment by phone</fullName>
                </value>
                <value>
                    <fullName>Credit Application</fullName>
                </value>
                <value>
                    <fullName>Credit Application (3rd party)</fullName>
                </value>
                <value>
                    <fullName>Trade-In Appraisal</fullName>
                </value>
                <value>
                    <fullName>Broadcast Email</fullName>
                </value>
                <value>
                    <fullName>Made Appointment</fullName>
                </value>
                <value>
                    <fullName>Demoed/Test Drove</fullName>
                </value>
                <value>
                    <fullName>Boat/Outboard Sales Presentation</fullName>
                </value>
                <value>
                    <fullName>Appointment Didn’t Show</fullName>
                </value>
                <value>
                    <fullName>Appointment Showed</fullName>
                </value>
                <value>
                    <fullName>Offer to Purchase</fullName>
                </value>
                <value>
                    <fullName>Model in Stock</fullName>
                </value>
                <value>
                    <fullName>Model not in Stock</fullName>
                </value>
                <value>
                    <fullName>Model on back order</fullName>
                </value>
                <value>
                    <fullName>Credit Denied</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson marked sold</fullName>
                </value>
                <value>
                    <fullName>Salesperson marked vehicle sold</fullName>
                </value>
                <value>
                    <fullName>Lost Sales</fullName>
                </value>
                <value>
                    <fullName>Any additional vehicle sold info (delivered, punched, etc.)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_SF_ID__c</fullName>
        <externalId>true</externalId>
        <label>Opportunity_SF_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Level_Agreement_TXT__c</fullName>
        <defaultValue>&quot;No Escalation&quot;</defaultValue>
        <inlineHelpText>This shows how high of an escalation was done for this opportunity. The highest level is Level 3 and that escalation goes to upper management.</inlineHelpText>
        <label>Service Level Agreement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Escalation</fullName>
                </value>
                <value>
                    <fullName>Level 1</fullName>
                </value>
                <value>
                    <fullName>Level 2</fullName>
                </value>
                <value>
                    <fullName>Level 3</fullName>
                </value>
                <value>
                    <fullName>Level 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Updated_by_New_MB__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Updated by New MB</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ZipCode_TXT__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Honda</fullName>
        <active>true</active>
        <businessProcess>HELMS Sales Process</businessProcess>
        <description>Used by the Honda Team</description>
        <label>Honda Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Routing_Dealer_CRM_Disposition__c.object
<CustomObject>
    <fields>
        <fullName>Arrival_Time_DT_c__c</fullName>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Auto_Response__c</fullName>
        <label>Auto Response</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Status__c</fullName>
        <label>Current Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HELMS_Opportunity_External_Key__c</fullName>
        <label>HELMS Opportunity External Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Processed_Job__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Processed Job</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Response_Time__c</fullName>
        <label>Response Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>The_Last_Event__c</fullName>
        <label>The Last Event</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Routing Dealer CRM Disposition</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Routing Dealer CRM Disposition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routing Dealer CRM Dispositions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

classes/HELMSOpportunityRoutingDispBatchTest.cls
@isTest 
public class HELMSOpportunityRoutingDispBatchTest
{
   @isTest static void testRoutingDispositionMethod()
    {        
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        List<Opportunity> listOpp = new List<Opportunity>();
       
        Id hondaRecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Honda Opportunity').getRecordTypeId();
        
        Opportunity oppty = new Opportunity(Name='TestLavanya1 TestGrandhi1',First_Name_TXT__c = 'TestLavanya1',Last_Name_TXT__c = 'TestGrandhi1',
        Stagename='Acknowledged',OpportunityStatus_TXT__c = 'Auto-response sent',Email__c='testLavanya@gmail.com',ZipCode_TXT__c='12345',
        Phone__c='7780190896',Updated_by_New_MB__c=false,RecordTypeId=hondaRecTypeId,Division_CD__c='A',PreferredDealerNumber_NUM__c='222276',
        CreatedDate = System.today()-5,CloseDate = System.today()+10,Service_Level_Agreement_TXT__c='Level 2');
       
        
         Opportunity oppty1 = new Opportunity(Name='TestLavanya2 TestGrandhi2',First_Name_TXT__c = 'TestLavanya2',Last_Name_TXT__c = 'TestGrandhi1',
        Stagename='Acknowledged',OpportunityStatus_TXT__c = 'Lead Opened',Email__c='testLavanya@gmail.com',ZipCode_TXT__c='12345',
        Phone__c='7780190896',Updated_by_New_MB__c=false,RecordTypeId=hondaRecTypeId,Division_CD__c='A',PreferredDealerNumber_NUM__c='222276',
        CreatedDate = System.today()-5,CloseDate = System.today()+10,Service_Level_Agreement_TXT__c='Level 2');
        
        Opportunity oppty2 = new Opportunity(Name='TestLavanya2 TestGrandhi2',First_Name_TXT__c = 'TestLavanya2',Last_Name_TXT__c = 'TestGrandhi1',
        Stagename='Acknowledged',OpportunityStatus_TXT__c = 'Auto-response sent',Email__c='testLavanya@gmail.com',ZipCode_TXT__c='12345',
        Phone__c='7780190896',Updated_by_New_MB__c=false,RecordTypeId=hondaRecTypeId,Division_CD__c='A',PreferredDealerNumber_NUM__c='222276',
        CreatedDate = System.today()-5,CloseDate = System.today()+10,Service_Level_Agreement_TXT__c='Level 2');
        
        Opportunity oppty3 = new Opportunity(Name='TestLavanya2 TestGrandhi2',First_Name_TXT__c = 'TestLavanya2',Last_Name_TXT__c = 'TestGrandhi1',
        Stagename='Acknowledged',OpportunityStatus_TXT__c = 'Auto-response sent',Email__c='testLavanya@gmail.com',ZipCode_TXT__c='12345',
        Phone__c='7780190896',Updated_by_New_MB__c=false,RecordTypeId=hondaRecTypeId,Division_CD__c='A',PreferredDealerNumber_NUM__c='222276',
        CreatedDate = System.today()-5,CloseDate = System.today()+10,Service_Level_Agreement_TXT__c='Level 2');
        
        
         listOpp.add(oppty);
        listOpp.add(oppty1);
         listOpp.add(oppty2);
         listOpp.add(oppty3);
        
        insert listOpp;
        
        for(Opportunity eachOpp:listOpp) {
            eachOpp.Opportunity_SF_ID__c = eachOpp.Id;
        }
        update listOpp;
        
        List<Task> tsk = new List<Task>();
        Task task = new Task(WhatId = Oppty.Id, Subject = 'inbound Call');
            tsk.add(task);
        insert task;
        
       Profile p = [Select Id From Profile Where Name = 'System Administrator'];
        User u = new User(firstname= 'Test',
                          lastname='User',
                          Alias='TUser',
                          email = 'test@test.com',
                          username= 'testWipro@test.com', 
                          profileId= p.id, 
                          emailencodingkey='UTF-8',
                          languagelocalekey='en_US',
                          localesidkey='en_US',
                          timezonesidkey='America/Los_Angeles');
        insert u;    
        
        System.runAs(u){
            List<Routing_Dealer_CRM_Disposition__c> listDealerDisp = new List<Routing_Dealer_CRM_Disposition__c>();
            for(integer i =0 ; i < 4 ; i++){
                Routing_Dealer_CRM_Disposition__c dealerDisp = new Routing_Dealer_CRM_Disposition__c();
                dealerDisp.HELMS_Opportunity_External_Key__c = listOpp[i].Id;
                dealerDisp.Response_Time__c = system.today();
                dealerDisp.The_Last_Event__c = String.Valueof(i+1);
                listDealerDisp.add(dealerDisp); 
            }
            
            insert listDealerDisp;
        }
        
        Test.startTest();

            string query='Select id,Name,Arrival_Time_DT_c__c,Auto_Response__c,Current_Status__c,Is_Processed_Job__c,Response_Time__c, HELMS_Opportunity_External_Key__c, OwnerId,The_Last_Event__c,CreatedDate from Routing_Dealer_CRM_Disposition__c where Is_Processed_Job__c !=true order by CreatedDate asc';
                
            HELMSOpportunityRoutingDispositionBatch  disbatch = new HELMSOpportunityRoutingDispositionBatch(query);
            Id batchId = Database.executeBatch(disbatch ,200);
            system.assertEquals('TestLavanya2 TestGrandhi2', oppty3.Name);
            
        Test.stopTest();
    }
    @IsTest
    public static void testSchedulebatch()
    {
        Test.startTest();
        
        HELMSOpportunityRoutingDispositionBatch disbatch= new HELMSOpportunityRoutingDispositionBatch();
        String sch = '0 0 5 * * ?';
        system.schedule('Test status Check', sch, disbatch);
        Test.stopTest();
    } 
}