objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>StatusReason_TXT__c</fullName>
        <defaultValue>(&quot;Pending&quot;)</defaultValue>
        <label>Status Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Inactivity</fullName>
                </value>
                <value>
                    <fullName>Duplicate Merged</fullName>
                </value>
                <value>
                    <fullName>Validation Email</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Lead Provider error</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Opt Out</fullName>
                </value>
                <value>
                    <fullName>Duplicate Similar</fullName>
                </value>
                <value>
                    <fullName>Matched Leads</fullName>
                </value>
                <value>
                    <fullName>Related Opportunity closed</fullName>
                </value>
                <value>
                    <fullName>Unable to assign Dealer</fullName>
                </value>
                <value>
                    <fullName>Name/Address/Email Error</fullName>
                </value>
                <value>
                    <fullName>Name/Address/Email Cache</fullName>
                </value>
                <value>
                    <fullName>Third Party Duplicate</fullName>
                </value>
                <value>
                    <fullName>Waiting for the routing window to start</fullName>
                </value>
                <value>
                    <fullName>Routing Window Expired</fullName>
                </value>
                <value>
                    <fullName>Concierge</fullName>
                </value>
                <value>
                    <fullName>Lead Enrichment call error</fullName>
                </value>
                <value>
                    <fullName>Dealer Assignment call failed</fullName>
                </value>
                <value>
                    <fullName>Journey Completed</fullName>
                </value>
                <value>
                    <fullName>New Opportunity Created</fullName>
                </value>
                <value>
                    <fullName>Journey incomplete, no response</fullName>
                </value>
                <value>
                    <fullName>Concierge Completed</fullName>
                </value>
                <value>
                    <fullName>Invalid email and phone</fullName>
                </value>
                <value>
                    <fullName>Customer is not Interested in the product</fullName>
                </value>
                <value>
                    <fullName>In nurturing journey</fullName>
                </value>
                <value>
                    <fullName>Waiting for Deal Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead_Expiration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to set the expiration of Leads due to no activity.</description>
    <fields>
        <fullName>A__c</fullName>
        <label>A</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lead Expiration</label>
</CustomObject>

objects/Logs__c.object
<CustomObject>
    <fields>
        <fullName>Error_Line_Number__c</fullName>
        <label>Error Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>130768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Trigger_or_Class_Name__c</fullName>
        <label>Trigger or Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Logs</label>
    <nameField>
        <label>Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

classes/LeadCloseConversionBatch.cls
//Batch Class for Lead Converstion
global class LeadCloseConversionBatch implements Database.Batchable<sObject>,Database.Stateful {
    //Query
    string query ;
    global LeadCloseConversionBatch(){
        
    }
    //Fetching Data
    global LeadCloseConversionBatch(string q){
        
        query = q;
    }
    //Start Method
    global Database.QueryLocator start(Database.BatchableContext bc)
    {   string ledstatus ='Closed - Not Converted';
        //query = 'Select Id,Name,LastModifiedDate,IsConverted,StatusReason_TXT__c,Status,Division_CD__c from Lead where IsConverted=false and Status!=:ledstatus';
        //System.debug('query-----'+query);
        return Database.getQueryLocator(query);
    }
    //Execute Method
    global void execute(Database.BatchableContext bc, List<Lead> leadListRecord)
    {
        //Lead_Expiration__c leadCustomVal = Lead_Expiration__c.getInstance();
        Lead_Expiration__c leadCustomVal = Lead_Expiration__c.getOrgDefaults();
        List<Lead> updatedLeadList = new List<Lead>();
        List<Logs__c> logRecordList = new List<Logs__c>();
        try{
             
            for(Lead ldRec : leadListRecord)
            {
               String leadDivision;
                if(ldRec.Division_CD__c!=null){
                     leadDivision = ldRec.Division_CD__c+'__C';
                  }        
                /* Lead_Expiration__c leadCustomVal = Lead_Expiration__c.getOrgDefaults();
                system.debug(leadCustomVal.A__c); */


                if(leadDivision!=null){
                    
                    //system.debug('Integer.valueOf(leadCustomVal.get(leadDivision))--------'+Integer.valueOf(leadCustomVal.get(leadDivision)));
                    Integer getCustomDivisionVal = Integer.valueOf(leadCustomVal.get(leadDivision));
                    Date lastModifiedDateVal = Date.valueOf(ldRec.LastModifiedDate);
                    Date todayDateVal = Date.valueOf(System.today());
                    Integer daysInBetween = lastModifiedDateVal.daysBetween(todayDateVal);
                    //system.debug('@@ Values of if condition : '+daysInBetween+' '+getCustomDivisionVal);
                    if(daysInBetween>=getCustomDivisionVal)
                    {
                        //System.debug('ldRec---------'+ldRec);
                        Lead ldUpdate = new Lead(Id=ldRec.Id,StatusReason_TXT__c='Inactivity',Status=System.Label.HELMS_Close_Lead_Status_Val);
                        updatedLeadList.add(ldUpdate);
                    }
                }
            }
            if(updatedLeadList.size()>0)
            {
                //System.debug('updatedLeadList---------'+updatedLeadList);
                update updatedLeadList;
            }
        }catch(Exception ex)
        {
            Logs__c logExceptionRecord = new Logs__c(Name='LeadCloseConversionBatch Batch Error',Trigger_or_Class_Name__c='LeadCloseConversionBatch',Error_Message__c = ex.getMessage(),Error_Line_Number__c = Integer.valueOf(ex.getLineNumber()));
            insert logExceptionRecord;
        }
              
        
        
    }
    //Finish Method
    global void finish(Database.BatchableContext bc)
    {
        
    }
    
    
}