objects/Lead.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <label>External IDs</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead_Disposition__e.object
<CustomObject>
    <fields>
        <fullName>ArrivalTime_DT__c</fullName>
        <description>Oppty createddate</description>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>AutoResponse_FLG__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Auto Response</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CurrentStatus_NM__c</fullName>
        <description>based on the Oppty status, map the following values (numeric portion only:

2 - In Process, use this if the oppty stage type = Open (as opposed to Closed/won or Closed/lost)
3 - Sold (if oppty stage type = Closed/won
4 - Inactive (if oppty stage type = Closed/Lost</description>
        <label>Current Status</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Id_TXT__c</fullName>
        <description>This should be the Oppty.Lead External ID field that we originally populated from the LDRA ID during lead creation from ADF. this field should have been mapped from Lead.External ID to the Oppty.Lead External ID during the lead conversion.</description>
        <label>Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastEvent_NM__c</fullName>
        <description>We will need a mapping from the Oppty stage/status combination to on of the following values.  Note that only the numeric portion of the below list is to be populated in the event:
1 - Sale (if oppty stage type changes to Closed/won)
2 - Meeting (oppty stage/status  change: tbd)
3 - Letter (oppty stage/status  change: tbd)</description>
        <label>Last Event</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ResponseTime_DT__c</fullName>
        <description>Date/time (last modified date) of the Oppty based on the status/stage changes as mentioned in the Last Event.</description>
        <label>Response Time</label>
        <type>DateTime</type>
    </fields>
    <label>Lead Disposition</label>
    <pluralLabel>Lead Dispositions</pluralLabel>
</CustomObject>

objects/Lead_Disposition_Last_Event_Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Create a custom setting to map Oppty state and status to one of the below numbers. Only create platform event if a matching entry was fround in the custom setting. 

trigger should fire afterupdate of oppty if status/stage changed

We will need a mapping from the Oppty stage/status combination to on of the following values.  Note that only the numeric portion of the below list is to be populated in the event: SEE LMS-1671
1.  Sale (if oppty stage type changes to Closed/won) = Closed Won
2-  Meeting (oppty stage/status change: tbd) = Dealer Visit
3 - Letter (oppty stage/status change: tbd) = &lt;not used&gt;
4 - Phone (oppty stage/status change: tbd) = In Conversation
5 - Note (oppty stage/status change: tbd) = In Conversation
6 - Inactive (if oppty stage type chagnes to Closed/lost) = Closed Inactive
7 - email (oppty stage/status change: tbd) = In Conversations</description>
    <fields>
        <fullName>CurrentStatus__c</fullName>
        <label>Current Status</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Event__c</fullName>
        <label>Last Event</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StageName__c</fullName>
        <label>StageName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Lead_Disposition_Last_Event_Status</label>
</CustomObject>

objects/Logs__c.object
<CustomObject>
    <fields>
        <fullName>Error_Line_Number__c</fullName>
        <label>Error Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>130768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Trigger_or_Class_Name__c</fullName>
        <label>Trigger or Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Logs</label>
    <nameField>
        <label>Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <label>External IDs</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OpportunityStatus_TXT__c</fullName>
        <label>Opportunity Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned/Routed to Dealer</fullName>
                </value>
                <value>
                    <fullName>Auto-response sent</fullName>
                </value>
                <value>
                    <fullName>Lead Opened</fullName>
                </value>
                <value>
                    <fullName>Lead Received</fullName>
                </value>
                <value>
                    <fullName>Customer phoned (Inbound phone)</fullName>
                </value>
                <value>
                    <fullName>Customer emailed (Inbound email)</fullName>
                </value>
                <value>
                    <fullName>Salesperson responded by Email</fullName>
                </value>
                <value>
                    <fullName>Salesperson responded by Phone</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson responded by email</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson responded by Phone</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson request another appointment by email</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson request another appointment by phone</fullName>
                </value>
                <value>
                    <fullName>Credit Application</fullName>
                </value>
                <value>
                    <fullName>Credit Application (3rd party)</fullName>
                </value>
                <value>
                    <fullName>Trade-In Appraisal</fullName>
                </value>
                <value>
                    <fullName>Broadcast Email</fullName>
                </value>
                <value>
                    <fullName>Made Appointment</fullName>
                </value>
                <value>
                    <fullName>Demoed/Test Drove</fullName>
                </value>
                <value>
                    <fullName>Boat/Outboard Sales Presentation</fullName>
                </value>
                <value>
                    <fullName>Appointment Didn’t Show</fullName>
                </value>
                <value>
                    <fullName>Appointment Showed</fullName>
                </value>
                <value>
                    <fullName>Offer to Purchase</fullName>
                </value>
                <value>
                    <fullName>Model in Stock</fullName>
                </value>
                <value>
                    <fullName>Model not in Stock</fullName>
                </value>
                <value>
                    <fullName>Model on back order</fullName>
                </value>
                <value>
                    <fullName>Credit Denied</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson marked sold</fullName>
                </value>
                <value>
                    <fullName>Salesperson marked vehicle sold</fullName>
                </value>
                <value>
                    <fullName>Lost Sales</fullName>
                </value>
                <value>
                    <fullName>Any additional vehicle sold info (delivered, punched, etc.)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Nurturing</fullName>
                </value>
                <value>
                    <fullName>Ready to Convert</fullName>
                </value>
                <value>
                    <fullName>Manual Validation</fullName>
                </value>
                <value>
                    <fullName>Closed - Not Converted</fullName>
                </value>
                <value>
                    <fullName>Closed - Converted</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/HELMSPlatformEventLeadDisposition.cls
/**** Opp Trigger Handler Name;HELMSPlatformEventLeadDisposition
User story Number : LMS-1553
SFDC will publish to a platform event queue for any Opportunity disposition data
****/
public class HELMSPlatformEventLeadDisposition{
    List<Lead_Disposition__e> publishEvents = new List<Lead_Disposition__e>();
    public void newLeadDispositionADFs(List<Opportunity> opty , Map<Id, Opportunity> oldMap , Boolean isInsert, Boolean isUpdate){
        try{
            Map<String,Lead_Disposition_Last_Event_Status__c> custom = new Map<string,Lead_Disposition_Last_Event_Status__c>();
            List<Lead_Disposition_Last_Event_Status__c> leadDis = Lead_Disposition_Last_Event_Status__c.getall().values();
                     
            for(Opportunity opp : opty){
                if(opp.External_ID__c!=null){
                    if( (isInsert && opp.StageName!=null) || (isUpdate && opp.StageName!=null && ((oldMap.get(opp.id)!=null && opp.StageName != oldMap.get(opp.id).StageName) || (oldMap.get(opp.id)!=null && opp.OpportunityStatus_TXT__c != oldMap.get(opp.id).OpportunityStatus_TXT__c) ))) {
                        Lead_Disposition__e eve = new Lead_Disposition__e();
                        eve.ArrivalTime_DT__c = opp.CreatedDate;
                        eve.AutoResponse_FLG__c = true ;
                        eve.Id_TXT__c = opp.External_ID__c ;                
                        eve.ResponseTime_DT__c = opp.LastModifiedDate ; 
                        
                        for(Lead_Disposition_Last_Event_Status__c sc:leadDis){
                            if((sc.StageName__c!=null && sc.StageName__c==opp.StageName && sc.Status__c!=null && sc.Status__c==opp.OpportunityStatus_TXT__c) || (sc.StageName__c!=null && sc.StageName__c==opp.StageName && sc.Status__c==null )){
                                eve.CurrentStatus_NM__c = sc.CurrentStatus__c ;  
                                eve.LastEvent_NM__c = sc.Last_Event__c ;
                                publishEvents.add(eve); 
                            }       
                                                     
                        }
                        
                                    
                        //publishEvents.add(eve); 
                    }
                }
            }    
            if(publishEvents.size()>0){
                //EventBus.publish(publishEvents);
                System.debug('--publish Lead disposition event---');
                
                
                // Call method to publish events
                List<Database.SaveResult> results = EventBus.publish(publishEvents);

                // Inspect publishing result for each event
                for (Database.SaveResult sr : results) {
                    if (sr.isSuccess()) {
                        System.debug('Successfully published event.');
                    } else {
                        for(Database.Error err : sr.getErrors()) {
                            System.debug('Error returned: ' +
                                        err.getStatusCode() +
                                        ' - ' +
                                        err.getMessage());
                            Logs__c  l =new Logs__c (name='Lead Disposition ADF- Trigger Handler',Trigger_or_Class_Name__c='HELMSPlatformEventLeadDisposition', Error_Message__c =err.getMessage() );
                            insert l;
                        }
                    }       
                }


            }
        
        }Catch(Exception ex){
            System.debug('Exception at line : '+ ex.getLineNumber());
            System.debug('Exception Message : '+ ex.getMessage());
            
            Logs__c  l =new Logs__c (name='Lead Disposition ADF- Trigger Handler',Trigger_or_Class_Name__c='HELMSPlatformEventLeadDisposition', Error_Message__c =ex.getMessage(), Error_Line_Number__c =Integer.valueOf(string.valueof(ex.getLineNumber() )) );
           insert l;
        }   
    }
    
}