objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>StatusReason_TXT__c</fullName>
        <defaultValue>(&quot;Pending&quot;)</defaultValue>
        <label>Status Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Inactivity</fullName>
                </value>
                <value>
                    <fullName>Duplicate Merged</fullName>
                </value>
                <value>
                    <fullName>Validation Email</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Lead Provider error</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Opt Out</fullName>
                </value>
                <value>
                    <fullName>Duplicate Similar</fullName>
                </value>
                <value>
                    <fullName>Matched Leads</fullName>
                </value>
                <value>
                    <fullName>Related Opportunity closed</fullName>
                </value>
                <value>
                    <fullName>Unable to assign Dealer</fullName>
                </value>
                <value>
                    <fullName>Name/Address/Email Error</fullName>
                </value>
                <value>
                    <fullName>Name/Address/Email Cache</fullName>
                </value>
                <value>
                    <fullName>Third Party Duplicate</fullName>
                </value>
                <value>
                    <fullName>Waiting for the routing window to start</fullName>
                </value>
                <value>
                    <fullName>Routing Window Expired</fullName>
                </value>
                <value>
                    <fullName>Concierge</fullName>
                </value>
                <value>
                    <fullName>Lead Enrichment call error</fullName>
                </value>
                <value>
                    <fullName>Dealer Assignment call failed</fullName>
                </value>
                <value>
                    <fullName>Journey Completed</fullName>
                </value>
                <value>
                    <fullName>New Opportunity Created</fullName>
                </value>
                <value>
                    <fullName>Journey incomplete, no response</fullName>
                </value>
                <value>
                    <fullName>Concierge Completed</fullName>
                </value>
                <value>
                    <fullName>Invalid email and phone</fullName>
                </value>
                <value>
                    <fullName>Customer is not Interested in the product</fullName>
                </value>
                <value>
                    <fullName>In nurturing journey</fullName>
                </value>
                <value>
                    <fullName>Waiting for Deal Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead_Expiration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to set the expiration of Leads due to no activity.</description>
    <fields>
        <fullName>A__c</fullName>
        <label>A</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>B__c</fullName>
        <label>B</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>M__c</fullName>
        <label>M</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>P__c</fullName>
        <label>P</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lead Expiration</label>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

classes/LeadCloseConversionBatchTest.cls
/****************************************************************************** 
 File Name:LeadCloseConversionBatch           
 Created On:     
 Created By:      Bandi Sujatha, Appirio
 Test Classes:    LeadCloseConversionBatchTest       
 HELMS Jira Story: 
===============================================================================
 Modification Log: 
 May 18th, 2021 Bandi Sujatha (Appirio) initial coding,cleanup 
*******************************************************************************/
@isTest
//Test Class for Lead Conversion Batch Class
public class LeadCloseConversionBatchTest
{
    //Method
    @isTest public static void testschedule() { 
        HELMS_LeadConversionScheduler testschdl = new HELMS_LeadConversionScheduler();
        String sch = '0 0 23 * * ?';
        system.schedule('Test status Check', sch, testschdl);
        
        Lead_Expiration__c le = new Lead_Expiration__c();
        le.A__c = 90;
        le.B__c = 90;
        le.M__c = 90;
        le.P__c = -1;
        insert le;
        
        Test.StartTest(); 
        Lead ld = new Lead();
        ld.lastName ='LastName';
        ld.IsConverted=false;
        ld.Division_CD__c='A';
        insert ld;
        
        String query = 'Select Id,Name,LastModifiedDate,IsConverted,StatusReason_TXT__c,Status,Division_CD__c from Lead where IsConverted=false';
        LeadCloseConversionBatch obj = new LeadCloseConversionBatch(query);
        DataBase.executeBatch(obj); 
        LeadCloseConversionBatch obj1 = new LeadCloseConversionBatch();
        system.assertEquals('LastName', ld.lastName);
        Test.stopTest();
             
      
        
    }
    //Second Method
    @isTest public static void testschedule1() { 
        HELMS_LeadConversionScheduler testschdl = new HELMS_LeadConversionScheduler();
        String sch = '0 0 23 * * ?';
        system.schedule('Test status Check', sch, testschdl);
        
        Lead_Expiration__c le = new Lead_Expiration__c();
        le.A__c = 90;
        le.B__c = 90;
        le.M__c = 90;
        le.P__c = -1;
        insert le;
        
        Test.StartTest(); 
        Lead ld = new Lead();
        ld.lastName ='LastName';
        ld.IsConverted=false;
       // ld.Division_CD__c='A';
        insert ld;
        
        String query = 'Select Id,Name,LastModifiedDate,IsConverted,StatusReason_TXT__c,Status from Lead where IsConverted=false';
        LeadCloseConversionBatch obj = new LeadCloseConversionBatch(query);
        DataBase.executeBatch(obj); 
        //LeadCloseConversionBatch obj1 = new LeadCloseConversionBatch();
        system.assertEquals('LastName', ld.lastName);
        Test.stopTest();
             
      
        
    }
}