objects/Logs__c.object
<CustomObject>
    <fields>
        <fullName>Error_Line_Number__c</fullName>
        <label>Error Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>130768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PE_Reply_Id__c</fullName>
        <label>PE Reply Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Rec_Id__c</fullName>
        <label>SF Rec Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_or_Class_Name__c</fullName>
        <label>Trigger or Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Logs</label>
    <nameField>
        <label>Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HELMSBatchMassDeleteLogs.cls
global class HELMSBatchMassDeleteLogs implements Database.batchable<sobject>, Schedulable{
    
    // string query='select Name,Error_Line_Number__c,Error_Message__c,PE_Reply_Id__c,SF_Rec_Id__c,Trigger_or_Class_Name__c from Logs__c WHERE CreatedDate = LAST_N_DAYS:30';
    global final string query;
    
    global HELMSBatchMassDeleteLogs(){
               
    }
    global HELMSBatchMassDeleteLogs(string query){
        this.query=query;
        
    }

    global Database.QueryLocator start(Database.batchableContext bc){
        return Database.getQueryLocator(query);
     
    }
    global void execute(Database.batchableContext bc,List<Logs__c> scope){

        if(!scope.isEmpty()){
            delete scope;
        }
    }
    global void finish(Database.batchableContext bc){
      
    }    
    
    global void execute (SchedulableContext sc){
        string query='select id from Logs__c WHERE CreatedDate < LAST_N_DAYS:60 order by CreatedDate desc';
    
        HELMSBatchMassDeleteLogs  deleteOldLogsjob = new HELMSBatchMassDeleteLogs(query);
        Id batchId = Database.executeBatch(deleteOldLogsjob ,1000);
    }
    
}