objects/Logs__c.object
<CustomObject>
    <fields>
        <fullName>Error_Line_Number__c</fullName>
        <label>Error Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>130768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Trigger_or_Class_Name__c</fullName>
        <label>Trigger or Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Logs</label>
    <nameField>
        <label>Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CRM_Payload__c</fullName>
        <label>CRM Payload</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Details_Urban_Science__c</fullName>
        <label>Error Details Urban Science</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity_SF_ID__c</fullName>
        <externalId>true</externalId>
        <label>Opportunity_SF_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_DSP__c</fullName>
        <label>Response DSP</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Response_Urban_Science__c</fullName>
        <label>Response Urban Science</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Routing_Error__c</fullName>
        <label>Routing Error</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sent_to_Urban_Science_Status__c</fullName>
        <label>Sent to Urban Science Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Routing_Acknowledgement_No_Response__c.object
<CustomObject>
    <description>Custom Object to fetch Blank Routing Acknowledgement Response</description>
    <fields>
        <fullName>CRM_Payload__c</fullName>
        <description>CRM Payload</description>
        <label>CRM Payload</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRM_XML_Response__c</fullName>
        <description>CRM XML Response</description>
        <label>CRM XML Response</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CreatedDate__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>CreatedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Error_Details_Urban_Science__c</fullName>
        <description>Error Details Urban Science</description>
        <label>Error Details Urban Science</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether the Opportunity is processed or not by the batch</description>
        <label>IsProcessed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_SF_ID__c</fullName>
        <label>Opportunity SF ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_DSP__c</fullName>
        <label>Response DSP</label>
        <length>70768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Urban_Science__c</fullName>
        <description>Urban Science Routing Response</description>
        <label>Response Urban Science</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Routing_Error__c</fullName>
        <description>Routing Error</description>
        <label>Routing Error</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sent_to_Urban_Science_Status__c</fullName>
        <label>Sent to Urban Science Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <description>Acknowledgement Status Code</description>
        <label>Status Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Routing Acknowledgement No Response</label>
    <nameField>
        <label>Routing Acknowledgement No Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routing Acknowledgement No Response</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HelmsBlankRoutingStatusBatch.cls
global class HelmsBlankRoutingStatusBatch implements Database.Batchable<sObject>,Database.Stateful,Schedulable { 
	global final string query;
    
    global HelmsBlankRoutingStatusBatch(){
               
    }
    global HelmsBlankRoutingStatusBatch(string query){
        this.query=query;
    }
    //Start Method
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }    
    //Execute Method
    global void execute(Database.BatchableContext BC, List<Routing_Acknowledgement_No_Response__c> newOppotunityBlankResponse) {
        try{
            //System.debug('newOppotunityBlankResponse : '+newOppotunityBlankResponse);
            HELMSLeadDealerAssignmentADFHandler dealerAssignObj = new HELMSLeadDealerAssignmentADFHandler();
            dealerAssignObj.updateOpportunityBlankResponse(newOppotunityBlankResponse);
            //dealerAssignObj.updateRoutingNoAckResponse(oppSFDICSet);
            
        }Catch(Exception ex){   
            //System.debug('Inside Catch');
            Logs__c  l =new Logs__c (name='Opportunity Routable Batch',Trigger_or_Class_Name__c='HelmsBlankRoutingStatusBatch', Error_Message__c =ex.getMessage(), Error_Line_Number__c =Integer.valueOf(string.valueof(ex.getLineNumber() )) );
           insert l;
        }
    }
    //Finish Method
    global void finish(Database.BatchableContext BC) {
		// Get the ID of the AsyncApexJob representing this batch job from Database.BatchableContext.
        // Query the AsyncApexJob object to retrieve the current job's information.
        //AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id = :BC.getJobId()];
        
        //then use the active job id and abort it
        //system.abortJob(a.id);
    }
    //Execute Method - Running the Job
    global void execute (SchedulableContext sc){
        string query= 'SELECT Id, Opportunity_SF_ID__c, IsProcessed__c, Error_Details_Urban_Science__c, Response_Urban_Science__c, Routing_Error__c, Sent_to_Urban_Science_Status__c, Status_Code__c, CRM_Payload__c, CRM_XML_Response__c, CreatedDate, CreatedDate__c,Response_DSP__c from Routing_Acknowledgement_No_Response__c where IsProcessed__c = false '; 
        HelmsBlankRoutingStatusBatch blankRoutingBatch = new HelmsBlankRoutingStatusBatch(query);
        Id batchId = Database.executeBatch(blankRoutingBatch,1);
    }
}