objects/Logs__c.object
<CustomObject>
    <fields>
        <fullName>Error_Line_Number__c</fullName>
        <label>Error Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>130768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Trigger_or_Class_Name__c</fullName>
        <label>Trigger or Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Logs</label>
    <nameField>
        <label>Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Model__c.object
<CustomObject>
    <fields>
        <fullName>Model_ID_Text__c</fullName>
        <label>Model ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_MSRP__c</fullName>
        <label>Model MSRP</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Model_Marketing_Name__c</fullName>
        <label>Model Marketing Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <label>Model Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Model_Group_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Model Group Id</label>
        <referenceTo>Product_Model_Group__c</referenceTo>
        <relationshipLabel>Product Models</relationshipLabel>
        <relationshipName>Product_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Model</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Product Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Model_Group__c.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Series_Group_Name__c</fullName>
        <label>Parent Series Group Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Model_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup reference to Product Model Master record whose records are populating from Integration</description>
        <label>Product Model Master</label>
        <referenceTo>Product_Model_Master__c</referenceTo>
        <relationshipLabel>Product Model Groups</relationshipLabel>
        <relationshipName>Product_Model_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Series_Group_Name__c</fullName>
        <label>Product Series Group Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <label>Subdivision</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <label>Product Model Group</label>
    <nameField>
        <label>Product Model Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Model Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Model_Master__c.object
<CustomObject>
    <description>This Object used by Integration to upload the Product Model data</description>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModelGroupName__c</fullName>
        <label>ModelGroupName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModelID__c</fullName>
        <externalId>true</externalId>
        <label>ModelID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModelMSRP__c</fullName>
        <label>ModelMSRP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModelMarketingName__c</fullName>
        <label>ModelMarketingName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModelYear__c</fullName>
        <label>ModelYear</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentSeriesGroupName__c</fullName>
        <label>ParentSeriesGroupName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeriesGroupName__c</fullName>
        <label>SeriesGroupName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubDivision__c</fullName>
        <label>SubDivision</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product Model Master</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Product Model Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Model Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/ModelGroupUploadHandler.cls
public class ModelGroupUploadHandler {
    public void addProductModelCustomObject(List<Product_Model_Master__c> listRec){
        try{
        List<Product_Model_Group__c> prodModelGrpList = new List<Product_Model_Group__c>();
        List<Product_Model__c> prodModelList = new List<Product_Model__c>();
        Map<String, Product_Model_Master__c> productModelmasterMap = new Map<String, Product_Model_Master__c>();
        Set<Id> recIds = new Set<Id>();
        for(Product_Model_Master__c rec : listRec){
            productModelmasterMap.put(rec.ID,rec); // New Map 
        }
        for (Id fieldName : productModelmasterMap.keySet()){
            Product_Model_Group__c modelGrpRec = new Product_Model_Group__c();
            modelGrpRec.Division__c = productModelmasterMap.get(fieldName).Division__c;
            modelGrpRec.Parent_Series_Group_Name__c = productModelmasterMap.get(fieldName).ParentSeriesGroupName__c;
                modelGrpRec.Name = productModelmasterMap.get(fieldName).ModelGroupName__c;
                modelGrpRec.Product_Model_Master__c = productModelmasterMap.get(fieldName).Id;
            modelGrpRec.Product_Series_Group_Name__c = productModelmasterMap.get(fieldName).SeriesGroupName__c;
                modelGrpRec.Subdivision__c = productModelmasterMap.get(fieldName).SubDivision__c;
            prodModelGrpList.add(modelGrpRec);
        }
        Database.SaveResult[] sr = Database.insert(prodModelGrpList, false);
       	for (Database.SaveResult ds : sr) {
            if (ds.isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
                recIds.add(ds.getId());
            }
       	}
        if(recIds.size() > 0){
            for(Product_Model_Group__c rec : [SELECT Id, Product_Model_Master__c FROM Product_Model_Group__c WHERE Id IN : recIds ]){
                Product_Model__c rec2 = new Product_Model__c();
                Id stringNewKey = rec.Product_Model_Master__c;
                if(!productModelmasterMap.isEmpty() && productModelmasterMap.containskey(stringNewKey)){
                    rec2.Product_Model_Group_Id__c = rec.Id;
                    rec2.Model_Year__c = productModelmasterMap.get(stringNewKey).ModelYear__c;
                    rec2.Model_MSRP__c = Decimal.ValueOf(productModelmasterMap.get(stringNewKey).ModelMSRP__c);
                    rec2.Model_Marketing_Name__c = productModelmasterMap.get(stringNewKey).ModelMarketingName__c;
                    rec2.Model_ID_Text__c = productModelmasterMap.get(stringNewKey).ModelID__c;
                    prodModelList.add(rec2);
                }
            }
        }
        if(prodModelList.size() > 0){
        	insert prodModelList;    
            }   
        }Catch(Exception ex) {
            Logs__c l = new Logs__c(name = 'Model Group Upload', Trigger_or_Class_Name__c = 'ModelGroupUploadHandler', Error_Message__c = ex.getMessage(), Error_Line_Number__c = Integer.valueOf(string.valueof(ex.getLineNumber())));
            insert l;
        }
    }
}