objects/Logs__c.object
<CustomObject>
    <fields>
        <fullName>Error_Line_Number__c</fullName>
        <label>Error Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>130768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Trigger_or_Class_Name__c</fullName>
        <label>Trigger or Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Logs</label>
    <nameField>
        <label>Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Offers__c.object
<CustomObject>
    <description>Business Unit: HELMS.
Jira Story: LMS-1950 Story name.
Description: This is store Opportunity Offers.
Source System: Coming from Integration.
Integration: Yes.
Data Transformation: N/A.
Functional Definition: This will be Stored Opportunity Offers.</description>
    <fields>
        <fullName>AK_Opportunity_Offer__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-1950 Story name.
Description: This is store AK Opportunity Offer.
Source System: Coming from Integration.
Integration: Yes.
Data Transformation: N/A.
Functional Definition: This will be Stored AK Opportunity Offer.</description>
        <label>AK Opportunity Offer</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-1950 Story name.
Description: This is store the End Date.
Source System: Coming from Integration.
Integration: Yes.
Data Transformation: N/A.
Functional Definition: This will be Stored Offers End Date.</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Offer_ID__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-1950 Story name.
Description: This is store the Offer ID.
Source System: Coming from Integration.
Integration: Yes.
Data Transformation: N/A.
Functional Definition: This will be Stored Offers ID.</description>
        <label>Offer ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer_Type__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-1950 Story name.
Description: This is store the Offer Type.
Source System: Coming from Integration.
Integration: Yes.
Data Transformation: N/A.
Functional Definition: This will be Stored Offers Type.</description>
        <label>Offer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Finance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Business Unit: HELMS.
Jira Story: LMS-1950 Story name.
Description: This is store the Opportunity ID.
Source System: Coming from Integration.
Integration: Yes.
Data Transformation: N/A.
Functional Definition: This will be Stored Opportunity ID.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Special_Description__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-1950 Story name.
Description: This is store the Special Description.
Source System: Coming from Integration.
Integration: Yes.
Data Transformation: N/A.
Functional Definition: This will be Stored Special Description.</description>
        <label>Special Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Special_Short_Description__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-1950 Story name.
Description: This is store the Special Short Description.
Source System: Coming from Integration.
Integration: Yes.
Data Transformation: N/A.
Functional Definition: This will be Stored Special Short Description.</description>
        <label>Special Short Description</label>
        <type>TextArea</type>
    </fields>
    <label>Opportunity Offers</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Offers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LeadAdditionalInfos__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-1950 Story name.
Description: This is store the Offers XML Data.
Source System: Coming from Integration.
Integration: Yes.
Data Transformation: N/A.
Functional Definition: This will be Stored Offers Data.</description>
        <label>LeadAdditionalInfos</label>
        <length>118216</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/HELMSOffersInsertHandler.cls
/**** Trigger Name:HELMSOffersInsertHandler
User story Number : LMS-1950
Show Customer Selected Offers to Dealers in Partner Community. 
****/

public with sharing class HELMSOffersInsertHandler {
    public static void handleOffersInsert(List<Opportunity> opty) {
        try{
            List<Offers__c> listOffers = new List<Offers__c>();
            //Iterating through opportunities
            for(Opportunity opp : opty){
                //String strLeadAdditionalInfos;
                if(opp.LeadAdditionalInfos__c!=null && opp.LeadAdditionalInfos__c != '' ){
                    //strLeadAdditionalInfos = HELMSLeadDealerAssignmentADFHandler.removeSpecialXMLChars(opp.LeadAdditionalInfos__c);
                    String addInfo= opp.LeadAdditionalInfos__c;
                    String comments = '';
                    Offers__c offer = new Offers__c();
                    /* New Code */
                    if(addInfo.contains('<LeadAdditionalInfo key="Offer Id">')){
                            offer.Offer_ID__c = addInfo.substringBetween('<LeadAdditionalInfo key="Offer Id">','</LeadAdditionalInfo>');
                    		   
                    }
                        if(addInfo.contains('<LeadAdditionalInfo key="Offer Name">')){
                            offer.Name = addInfo.substringBetween('<LeadAdditionalInfo key="Offer Name">','</LeadAdditionalInfo>');
                        }
                        if(addInfo.contains('<LeadAdditionalInfo key="Offer Type">')){
                            offer.Offer_Type__c = addInfo.substringBetween('<LeadAdditionalInfo key="Offer Type">','</LeadAdditionalInfo>');
                        }
                        if(addInfo.contains('<LeadAdditionalInfo key="special_short_description">')){
                            offer.Special_Short_Description__c =addInfo.substringBetween('<LeadAdditionalInfo key="special_short_description">','</LeadAdditionalInfo>');
                        }
                    	if(addInfo.contains('<LeadAdditionalInfo key="special_description">')){
                            offer.Special_Description__c = addInfo.substringBetween('<LeadAdditionalInfo key="special_description">','</LeadAdditionalInfo>');
                        }
                    	if(addInfo.contains('<LeadAdditionalInfo key="AK Opportunity Offer">')){
                            offer.AK_Opportunity_Offer__c = addInfo.substringBetween('<LeadAdditionalInfo key="AK Opportunity Offer">','</LeadAdditionalInfo>');
                        }
                        if(addInfo.contains('<LeadAdditionalInfo key="end_date">')){
                            String strDate = addInfo.substringBetween('<LeadAdditionalInfo key="end_date">','</LeadAdditionalInfo>');
                            strDate = strDate.substring(7, strDate.length() - 1);
                            strDate = strDate.trim();
                            offer.End_Date__c = Date.Parse(strDate);
                        }
                    /* New Code */
                    /*
                    Dom.Document doc = new Dom.Document(); 
                    doc.load(strLeadAdditionalInfos);
                    Dom.XMLNode rootElement = doc.getRootElement();
                    //Iterating through child elements and assigning the values to Offers object
                    Offers__c offer = new Offers__c();
                    for(Dom.XMLNode childElement : rootElement.getChildElements()){
                        
                        offer.Opportunity__c = opp.Id;
                         if(childElement.getAttributeValue('key', null) == 'Offer Id'){
                            offer.Offer_ID__c = childElement.getText(); 
                            System.debug('OfferId'+childElement.getText());
                        } else if(childElement.getAttributeValue('key',null) == 'Offer Name'){
                            System.debug('OfferName'+childElement.getText());
                            offer.Name = childElement.getText();
                        } else if(childElement.getAttributeValue('key', null) == 'Offer Type'){
                            offer.Offer_Type__c = childElement.getText();
                        } else if(childElement.getAttributeValue('key', null) == 'end_date'){
                            String strDate = childElement.getText();
                            strDate = strDate.substring(7, strDate.length() - 1);
                            //strDate = strDate.substring(0, strDate.indexOf('Expires'));
                            strDate = strDate.trim();
                            offer.End_Date__c = Date.Parse(strDate);
                        } else if(childElement.getAttributeValue('key', null) == 'special_short_description'){
                            offer.Special_Short_Description__c = childElement.getText();
                        } else if(childElement.getAttributeValue('key', null) == 'special_description'){
                            offer.Special_Description__c = childElement.getText();
                        }else if(childElement.getAttributeValue('key', null) == 'AK Opportunity Offer'){
                            offer.AK_Opportunity_Offer__c = childElement.getText();
                        }
                        
                    }
					*/
                    listOffers.add(offer);
                }
            }
            Integer j = 0;
            while(j< listOffers.Size()){
                if(listOffers[j].Offer_ID__c == null && listOffers[j].Name == null && listOffers[j].End_Date__c == null && listOffers[j].Special_Short_Description__c == null && listOffers[j].Special_Description__c == null && listOffers[j].AK_Opportunity_Offer__c == null){
                    listOffers.remove(j);
                } else {
                    j++;

            }
            
            
            if(listOffers.Size() > 0){
                insert listOffers;
            }
            }}Catch(Exception ex){
            System.debug('exception=====>>>>>>'+ex.getMessage());
            Logs__c  l =new Logs__c (name='Opportunity Trigger',Trigger_or_Class_Name__c='HELMSOffersInsertHandler', Error_Message__c =ex.getMessage(), Error_Line_Number__c =Integer.valueOf(string.valueof(ex.getLineNumber() )) );
            insert l;
        }
    }
}