objects/Matchback_New__c.object
<CustomObject>
    <fields>
        <fullName>Matchback_Date__c</fullName>
        <label>Retail Sales Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Matchback_Status__c</fullName>
        <label>Matchback Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Matched to Dealer</fullName>
                </value>
                <value>
                    <fullName>Matched to other Dealer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Matchback New</relationshipLabel>
        <relationshipName>Matchback_New</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>RDR_Sales__c</fullName>
        <label>RDR Sales</label>
        <referenceTo>RDR_Sales__c</referenceTo>
        <relationshipLabel>Matchback New</relationshipLabel>
        <relationshipName>Matchback_New</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Matchback New</label>
    <nameField>
        <displayFormat>Matchback - {0000000}</displayFormat>
        <label>Matchback New Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matchback New</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Division_CD__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name_TXT__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name_TXT__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Matchback_Date__c</fullName>
        <label>Retail Sales Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PreferredDealerNumber_NUM__c</fullName>
        <label>Preferred Dealer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_TXT__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Updated_by_New_MB__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Updated by New MB</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ZipCode_TXT__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Honda</fullName>
        <active>true</active>
        <businessProcess>HELMS Sales Process</businessProcess>
        <description>Used by the Honda Team</description>
        <label>Honda Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RDR_Sales__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Address_ZIP_Code_TXT__c</fullName>
        <label>Customer Address ZIP Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Cellphone_Number__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-5532 Story name.
Description: This is to store the CELL_PHONE
Source System: Coming from Integration from Mainframe/SAP.
Integration: NA.
Data Transformation: N/A.</description>
        <label>Customer Cellphone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Customer_First_Name_NUM__c</fullName>
        <label>Customer First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Home_Phone_Number__c</fullName>
        <label>Customer Home Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Customer_Last_Name_NM__c</fullName>
        <label>Customer Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Street_Address_TXT__c</fullName>
        <label>Customer Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Number_NUM__c</fullName>
        <label>Dealer Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_id_TXT__c</fullName>
        <label>Email id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Driver_Cellphone_Number__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-5532 Story name.
Description: This is to store the Driver Cell Phone
Source System: Coming from Integration from Mainframe/SAP.
Integration: NA.
Data Transformation: N/A.</description>
        <label>Primary Driver Cellphone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Primary_Driver_Email__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-5532 Story name.
Description: This is to store the Driver Email
Source System: Coming from Integration from Mainframe/SAP.
Integration: NA.
Data Transformation: N/A.</description>
        <label>Primary Driver Email</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Driver_Home_Phone_Number__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-5532 Story name.
Description: This is to store the Driver Home Phone
Source System: Coming from Integration from Mainframe/SAP.
Integration: NA.
Data Transformation: N/A.</description>
        <label>Primary Driver Home Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Primary_Driver_Phone_Number__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-5532 Story name.
Description: This is to store the Driver Phone
Source System: Coming from Integration from Mainframe/SAP.
Integration: NA.
Data Transformation: N/A.</description>
        <label>Primary Driver Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sales_Date_DT__c</fullName>
        <label>Sales Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Telephone_Number_NUM__c</fullName>
        <label>Telephone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Updated_by_New_MB__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Updated by New MB</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vin_TXT__c</fullName>
        <label>Vin</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XPROD_DIV_CD__c</fullName>
        <label>XPROD-DIV-CD</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>RDR Sales</label>
    <nameField>
        <displayFormat>RDR Sales - {00000000}</displayFormat>
        <label>RDR Sales</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RDR Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

classes/HELMSMatchbackBatchTest.cls
@isTest
public class HELMSMatchbackBatchTest {
    @isTest 
    static void testHELMSMatchback(){
        
        RDR_Sales__c rdrSales = new RDR_Sales__c();
        rdrSales.Customer_First_Name_NUM__c = 'TestVinay1';
        rdrSales.Customer_Last_Name_NM__c ='TestTalapalle1';
        rdrSales.XPROD_DIV_CD__c = 'A';
        rdrSales.Telephone_Number_NUM__c = '7780190896';
        rdrSales.Primary_Driver_Email__c = 'vinay123@gmail.com';
        rdrSales.Customer_Home_Phone_Number__c = '45434343443';
        rdrSales.Primary_Driver_Home_Phone_Number__c = '7780190896';
        rdrSales.Primary_Driver_Phone_Number__c = '7780190896';
        rdrSales.Customer_Cellphone_Number__c = '7780190896';
        rdrSales.Primary_Driver_Cellphone_Number__c = '3171231234';
        rdrSales.Customer_Address_ZIP_Code_TXT__c = '65456';
        rdrSales.Email_id_TXT__c = 'testvinay@gmail.com';
        rdrSales.Sales_Date_DT__c = system.today()-1;
        rdrSales.Dealer_Number_NUM__c = '222276';
        rdrSales.Vin_TXT__c = '76876544567';
        rdrSales.Customer_Address_ZIP_Code_TXT__c = '12345';
        rdrSales.Customer_Street_Address_TXT__c = '123 Hollywood Blvd';
        
        insert rdrSales;
        
        Id hondaRecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Honda Opportunity').getRecordTypeId();
        
        Opportunity opp = new Opportunity();
        opp.Name='TestVinay1 TestTalapalle1';
        opp.First_Name_TXT__c = 'TestVinay1';
        opp.Last_Name_TXT__c = 'TestTalapalle1';
        opp.Stagename='Assigned to Dealer';
        opp.Email__c='testvinay@gmail.com';
        opp.ZipCode_TXT__c='12345';
        opp.Phone__c='7780190896';
        opp.Updated_by_New_MB__c=false;
        opp.RecordTypeId=hondaRecTypeId;
        opp.Division_CD__c='A';
        opp.PreferredDealerNumber_NUM__c='222276';
        opp.CloseDate= system.today();
        opp.Street_TXT__c = '123 Hollywood Blvd';
        opp.ZipCode_TXT__c = '12345';
        
        insert opp;
        
        Matchback_New__c mB1 = new Matchback_New__c();
        mB1.Opportunity__c = opp.Id;
        mB1.RDR_Sales__c = rdrSales.Id;
        mB1.Matchback_Date__c = rdrSales.Sales_Date_DT__c;
        mB1.Matchback_Status__c = 'Matched to Dealer';
        
        insert mB1;
        
        Matchback_New__c mB2 = new Matchback_New__c();
        mB2.Opportunity__c = opp.Id;
        mB2.RDR_Sales__c = rdrSales.Id;
        mB2.Matchback_Date__c = rdrSales.Sales_Date_DT__c;
        mB2.Matchback_Status__c = 'Matched to other Dealer';
        
        insert mB2;
        
        Test.startTest();    
        HELMSMatchbackBatch matchbackBatch = new HELMSMatchbackBatch(); 
        Database.executeBatch(matchbackBatch);
        Test.stopTest();
    }
}