objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>OpportunityStatus_TXT__c</fullName>
        <label>Opportunity Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned/Routed to Dealer</fullName>
                </value>
                <value>
                    <fullName>Auto-response sent</fullName>
                </value>
                <value>
                    <fullName>Lead Opened</fullName>
                </value>
                <value>
                    <fullName>Lead Received</fullName>
                </value>
                <value>
                    <fullName>Customer phoned (Inbound phone)</fullName>
                </value>
                <value>
                    <fullName>Customer emailed (Inbound email)</fullName>
                </value>
                <value>
                    <fullName>Salesperson responded by Email</fullName>
                </value>
                <value>
                    <fullName>Salesperson responded by Phone</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson responded by email</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson responded by Phone</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson request another appointment by email</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson request another appointment by phone</fullName>
                </value>
                <value>
                    <fullName>Credit Application</fullName>
                </value>
                <value>
                    <fullName>Credit Application (3rd party)</fullName>
                </value>
                <value>
                    <fullName>Trade-In Appraisal</fullName>
                </value>
                <value>
                    <fullName>Broadcast Email</fullName>
                </value>
                <value>
                    <fullName>Made Appointment</fullName>
                </value>
                <value>
                    <fullName>Demoed/Test Drove</fullName>
                </value>
                <value>
                    <fullName>Boat/Outboard Sales Presentation</fullName>
                </value>
                <value>
                    <fullName>Appointment Didn’t Show</fullName>
                </value>
                <value>
                    <fullName>Appointment Showed</fullName>
                </value>
                <value>
                    <fullName>Offer to Purchase</fullName>
                </value>
                <value>
                    <fullName>Model in Stock</fullName>
                </value>
                <value>
                    <fullName>Model not in Stock</fullName>
                </value>
                <value>
                    <fullName>Model on back order</fullName>
                </value>
                <value>
                    <fullName>Credit Denied</fullName>
                </value>
                <value>
                    <fullName>Dealer Salesperson marked sold</fullName>
                </value>
                <value>
                    <fullName>Salesperson marked vehicle sold</fullName>
                </value>
                <value>
                    <fullName>Lost Sales</fullName>
                </value>
                <value>
                    <fullName>Any additional vehicle sold info (delivered, punched, etc.)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubDiv_TXT__c</fullName>
        <label>SubDivision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>NSX</fullName>
        <active>true</active>
        <businessProcess>NSX Processes</businessProcess>
        <description>Used by the Honda NSX Team</description>
        <label>NSX Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/HELMSOpptystageandstatusonTaskandevent.cls
/*----------------------------------------------------------------------------------------------------------------------------------------------------
Class Name : HELMSOpptystageandstatusonTaskandevent 
Test Class Name : HELMSOpptyStageStatusTestClass
Last Modified Version Owner : Grandhi Lavanya
Comments : Code to update opportuntiy status and stage when task or event or log a call. these options are available in activity section - LMS-4612-R4.2
-------------------------------------------------------------------------------------------------------------------------------------------------------
*/
public class HELMSOpptystageandstatusonTaskandevent {
      /*updateopptyStageandStatusforTask - if we created any task in partner comunity, opportunity stages will update automatically. */
    public static void updateopptyStageandStatusforTask(List<Task> taskList){
    
        set<Id> oppIds = new Set<Id>();
        List<Opportunity> oppty = new List<Opportunity>();  
        
        for(Task t : taskList){
           //  system.debug('t:'+t);
          String wId = t.whatId;
          if(wId!=null && wId.startsWith('006') && t.Subject != null ){
            oppIds.add(t.whatId);
          }
        }
       
        List<Opportunity> opps = [select Id,StageName, OpportunityStatus_TXT__c, SubDiv_TXT__c from opportunity where id in: oppIds];
     //   system.debug('opps:'+opps);
          
        for(Opportunity opp : opps){
            for(Task ta : taskList){
               
                if(ta.Subject == HELMSConstants.inboundCall )
                {
                    if((opp.stageName == HELMSConstants.Acknowledged || opp.stageName == HELMSConstants.Assigned_to_Dealer ||
                        opp.stageName == HELMSConstants.In_Conversation) && opp.OpportunityStatus_TXT__c  != HELMSConstants.CustomerPhoned && opp.SubDiv_TXT__c != HELMSConstants.NSX){
                        
                         opp.stageName = HELMSConstants.In_Conversation;
                        opp.OpportunityStatus_TXT__c  = HELMSConstants.CustomerPhoned;
                    }
                }else if(ta.Subject == HELMSConstants.outboundCall){
                    if((opp.stageName == HELMSConstants.Acknowledged  || opp.stageName == HELMSConstants.Assigned_to_Dealer ||
                       opp.stageName == HELMSConstants.In_Conversation ) &&  opp.SubDiv_TXT__c != HELMSConstants.NSX){
                           
                    opp.stageName = HELMSConstants.In_Conversation;
                  opp.OpportunityStatus_TXT__c  = HELMSConstants.salespersonbyphone;
                }
                }
                if(ta.Subject != HELMSConstants.outboundCall && ta.Subject != HELMSConstants.inboundCall){
                     if(opp.StageName== HELMSConstants.Assigned_to_Dealer && opp.SubDiv_TXT__c != HELMSConstants.NSX){
                         
                              opp.stageName = HELMSConstants.Acknowledged ;
                              opp.OpportunityStatus_TXT__c  = HELMSConstants.LeadOpened;
                              system.debug('stageName ---------> ' + opp.stageName );
                         
                     } else if((opp.stageName == HELMSConstants.In_Conversation && opp.OpportunityStatus_TXT__c != HELMSConstants.Madeappointment) && opp.SubDiv_TXT__c != HELMSConstants.NSX){
                                opp.OpportunityStatus_TXT__c  = HELMSConstants.Madeappointment;
                                                         
                  } 
                }
          oppty.add(opp);
        }
         }  
        
        if(oppty.size()>0)
        {
            update oppty;
        }
    }
    /*updateopptyStageandStatusforEvent - if we created any event in partner comunity, opportunity stages will update automatically. */
    public static void updateopptyStageandStatusforEvent(List<Event> eventList){ 
    
        set<Id> oppIds = new Set<Id>();
        List<Opportunity> oppty = new List<Opportunity>();  
    
        for(Event t : eventList){
          String wId = t.whatId;
          if(wId!=null && wId.startsWith('006') && t.Subject != null){
            oppIds.add(t.whatId);
          }
        }
        
        List<Opportunity> opps = [select Id,StageName, OpportunityStatus_TXT__c, SubDiv_TXT__c from opportunity where id in: oppIds];
            
        for(Opportunity opp : opps){
                     if(opp.StageName== HELMSConstants.Assigned_to_Dealer  &&  opp.SubDiv_TXT__c != HELMSConstants.NSX){
                              opp.stageName = HELMSConstants.Acknowledged ;
                              opp.OpportunityStatus_TXT__c  = HELMSConstants.LeadOpened;
                     } else if((opp.stageName == HELMSConstants.In_Conversation && opp.OpportunityStatus_TXT__c != HELMSConstants.Madeappointment) && opp.SubDiv_TXT__c != HELMSConstants.NSX){
                                opp.OpportunityStatus_TXT__c  = HELMSConstants.Madeappointment;
                                                         
           } 
          oppty.add(opp);   
        }
        if(oppty.size()>0)
        {
            update oppty;
        }
    }
     /*updateopptyStageandStatusforEmailMessage - if we send any mail in partner comunity, opportunity stages will update automatically. */
   public static void updateopptyStageandStatusforEmailMessage(List<EmailMessage> EmailMessage){
    
    set<Id> oppIds = new Set<Id>();
        List<Opportunity> oppty = new List<Opportunity>();  
    
        for(EmailMessage t : EmailMessage){
          String wId = t.RelatedToId;
          if(wId!=null && wId.startsWith('006')){
            oppIds.add(t.RelatedToId);
          }
        }
        
        List<Opportunity> opps = [select Id,StageName, OpportunityStatus_TXT__c, SubDiv_TXT__c from opportunity where id in: oppIds];
    
        for(Opportunity opp : opps){
                     if((opp.StageName== HELMSConstants.Assigned_to_Dealer || opp.stageName == HELMSConstants.In_Conversation || opp.stageName == HELMSConstants.Acknowledged ) &&  opp.SubDiv_TXT__c != HELMSConstants.NSX){
                              opp.stageName = HELMSConstants.In_Conversation;
                              opp.OpportunityStatus_TXT__c  = HELMSConstants.salespersonbyemail;
                         
           } 
          oppty.add(opp);
        }
        if(oppty.size()>0)
        {
            update oppty;
        }
    }
     /*updateopptyStageandStatusforNote - if we created any note in partner comunity, opportunity stages will update automatically. */
      public static void updateopptyStageandStatusforNote(List<ContentDocumentLink> Note){
              set<Id> oppIds = new Set<Id>();
              List<Opportunity> oppty = new List<Opportunity>();
             Set<Id> newSet = new Set<Id>();
         
            for(ContentDocumentLink t : Note){
                 newSet.add(t.ContentDocumentId);
                    
             }
        //   system.debug('newSet---->'+newSet);
     //  List<ContentDocumentLink> conLinks = [select Id, LinkedEntityId,ContentDocumentId from ContentDocumentLink where LinkedEntityId IN :oppIds];
    List<ContentDocumentLink> conLinks = [select Id, LinkedEntityId,ContentDocumentId from ContentDocumentLink where ContentDocumentId IN :newSet];
           for(ContentDocumentLink Cdl : conLinks )   {
         string LinkedEntityId = cdl.LinkedEntityId;
               if(LinkedEntityId.substring(0,3) == '006'){
               oppIds.add(cdl.LinkedEntityId);
               }
           } 
      // system.debug('oppIds---->'+oppIds);
        List<Opportunity> opps = [select Id,StageName, OpportunityStatus_TXT__c, SubDiv_TXT__c from opportunity where id in: oppIds];
        for(Opportunity opp : opps){
                     if(opp.StageName== HELMSConstants.Assigned_to_Dealer){
                              opp.stageName = HELMSConstants.Acknowledged ;
                              opp.OpportunityStatus_TXT__c  = HELMSConstants.LeadOpened;
                         
           } else if(opp.stageName == HELMSConstants.In_Conversation && opp.OpportunityStatus_TXT__c  != HELMSConstants.Note){
                              opp.stageName = HELMSConstants.In_Conversation;
                              opp.OpportunityStatus_TXT__c  = HELMSConstants.Note;
                         
           } 
          oppty.add(opp);
        }
        if(oppty.size()>0)
        {
            update oppty;
        }
    }
    
    
}