objects/Product_Model__c.object
<CustomObject>
    <fields>
        <fullName>Model_ID_Text__c</fullName>
        <label>Model ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Model_Group_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Model Group Id</label>
        <referenceTo>Product_Model_Group__c</referenceTo>
        <relationshipLabel>Product Models</relationshipLabel>
        <relationshipName>Product_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Model</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Product Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Model_Group__c.object
<CustomObject>
    <label>Product Model Group</label>
    <nameField>
        <label>Product Model Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Model Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RDR_Sales__c.object
<CustomObject>
    <fields>
        <fullName>Model_ID__c</fullName>
        <label>Model Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Name_Code_CD__c</fullName>
        <label>Model Name Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RDR_Sold_Model__c</fullName>
        <label>RDR Sold Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RDR Sales</label>
    <nameField>
        <displayFormat>RDR Sales - {00000000}</displayFormat>
        <label>RDR Sales</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RDR Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RDRSalesTriggerHandler.cls
public class RDRSalesTriggerHandler {
    public void rdrsalemodel(List<RDR_Sales__c> lstrdr){
        Map<String, Product_Model__c> currentPMsToRealtedMId = new Map<String, Product_Model__c>();
        
        for(Product_Model__c pm : [SELECT Id, Model_ID_Text__c, Product_Model_Group_Id__r.Id, 
                                   Product_Model_Group_Id__r.Name from Product_Model__c ]){
                                       currentPMsToRealtedMId.put(pm.Model_ID_Text__c, pm);
                                   }
        for(RDR_sales__c rdr: lstrdr){
            
            if(rdr.Model_ID__c!=null && !(rdr.Model_ID__c.isNumeric()) && currentPMsToRealtedMId.containskey(rdr.Model_ID__c))    
            rdr.RDR_Sold_Model__c=currentPMsToRealtedMId.get(rdr.Model_ID__c).Product_Model_Group_Id__r.Name;
            else{
            if(rdr.Model_Name_Code_CD__c!=null && currentPMsToRealtedMId.containskey(rdr.Model_Name_Code_CD__c))    
            rdr.RDR_Sold_Model__c=currentPMsToRealtedMId.get(rdr.Model_Name_Code_CD__c).Product_Model_Group_Id__r.Name;
            }
        }
    }
}