objects/Product_Model__c.object
<CustomObject>
    <fields>
        <fullName>Model_ID_Text__c</fullName>
        <label>Model ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Marketing_Name__c</fullName>
        <label>Model Marketing Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Model_Group_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Model Group Id</label>
        <referenceTo>Product_Model_Group__c</referenceTo>
        <relationshipLabel>Product Models</relationshipLabel>
        <relationshipName>Product_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Model</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Product Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Model_Group__c.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <label>Subdivision</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Subdivision</valueSetName>
        </valueSet>
    </fields>
    <label>Product Model Group</label>
    <nameField>
        <label>Product Model Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Model Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RDR_Sales__c.object
<CustomObject>
    <fields>
        <fullName>Auto_VIN_Status_Code__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-5532 Story name.
Description: This is to store the VIN-STATUS
Source System: Coming from Integration from Mainframe/SAP.
Integration: NA.
Data Transformation: N/A.</description>
        <label>Auto VIN Status Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_First_Name_NUM__c</fullName>
        <label>Customer First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Number_NUM__c</fullName>
        <label>Dealer Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_ID__c</fullName>
        <label>Model Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Name_Code_CD__c</fullName>
        <label>Model Name Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Dealer_Number_From_Buy_Sell__c</fullName>
        <label>New Dealer Number From Buy Sell</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Code_CD__c</fullName>
        <label>Status Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vin_TXT__c</fullName>
        <label>Vin</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XPROD_DIV_CD__c</fullName>
        <label>XPROD-DIV-CD</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>RDR Sales</label>
    <nameField>
        <displayFormat>RDR Sales - {00000000}</displayFormat>
        <label>RDR Sales</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RDR Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A-Honda</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B-Acura</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <default>true</default>
        <label>P-PowerEquipment</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>M-Motorcycle</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>dk</fullName>
        <isActive>false</isActive>
        <label>dk</label>
    </customValue>
    <customValue>
        <fullName>powerequipment</fullName>
        <isActive>false</isActive>
        <label>powerequipment</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

globalValueSets/Subdivision.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Marine</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>PowerEquipment</fullName>
        <label>Power Equipment</label>
    </customValue>
    <customValue>
        <fullName>NSX</fullName>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
    </customValue>
    <masterLabel>Subdivision</masterLabel>
</GlobalValueSet>

classes/RDRSoldModelCorrectionBatchTest.cls
@IsTest
public class RDRSoldModelCorrectionBatchTest {
    @IsTest
    static void batchmethodtest(){
        List<RDR_Sales__c> rdrList = new List<RDR_Sales__c>();
        RDR_Sales__c rdrRec = new RDR_Sales__c(Vin_TXT__c= '9D2ME1345NR403953',Status_Code_CD__c='03',
                                               Dealer_Number_NUM__c='104275',Auto_VIN_Status_Code__c='RR2',XPROD_DIV_CD__c='A',
                                               Customer_First_Name_NUM__c='Kiran301',New_Dealer_Number_From_Buy_Sell__c='90009',
                                              Model_ID__c='6793',Model_Name_Code_CD__c='ABCD8954');
        rdrList.add(rdrRec);
        RDR_Sales__c rdrRec1 = new RDR_Sales__c(Vin_TXT__c= '9D2ME1345NR403953',Status_Code_CD__c='03',
                                               Dealer_Number_NUM__c='104275',Auto_VIN_Status_Code__c='RR2',XPROD_DIV_CD__c='A',
                                               Customer_First_Name_NUM__c='Kiran302',New_Dealer_Number_From_Buy_Sell__c='90009',
                                               Model_ID__c='ABCD8954',Model_Name_Code_CD__c='8954');
        rdrList.add(rdrRec1);
        insert rdrList;
        
        List<Product_Model_Group__c> tPMGs = new List<Product_Model_Group__c>();
        tPMGs.add(new Product_Model_Group__c(Name='TestPMG1',	Division__c='A',  Subdivision__c='Honda'));
        tPMGs.add(new Product_Model_Group__c(Name='TestPMG2',	Division__c='B',  Subdivision__c='Acura'));
        tPMGs.add(new Product_Model_Group__c(Name='TestPMG3',	Division__c='M',  Subdivision__c='Motorcycle'));
        insert tPMGs;
        List<Product_Model__c> tPGs = new List<Product_Model__c>();
        List<Product_Model_Group__c> insertedPMGS = [select Id, Name FROM Product_Model_Group__c];
        tPGs.add(new Product_Model__c(Model_ID_Text__c='6793', 	Model_Marketing_Name__c = 'PMG1' ,	Product_Model_Group_Id__c=insertedPMGS[0].Id));
        tPGs.add(new Product_Model__c(Model_ID_Text__c='4545', Model_Marketing_Name__c = 'PMG1',	Product_Model_Group_Id__c=insertedPMGS[0].Id));
        tPGs.add(new Product_Model__c(Model_ID_Text__c='ABCD8954', 	Model_Marketing_Name__c = 'PMG2', Product_Model_Group_Id__c=insertedPMGS[1].Id));
        tPGs.add(new Product_Model__c(Model_ID_Text__c='4343', Model_Marketing_Name__c = 'PMG2', 	Product_Model_Group_Id__c=insertedPMGS[1].Id));
        tPGs.add(new Product_Model__c(Model_ID_Text__c='5945', Model_Marketing_Name__c = 'PMG3', 	Product_Model_Group_Id__c=insertedPMGS[2].Id));
        tPGs.add(new Product_Model__c(Model_ID_Text__c='9054', Model_Marketing_Name__c = 'PMG3', 	Product_Model_Group_Id__c=insertedPMGS[2].Id));
        insert tPGs;
        
        RDRSoldModelCorrectionBatch cs = new RDRSoldModelCorrectionBatch();
        Id JobID=Database.executeBatch(cs);
        String sch = '0 0 23 * * ?';
		system.schedule('Testing', sch, cs );
        
        
        
    }

}