objects/RDR_Sales__c.object
<CustomObject>
    <fields>
        <fullName>Auto_VIN_Status_Code__c</fullName>
        <description>Business Unit: HELMS.
Jira Story: LMS-5532 Story name.
Description: This is to store the VIN-STATUS
Source System: Coming from Integration from Mainframe/SAP.
Integration: NA.
Data Transformation: N/A.</description>
        <label>Auto VIN Status Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_First_Name_NUM__c</fullName>
        <label>Customer First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Number_NUM__c</fullName>
        <label>Dealer Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Dealer_Number_From_Buy_Sell__c</fullName>
        <label>New Dealer Number From Buy Sell</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Code_CD__c</fullName>
        <label>Status Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vin_TXT__c</fullName>
        <label>Vin</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XPROD_DIV_CD__c</fullName>
        <label>XPROD-DIV-CD</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>RDR Sales</label>
    <nameField>
        <displayFormat>RDR Sales - {00000000}</displayFormat>
        <label>RDR Sales</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RDR Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/loadingRDRTest.cls
@isTest
public class loadingRDRTest {
    
    @isTest
    static void updateRDR(){
        List<RDR_Sales__c> rdrList = new List<RDR_Sales__c>();
        RDR_Sales__c rdrRec = new RDR_Sales__c(Vin_TXT__c= '9D2ME1345NR403953',Status_Code_CD__c='03',
                                               Dealer_Number_NUM__c='104275',Auto_VIN_Status_Code__c='RR2',XPROD_DIV_CD__c='A',
                                               Customer_First_Name_NUM__c='Kiran301',New_Dealer_Number_From_Buy_Sell__c='90009');
        insert rdrRec;
        
         RDR_Sales__c rdrRec1 = new RDR_Sales__c(Vin_TXT__c= '9D2ME1345NR403953',Status_Code_CD__c='03',
                                               Dealer_Number_NUM__c='104275',Auto_VIN_Status_Code__c='RR2',XPROD_DIV_CD__c='A',
                                               Customer_First_Name_NUM__c='Kiran302',New_Dealer_Number_From_Buy_Sell__c='90009');
        insert rdrRec1;
        
           RDR_Sales__c rdrRec2 = new RDR_Sales__c(Vin_TXT__c= '9D2ME1345NR403953',Status_Code_CD__c='03',
                                               Dealer_Number_NUM__c='104275',Auto_VIN_Status_Code__c='RR2',XPROD_DIV_CD__c='B',
                                               Customer_First_Name_NUM__c='Kiran301',New_Dealer_Number_From_Buy_Sell__c='90009');
        insert rdrRec2;
        
         RDR_Sales__c rdrRec3 = new RDR_Sales__c(Vin_TXT__c= '9D2ME1345NR403953',Status_Code_CD__c='03',
                                               Dealer_Number_NUM__c='104275',Auto_VIN_Status_Code__c='RR2',XPROD_DIV_CD__c='B',
                                               Customer_First_Name_NUM__c='Kiran302',New_Dealer_Number_From_Buy_Sell__c='90009');
        insert rdrRec3;
        
        rdrList.add(rdrRec);
        
       system.assertEquals('9D2ME1345NR403953', rdrRec3.Vin_TXT__c);
     
    }

}