objects/Routing_Disposition_Failure__c.object
<CustomObject>
    <fields>
        <fullName>Payload__c</fullName>
        <label>Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Routing Disposition Failure</label>
    <nameField>
        <displayFormat>R-{0000000000}</displayFormat>
        <label>Routing Disposition Failure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routing Disposition Failure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HelmsDispFailureLogDeletionBatchTest.cls
@isTest 
public class HelmsDispFailureLogDeletionBatchTest 
{
    @isTest static void testMethod1() 
    {
        List<Routing_Disposition_Failure__c> lstDisp= new List<Routing_Disposition_Failure__c>();
        for(Integer i=0 ;i <200;i++)
        {
            Routing_Disposition_Failure__c dis = new Routing_Disposition_Failure__c();
            dis.Payload__c ='p'+i;
            lstDisp.add(dis);
        }
        
        insert lstDisp;
        for(Routing_Disposition_Failure__c d: lstDisp){
            date createddate=system.today().addDays(-60);
            Test.setCreatedDate(d.id, createddate);
        }
        
        Test.startTest();

            HelmsDispFailureLogDeletionBatch sh1 = new HelmsDispFailureLogDeletionBatch();
			String sch = '0 0 23 * * ?'; 
            system.schedule('Test Territory Check', sch, sh1); 
            
        Test.stopTest();
    }
}